#include "encore/basement_progression.hpp"
#include "encore/native_session.hpp"
#include "encore/content.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
using namespace encore::upstream;
#define CHECK(x) do{if(!(x)){std::fprintf(stderr,"Basement check failed %d: %s (%s)\n",__LINE__,#x,error.c_str());std::exit(1);}}while(0)
static uint32_t word(const std::vector<uint8_t>&b,size_t i){return b[i]|uint32_t(b[i+1])<<8|uint32_t(b[i+2])<<16|uint32_t(b[i+3])<<24;}
static void put(std::vector<uint8_t>&b,size_t i,uint32_t v){for(unsigned k=0;k<4;++k)b[i+k]=uint8_t(v>>(8*k));}
static void fix(std::vector<uint8_t>&b){put(b,16,0);put(b,16,encore::crc32(b.data(),b.size()));}
int main(int argc,char**argv){
 const std::string root=argc>1?argv[1]:"romfs/data";std::string error;BasementProgressionData data;NativeSessionData session;
 CHECK(data.load_file((root+"/house.encbasement").c_str(),error));CHECK(session.load_file((root+"/opening.encsession").c_str(),error));CHECK(data.bind_reviewed_commit(data.reviewed_commit(),error));CHECK(!data.bind_reviewed_commit("foreign",error));
 CHECK(data.key_items().size()==3&&data.skills().size()==1);CHECK(!data.door().remove_key);CHECK(data.key_item(data.door().key_id)->source=="KeyBasement");CHECK(data.key_item(data.present().key_id)->source=="GGFDiary");
 SessionSnapshot next;const auto initial=session.defaults();CHECK(prepare_basement_key_item(data,data.door().key_id,UINT32_MAX,initial,next,error));CHECK(next.key_items.size()==initial.key_items.size()+1&&next.key_items.back().uid==UINT32_MAX&&next.key_items.back().doses==1&&!next.key_items.back().equipped);const auto retained=next;CHECK(!prepare_basement_key_item(data,data.present().key_id,UINT32_MAX,next,next,error));CHECK(next.key_items.size()==retained.key_items.size());CHECK(!prepare_basement_key_item(data,999,0,initial,next,error));
 auto character=initial.characters.front();character.learned_skills={data.telepathy_skill()};SessionCharacter learned;CHECK(prepare_basement_skill(data,data.skills().front().id,character,learned,error));CHECK(learned.learned_skills.size()==2);SessionCharacter again;CHECK(prepare_basement_skill(data,data.skills().front().id,learned,again,error));CHECK(again.learned_skills==learned.learned_skills);CHECK(again.hp==character.hp&&again.pp==character.pp&&again.inventory.size()==character.inventory.size());character.character_id="unknown";CHECK(!prepare_basement_skill(data,data.skills().front().id,character,again,error));character=initial.characters.front();character.learned_skills={"unknown"};CHECK(!prepare_basement_skill(data,data.skills().front().id,character,again,error));
 bool scratch=false,telepathy=false,treats=false;BasementFlagQuery flags=[&](std::string_view flag,bool&v,std::string&){if(flag=="mick_scratch")v=scratch;else if(flag=="mick_telepathy")v=telepathy;else if(flag=="got_dog_treats")v=treats;else if(flag=="gave_treats")v=false;else return false;return true;};std::string path;CHECK(data.mick_program(false,flags,path,error)&&path=="Podunk/woof");CHECK(data.mick_program(true,flags,path,error)&&path=="Podunk/woof_food");scratch=true;CHECK(data.mick_program(false,flags,path,error)&&path=="Podunk/woof_secret");CHECK(data.mick_program(true,flags,path,error)&&path=="Podunk/woof_key");telepathy=true;CHECK(data.mick_program(true,flags,path,error)&&path=="Podunk/woof_food");CHECK(data.mick_program(false,flags,path,error)&&path=="Podunk/woof_deal");treats=true;const auto oldpath=path;CHECK(!data.mick_program(false,flags,path,error)&&path==oldpath);
 CHECK(data.fade_rect().z>0&&data.fade_rect().w>0&&data.music_regions().size()==4);CHECK(data.white_fade(0).w==data.fade_keys().front().color.w);CHECK(data.white_fade(data.fade_length()).w==data.fade_keys().back().color.w);const auto a=data.fade_keys()[1],b=data.fade_keys()[2];CHECK(std::abs(data.white_fade((a.time+b.time)/2).w-(a.color.w+b.color.w)/2)<1e-5);
 unsigned grants=0,skills=0;BasementProgressionHost host;host.validate_key_item=[](const auto&,std::string&){return true;};host.validate_skill=[](const auto&,std::string&){return true;};host.grant_key_item=[&](const auto&,std::string&){++grants;return true;};host.learn_skill=[&](const auto&,std::string&){++skills;return true;};BasementProgressionConsumer consumer;CHECK(consumer.bind(data,host,error));CHECK(consumer.grant_key_item(data.door().key_id,error));CHECK(consumer.learn_skill(data.skills().front().id,error));CHECK(grants==1&&skills==1);CHECK(!consumer.grant_key_item(999,error)&&grants==1);CHECK(!consumer.learn_skill(999,error)&&skills==1);host.validate_skill=[](const auto&,std::string&){return false;};CHECK(!consumer.bind(data,host,error));CHECK(consumer.learn_skill(data.skills().front().id,error)&&skills==2);
 std::vector<uint8_t>bytes;CHECK(encore::read_file((root+"/house.encbasement").c_str(),bytes,1024*1024,error));const auto pin=data.reviewed_commit();for(size_t size=0;size<bytes.size();++size)CHECK(!data.load(bytes.data(),size,error));for(const auto entry:std::vector<std::pair<size_t,uint32_t>>{{8,2},{20,2},{24,2},{28,9},{52,1},{64,99},{68,0},{76,9}}){auto corrupt=bytes;put(corrupt,entry.first,entry.second);fix(corrupt);CHECK(!data.load(corrupt.data(),corrupt.size(),error));}CHECK(data.valid()&&data.reviewed_commit()==pin);
 auto corrupt=bytes;put(corrupt,word(bytes,64+16+4)+8,0);fix(corrupt);CHECK(!data.load(corrupt.data(),corrupt.size(),error));corrupt=bytes;put(corrupt,word(bytes,64+2*16+4)+12,UINT32_MAX);fix(corrupt);CHECK(!data.load(corrupt.data(),corrupt.size(),error));corrupt=bytes;corrupt.back()^=1;CHECK(!data.load(corrupt.data(),corrupt.size(),error));
 std::puts("Manual basement source policy/atomic effects/format checks passed");
}
