#include "encore/battle_action_presentation.hpp"
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <limits>
using namespace encore::upstream;
namespace {unsigned checks=0;void check(bool v,const char*m){++checks;if(!v){std::cerr<<"FAIL "<<m<<"\n";std::exit(1);}}void near(double a,double b,double t,const char*m){check(std::isfinite(a)&&std::abs(a-b)<=t,m);}}
int main(int argc,char**argv){
 check(argc==4,"round, entry and unchanged native HP/text reference supplied");BattleRoundData data;BattleData entry;std::string error;check(data.load_file(argv[1],error),error.c_str());check(entry.load_file(argv[2],error),error.c_str());auto v=data.view();auto e=entry.view();const auto b=v.binding();
 BattleHpRoll hp;check(hp.begin(v,62,62),"HP initialize");check(hp.digit_frame(0)==16&&hp.digit_frame(1)==48&&!hp.digit_visible(2),"HP source digit atlas");check(hp.set_target(60),"HP damage target");const double frame=v.rule(RoundRule::HpFrameSeconds);check(hp.idle_frame(frame),"HP one transition tick");check(hp.display_hp()==61&&hp.current_hp()==62&&hp.digit_frame(0)==15,"source decrement wraps frame7 and reported HP remains upper integer");
 for(int i=1;i<16;++i){check(hp.idle_frame(frame),"HP transition");}
 check(hp.display_hp()==60&&hp.scrolling(),"HP target reached but completion deferred next quantum");check(hp.idle_frame(frame)&&hp.take_done()&&!hp.scrolling(),"source HP done on subsequent frame");
 hp.set_target(61);for(int i=0;i<8;++i)hp.idle_frame(frame);check(hp.display_hp()==61,"healing increments only after wrap");check(!hp.idle_frame(-1),"negative HP delta fails");
 BattleTextPacer text;check(text.begin(v,"AB"),"text begin");const auto timing=BattleValue{float(v.rule(RoundRule::TextSecondsPerChar)),0,0,float(v.rule(RoundRule::TextAutoAdvanceSeconds))};check(text.physics_frame(v.rule(RoundRule::TextSecondsPerChar))&&text.visible_characters()==0,"source text strict greater than");check(text.physics_frame(v.rule(RoundRule::TextSecondsPerChar))&&text.visible_characters()==1,"first character");text.input(false,true);check(text.physics_frame(v.rule(RoundRule::TextSecondsPerChar))&&text.finished()&&!text.done(),"B speeds printing without instantly advancing finished phrase");check(text.idle_frame(timing.w)&&!text.done(),"timer exact zero not done");check(text.idle_frame(.001)&&text.done(),"timer strict negative done");
 text.begin(v,"A");text.input(true,false);text.physics_frame(.1);check(text.finished(),"A speed multiplier");text.input(true,false);check(text.done(),"A completes finished text");text.begin(v,"");check(!text.done()&&text.idle_frame(0)&&text.done(),"empty dialogue deferred one idle");
 SourceRandom rng(13);BattleActionPresentation p;check(p.begin(v,e,rng),p.error());BattlePose party;party.rect={128,96,64,64};party.color={1,1,1,1};party.visible=true;BattlePose enemy=party;enemy.rect={143.5,49,33,49};check(p.set_actor_base(b.player_participant,party)&&p.set_actor_base(b.enemy_participant,enemy)&&p.set_plate_base({128,132,65,49}),"source base injection");
 // Regression: main binds on the first Commands frame, while the source
 // .12-second reveal is still running. Preserve this progress; do not freeze
 // the partially hidden y as the next-round shown position.
 BattleActionPresentation handoff;check(handoff.begin(v,e,rng),"handoff initializes");BattlePose partial=party;const float show_seconds=v.parameter(RoundParameter::PartyShown).y;const float shown_distance=v.parameter(RoundParameter::PartyShown).x;partial.rect.y+=shown_distance*(1-float(1.0/60.0)/show_seconds);check(handoff.set_actor_base(b.player_participant,partial),handoff.error());near(handoff.actor_pose(b.player_participant).rect.y,partial.rect.y,1e-5,"handoff preserves initial tween position");BattleRoundCue menu;menu.kind=BattleRoundCueKind::ShowMenu;menu.actor=b.player_participant;check(handoff.emit(menu,rng),"initial menu keeps reveal running");handoff.idle_frame(show_seconds);near(handoff.actor_pose(b.player_participant).rect.y,party.rect.y,1e-5,"handoff completes original show to stable base");
 const auto attack=v.skill(b.basic_skill);check(p.sample(attack.user_media,0).frame==123,"original bash frame0");check(p.sample(attack.user_media,.08).frame==124,"original bash frame1");check(p.sample(attack.user_media,.643).frame==17,"source final bash frame");
 const auto ef=v.presentation(RoundPresentationSlot::EnemyFlash);near(p.sample(ef,.05).glow_modifier,.9,1e-6,"original additive glow");
 const auto ea=v.presentation(RoundPresentationSlot::EnemyAttack);near(p.sample(ea,.05).offset.y,-9.375,1e-5,"source quartic enemy anticipation");near(p.sample(ea,.15).offset.y,-9.375,1e-5,"source quartic enemy return");
 BattleRoundCue cue;cue.kind=BattleRoundCueKind::Attack;cue.actor=b.player_participant;cue.target=b.enemy_participant;cue.skill=b.basic_skill;check(p.emit(cue,rng),p.error());check(!p.ready(BattleRoundGate::ApplyDamage,cue.actor),"impact starts gated");p.idle_frame(.07);check(!p.ready(BattleRoundGate::ApplyDamage,cue.actor),"impact not early");p.idle_frame(.002);check(p.ready(BattleRoundGate::ApplyDamage,cue.actor),"source method event releases impact before animation end");
 cue.kind=BattleRoundCueKind::Hit;cue.amount=13;cue.hp_after=17;auto expected=rng;expected.rand_range(32,64);expected.randi();check(p.emit(cue,rng),p.error());check(rng.state()==expected.state()&&rng.raw_draw_count()==expected.raw_draw_count(),"number RNG exactly; unbound HitEffect script consumes nothing");check(p.overlays().size()>=2,"damage number and bash effect concurrent");p.idle_frame(.21);check(!p.overlays().empty(),"number outlives hit effect");
 cue.kind=BattleRoundCueKind::TargetOpen;check(p.emit(cue,rng)&&p.target_open(),"target selection visible");const auto target=p.actor_pose(b.enemy_participant);near(target.glow_modifier,.25,1e-6,"target source glow");cue.kind=BattleRoundCueKind::TargetClose;check(p.emit(cue,rng)&&!p.target_open(),"target close");
 cue.kind=BattleRoundCueKind::Hit;cue.smash=true;cue.hp_after=0;check(p.emit(cue,rng),p.error());near(p.time_scale(),.5,1e-8,"SMASH source initial time scale");near(p.advance_real_time(.25),1-std::sqrt(.75)+.5,1e-8,"source circular real-time slowmo curve");near(p.advance_real_time(.25),1,1e-8,"source restores normal at real deadline");
 cue.kind=BattleRoundCueKind::Defeat;check(p.emit(cue,rng),p.error());p.idle_frame(.71);check(!p.actor_pose(b.enemy_participant).visible,"source defeat hides only after source clip");
 check(!p.physics_frame(std::numeric_limits<double>::infinity()),"nonfinite text delta rejected");SourceRandom other(13);check(!p.emit(cue,other),"unshared presentation RNG rejected");
 // Manual victory text follows the actual _input mapping: both A and B are
 // next-phrase edges; a press made while printing only changes its speed.
 BattleTextPacer manual;check(manual.begin(v,"AB",false),"manual outcome text begins");manual.input(false,true);manual.physics_frame(.1);check(manual.finished()&&!manual.done(),"typing B edge cannot acknowledge the newly completed phrase");manual.idle_frame(100);check(!manual.done(),"manual phrase has no automatic timeout");manual.input(false,true);check(manual.done(),"source B event acknowledges an already finished phrase");
 manual.begin(v,"AB",false);manual.input(true,false);manual.physics_frame(.1);manual.idle_frame(100);check(manual.finished()&&!manual.done(),"A acceleration also preserves manual gate");manual.input(true,false);check(manual.done(),"later A event acknowledges manual phrase");
 BattleHpRoll stopped;stopped.begin(v,62,62);stopped.set_target(60);stopped.idle_frame(frame);check(stopped.current_hp()==62&&stopped.display_hp()==61,"synthetic mid-digit damage boundary");check(stopped.stop_scrolling()==61&&!stopped.scrolling()&&stopped.current_hp()==61&&stopped.target_hp()==61,"source stop commits raw display HP and clears fraction");check(stopped.set_instant(62)&&!stopped.set_instant(63),"instant HP bounds checked");
 BattleActionPresentation victory;check(victory.begin(v,e,rng),"victory presentation begin");victory.set_actor_base(b.player_participant,party);victory.set_actor_base(b.enemy_participant,enemy);victory.set_plate_base({128,132,65,49});
 check(!victory.begin_return(),"return is blocked before source victory");check(victory.begin_victory(),"source victory visuals begin");check(!victory.commands_visible()&&victory.actor_pose(b.player_participant).frame==81,"victory original first frame and commands hidden");check(!victory.begin_outcome_text("early"),"XP text cannot precede play_win gate");
 victory.idle_frame(3);check(!victory.victory_done(),"play_win timer exact zero does not release");victory.idle_frame(.001);check(victory.victory_done(),"play_win timer strict negative releases");check(victory.actor_pose(b.player_participant).frame==95,"source victory holds final frame");
 const auto banner=v.presentation(RoundPresentationSlot::VictoryBanner);check(victory.sample(banner,double(float(.1))).frame==1&&victory.sample(banner,double(float(.1))+1.0/60.0).frame==2,"native discrete banner key keeps preceding frame at exact boundary");
 check(victory.begin_outcome_text(v.string(v.text(v.victory().exp_text).text)),"manual XP text begins");check(!victory.begin_return(),"return blocked until actual acknowledgment");victory.input(false,true);victory.physics_frame(.1);victory.idle_frame(2);check(!victory.dialogue().done(),"EXP survives long idle");victory.input(true,false);victory.idle_frame(1.0/60.0);check(victory.begin_return(),"acknowledged result starts transitionOut");check(!victory.begin_party_return({180,100}),"jump cannot start before source callback");
 std::vector<std::pair<RoundEventKind,int>> callbacks;
 for(int tick=1;tick<=162;++tick){check(victory.idle_frame(1.0/60.0),"return frame advances");for(const auto event:victory.take_return_events()){callbacks.emplace_back(event,tick);if(event==RoundEventKind::JumpPartyToWorld){near(victory.return_time(),1.666665792465210,1e-7,"native float32 AnimationPlayer callback cursor");near(132+victory.return_plate_offset(),174.777527,3e-5,"native source plate position at jump callback");check(victory.begin_party_return({220,130},{80,60}),"fresh expanded projection starts same-pass world jump");const auto pose=victory.return_party_pose();check(pose.visible&&pose.frame==183&&pose.anchor.x==0&&pose.anchor.y==0,"native world sprite and absolute viewport pose");}}
  if(tick==44)check(victory.battle_background_visible(),"battle background preserved before source callback");
  if(tick==45)check(!victory.battle_background_visible(),"battle background released at source callback");
  if(tick==48)check(!victory.enemies_visible(),"enemies hidden at source callback");
  if(tick==134)check(!victory.return_party_pose().visible,"jump sprite hides on native landing frame");
  if(tick==161)check(!victory.return_done(),"return remains gated before animation_finished");}
 const auto native_jump=victory.sample(v.presentation(RoundPresentationSlot::PartyJumpToWorld),double(float(1.0/60.0)),{160.5f,174.777527f},{269.5f,218.222473f});near(native_jump.rect.x,168.666672,2e-5,"native first jump x sample");near(native_jump.rect.y+native_jump.offset.y,192.834488,3e-5,"native first jump y sample");
 const std::vector<std::pair<RoundEventKind,int>> expected_callbacks={{RoundEventKind::TurnPartyToWorld,6},{RoundEventKind::HideBattleBackground,45},{RoundEventKind::HideEnemies,48},{RoundEventKind::JumpPartyToWorld,99},{RoundEventKind::PartyReturnLanded,134},{RoundEventKind::RotatePartyOriginal,144}};
 check(callbacks==expected_callbacks,"native source callbacks and same-pass jump completion match");check(victory.return_done(),"native transition animation finishes frame162");check(victory.return_overlays().size()==2,"both source black curtains persist through return");near(victory.return_plate_offset(),77,1e-5,"source info plate exits with original track");
 BattleHpRoll native_hp;native_hp.begin(v,62,62);native_hp.set_target(60);BattleTextPacer native_text;native_text.begin(v,"Ninten attacks!");std::ifstream reference(argv[3]);check(bool(reference),"native reference exists");int frame_index,cur,sub,current,ones,tens,hundreds,scroll,visible,finished;unsigned rows=0;
 while(reference>>frame_index>>cur>>sub>>current>>ones>>tens>>hundreds>>scroll>>visible>>finished){native_hp.idle_frame(1.0/60.0);native_text.physics_frame(1.0/60.0);check(native_hp.display_hp()==cur&&native_hp.current_hp()==current,"native HP integer and ceiling");check(native_hp.digit_frame(0)==unsigned(ones)&&native_hp.digit_frame(1)==unsigned(tens)&&native_hp.digit_frame(2)==unsigned(hundreds),"native rolling atlas frames");check(native_hp.scrolling()==bool(scroll),"native HP completion timing");check(native_text.visible_characters()==unsigned(visible)&&native_text.finished()==bool(finished),"native exact source text pacing");++rows;}check(rows==100,"all native reference rows compared");
 std::cout<<checks<<" presentation checks passed\n";
}
