#!/usr/bin/env python3
"""Bounded Doll/Mimmie camera oracle, unchanged native Godot 3.6.2 scripts.
Reuses the reviewed lamp oracle's isolated services. No full-game timing claim.
"""
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from tools.reference_cutscene_camera import prepare,REVIEW
from tools.run_scene_reference import invoke,digest

def cases():
    def a(tick,op,x=0,y=0,length=0):return dict(tick=tick,op=op,x=x,y=y,length=length)
    actions=[a(0,'shake',length=.8),a(2,'change'),a(2,'return',length=1),a(3,'shake',length=.8),a(5,'lamp',128,90),a(8,'mimmie',128,110),a(10,'change_mimmie'),a(10,'return',length=1),a(11,'shake',length=.2),a(14,'lamp',128,106),a(18,'mimmie',136,144),a(22,'change'),a(22,'return',length=1),a(23,'lamp',128,90),a(28,'shake',length=.2),a(32,'change_mimmie'),a(37,'change'),a(70,'lamp',128,138),a(75,'restore'),a(76,'pause')]
    # The second case revisits an actor without returncam, observing its retained
    # tween/paused state rather than replacing it immediately with a new tween.
    retained=[a(0,'change'),a(0,'move',128,90,length=1),a(2,'shake',length=.8),a(5,'pause'),a(6,'change_mimmie'),a(6,'return',length=1),a(10,'mimmie',136,160),a(12,'change'),a(15,'return',length=1),a(18,'change_mimmie'),a(40,'change'),a(80,'restore')]
    area=json.loads((ROOT/'content/native-opening.json').read_text())['sections']['CameraArea'][2]
    return [dict(name=f'{name}_{size[0]}x{size[1]}',ticks=115,player=[128,169],lamp=[128,74],mimmie=[128,90],viewport=size,area=area,actions=seq) for size in ([400,240],[320,180]) for name,seq in [('doll_mimmie_doll_return_and_shakers',actions),('dormant_actor_tween_and_pause',retained)]]

def fixture(doc):
    if doc['godot']['string']!='3.6.2-stable (official)' or [r['definition'] for r in doc['cases']]!=cases():raise ValueError('native camera result domain mismatch')
    def n(x):
        v=format(float(x),'.9g');return v+('f' if '.' in v or 'e' in v else '.0f')
    def v(x):return '{'+','.join(map(n,x))+'}'
    code=['// Generated by tests/doll_camera_reference.py from unchanged upstream scripts.','#pragma once','#include "encore/movement.hpp"','namespace doll_camera_reference {','using encore::upstream::Vec2;','struct Action {unsigned tick;const char* op;Vec2 target;double length;};','struct Frame {Vec2 global,center,offset,physics_global,physics_center;unsigned camera;};','struct Case {const char* name;Vec2 player,doll,mimmie,viewport;const Action* actions;unsigned action_count;const Frame* frames;unsigned frame_count;};']
    for i,row in enumerate(doc['cases']):
        if len(row['frames'])!=row['definition']['ticks']:raise ValueError('incomplete trace')
        code.append(f'constexpr Action actions_{i}[]={{')
        for a in row['definition']['actions']:code.append('{'+str(a['tick'])+',"'+a['op']+'",'+v([a['x'],a['y']])+','+str(a['length'])+'},')
        code.append('};\nconstexpr Frame frames_'+str(i)+'[]={')
        for f in row['frames']:code.append('{'+','.join(v(f[k]) for k in ('global','center','offset','physics_global','physics_center'))+','+str(f['camera'])+'},')
        code.append('};')
    code.append('constexpr Case cases[]={')
    for i,row in enumerate(doc['cases']):
        d=row['definition'];code.append('{"'+d['name']+'",'+','.join(v(d[k]) for k in ('player','lamp','mimmie','viewport'))+f',actions_{i},sizeof(actions_{i})/sizeof(Action),frames_{i},sizeof(frames_{i})/sizeof(Frame)'+'},')
    return '\n'.join(code+['};','}'])+'\n'

def main():
    p=argparse.ArgumentParser();p.add_argument('--godot',type=Path,required=True);p.add_argument('--work',type=Path,required=True);p.add_argument('--reports',type=Path,required=True);args=p.parse_args()
    work=args.work.resolve();report=args.reports.resolve();review=json.loads(REVIEW.read_text())
    prepare(ROOT/'upstream/MOTHER-Encore',work,review)
    (work/'cases.json').write_text(json.dumps(cases()))
    (work/'probe.gd').write_bytes((ROOT/'tests/godot_doll_camera_probe.gd').read_bytes())
    review['scope']='Isolated Doll/Mimmie/player Camera2D transfer, return, dormant tween and shaker mechanics, both supported viewport sizes; synthetic command timings'
    for src in ['Scripts/Main/roomshaker.gd','Data/Dialogue/Podunk/cutscenes/doll_attack.yaml']:review['sources'][src]=digest(ROOT/'upstream/MOTHER-Encore'/src)
    (work/'metadata.json').write_text(json.dumps(review))
    report.mkdir(parents=True,exist_ok=False)
    invoke(args.godot.resolve(),work,['--fixed-fps','60','--script',str(work/'probe.gd'),'--encore-out='+str(report/'reference.json')],report/'godot.txt')
    doc=json.loads((report/'reference.json').read_text());(report/'doll_camera_v0410.hpp').write_text(fixture(doc))
    receipt=dict(engine_sha256=digest(args.godot),source_hashes=review['sources'],reference_sha256=digest(report/'reference.json'),fixture_sha256=digest(report/'doll_camera_v0410.hpp'),tools_sha256={str(p.relative_to(ROOT)):digest(p) for p in [Path(__file__).resolve(),ROOT/'tests/godot_doll_camera_probe.gd']},scope=review['scope'],hardware='not run',emulator='not run')
    (report/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
    print('Doll camera native reference complete:',len(doc['cases']),'cases')
if __name__=='__main__':main()
