// Manual only. Original source ambient butterflies, not fixture gameplay.
#include "encore/field_butterfly.hpp"
#include <cassert>
#include <cmath>
#include <fstream>
#include <iterator>
#include <limits>
using namespace encore::upstream;
int main(int argc,char**argv){assert(argc==2);FieldButterflyData d;std::string e;assert(d.load_file(argv[1],e));assert(d.bindings().size()==94&&d.assets().size()==5&&d.pixel_snap());bool admit=true;unsigned publications=0;FieldButterflyBody actor;actor.party_member_player=actor.global_player=actor.walking=true;FieldButterflyHost h;h.admit_ready=[&](const auto&,auto&err){if(!admit)err="unsupported listeners";return admit;};h.body_snapshot=[&](uint32_t body,auto&out,auto&err){if(!body){err="unknown body";return false;}out=actor;return true;};h.publish=[&](const auto&,const auto&s,auto&){assert(std::isfinite(s.position.x)&&s.frame<d.frames());++publications;return true;};FieldButterflyRuntime r;assert(r.initialize(d,h,e));SourceRandom random(97),source=random;for(const auto&b:d.bindings()){auto image=source.randi()%d.modulus();assert(r.ready(b.id,random,e));assert(r.state(b.id)->asset==image&&!r.state(b.id)->visible&&!r.state(b.id)->process);}assert(random.state()==source.state()&&random.raw_draw_count()==94);const auto&b=d.bindings().front();auto retained=random.state();assert(!r.ready(b.id,random,e)&&random.state()==retained);assert(!r.screen_enter(0,random,e)&&random.state()==retained);float fly=float(source.randf()*d.fly_seek()),orbit=float(source.randf()*d.orbit_seek());assert(r.screen_enter(b.id,random,e)&&random.state()==source.state());assert(r.state(b.id)->fly_time==fly&&r.state(b.id)->visible&&r.state(b.id)->process);assert(r.state(b.id)->orbit_time>=0&&r.state(b.id)->orbit_time<=d.clip(2)->length);(void)orbit;
 actor.world=r.world_position(b.id);actor.world.x+=r.state(b.id)->sprite_position.x-2;actor.world.y+=r.state(b.id)->sprite_position.y;assert(r.body_enter(b.id,1,e)&&!r.state(b.id)->flip);auto old=r.state(b.id)->position;assert(r.idle_process(b.id,.0625,true,e));assert(r.state(b.id)->position.x!=old.x||r.state(b.id)->position.y!=old.y);assert(r.body_exit(b.id,1,e)&&r.body_exit(b.id,1,e)&&r.state(b.id)->waiters.size()==2);assert(r.screen_exit(b.id,e));old=r.state(b.id)->position;for(unsigned i=0;i<16;++i)assert(r.idle_leaf(b.timer_id,.0625,true,e));assert(r.state(b.id)->timer_left==0&&r.state(b.id)->waiters.front()==0);assert(r.idle_leaf(b.timer_id,.0625,true,e)&&r.state(b.id)->input.x==0&&r.state(b.id)->input.y==0&&r.state(b.id)->waiters.front()==1);for(unsigned i=0;i<17;++i)assert(r.idle_leaf(b.timer_id,.0625,true,e));assert(r.state(b.id)->returning&&r.state(b.id)->waiters.empty());assert(r.idle_process(b.id,.0625,true,e)&&r.state(b.id)->position.x==old.x&&r.state(b.id)->position.y==old.y);assert(r.screen_enter(b.id,random,e));for(unsigned i=0;i<8;++i)assert(r.idle_process(b.id,.0625,true,e));assert(r.state(b.id)->position.x==b.position.x&&r.state(b.id)->position.y==b.position.y&&!r.state(b.id)->returning);
 // The collision Area follows Sprite position, never the rendering offset.
 auto centre=r.area_center(b.id);auto w=r.world_position(b.id);assert(centre.x==w.x+(r.state(b.id)->sprite_position.x+b.area_center.x)*b.parent_scale);for(unsigned i=0;i<160;++i){assert(r.idle_leaf(b.fly_id,.0625,true,e));assert(r.idle_leaf(b.orbit_id,.0625,true,e));}assert(r.state(b.id)->frame<d.frames());auto time=r.state(b.id)->orbit_time;assert(r.idle_leaf(b.orbit_id,.0625,false,e)&&r.state(b.id)->orbit_time==time);assert(!r.idle_leaf(0,.0625,true,e));assert(!r.idle_process(b.id,std::numeric_limits<double>::quiet_NaN(),true,e));assert(!r.body_enter(b.id,0,e));assert(r.exit_tree(b.id,e)&&!r.state(b.id)->alive);assert(!r.body_enter(b.id,1,e));FieldButterflyRuntime rejected;assert(rejected.initialize(d,h,e));admit=false;retained=random.state();assert(!rejected.ready(b.id,random,e)&&random.state()==retained);assert(!FieldButterflyRuntime{}.initialize(d,{},e));
 std::ifstream f(argv[1],std::ios::binary);std::vector<uint8_t>bytes((std::istreambuf_iterator<char>(f)),{});auto recalc=[](auto&b){uint32_t crc=~0u;for(size_t i=0;i<b.size();++i){crc^=i>=16&&i<20?0:b[i];for(unsigned j=0;j<8;++j)crc=(crc>>1)^(0xedb88320u&uint32_t(-int32_t(crc&1)));}crc=~crc;for(unsigned j=0;j<4;++j)b[16+j]=uint8_t(crc>>(j*8));};for(unsigned at:{8u,20u,24u,52u}){auto bad=bytes;bad[at]=99;recalc(bad);assert(!d.load(bad.data(),bad.size(),e)&&d.valid());}assert(!d.load(nullptr,0,e));auto bad=bytes;bad.back()^=1;assert(!d.load(bad.data(),bad.size(),e));
}
