// Manual only. Source-derived pack with host doubles; never an M0 game path.
#include "encore/field_present.hpp"
#include <cassert>
#include <algorithm>
#include <fstream>
#include <iterator>
#include <limits>
using namespace encore::upstream;
int main(int argc,char**argv){assert(argc==2);FieldPresentData data;std::string e;assert(data.load_file(argv[1],e));assert(data.bindings().size()==16&&data.pending().size()==3);for(const auto&b:data.bindings()){assert(b.collision_layer==517&&b.sparkles_ready<b.ready_ordinal);assert(data.item(b.item));}
 std::vector<std::string>trace;std::vector<uint32_t>collected;bool space=true,reject=false;FieldPresentHost h;h.admit_ready=[](auto&,std::string&){return true;};h.admit_interaction=[&](auto&,std::string&e){if(reject){e="source programme pending";return false;}return true;};h.read_flag=[&](const auto&b,bool&out,std::string&){out=std::find(collected.begin(),collected.end(),b.id)!=collected.end();return true;};h.write_flag=[&](const auto&b,bool value,std::string&){trace.push_back(value?"flag+":"flag-");collected.erase(std::remove(collected.begin(),collected.end(),b.id),collected.end());if(value)collected.push_back(b.id);return true;};h.inventory_space=[&](bool&out,std::string&){trace.push_back("space");out=space;return true;};h.select_item=[&](const auto&i,bool give,std::string&){assert(i.doses>0);trace.push_back(give?"give":"context");return true;};h.prompt_enabled=[](uint32_t,bool,std::string&){return true;};h.sound=[&](uint32_t,bool on,std::string&){trace.push_back(on?"sound+":"sound-");return true;};h.dialogue=[&](std::string_view path,std::string&){trace.push_back(std::string(path));return true;};FieldPresentRuntime r;assert(r.initialize(data,h,e));SourceRandom random(13);auto reference=random;
 struct Ready{uint32_t ordinal,id;bool child;};std::vector<Ready>events;for(const auto&b:data.bindings()){events.push_back({b.sparkles_ready,b.sparkles_id,true});events.push_back({b.ready_ordinal,b.id,false});}std::sort(events.begin(),events.end(),[](auto&a,auto&b){return a.ordinal<b.ordinal;});for(const auto&step:events){if(step.child){reference.rand_range(data.random_low(),data.random_high());assert(r.ready_sparkles(step.id,random,e));}else assert(r.ready_present(step.id,e));}assert(random.state()==reference.state());const auto&b=data.bindings().front();assert(!r.ready_sparkles(b.sparkles_id,random,e)&&random.state()==reference.state());assert(!r.ready_present(b.id,e));assert(!r.interact(data.pending().front().id,e));
 trace.clear();assert(r.interact(b.id,e));assert((trace==std::vector<std::string>{"space","give","flag+",b.dialogue}));assert(r.state(b.id)->opened&&!r.state(b.id)->sparkle_playing&&!r.state(b.id)->sparkle_visible);for(unsigned i=0;i<7;++i)assert(r.idle_frame(.1,true,e));assert(r.state(b.id)->frame==b.opened_frame&&!r.state(b.id)->audio_playing);assert(std::find(trace.begin(),trace.end(),"sound+")!=trace.end());trace.clear();assert(r.interact(b.id,e)&&trace==std::vector<std::string>{data.empty_message()});
 const auto&full=data.bindings()[1];space=false;trace.clear();assert(r.interact(full.id,e));assert((trace==std::vector<std::string>{"space","context",full.full}));assert(!r.state(full.id)->opened&&r.state(full.id)->revert_waiters.size()==1);assert(r.interact(full.id,e)&&r.state(full.id)->revert_waiters.size()==2);for(unsigned i=0;i<7;++i)assert(r.idle_frame(.1,true,e));assert(r.state(full.id)->wrapped&&r.state(full.id)->revert_waiters.empty());for(unsigned i=0;i<4;++i)assert(r.idle_frame(.1,true,e));assert(r.state(full.id)->frame==full.initial_frame&&!r.state(full.id)->animation_playing);
 auto retained=*r.state(full.id);reject=true;assert(!r.interact(full.id,e)&&r.state(full.id)->animation_time==retained.animation_time&&r.state(full.id)->revert_waiters.empty());reject=false;assert(r.interact(full.id,e)&&r.exit_tree(full.id,e)&&r.state(full.id)->revert_waiters.empty()&&!r.state(full.id)->alive);assert(!r.interact(full.id,e));assert(!r.idle_frame(std::numeric_limits<double>::quiet_NaN(),true,e));assert(!r.idle_frame(-1,true,e));assert(!r.idle_frame(.2,true,e));
 // Saved collected flag still consumes the child's shared draw, then hides it.
 FieldPresentRuntime saved;assert(saved.initialize(data,h,e));auto before=random;assert(saved.ready_sparkles(b.sparkles_id,random,e)&&random.state()!=before.state());assert(saved.ready_present(b.id,e)&&saved.state(b.id)->frame==b.opened_frame&&!saved.state(b.id)->sparkle_playing);assert(!FieldPresentRuntime{}.initialize(data,{},e));
 std::ifstream f(argv[1],std::ios::binary);std::vector<uint8_t>bytes((std::istreambuf_iterator<char>(f)),{});auto recalc=[](std::vector<uint8_t>&b){uint32_t crc=~0u;for(size_t i=0;i<b.size();++i){crc^=i>=16&&i<20?0:b[i];for(unsigned j=0;j<8;++j)crc=(crc>>1)^(0xedb88320u&uint32_t(-int32_t(crc&1)));}crc=~crc;for(unsigned i=0;i<4;++i)b[16+i]=uint8_t(crc>>(i*8));};for(unsigned at:{8u,20u,24u}){auto malformed=bytes;malformed[at]=99;recalc(malformed);assert(!data.load(malformed.data(),malformed.size(),e)&&data.valid());}auto malformed=bytes;malformed.back()^=1;assert(!data.load(malformed.data(),malformed.size(),e));assert(!data.load(nullptr,0,e));
}
