#include "encore/field_dead_bush.hpp"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <fstream>
#include <iterator>
#include <map>
using namespace encore::upstream;
namespace{std::vector<uint8_t>read(const char*p){std::ifstream f(p,std::ios::binary);return{std::istreambuf_iterator<char>(f),{}};}void put(std::vector<uint8_t>&b,size_t at,uint32_t v){for(unsigned i=0;i<4;++i)b[at+i]=uint8_t(v>>(8*i));}void checksum(std::vector<uint8_t>&b){uint32_t c=~0u;for(size_t i=0;i<b.size();++i){c^=i>=16&&i<20?0:b[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}put(b,16,~c);}}
// Manual source-core tests only. GPU sprites, NDSP, real signal/geometry/prompt
// and SceneTree deferred factories require their actual platform consumers.
int main(int argc,char**argv){assert(argc==2);auto raw=read(argv[1]);FieldBushData data;std::string error;assert(data.load(raw.data(),raw.size(),error)&&data.records().size()==13);auto reject=[&](std::vector<uint8_t>b){checksum(b);assert(!data.load(b.data(),b.size(),error));assert(data.valid()&&data.records().size()==13);};for(size_t at:{size_t(8),size_t(20),size_t(24),size_t(28),size_t(52),size_t(56),size_t(60)}){auto b=raw;put(b,at,0);reject(b);}auto corrupt=raw;corrupt.back()^=1;assert(!data.load(corrupt.data(),corrupt.size(),error));for(size_t cut:{size_t(0),size_t(63),raw.size()-1})assert(!data.load(raw.data(),cut,error));
 FieldBushRuntime unbound;assert(!unbound.initialize(data,{},error));assert(!unbound.create(data.records().front().id));
 std::map<std::string,bool>flags;std::vector<std::string>events;unsigned vibrations=0,frees=0,dialogs=0,deferred=0,audios=0;uint64_t next_root=0;std::map<uint64_t,uint32_t>root_parent;std::map<uint64_t,Vec2>root_local;std::map<uint32_t,std::function<bool(bool)>>viewport;std::map<uint32_t,std::function<bool(uint32_t)>>hitbox;FieldBushRuntime runtime;
 FieldBushHost h;h.bind=[&](const FieldBushData&d,std::string&){return&d==&data;};h.resolve_node=[](uint32_t id,bool&exists,std::string&){exists=id!=0;return true;};h.read_flag=[&](std::string_view key,bool&present,bool&value,std::string&){auto i=flags.find(std::string(key));present=i!=flags.end();value=present&&i->second;return true;};h.connect_viewport=[&](uint32_t id,auto cb,std::string&){viewport[id]=cb;return true;};h.connect_hitbox=[&](uint32_t id,auto cb,std::string&){hitbox[id]=cb;return true;};h.publish=[](uint32_t,const FieldBushInstance&,std::string&){return true;};h.duplicate_sprite=[&](uint32_t id,uint32_t sprite,uint64_t&roots,std::string&){assert(data.record(id)->sprite_id==sprite&&runtime.instance(id));roots=++next_root;events.push_back("clone");return true;};h.roots_frame=[&](uint64_t id,uint32_t frame,std::string&){assert(id&&frame==data.roots_frame());events.push_back("frame");return true;};h.roots_add_child=[&](uint64_t id,uint32_t parent,std::string&){root_parent[id]=parent;events.push_back("add");return true;};h.sprite_global_position=[&](uint32_t,Vec2&out,std::string&){events.push_back("global");out={31,71};return true;};h.roots_local_position=[&](uint64_t id,Vec2 local,std::string&){root_local[id]=local;events.push_back("local");return true;};h.audio_play=[&](uint32_t,const FieldBushSound&s,std::string&){assert(s.id==data.sound().id);++audios;events.push_back("sound");return true;};h.prompt_enabled=[&](uint32_t id,bool enabled,std::string&){assert(!enabled&&std::any_of(data.records().begin(),data.records().end(),[&](const auto&d){return d.prompt_id==id;}));events.push_back("prompt");return true;};h.boolean_setting=[&](std::string_view gate,bool&enabled,std::string&){assert(gate==data.vibration_gate());enabled=true;return true;};h.vibrate=[&](uint32_t device,float weak,float strong,float length,std::string&){assert(device==data.vibration_device()&&weak==data.vibration()[0]&&strong==data.vibration()[1]&&length==data.vibration()[2]);++vibrations;return true;};h.open_dialogue=[&](uint32_t,const FieldBushDialogue&d,std::string&){++dialogs;assert(d.program==data.dialogue(flags[data.bat_flag()]).program);return true;};h.call_deferred=[&](const FieldBushDescriptor&d,FieldBushDeferredKind kind,std::string&){assert(d.called_id&&kind==FieldBushDeferredKind::CutsceneCheckStart);++deferred;return true;};h.queue_free=[&](uint32_t,std::string&){++frees;return true;};assert(runtime.initialize(data,h,error));for(const auto&d:data.records()){assert(runtime.create(d.id));assert(runtime.ready(d.id));assert(!runtime.instance(d.id)->visible);assert(!runtime.ready(d.id));}
 const auto&first=data.records().front();assert(viewport[first.id](true));assert(!runtime.interact(first.id));flags[data.bat_flag()]=false;assert(runtime.interact(first.id));flags[data.bat_flag()]=true;assert(runtime.interact(first.id)&&dialogs==2);assert(viewport[first.id](false));assert(runtime.interact(first.id)&&dialogs==2);assert(runtime.grow(first.id)&&runtime.grow(first.id));assert(runtime.instance(first.id)->grow_waiters==2&&vibrations==2);assert(runtime.idle_frame(first.id,data.clip(FieldBushClipRole::Grow)->length));assert(runtime.instance(first.id)->clip==FieldBushClipRole::Idle&&!runtime.instance(first.id)->grow_waiters);
 events.clear();assert(hitbox[first.id](9));assert((events==std::vector<std::string>{"clone","frame","add","global","local","sound","prompt"}));assert(root_parent[1]==first.new_parent_id&&root_local[1].x==31&&root_local[1].y==71);assert(runtime.idle_frame(first.id,data.clip(FieldBushClipRole::Break)->length));assert(runtime.instance(first.id)->body_disabled&&runtime.instance(first.id)->hit_disabled&&runtime.instance(first.id)->interact_disabled&&!runtime.instance(first.id)->queued&&frees==0);
 const auto found=std::find_if(data.records().begin(),data.records().end(),[](const auto&d){return d.call_kind==FieldBushDeferredKind::CutsceneCheckStart;});assert(found!=data.records().end());flags[found->disappear_flag]=false;assert(runtime.grow(found->id));assert(hitbox[found->id](10));assert(runtime.idle_frame(found->id,data.clip(FieldBushClipRole::Break)->length));assert(deferred==1&&frees==1&&runtime.instance(found->id)->queued&&runtime.instance(found->id)->clip==FieldBushClipRole::Idle);const auto root_count=root_parent.size();assert(runtime.commit_deleted(found->id));assert(root_parent.size()==root_count);assert(!runtime.grow(found->id));assert(!runtime.idle_frame(first.id,std::nanf("")));assert(!runtime.idle_frame(first.id,-1));assert(!runtime.hitbox_entered(first.id,0));
 // Required effect failure poisons retries after actual partial mutations.
 FieldBushRuntime failed;auto bad_host=h;bad_host.prompt_enabled=[](uint32_t,bool,std::string&e){e="manual required prompt failure";return false;};assert(failed.initialize(data,bad_host,error));assert(failed.create(first.id)&&failed.ready(first.id));assert(!failed.hitbox_entered(first.id,1));assert(!failed.hitbox_entered(first.id,1));
}
