#include <cstring>
#include "encore/field_equipment_menu.hpp"
#include "encore/native_session.hpp"
#include "encore/content.hpp"
#include "encore/crc32.hpp"
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <limits>
using namespace encore::upstream;
static unsigned checks=0;
#define CHECK(x) do{++checks;if(!(x)){std::fprintf(stderr,"Field equipment manual check failed at %d: %s (%s)\n",__LINE__,#x,error.c_str());std::exit(1);}}while(0)
static uint32_t get(const std::vector<uint8_t>&b,size_t n){return b[n]|uint32_t(b[n+1])<<8|uint32_t(b[n+2])<<16|uint32_t(b[n+3])<<24;}
static void put(std::vector<uint8_t>&b,size_t n,uint32_t v){for(unsigned i=0;i<4;++i)b[n+i]=uint8_t(v>>(i*8));}
static void fix(std::vector<uint8_t>&b){put(b,16,0);put(b,16,encore::crc32(b.data(),b.size()));}
static uint32_t section(const std::vector<uint8_t>&b,FieldSection s){return get(b,64+(uint32_t(s)-1)*16+4);}
int main(int argc,char**argv){
 const std::string root=argc>1?argv[1]:"romfs";std::string error;ItemData items;FieldEquipmentData data;NativeSessionData session;std::vector<uint8_t>bytes;
 CHECK(items.load_file((root+"/data/opening.encitems").c_str(),error));CHECK(session.load_file((root+"/data/opening.encsession").c_str(),error));CHECK(encore::read_file((root+"/data/opening.encfield").c_str(),bytes,2*1024*1024,error));CHECK(data.load(bytes.data(),bytes.size(),error));const auto v=data.view();CHECK(v.bind_items(items.view(),error));CHECK(uint32_t(v.parameter(FieldParameter::OwnerId))==items.view().metadata().owner);CHECK(v.verify_resources(root.c_str(),error));
 FieldEquipmentSnapshot current;current.owner=std::string(v.binding(FieldBinding::Owner));current.nickname=session.defaults().characters.front().nickname;current.level=session.levels().front().level;current.cash=UINT32_MAX;CHECK(current.inventory.initialize(items.view()));current.stats=session.levels().front().stats;
 // The source draws unsigned UIDs: zero must survive None/equip transitions.
 auto start=current.inventory.instances();CHECK(!start.empty());start[0].id=0;CHECK(current.inventory.restore(items.view(),start,error));const auto equipment=v.equipment(0);const auto item=start[0];unsigned commits=0;bool reject_commit=false;std::array<int32_t,7>projected{};
 auto candidate=[&](uint32_t slot,bool none,uint32_t uid,FieldEquipmentSnapshot&out,std::string&e){if(slot>=v.count(FieldSection::Slots)){e="manual host rejects slot";return false;}out=current;auto instances=out.inventory.instances();bool found=none;for(auto&i:instances){const auto d=items.view().definition(i.definition);if(i.equipped&&d.equipment_slot==slot)i.equipped=0;if(!none&&i.id==uid){if(!(d.flags&uint32_t(ItemDefinitionFlag::Equipment))||d.equipment_slot!=slot){e="manual host rejects receiver/slot";return false;}i.equipped=1;found=true;}}if(!found){e="manual host rejects missing UID";return false;}if(!out.inventory.restore(items.view(),instances,e))return false;auto c=session.defaults().characters.front();c.inventory.clear();for(const auto&i:instances){SessionItem s;s.uid=i.id;s.item_id=std::string(items.view().string(items.view().definition(i.definition).source));s.equipped=i.equipped!=0;s.doses=i.doses;c.inventory.push_back(s);}return native_session_derived_stats(session,items.view(),c,out.stats,e);};
 FieldEquipmentHost host;host.read=[&](FieldEquipmentSnapshot&s,std::string&){s=current;return true;};host.preview=[&](uint32_t slot,bool none,uint32_t uid,std::array<int32_t,7>&s,std::string&e){FieldEquipmentSnapshot next;if(!candidate(slot,none,uid,next,e))return false;s=next.stats;return true;};host.commit=[&](uint32_t slot,bool none,uint32_t uid,std::string&e){if(reject_commit){e="manual host commit rejected";return false;}FieldEquipmentSnapshot next;if(!candidate(slot,none,uid,next,e))return false;current=std::move(next);++commits;return true;};
 FieldEquipmentMenu menu;CHECK(menu.initialize(v,host));CHECK(menu.open());CHECK(menu.phase()==FieldEquipmentPhase::PauseOpening);CHECK(menu.input(0,0,true,false));CHECK(menu.phase()==FieldEquipmentPhase::PauseOpening);CHECK(menu.idle_frame(v.clip(FieldClipRole::PauseOpen).duration));CHECK(menu.phase()==FieldEquipmentPhase::Pause);
 // Goods/PSI/Status/Map/Options are source-known but not falsely executable.
 menu.take_sounds();CHECK(menu.input(0,0,true,false));auto sounds=menu.take_sounds();CHECK(sounds.size()==1&&sounds.front()==FieldEquipmentSound::Restricted&&commits==0);
 uint32_t equip_command=0;for(uint32_t i=0;i<v.count(FieldSection::Commands);++i)if(v.command(i).enabled)equip_command=i;while(menu.command_selection()!=equip_command)CHECK(menu.input(0,1,false,false));CHECK(menu.input(0,0,true,false));CHECK(menu.equipment_visible());CHECK(menu.idle_frame(v.clip(FieldClipRole::EquipOpen).duration));CHECK(menu.phase()==FieldEquipmentPhase::Slots);
 // An empty source slot with no suitable item must reject rather than open None.
 CHECK(menu.slot_selection()==0);CHECK(menu.input(0,0,true,false));CHECK(menu.phase()==FieldEquipmentPhase::Slots);while(menu.slot_selection()!=equipment.slot)CHECK(menu.input(0,1,false,false));CHECK(menu.equipped_item(equipment.slot)&&menu.equipped_item(equipment.slot)->id==0);CHECK(menu.input(0,0,true,false));CHECK(menu.phase()==FieldEquipmentPhase::Candidates&&menu.candidate_count()==1&&menu.candidate(0).none);CHECK(menu.selected_item()==nullptr);projected=current.stats;for(size_t i=0;i<7;++i)projected[i]-=equipment.boosts[i];CHECK(menu.preview_stats()==projected);CHECK(current.inventory.instance(0).equipped&&commits==0);
 CHECK(menu.input(0,0,false,true));CHECK(menu.phase()==FieldEquipmentPhase::Slots&&current.inventory.instance(0).equipped&&commits==0);CHECK(menu.input(0,0,true,false));reject_commit=true;CHECK(!menu.input(0,0,true,false));CHECK(current.inventory.instance(0).equipped&&commits==0&&menu.phase()==FieldEquipmentPhase::Candidates);reject_commit=false;CHECK(menu.input(0,0,true,false));CHECK(!current.inventory.instance(0).equipped&&current.inventory.instance(0).id==0&&commits==1&&current.stats==projected);
 // Unequipped candidate keeps inventory order and has no trailing None while
 // slot is empty; selecting the real UID zero equips the actual same instance.
 CHECK(menu.input(0,0,true,false));CHECK(menu.candidate_count()==1&&!menu.candidate(0).none&&menu.candidate(0).item.id==0);CHECK(menu.input(0,0,true,false));CHECK(current.inventory.instance(0).equipped&&current.inventory.instance(0).id==0&&commits==2);CHECK(menu.input(0,0,false,true));CHECK(menu.phase()==FieldEquipmentPhase::Pause&&menu.equipment_visible());CHECK(menu.idle_frame(v.clip(FieldClipRole::EquipClose).duration));CHECK(!menu.equipment_visible());CHECK(menu.input(0,0,false,true));CHECK(menu.idle_frame(v.clip(FieldClipRole::PauseClose).duration));CHECK(!menu.active());
 CHECK(!menu.input(2,0,false,false));CHECK(!menu.idle_frame(std::numeric_limits<double>::quiet_NaN()));CHECK(!menu.idle_frame(-1));CHECK(!menu.idle_frame(2));auto foreign=current;foreign.owner="unknown-party";host.read=[&](FieldEquipmentSnapshot&s,std::string&){s=foreign;return true;};FieldEquipmentMenu rejected;CHECK(!rejected.initialize(v,host));CHECK(!FieldEquipmentMenu{}.initialize(v,{}));
 // All malformed loads preserve the previously checked owner/view.
 const auto retained=data.view();for(size_t n=0;n<bytes.size();++n)CHECK(!data.load(bytes.data(),n,error));CHECK(data.view().same_content(retained));auto bad=[&](size_t at,uint32_t value){auto b=bytes;put(b,at,value);fix(b);CHECK(!data.load(b.data(),b.size(),error));CHECK(data.view().same_content(retained));};
 for(auto x:std::vector<std::pair<size_t,uint32_t>>{{0,0},{8,1},{8,3},{12,0},{20,2},{24,2},{28,11},{52,1},{64,0},{68,0},{72,UINT32_MAX},{76,2}})bad(x.first,x.second);
 const auto parameters=section(bytes,FieldSection::Parameters),bindings=section(bytes,FieldSection::Bindings),commands=section(bytes,FieldSection::Commands),slots=section(bytes,FieldSection::Slots),equipment_section=section(bytes,FieldSection::Equipment),resources=section(bytes,FieldSection::Resources),layouts=section(bytes,FieldSection::Layouts),clips=section(bytes,FieldSection::Clips),keys=section(bytes,FieldSection::Keys);
 for(auto x:std::vector<std::pair<size_t,uint32_t>>{{parameters,99},{parameters+4,0x7fc00000},{parameters+8*(uint32_t(FieldParameter::OwnerId)-1)+4,0},{bindings+4,UINT32_MAX},{commands+12,1},{slots+4,UINT32_MAX},{equipment_section+8,4},{resources+8,2},{resources+12,0},{resources+60,0},{layouts+4,99},{layouts+8,0},{layouts+36,0x7f800000},{clips,99},{clips+4,1},{clips+8,0},{clips+12,0},{keys,0x7fc00000}})bad(x.first,x.second);
 auto b=bytes;b[section(bytes,FieldSection::Strings)]=0xff;fix(b);CHECK(!data.load(b.data(),b.size(),error));b=bytes;b.push_back(0);put(b,12,uint32_t(b.size()));fix(b);CHECK(!data.load(b.data(),b.size(),error));b=bytes;std::fill(b.begin()+32,b.begin()+52,0);fix(b);CHECK(!data.load(b.data(),b.size(),error));FieldEquipmentData other;b=bytes;b[32]^=1;fix(b);CHECK(other.load(b.data(),b.size(),error));CHECK(!other.view().bind_items(items.view(),error));
 // Owner is an adapter ID, never a string offset; a different valid ID loads
 // structurally but must fail the cross-resource startup binding.
 b=bytes;float foreign_owner=float(items.view().metadata().owner+1);uint32_t owner_bits;std::memcpy(&owner_bits,&foreign_owner,4);put(b,parameters+8*(uint32_t(FieldParameter::OwnerId)-1)+4,owner_bits);fix(b);CHECK(other.load(b.data(),b.size(),error));CHECK(!other.view().bind_items(items.view(),error));
 b=bytes;put(b,resources+64,get(b,resources+64)^1);fix(b);CHECK(other.load(b.data(),b.size(),error));CHECK(!other.view().verify_resources(root.c_str(),error));CHECK(!v.verify_resources("missing-field-resource-root",error));
 CHECK(FieldEquipmentView{}.count(FieldSection::Strings)==0);CHECK(v.count(FieldSection(UINT32_MAX))==0);CHECK(v.string(UINT32_MAX).empty());CHECK(v.parameter(FieldParameter(UINT32_MAX))==0);CHECK(v.resource(UINT32_MAX).file_bytes==0);std::printf("Field equipment manual checks: %u; original None/candidate/UID/stats/cancel and strict malformed resource rejection\n",checks);
}
