// Manual suite only; no automatic CMake/CI registration or execution.
#include "encore/field_emotes.hpp"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <fstream>
#include <iterator>
#include <map>
using namespace encore::upstream;
namespace {void put(std::vector<uint8_t>&v,size_t p,uint32_t u){for(unsigned i=0;i<4;++i)v[p+i]=uint8_t(u>>(8*i));}void checksum(std::vector<uint8_t>&v){uint32_t c=~0u;for(size_t i=0;i<v.size();++i){c^=i>=16&&i<20?0:v[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}put(v,16,~c);}}
int main(int argc,char**argv){assert(argc==2);std::ifstream f(argv[1],std::ios::binary);std::vector<uint8_t>raw((std::istreambuf_iterator<char>(f)),{});FieldEmoteData data;std::string error;assert(data.load(raw.data(),raw.size(),error));assert(data.records().size()==71&&data.clips().size()==14&&data.sounds().size()==2);
 for(auto offset:{size_t(8),size_t(20),size_t(24),size_t(60)}){auto broken=raw;put(broken,offset,99);checksum(broken);assert(!data.load(broken.data(),broken.size(),error));assert(data.valid());}auto broken=raw;broken.back()^=1;assert(!data.load(broken.data(),broken.size(),error));auto trailing=raw;trailing.push_back(0);put(trailing,12,uint32_t(trailing.size()));checksum(trailing);assert(!data.load(trailing.data(),trailing.size(),error));
 std::map<uint32_t,FieldEmoteInstance>poses;Vec2 direction{-1,0};size_t stream_changes=0,starts=0,stops=0,finished=0;FieldEmoteHost host;host.resolve_object=[](const auto&d,bool&exists,uint32_t&out,std::string&){exists=d.object_id!=0;out=d.object_id;return true;};host.resolve_direction=[](const auto&d,uint32_t&out,std::string&){out=d.direction_id;return true;};host.texture_geometry=[](uint32_t,uint32_t&height,uint32_t&rows,std::string&){height=128;rows=4;return true;};host.direction=[&](uint32_t,Vec2&out,std::string&){out=direction;return true;};host.publish=[&](uint32_t id,const auto&s,std::string&){poses[id]=s;return true;};host.sound_stream=[&](uint32_t,const auto&,std::string&){++stream_changes;return true;};host.sound_playing=[&](uint32_t,const auto&,bool playing,std::string&){if(playing)++starts;else++stops;return true;};host.animation_finished=[&](uint32_t,const auto&,std::string&){++finished;return true;};FieldEmoteRuntime runtime;assert(!runtime.initialize(data,{},error));assert(runtime.initialize(data,host,error));assert(!runtime.create(0));
 for(const auto&d:data.records()){assert(runtime.create(d.id)&&runtime.ready(d.id));assert(!runtime.ready(d.id));assert(!runtime.create(d.id));assert(runtime.instance(d.id)->position.y==d.position.y);}
 auto npc=std::find_if(data.records().begin(),data.records().end(),[](const auto&d){return d.object_id!=0;});auto phone=std::find_if(data.records().begin(),data.records().end(),[](const auto&d){return d.object_id==0;});assert(npc!=data.records().end()&&phone!=data.records().end());const uint32_t id=npc->id;assert(runtime.sprite_changed(npc->object_id));assert(runtime.instance(id)->position.y==-(32+data.bubble_gap()));assert(!runtime.set_bubble_offset(phone->id));assert(!runtime.sprite_changed(0));assert(!runtime.play(id,"manual-unknown-clip"));
 const auto*dot=data.clip("dot");const auto*sweat=data.clip("sweat");const auto*angry=data.clip("angry");const auto*shock=data.clip("shock");assert(dot&&sweat&&angry&&shock);assert(runtime.play(id,dot->id));assert(runtime.instance(id)->frame==npc->frame);assert(runtime.idle_frame(id,0)&&runtime.instance(id)->frame==0);assert(runtime.idle_frame(id,0.05f)&&runtime.instance(id)->frame==0);assert(runtime.idle_frame(id,0.0001f)&&runtime.instance(id)->frame==1);float retained=runtime.instance(id)->elapsed;assert(runtime.play(id,dot->id));assert(runtime.instance(id)->elapsed==retained);assert(runtime.visibility(id,false));assert(runtime.idle_frame(id,0.1f));assert(runtime.instance(id)->elapsed>retained);assert(runtime.idle_frame(id,dot->length));assert(!runtime.is_playing(id)&&finished==1);assert(runtime.play(id,dot->id)&&runtime.instance(id)->elapsed==0);
 assert(runtime.play(id,sweat->id));assert(runtime.instance(id)->scale.x==-1);assert(runtime.idle_frame(id,0));assert(runtime.instance(id)->offset.y==10);direction={1,0};assert(runtime.play(id,angry->id));assert(runtime.instance(id)->scale.x==-1);assert(runtime.idle_frame(id,angry->length/2));assert(std::abs(runtime.instance(id)->offset.y-5)<0.00001f);assert(runtime.play(id,dot->id));assert(runtime.instance(id)->scale.x==1);
 assert(runtime.play(id,shock->id));assert(starts==0);assert(runtime.idle_frame(id,0));assert(stream_changes==1&&starts==1&&runtime.instance(id)->sound_playing);assert(runtime.seek(id,0,true));assert(stream_changes==2&&starts==2);assert(runtime.idle_frame(id,shock->length));assert(stops>=1&&!runtime.instance(id)->sound_playing);assert(runtime.stop(id)&&runtime.instance(id)->elapsed==0);
 // Phone objectPath is genuinely empty: ordinary emote playback is supported;
 // only actual invalid bubble/directional calls fail rather than blanket ignore.
 assert(runtime.play(phone->id,dot->id));assert(!runtime.play(phone->id,sweat->id));FieldEmoteRuntime reverse;assert(reverse.initialize(data,host,error));assert(reverse.create(data.records().back().id)&&reverse.ready(data.records().back().id));assert(reverse.create(data.records().front().id));assert(!reverse.ready(data.records().front().id));
 return 0;
}
