#include "encore/field_payphone.hpp"
#include <cassert>
#include <fstream>
#include <iterator>
using namespace encore::upstream;
// Manual source-core test. Does not stand in for the real NDSP, Canvas cash
// box, save policy, inventory UID ownership, or full SceneHost integration.
int main(int argc,char**argv){assert(argc==2);std::ifstream f(argv[1],std::ios::binary);std::vector<uint8_t>raw{std::istreambuf_iterator<char>(f),{}};FieldPayphoneData d;std::string e;assert(d.load(raw.data(),raw.size(),e)&&d.records().size()==4);FieldPayphoneRuntime missing;assert(!missing.initialize(d,{},e));auto b=raw;b.back()^=1;assert(!d.load(b.data(),b.size(),e)&&d.valid());assert(!d.load(raw.data(),raw.size()-1,e));
 std::vector<std::string>events;int64_t cash=0;FieldPayphoneCard card;unsigned spent=0;FieldPayphoneHost h;h.bind=[&](const auto&x,std::string&){return&x==&d;};h.read_flag=[](auto,bool&p,bool&v,std::string&){p=v=false;return true;};h.connect_flags=[](auto,auto,std::string&){return true;};h.visibility=[](auto,bool,std::string&){return true;};h.queue_free=[](auto,std::string&){return true;};h.find_card=[&](auto,auto&out,std::string&){out=card;return true;};h.lookup_card=[&](auto uid,auto&out,std::string&){out=card;return uid==card.uid;};h.reduce_or_drop=[&](auto uid,auto step,std::string&){assert(uid==card.uid&&step==d.card_step());events.push_back("reduce");spent+=step;if(card.doses>step)card.doses-=step;else card={};return true;};h.read_cash=[&](auto&out,std::string&){out=cash;return true;};h.add_cash=[&](auto v,std::string&){events.push_back("spend");cash+=v;return true;};h.set_stream=[&](auto,const auto&s,std::string&){assert(s.id==d.sound().id);events.push_back("stream");return true;};h.play_idle=[&](auto,auto frame,std::string&){assert(frame==d.idle_frame());events.push_back("idle");return true;};h.set_location=[&](auto,std::string&){events.push_back("location");return true;};h.box_open=[&](bool units,auto&id,std::string&){id=units?1:2;events.push_back(units?"units":"cash");return true;};h.box_update=[&](auto,std::string&){events.push_back("update");return true;};h.box_close=[&](auto,std::string&){events.push_back("close");return true;};h.audio_play=[&](auto,std::string&){events.push_back("audio");return true;};h.open_dialogue=[&](auto,auto p,std::string&){events.push_back(p==d.no_money_program()?"no-money":"dialogue");return true;};FieldPayphoneRuntime r;assert(r.initialize(d,h,e));for(const auto&n:d.records()){assert(r.create(n.id));assert(r.ready(n.id));}auto id=d.records().front().id;
 assert(r.interact(id));assert((events==std::vector<std::string>{"stream","idle","location","cash","no-money"}));events.clear();assert(r.idle_frame(d.update_seconds()+.001f));assert(events==std::vector<std::string>{"update"});events.clear();assert(r.idle_frame(d.close_seconds()+.001f));assert(events==std::vector<std::string>{"close"});
 cash=d.cash_cost();events.clear();assert(r.interact(id)&&cash==0);assert((events==std::vector<std::string>{"stream","idle","location","cash","audio","dialogue","spend"}));
 card={9,d.card_max_doses(),d.card_name()};events.clear();assert(r.interact(id)&&spent==d.card_step()&&cash==0);assert((events==std::vector<std::string>{"stream","idle","location","units","audio","dialogue","reduce"}));card={9,d.card_step(),d.card_name()};assert(r.interact_item(id,9)&&!card.uid);card={9,d.card_max_doses()+1,d.card_name()};assert(!r.interact(id));assert(!r.idle_frame(-1));
}
