#include <cstdlib>
#include "tests/gpu_span_common.hpp"
#include "encore/row_linear_background_kernel.hpp"
void require(bool b,const char* s){if(!b){std::fprintf(stderr,"FAIL %s\n",s);std::exit(1);}}
int main(){encore::upstream::BattleData data;std::string error;require(data.load_file("romfs/data/pillow-entry.encbattle",error),"data");auto view=data.view();gpu_span::Image src[2],pal[2];std::vector<encore::BackgroundKernel::Layer> layers;std::vector<encore::ScalarBackgroundKernel::Layer> scalar;
 for(unsigned n=0;n<2;++n){auto b=view.background(n);auto r=view.resource(b.resource);require(gpu_span::image("romfs/"+std::string(view.string(r.path)),r,src[n]),"source");layers.push_back(gpu_span::layer<encore::BackgroundKernel>(b,src[n],pal[n]));scalar.push_back(gpu_span::layer<encore::ScalarBackgroundKernel>(b,src[n],pal[n]));}
 constexpr uint32_t w=400,h=240;encore::RowLinearBackgroundKernel kernel;encore::ScalarBackgroundKernel oracle;require(kernel.prepare(layers,w,h)&&oracle.prepare(scalar,w,h,error),"prepare");std::vector<encore::RowLinearBackgroundKernel::CertifiedRow> rows(h);std::vector<uint8_t> yes(h);std::vector<uint32_t> expected(w*h),actual(w*h);std::vector<gpu_span::Span> fallback(16384);
 for(float t:{0.f,1.25f,60.f,1000.f,-80.71f}){uint32_t accepted=0;require(kernel.certify_integer_rows(t,rows.data(),yes.data(),accepted),"certificate");require(oracle.compose(t,0,expected.data()),"oracle");yes[0]=yes[h-1]=0;size_t count=0;require(kernel.generate_spans(t,fallback.data(),fallback.size(),count,yes.data()),"fallback");for(size_t i=0;i<count;++i){auto s=fallback[i];std::fill_n(actual.data()+s.y*w+s.x,s.width,s.color);}for(uint32_t y=0;y<h;++y)if(yes[y])for(uint32_t x=0;x<w;++x){uint32_t c[2];for(unsigned n=0;n<2;++n){const int at=int(x)+rows[y].shift[n];const uint32_t tx=(at%int(src[n].width)+int(src[n].width))%int(src[n].width);c[n]=src[n].palette[src[n].indices[rows[y].source_y[n]*src[n].width+tx]];}uint32_t result=0xff000000;for(unsigned s=0;s<24;s+=8)result|=(((((c[0]>>s)&255)+((c[1]>>s)&255))+1)/2)<<s;actual[y*w+x]=result;}
 require(actual==expected,"certified row indices and fallbacks exact");std::printf("INTEGER_ROW t=%.3f accepted=%u rejected=%u forced_fallback_rows=2 spans=%zu PASS\n",double(t),accepted,h-accepted,count);}
 // At a mathematical texel boundary the certificate must reject, rather than
 // assume that the original sequence rounds in the favorable direction.
 auto edge=layers;for(auto& l:edge){l.amplitude_x=0;l.move_x=-0.5f/176.f;l.ping_pong_speed_x=1;}encore::RowLinearBackgroundKernel boundary;require(boundary.prepare(edge,w,h),"boundary prepare");uint32_t accepted=999;require(boundary.certify_integer_rows(0,rows.data(),yes.data(),accepted)&&accepted==0,"boundary rows fail closed");std::puts("PASS integer row certificate, 480000 exact pixels and forced fallback");}
