#include "encore/house_data.hpp"
#include "encore/content.hpp"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
using namespace encore::upstream;
static unsigned checks=0;
#define CHECK(x) do{++checks;if(!(x)){std::fprintf(stderr,"HouseData check failed at %d: %s\n",__LINE__,#x);std::exit(1);}}while(0)
static uint32_t get(const std::vector<uint8_t>&b,size_t p){return uint32_t(b[p])|(uint32_t(b[p+1])<<8)|(uint32_t(b[p+2])<<16)|(uint32_t(b[p+3])<<24);}
static void put(std::vector<uint8_t>&b,size_t p,uint32_t v){for(unsigned i=0;i<4;++i)b[p+i]=uint8_t(v>>(8*i));}
static void fix(std::vector<uint8_t>&b){put(b,16,0);put(b,16,encore::crc32(b.data(),b.size()));}
static uint32_t section(const std::vector<uint8_t>&b,HouseSection s){return get(b,64+(uint32_t(s)-1)*16+4);}
int main(int argc,char**argv){
 const char*path=argc>1?argv[1]:"romfs/data/opening.enchouse";std::string error;std::vector<uint8_t>b;CHECK(encore::read_file(path,b,1024*1024,error));HouseData data;CHECK(data.load(b.data(),b.size(),error));auto v=data.view();CHECK(v.valid());CHECK(v.count(HouseSection::Doors)==8);CHECK(v.count(HouseSection::Boundaries)==3);CHECK(v.count(HouseSection::Segments)>5);
 const float destinations[][2]={{220,385},{430,387},{32,681},{155,401}};for(unsigned i=0;i<4;++i){auto d=v.door(i);CHECK(d.destination.x==destinations[i][0]&&d.destination.y==destinations[i][1]);CHECK(d.fade_in_length==1&&d.fade_in_opaque==.4&&d.fade_out_length==1&&d.fade_out_mostly==.4&&d.fade_in_speed==1.5&&d.fade_out_speed==1.5);}
 auto npc=v.npc(0);CHECK(npc.position.x==192&&npc.position.y==704&&npc.body_id==9);CHECK(npc.interact_center.x==191.5f&&npc.interact_center.y==709);CHECK(npc.flags==15);CHECK(npc.return_delay==1);CHECK(v.interaction().ray_origin.y==6&&v.interaction().ray_length==16);CHECK(v.interaction().text_seconds==.02);CHECK(v.interaction().voice_pitch_min==.85&&v.interaction().voice_pitch_max==1);CHECK(v.string(v.interaction().bullet_string)=="@ ");CHECK(v.interaction().max_player_name_length==7);CHECK(v.segment(0).flags==3&&v.segment(3).flags==5);CHECK(v.string(v.segment(0).speaker)=="Carol");CHECK(v.token(1).kind==uint32_t(HouseTokenKind::PlayerName));CHECK(v.string(v.token(0).text)=="Are you okay, ");CHECK(v.parameter(HouseParameter::FadeShader).x==1&&v.parameter(HouseParameter::FadeShader).y==1);CHECK(v.parameter(HouseParameter::FadeCuts).x==1&&v.parameter(HouseParameter::FadeCuts).w==1);CHECK(v.clip_for(HouseClipRole::NpcIdleDown,npc.profile)<v.count(HouseSection::Clips));
 CHECK(get(b,8)==7&&get(b,24)==7&&get(b,28)==7);CHECK(v.count(HouseSection::Segments)==129&&v.count(HouseSection::Dialogues)==66);
 CHECK(v.count(HouseSection::OpenableDoors)==4&&v.count(HouseSection::Profiles)==4);CHECK(v.npc(1).position.x==120&&v.npc(1).position.y==88&&v.npc(1).profile==1&&v.npc(1).segment_count==2);CHECK(v.npc(2).shadow_resource==house_no_index&&v.profile(2).directions==1&&v.profile(2).flags==1);CHECK(v.profile(1).sprite_offset.y==-3&&v.profile(2).sprite_offset.y==-2);CHECK(v.clip_for(HouseClipRole::NpcIdleDown,2)!=house_no_index&&v.clip_for(HouseClipRole::NpcTalkDown,2)==house_no_index);
 CHECK(v.count(HouseSection::Npcs)==4&&v.npc(3).room_actor_index==4&&v.npc(3).profile==3);CHECK(v.npc(3).position.x==472&&v.npc(3).position.y==88&&v.npc(3).body_id==11&&v.npc(3).segment_count==0);CHECK(v.dialogue(3).id==4&&v.dialogue(4).id==5&&v.dialogue(4).segment_count==3);CHECK(v.string(v.dialogue(3).source_path)=="Data/Dialogue/Podunk/cutscenes/doll_defeated.yaml");
 auto opened=v.openable_door(1);CHECK(opened.player_body_id==3&&opened.nonplayer_body_id==4&&opened.policy==1);CHECK(opened.trigger_center.x==64&&opened.trigger_center.y==353.5f&&opened.trigger_extents.y==19.5f);CHECK(opened.interact_center.y==368&&opened.collision_center.y==364);CHECK(opened.normal_mask==5&&opened.normal_values==1&&opened.action_mask==7&&opened.action_values==6);CHECK(opened.close_delay==.3&&opened.ram_required_y==-1&&opened.ram_duration==.2);CHECK(v.string(opened.flag)=="mimmie_door_opened");CHECK(v.string(v.openable_door(2).key)=="KeyBasement");CHECK(v.dialogue(opened.blocked_dialogue).first_segment==4);CHECK(v.segment(4).speaker==0&&v.segment(4).voice==0&&v.string(v.token(v.segment(4).first_token).text)=="The door won't open!");
 auto story=v.story_trigger(0);CHECK(story.center.x==128&&story.center.y==176&&story.extents.x==16&&story.extents.y==8);CHECK(story.disposition==2&&story.program_index==1&&story.condition_count==2);CHECK(v.npc(0).room_actor_index==5&&v.npc(1).room_actor_index==3&&v.npc(2).room_actor_index==2);CHECK(v.string(v.story_condition(0).flag)=="doll_melody"&&v.story_condition(0).kind==1&&!v.story_condition(0).value);CHECK(v.string(v.story_condition(1).flag)=="doll_defeated"&&v.story_condition(1).kind==2&&!v.story_condition(1).value);CHECK(v.door(4).destination.x==128&&v.door(4).destination.y==169&&v.door(5).destination.x==64&&v.door(5).destination.y==369);
 for(size_t n=0;n<b.size();++n){CHECK(!data.load(b.data(),n,error));}
 CHECK(data.view().npc(0).body_id==9);
 // Re-encoding the same expanded data with legacy limits is forbidden; the
 // decoder must also reject a future revision without replacing current state.
 for(uint32_t revision:{6u,8u}){auto bad=b;for(size_t offset:{size_t(8),size_t(24),size_t(28)})put(bad,offset,revision);fix(bad);CHECK(!data.load(bad.data(),bad.size(),error));CHECK(data.view().count(HouseSection::Dialogues)==66);}
 auto grow_section=[&](HouseSection section_id,uint32_t count){auto bad=b;const size_t directory=64+(uint32_t(section_id)-1)*16;const uint32_t offset=get(bad,directory+4),old_count=get(bad,directory+8),amount=get(bad,directory+12);const uint32_t stride=uint32_t(bad[directory+2])|(uint32_t(bad[directory+3])<<8);const uint32_t extra=(count-old_count)*stride;
  bad.insert(bad.begin()+offset+amount,extra,0);put(bad,directory+8,count);put(bad,directory+12,count*stride);for(uint32_t i=uint32_t(section_id);i<get(bad,20);++i){const size_t next=64+i*16;const auto start=get(bad,next+4);if(start)put(bad,next+4,start+extra);}put(bad,12,uint32_t(bad.size()));fix(bad);return bad;};
 for(auto limit:std::vector<std::pair<HouseSection,uint32_t>>{{HouseSection::Segments,257},{HouseSection::Dialogues,129},{HouseSection::Tokens,257}}){auto bad=grow_section(limit.first,limit.second);CHECK(!data.load(bad.data(),bad.size(),error));CHECK(error=="House capacity rejected");CHECK(data.view().count(HouseSection::Segments)==129);}
 for(auto edit:std::vector<std::pair<size_t,uint32_t>>{{8,0},{8,1},{8,2},{20,13},{24,0},{24,2},{28,2},{28,99},{52,1},{68,0},{72,999999},{80+2,99999}}){auto bad=b;put(bad,edit.first,edit.second);fix(bad);CHECK(!data.load(bad.data(),bad.size(),error));}
 auto d=section(b,HouseSection::Doors),n=section(b,HouseSection::Npcs),s=section(b,HouseSection::Segments),t=section(b,HouseSection::Tokens),q=section(b,HouseSection::Interaction),r=section(b,HouseSection::Resources),c=section(b,HouseSection::Clips),k=section(b,HouseSection::Keys),p=section(b,HouseSection::Parameters),o=section(b,HouseSection::Overrides),z=section(b,HouseSection::Boundaries);
 for(auto edit:std::vector<std::pair<size_t,uint32_t>>{{d,0},{d+4,2},{d+16,0x7fc00000},{d+24,0},{d+40,0},{d+52,0x7ff80000},{d+100,0x40000000},{n+8,0},{n+12,999},{n+20,999},{n+24,0},{n+28,0},{n+48,0},{n+84,16},{s+8,2},{s+12,999},{s+16,0},{s+20,4},{t,99},{t+12,1},{q+8,0},{q+16,0x7ff80000},{q+36,0},{q+40,0},{q+48,0},{q+56,0x7ff80000},{r+4,2},{r+8,9},{r+12,0},{r+20,0},{c,0},{c+4,99},{c+8,999},{c+12,999},{c+16,0},{c+24,0x7ff80000},{c+28,2},{c+32,2},{k+4,0x7ff80000},{k+8,0x7fc00000},{k+20,999},{p,99},{p+4,0x7fc00000},{o,999},{o+4,0},{o+8,2},{z+8,99},{z+20,0}}){auto bad=b;put(bad,edit.first,edit.second);fix(bad);CHECK(!data.load(bad.data(),bad.size(),error));}
 for(auto edit:std::vector<std::pair<uint32_t,uint32_t>>{{uint32_t(HouseParameter::DialogueRect),12},{uint32_t(HouseParameter::NameSizing),8},{uint32_t(HouseParameter::FontMetrics),4},{uint32_t(HouseParameter::DisplayReference),4},{uint32_t(HouseParameter::TextTiming),4}}){auto bad=b;put(bad,p+(edit.first-1)*20+edit.second,0);fix(bad);CHECK(!data.load(bad.data(),bad.size(),error));}
 auto pr=section(b,HouseSection::Profiles),di=section(b,HouseSection::Dialogues),op=section(b,HouseSection::OpenableDoors),st=section(b,HouseSection::StoryTriggers),sc=section(b,HouseSection::StoryConditions);
 for(auto edit:std::vector<std::pair<size_t,uint32_t>>{{n+88,999},{n+92,2},{n+96,64},{c+36,house_no_index},{pr+4,999},{pr+8,0x7fc00000},{pr+24,2},{pr+28,8},{di+8,999},{di+12,0},{op+8,0},{op+16,999},{op+36,999},{op+40,2},{op+60,16},{op+64,0},{op+68,8},{op+72,8},{op+80,0},{op+100,0},{op+164,0x40000000},{op+172,0x7ff80000},{op+196,0x7ff80000},{st+28,999},{st+32,0},{st+36,3},{st+40,house_no_index},{st+40,1024},{sc,9},{sc+4,0},{sc+8,2}}){auto bad=b;put(bad,edit.first,edit.second);fix(bad);CHECK(!data.load(bad.data(),bad.size(),error));}
 auto boundary=b;put(boundary,st+36,1);put(boundary,st+40,house_no_index);fix(boundary);CHECK(data.load(boundary.data(),boundary.size(),error));CHECK(data.view().story_trigger(0).disposition==1);put(boundary,st+40,0);fix(boundary);CHECK(!data.load(boundary.data(),boundary.size(),error));CHECK(data.view().story_trigger(0).disposition==1);CHECK(data.load(b.data(),b.size(),error));
 auto duplicate_actor=b;put(duplicate_actor,n+96,data.view().npc(1).room_actor_index);fix(duplicate_actor);CHECK(!data.load(duplicate_actor.data(),duplicate_actor.size(),error));
 auto duplicate=b;put(duplicate,d+112,get(b,d));fix(duplicate);CHECK(!data.load(duplicate.data(),duplicate.size(),error));auto orphan=b;put(orphan,s+12,1);fix(orphan);CHECK(!data.load(orphan.data(),orphan.size(),error));auto badcrc=b;badcrc.back()^=1;CHECK(!data.load(badcrc.data(),badcrc.size(),error));
 auto changed=b;float x=221;uint32_t bits;std::memcpy(&bits,&x,4);put(changed,d+32,bits);fix(changed);CHECK(data.load(changed.data(),changed.size(),error));CHECK(data.view().door(0).destination.x==221);CHECK(!data.load(badcrc.data(),badcrc.size(),error));CHECK(data.view().door(0).destination.x==221);CHECK(data.load(b.data(),b.size(),error));std::fill(b.begin(),b.end(),0);CHECK(data.view().door(0).destination.x==220);CHECK(!HouseView{}.valid());CHECK(HouseView{}.count(HouseSection::Doors)==0);CHECK(HouseView{}.clip_for(HouseClipRole::Cursor)==house_no_index);
 std::printf("HouseData: %u checks, bounded schema/opcode/span/ownership rejection and transactional data-only reload\n",checks);
}
