#include "encore/house_runtime.hpp"
#include "encore/house_presentation.hpp"
#include <cstdlib>
#include <iostream>
using namespace encore::upstream;
namespace {
void check(bool ok,const char*why){if(!ok){std::cerr<<why<<'\n';std::exit(1);}}
struct Effects {
 bool owns=false,reject=false;unsigned selected=0,removed=0,granted=0,starts=0,stops=0;
 OpeningWorld*world=nullptr;const BasementProgressionData*data=nullptr;
 HouseBasementHost host(){HouseBasementHost h;
  h.validate_key_item=[&](const BasementKeyItem&,std::string&e){if(reject){e="unadmitted source keybag";return false;}return true;};
  h.key_owned=[&](const BasementKeyItem&k,bool&out,std::string&){check(k.id==data->door().key_id,"door source item identity");out=owns;return true;};
  h.select_key_item=[&](const BasementKeyItem&,std::string&){check(world->story_flag(data->door().flag),"flag precedes current-item selection");++selected;return true;};
  h.remove_key_item=[&](const BasementKeyItem&,std::string&){++removed;return true;};
  h.grant_key_item=[&](const BasementKeyItem&k,std::string&){check(k.id==data->present().key_id,"diary source identity");check(!world->story_flag(data->present().flag),"keybag grant precedes Present flag");++granted;return true;};
  h.validate_present_sound=[](const BasementActorData&,std::string&){return true;};
  h.present_sound=[&](const BasementActorData&d,bool playing,std::string&){check(!d.present_sound().empty(),"admitted source audio");if(playing)++starts;else ++stops;return true;};return h;
 }
};
void bind_music(OpeningWorld&w,const BasementProgressionData&d,const BasementActorData&actors,std::string&e){BasementProgressionHost host;host.validate_key_item=[&d](const BasementKeyItem&k,std::string&){const auto*source=d.key_item(k.id);return source&&source->source==k.source&&source->doses==k.doses&&source->grant==k.grant;};host.validate_skill=[&d](const BasementSkill&s,std::string&){const auto*source=d.skill(s.id);return source&&source->character==s.character&&source->skill==s.skill&&source->sort_rank==s.sort_rank;};host.grant_key_item=[](const BasementKeyItem&,std::string&e){e="World keygrant is outside Door/Present consumer suite";return false;};host.learn_skill=[](const BasementSkill&,std::string&e){e="World skillgrant is outside Door/Present consumer suite";return false;};check(w.bind_basement(d,actors,host,e),e.c_str());check(w.bind_music_region_validator([&d](std::string_view scene,std::string_view node,bool play,double fade,std::string&e){for(const auto&r:d.music_regions())if(r.scene==scene&&r.node==node){if((play&&fade==0)||(!play&&(fade==0||fade==r.default_stop_seconds))){e.clear();return true;}}e="Unreviewed source music call";return false;},e),e.c_str());}
void approach(OpeningWorld&w,HouseView house,Vec2 center,Vec2 extents){const auto ray=house.interaction();check(w.warp_same_scene({center.x-ray.ray_origin.x,center.y+extents.y+ray.ray_length/2-ray.ray_origin.y},{0,-1}),"source interaction approach");}
}
int main(int argc,char**argv){
 check(argc==6,"House, Room, font, basement and actor binary paths required");std::string e;HouseData house;RoomData room;BattleData font;BasementProgressionData data;BasementActorData actors;
 check(house.load_file(argv[1],e),e.c_str());check(room.load_file(argv[2],e),e.c_str());check(font.load_file(argv[3],e),e.c_str());check(data.load_file(argv[4],e),e.c_str());check(actors.load_file(argv[5],e),e.c_str());
 SourceRandom random(91);OpeningWorld world;HousePresentation presentation;HouseRuntime runtime;Effects effects;effects.world=&world;effects.data=&data;
 bind_music(world,data,actors,e);check(world.initialize(room.view()),world.error());world.attach_random(random);check(world.set_story_flag(data.door().flag,false,false),"source door flag linked");check(world.set_story_flag(data.present().flag,false,false),"source diary flag linked");
 check(presentation.begin(house.view(),font.view(),random),presentation.error());check(runtime.initialize(house.view(),world,presentation),runtime.error());
 auto missing=effects.host();missing.grant_key_item={};check(!runtime.bind_basement(data,actors,missing,e),"missing grant host rejected");check(!runtime.basement_bound()&&runtime.phase()==HousePhase::Idle&&!world.house_paused(),"failed admission has no scene mutation");
 effects.reject=true;check(!runtime.bind_basement(data,actors,effects.host(),e),"unadmitted source item rejected");effects.reject=false;check(runtime.bind_basement(data,actors,effects.host(),e),e.c_str());check(!runtime.basement_present_opened()&&runtime.basement_present_frame()==data.present().closed_frame,"Ready closed source frame");
 BasementActorData invalid;check(!runtime.bind_basement(data,invalid,effects.host(),e)&&runtime.basement_bound(),"failed replacement keeps previous checked binding");
 uint32_t door=house_no_index;for(uint32_t i=0;i<house.view().count(HouseSection::OpenableDoors);++i)if(house.view().string(house.view().openable_door(i).source_path)==data.door().node)door=i;check(door!=house_no_index&&runtime.door_interaction_supported(door),"actual Door3 bound");
 const auto source_door=house.view().openable_door(door);const double dt=double(float(1./60));
 auto finish_feedback=[&](){for(unsigned frame=0;frame<2000&&runtime.phase()!=HousePhase::Idle;++frame){check(world.idle_frame(dt),world.error());check(presentation.physics_frame(dt,world.player().position),presentation.error());check(presentation.idle_frame(dt),presentation.error());check(runtime.idle_frame(dt,true,false),runtime.error());}check(runtime.phase()==HousePhase::Idle,"source feedback returns control");};
 approach(world,house.view(),source_door.interact_center,source_door.interact_extents);check(runtime.idle_frame(dt,true,false),runtime.error());check(runtime.phase()==HousePhase::StoryRunning&&!runtime.openable_state(door).unlocked&&!world.story_flag(data.door().flag)&&!effects.selected&&!effects.removed,"missing key selects source locked feedback only");check(room.view().string(room.view().program(world.story_program_index()).source_path_string)==data.door().locked,"locked feedback programme identity");finish_feedback();
 effects.owns=true;approach(world,house.view(),source_door.interact_center,source_door.interact_extents);check(runtime.idle_frame(dt,true,false),runtime.error());check(runtime.openable_state(door).unlocked&&runtime.openable_state(door).action&&world.story_flag(data.door().flag)&&effects.selected==1&&effects.removed==unsigned(data.door().remove_key),"owned key writes flag, opens, unlocks, preserves source removal policy");check(room.view().string(room.view().program(world.story_program_index()).source_path_string)==data.door().opened,"opened feedback programme identity");check(runtime.after_physics(),runtime.error());check(!world.body_enabled(source_door.player_body_id),"unlock uses deferred collider change");finish_feedback();
 const auto rect=data.present().interaction;approach(world,house.view(),{rect.x,rect.y},{rect.z,rect.w});check(runtime.idle_frame(dt,true,false),runtime.error());check(effects.granted==1&&runtime.basement_present_opened()&&world.story_flag(data.present().flag),"Present grants source keybag then flag synchronously");check(runtime.basement_present_playback().visible&&runtime.basement_present_playback().elapsed==0&&!effects.starts,"source play schedules time-zero audio for next idle");check(room.view().string(room.view().program(world.story_program_index()).source_path_string)==data.present().dialogue,"complete authored diary graph begins in existing Room scheduler");
 for(unsigned i=0;i<50;++i)check(runtime.idle_frame(dt,false,false),runtime.error());check(effects.starts==1&&effects.stops==1&&runtime.basement_present_frame()==data.present().opened_frame,"idle sprite keys hold final frame and stop source audio once");check(runtime.seen_dialogue_keys().empty(),"Door and Present do not write NPC seen flags");
 // A fresh scene with the persisted source flag reconstructs Present Ready;
 // this is distinct from fabricating completion of the dream programme.
 OpeningWorld restored;HousePresentation restored_presentation;HouseRuntime restored_runtime;Effects restored_effects;restored_effects.world=&restored;restored_effects.data=&data;bind_music(restored,data,actors,e);check(restored.initialize(room.view()),restored.error());restored.attach_random(random);check(restored.set_story_flag(data.present().flag,true,false),"restore diary flag");check(restored_presentation.begin(house.view(),font.view(),random),restored_presentation.error());check(restored_runtime.initialize(house.view(),restored,restored_presentation),restored_runtime.error());check(restored_runtime.bind_basement(data,actors,restored_effects.host(),e),e.c_str());check(restored_runtime.basement_present_frame()==data.present().opened_frame&&!restored_runtime.basement_present_playback().visible,"Ready source opened frame without replay");approach(restored,house.view(),{rect.x,rect.y},{rect.z,rect.w});check(restored_runtime.idle_frame(dt,true,false),restored_runtime.error());check(restored_effects.granted==0&&restored_effects.starts==0&&room.view().string(room.view().program(restored.story_program_index()).source_path_string)==data.present().empty,"repeat Present uses source empty graph without another UID/audio");
 std::cout<<"Actual House basement admission, key/flag/deferred collider, Present source sequence and persisted repeat cases\n";
}
