#include "encore/localized_presentation.hpp"
#include "encore/new_game_setup.hpp"
#include "encore/battle_action_presentation.hpp"
#include "encore/source_font.hpp"
#include "encore/utf8.hpp"
#include <cassert>
#include <iostream>
using namespace encore::upstream;
bool advance(void*p,uint32_t cp,float&value){std::string error;return static_cast<encore::SourceFontCatalog*>(p)->advance(cp,value,error);}
int main(int argc,char**argv){assert(argc==4);const std::string base=argv[1];std::string e;LocaleCatalog catalog;if(!catalog.load_file(argv[2],e)){std::cerr<<e;return 1;}LocaleSelection selected;assert(selected.bind(catalog,e));assert(!selected.select("pl",e));assert(selected.select("zh_CN",e));LocalizedPresentation locale(selected);encore::SourceFontCatalog fonts;assert(fonts.load(argv[3],e));assert(fonts.select_font("Fonts/EBMain_zh_cn.tres",e));
 HouseData house;BattleData battle;assert(house.load_file((base+"/opening.enchouse").c_str(),e));assert(battle.load_file((base+"/opening.encbattle").c_str(),e));SourceRandom random(0);uint32_t checked=0,inline_wait=0,source_changes=0;
 for(uint32_t first=0;first<house.view().count(HouseSection::Segments);++first)for(uint32_t count=1;count<=8;++count){if(!catalog.binding("house/"+std::to_string(first)+"/"+std::to_string(count)))continue;LocalizedHouseSpan span;if(!locale.house(house.view(),first,count,"Ab",span,e)){std::cerr<<first<<" "<<e<<"\n";return 2;}source_changes+=span.segments.size()!=count;for(auto&segment:span.segments)for(auto&token:segment.tokens)inline_wait+=token.kind==10;HousePresentation presentation;assert(presentation.begin(house.view(),battle.view(),random));presentation.set_text_value_callback([](void*,HouseTokenKind,std::string&value){value="5";return true;},nullptr);presentation.set_locale_resolver(LocalizedPresentation::resolve_house,&locale);presentation.set_glyph_advance(advance,&fonts);presentation.set_font_line_height(fonts.selected()->height);if(!presentation.begin_dialogue(first,count,"Ab")){std::cerr<<"House "<<first<<": "<<presentation.error()<<"\n";return 3;}for(unsigned frame=0;frame<3000&&!presentation.dialogue_finished();++frame){presentation.input(true,false,true);assert(presentation.physics_frame(.016,{0,0}));assert(presentation.idle_frame(.016));}assert(presentation.dialogue_finished());for(const auto&line:presentation.dialogue_pose().lines){float width=0;assert(fonts.measure(line.text,width,e));assert(width<=house.view().parameter(HouseParameter::DialogueText).z);}++checked;}
 assert(checked>=49&&inline_wait==2&&source_changes>0);
 for(const char*filename:{"opening.encround","doll-entry.encround","pillow-entry.encround"}){BattleRoundData round;assert(round.load_file((base+"/"+filename).c_str(),e));for(uint32_t i=0;i<round.view().count(RoundSection::Texts);++i){std::string value;if(!locale.battle(round.view(),i,"Ab",value,e)){std::cerr<<filename<<":"<<i<<" "<<e<<"\n";return 4;}for(size_t p=0;p<value.size();){uint32_t cp;assert(encore::utf8_next(value,p,cp));if(cp=='\n')continue;float w;if(!fonts.advance(cp,w,e)){std::cerr<<filename<<":"<<i<<" "<<e<<"\n";return 5;}}}BattleTextPacer pacer;assert(pacer.begin(round.view(),"名字A"));assert(pacer.set_text_speed(.01));assert(pacer.physics_frame(.015));assert(pacer.visible_characters()==1&&pacer.visible_text()=="名");assert(pacer.begin(round.view(),"名\n字"));assert(pacer.physics_frame(.015));assert(pacer.visible_characters()==1&&pacer.visible_text()=="名\n");}
 NewGameSetupData naming;StartupSettingsData settings;assert(naming.load_file((base+"/opening.encnewgame").c_str(),e));assert(settings.load_file((base+"/opening.encsettings").c_str(),e));for(size_t p=0;p<settings.panels.size();++p)for(size_t i=0;i<settings.panels[p].labels.size();++i){std::string out;assert(catalog.bound("settings.panel/"+std::to_string(p)+"/"+std::to_string(i),settings.panels[p].labels[i].text,selected.code(),out,e));assert(!out.empty());float width;assert(fonts.measure(out,width,e));}
 NewGameSetup menu;menu.set_locale(&selected);assert(menu.open(naming,settings,e));const auto original=menu.name();assert(menu.prompt()!="What is this boy's name?");assert(menu.name()==original);assert(selected.select("en",e));assert(menu.prompt()=="What is this boy's name?"&&menu.name()==original);
 std::cout<<"Localized slice passed: "<<checked<<" House spans, inline WAIT, changed translated segment counts, all three battle text records, shared scalar pacing, naming language toggle with unchanged names\n";
}
