#include "encore/basement_progression.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <set>
namespace encore::upstream {namespace {
uint32_t word(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
float real(const uint8_t*p){const auto v=word(p);float f;std::memcpy(&f,&v,4);return f;}
bool reject(std::string&e,const char*s){e=s;return false;}
bool identifier(std::string_view s){return !s.empty()&&s.size()<=256&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c=='_'||c>='a'&&c<='z'||c>='A'&&c<='Z'||c>='0'&&c<='9';});}
bool path(std::string_view s){if(s.empty()||s.size()>4096||s.front()=='/'||s.back()=='/'||s.find('\\')!=s.npos||s.find(':')!=s.npos)return false;size_t at=0;while(at<s.size()){auto end=s.find('/',at);if(end==s.npos)end=s.size();const auto part=s.substr(at,end-at);if(part.empty()||part=="."||part=="..")return false;for(unsigned char c:part)if(c<32||c==127)return false;at=end+1;}return true;}
bool utf8(std::string_view s){size_t at=0;while(at<s.size()){uint32_t c=uint8_t(s[at++]),n=0,min=0;if(c<128){if(c<32||c==127)return false;continue;}if(c>=0xc2&&c<=0xdf){c&=31;n=1;min=128;}else if(c>=0xe0&&c<=0xef){c&=15;n=2;min=2048;}else if(c>=0xf0&&c<=0xf4){c&=7;n=3;min=65536;}else return false;if(at+n>s.size())return false;while(n--){const auto b=uint8_t(s[at++]);if((b&192)!=128)return false;c=c<<6|(b&63);}if(c<min||c>0x10ffff||(c>=0xd800&&c<=0xdfff))return false;}return true;}
uint32_t checksum(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=i>=16&&i<20?0:p[i];for(int k=0;k<8;++k)c=c>>1^(0xedb88320u&uint32_t(-int32_t(c&1)));}return ~c;}
}
bool BasementProgressionData::load(const uint8_t*p,size_t n,std::string&e){
 const uint32_t strides[]={1,20,16,4,16,24,88,20,8,12,52,12,16};constexpr uint32_t sections=13,header=64+sections*16;
 if(!p||n<header||n>1024*1024||std::memcmp(p,"ENCBASM1",8)||word(p+8)!=1||word(p+12)!=n||word(p+20)!=1||word(p+24)!=1||word(p+28)!=sections||word(p+16)!=checksum(p,n))return reject(e,"Basement header/version/CRC rejected");
 for(size_t i=52;i<64;++i)if(p[i])return reject(e,"Basement header reserved bytes rejected");bool pin=false;for(size_t i=32;i<52;++i)pin|=p[i]!=0;if(!pin)return reject(e,"Basement source pin missing");
 uint32_t offsets[sections]{},counts[sections]{};size_t end=header;
 for(uint32_t i=0;i<sections;++i){const auto*d=p+64+i*16;const auto aligned=(end+3)&~size_t(3);for(size_t j=end;j<aligned;++j)if(j>=n||p[j])return reject(e,"Basement alignment rejected");end=aligned;offsets[i]=word(d+4);counts[i]=word(d+8);if(word(d)!=i+1||offsets[i]!=end||word(d+12)!=strides[i]||counts[i]>65536||size_t(counts[i])*strides[i]>n-end)return reject(e,"Basement directory rejected");end+=size_t(counts[i])*strides[i];}
 if(end!=n||!counts[0]||counts[0]>65536||p[offsets[0]]||p[offsets[0]+counts[0]-1]||counts[1]!=3||counts[2]!=1||!counts[3]||counts[3]>512||!counts[4]||counts[4]>32||counts[5]!=1||counts[6]!=1||counts[7]<2||counts[7]>64||counts[8]!=1||counts[9]!=1||(!counts[10]||counts[10]>16)||counts[11]!=counts[10]||counts[12]!=1)return reject(e,"Basement section capacity/trailing rejected");
 std::set<uint32_t>starts;for(uint32_t at=0;at<counts[0];){starts.insert(at);const auto*begin=p+offsets[0]+at;const auto*last=std::find(begin,p+offsets[0]+counts[0],uint8_t(0));const std::string_view s(reinterpret_cast<const char*>(begin),size_t(last-begin));if(s.size()>4096||!utf8(s))return reject(e,"Basement string UTF-8 rejected");at+=uint32_t(s.size())+1;}
 bool refs=true;auto text=[&](uint32_t at){if(!starts.count(at)){refs=false;return std::string{};}return std::string(reinterpret_cast<const char*>(p+offsets[0]+at));};auto row=[&](uint32_t section,uint32_t index){return p+offsets[section]+size_t(index)*strides[section];};
 BasementProgressionData candidate;const char*hex="0123456789abcdef";for(size_t i=32;i<52;++i){candidate.commit_+=hex[p[i]>>4];candidate.commit_+=hex[p[i]&15];}
 std::set<uint32_t>ids;std::set<std::string>names;
 for(uint32_t i=0;i<counts[1];++i){const auto*r=row(1,i);BasementKeyItem k{word(r),word(r+8),word(r+12)!=0,text(word(r+4)),text(word(r+16))};if(!k.id||!ids.insert(k.id).second||!identifier(k.source)||!names.insert(k.source).second||!k.doses||k.doses>65535||word(r+12)>1||!identifier(k.name_key))return reject(e,"Basement key item binding rejected");candidate.keys_.push_back(std::move(k));}
 names.clear();for(uint32_t i=0;i<counts[3];++i){auto id=text(word(row(3,i)));if(!identifier(id)||!names.insert(id).second)return reject(e,"Basement skill ordering rejected");candidate.order_.push_back(std::move(id));}
 for(uint32_t i=0;i<counts[2];++i){const auto*r=row(2,i);BasementSkill s{word(r),word(r+12),text(word(r+4)),text(word(r+8))};if(!s.id||!identifier(s.character)||!identifier(s.skill)||s.sort_rank>=candidate.order_.size()||candidate.order_[s.sort_rank]!=s.skill)return reject(e,"Basement learned skill policy rejected");candidate.skills_.push_back(std::move(s));}
 std::set<bool>defaults;
 for(uint32_t i=0;i<counts[4];++i){const auto*r=row(4,i);BasementNpcOverride o{word(r)!=0,word(r+12)!=0,text(word(r+4)),text(word(r+8))};if(word(r)>1||word(r+12)>1||(!o.flag.empty()&&!identifier(o.flag))||!path(o.program))return reject(e,"Basement NPC override rejected");if(o.flag.empty()&&!defaults.insert(o.thoughts).second)return reject(e,"Basement duplicate default NPC path");candidate.overrides_.push_back(std::move(o));}
 if(defaults.size()!=2)return reject(e,"Basement NPC default missing");
 const auto*mick=row(9,0);candidate.mick_scene_=text(word(mick));candidate.mick_node_=text(word(mick+4));candidate.telepathy_skill_=text(word(mick+8));if(!path(candidate.mick_scene_)||!path(candidate.mick_node_)||!identifier(candidate.telepathy_skill_)||std::find(candidate.order_.begin(),candidate.order_.end(),candidate.telepathy_skill_)==candidate.order_.end())return reject(e,"Basement Mick source/skill rejected");
 const auto*d=row(5,0);candidate.door_={word(d+4),word(d+12)!=0,text(word(d)),text(word(d+8)),text(word(d+16)),text(word(d+20))};if(!ids.count(candidate.door_.key_id)||word(d+12)>1||!path(candidate.door_.node)||!identifier(candidate.door_.flag)||!path(candidate.door_.opened)||!path(candidate.door_.locked))return reject(e,"Basement door binding rejected");
 const auto*r=row(6,0);candidate.present_={word(r+4),word(r+20),text(word(r)),text(word(r+8)),text(word(r+12)),text(word(r+16)),{real(r+24),real(r+28),real(r+32),real(r+36)},{real(r+40),real(r+44),real(r+48),real(r+52)},word(r+56)!=0,word(r+60),word(r+64)!=0,word(r+68)!=0,word(r+72)!=0,word(r+76)!=0,word(r+80),word(r+84)};const auto&present=candidate.present_;if(word(r+56)>1||word(r+60)>3||word(r+64)>1||word(r+68)||word(r+72)||word(r+76)||word(r+80)>=65536||!word(r+84))return reject(e,"Basement present flag/pickup/turn policy rejected");if(!ids.count(present.key_id)||present.opened_frame>=65536||!path(present.node)||!identifier(present.flag)||!path(present.dialogue)||!path(present.empty)||!std::isfinite(present.geometry.x)||!std::isfinite(present.geometry.y)||!std::isfinite(present.geometry.z)||!std::isfinite(present.geometry.w)||std::abs(present.geometry.x)>8192||std::abs(present.geometry.y)>8192||present.geometry.z<=0||present.geometry.w<=0||present.geometry.z>8192||present.geometry.w>8192)return reject(e,"Basement present binding rejected");for(float value:{present.interaction.x,present.interaction.y,present.interaction.z,present.interaction.w})if(!std::isfinite(value)||std::abs(value)>8192)return reject(e,"Basement present interaction rejected");if(present.interaction.z<=0||present.interaction.w<=0)return reject(e,"Basement present interaction extent rejected");
 std::set<uint32_t>music_ids;std::set<std::string>music_nodes;for(uint32_t i=0;i<counts[10];++i){const auto*music=row(10,i);BasementMusicBinding binding={text(word(music)),text(word(music+4)),text(word(music+8)),word(music+12),word(music+16),real(music+20),real(music+24),real(music+28),real(music+32),{real(music+36),real(music+40),real(music+44),real(music+48)}};const auto&mb=binding;if(!path(mb.scene)||!path(mb.node)||mb.music.substr(0,6)!="res://"||!path(std::string_view(mb.music).substr(6))||!mb.track_id||!mb.region_id||!music_ids.insert(mb.region_id).second||!music_nodes.insert(mb.node).second)return reject(e,"Basement music identity rejected");for(float v:{mb.default_stop_seconds,mb.fadein_seconds,mb.fadeout_seconds})if(!std::isfinite(v)||v<0||v>60)return reject(e,"Basement music fade rejected");if(!std::isfinite(mb.volume_db)||mb.volume_db < -120||mb.volume_db>24)return reject(e,"Basement music gain rejected");for(float v:{mb.geometry.x,mb.geometry.y,mb.geometry.z,mb.geometry.w})if(!std::isfinite(v)||std::abs(v)>8192)return reject(e,"Basement music geometry rejected");if(mb.geometry.z<=0||mb.geometry.w<=0)return reject(e,"Basement music area extent rejected");candidate.music_regions_.push_back(std::move(binding));}std::set<uint32_t>ordinals;for(uint32_t i=0;i<counts[11];++i){const auto*r=row(11,i);auto&binding=candidate.music_regions_[i];binding.parent_disappear_flag=text(word(r+4));binding.source_ordinal=word(r+8);if(word(r)!=binding.region_id||(!binding.parent_disappear_flag.empty()&&!identifier(binding.parent_disappear_flag))||!binding.source_ordinal||!ordinals.insert(binding.source_ordinal).second)return reject(e,"Basement music lifecycle/order rejected");}candidate.music_=candidate.music_regions_.front();const auto*rect=row(12,0);candidate.fade_rect_={real(rect),real(rect+4),real(rect+8),real(rect+12)};for(float v:{candidate.fade_rect_.x,candidate.fade_rect_.y,candidate.fade_rect_.z,candidate.fade_rect_.w})if(!std::isfinite(v)||std::abs(v)>8192)return reject(e,"Diary fade geometry rejected");if(candidate.fade_rect_.z<=0||candidate.fade_rect_.w<=0)return reject(e,"Diary fade extent rejected");
 float previous=-1;
 for(uint32_t i=0;i<counts[7];++i){const auto*k=row(7,i);BasementFadeKey f{real(k),{real(k+4),real(k+8),real(k+12),real(k+16)}};if(!std::isfinite(f.time)||f.time<0||f.time<=previous)return reject(e,"Basement fade time rejected");for(float c:{f.color.x,f.color.y,f.color.z,f.color.w})if(!std::isfinite(c)||c<0||c>1)return reject(e,"Basement fade color rejected");previous=f.time;candidate.fade_.push_back(f);}
 const auto*parameter=row(8,0);candidate.fade_length_=real(parameter+4);if(word(parameter)!=1||!std::isfinite(candidate.fade_length_)||candidate.fade_length_<=0||candidate.fade_length_>120||candidate.fade_.front().time!=0||candidate.fade_.back().time!=candidate.fade_length_)return reject(e,"Basement fade duration rejected");if(!refs)return reject(e,"Basement string reference rejected");candidate.valid_=true;*this=std::move(candidate);e.clear();return true;
}
bool BasementProgressionData::load_file(const char*path,std::string&e){if(!path||!*path)return reject(e,"Basement file path missing");FILE*f=std::fopen(path,"rb");if(!f)return reject(e,"Basement file unavailable");std::vector<uint8_t>b;uint8_t block[4096];bool ok=true;for(;;){const auto n=std::fread(block,1,sizeof block,f);if(b.size()+n>1024*1024){ok=false;break;}b.insert(b.end(),block,block+n);if(n<sizeof block){ok=!std::ferror(f);break;}}if(std::fclose(f))ok=false;if(!ok)return reject(e,"Basement file read rejected");return load(b.data(),b.size(),e);}
bool BasementProgressionData::bind_reviewed_commit(std::string_view pin,std::string&e)const{if(!valid_||pin!=commit_)return reject(e,"Basement reviewed source binding rejected");e.clear();return true;}
const BasementKeyItem*BasementProgressionData::key_item(uint32_t id)const{const auto at=std::find_if(keys_.begin(),keys_.end(),[&](const auto&k){return k.id==id;});return at==keys_.end()?nullptr:&*at;}
const BasementSkill*BasementProgressionData::skill(uint32_t id)const{const auto at=std::find_if(skills_.begin(),skills_.end(),[&](const auto&k){return k.id==id;});return at==skills_.end()?nullptr:&*at;}
BattleValue BasementProgressionData::white_fade(double elapsed)const{if(!valid_||!std::isfinite(elapsed)||elapsed<0)return {};if(elapsed>=fade_length_)return fade_.back().color;const auto right=std::upper_bound(fade_.begin(),fade_.end(),elapsed,[](double t,const auto&k){return t<k.time;});if(right==fade_.begin())return right->color;const auto&left=*(right-1);const auto amount=float((elapsed-left.time)/(right->time-left.time));return {left.color.x+(right->color.x-left.color.x)*amount,left.color.y+(right->color.y-left.color.y)*amount,left.color.z+(right->color.z-left.color.z)*amount,left.color.w+(right->color.w-left.color.w)*amount};}
bool BasementProgressionData::mick_program(bool thoughts,const BasementFlagQuery&query,std::string&program,std::string&e)const{if(!valid_||!query)return reject(e,"Basement NPC selection requires checked flag host");const BasementNpcOverride*selected=nullptr;for(const auto&o:overrides_){if(o.thoughts!=thoughts)continue;bool enabled=o.flag.empty();if(!enabled&&!query(o.flag,enabled,e))return false;if(enabled)selected=&o;}if(!selected||!selected->supported)return reject(e,"Basement selected Mick branch unsupported");program=selected->program;e.clear();return true;}
bool prepare_basement_key_item(const BasementProgressionData&data,uint32_t id,uint32_t uid,const SessionSnapshot&state,SessionSnapshot&out,std::string&e){const auto*policy=data.key_item(id);if(!data.valid()||!policy||!policy->grant)return reject(e,"Basement grant key item unsupported");if(!validate_session_snapshot(state,e))return false;std::set<uint32_t>uids;auto check=[&](const SessionItem&i){if(!uids.insert(i.uid).second)return false;return i.uid!=uid;};for(const auto&c:state.characters)for(const auto&i:c.inventory)if(!check(i))return reject(e,"Basement grant UID collision");for(const auto&i:state.storage)if(!check(i))return reject(e,"Basement grant UID collision");for(const auto&i:state.key_items){const auto known=std::find_if(data.key_items().begin(),data.key_items().end(),[&](const auto&k){return k.source==i.item_id;});if(!check(i)||known==data.key_items().end()||i.equipped||i.doses!=known->doses)return reject(e,"Basement existing key item/UID rejected");}auto next=state;next.key_items.push_back({policy->source,false,policy->doses,uid});if(!validate_session_snapshot(next,e))return false;out=std::move(next);e.clear();return true;}
bool prepare_basement_skill(const BasementProgressionData&data,uint32_t id,const SessionCharacter&state,SessionCharacter&out,std::string&e){const auto*policy=data.skill(id);if(!data.valid()||!policy||policy->character!=state.character_id)return reject(e,"Basement learned skill target rejected");std::set<std::string>seen;for(const auto&s:state.learned_skills)if(!seen.insert(s).second||std::find(data.skill_order().begin(),data.skill_order().end(),s)==data.skill_order().end())return reject(e,"Basement existing learned skill unsupported");auto next=state;if(!seen.count(policy->skill))next.learned_skills.push_back(policy->skill);std::sort(next.learned_skills.begin(),next.learned_skills.end(),[&](const auto&a,const auto&b){return std::find(data.skill_order().begin(),data.skill_order().end(),a)<std::find(data.skill_order().begin(),data.skill_order().end(),b);});out=std::move(next);e.clear();return true;}
bool BasementProgressionConsumer::bind(const BasementProgressionData&data,BasementProgressionHost host,std::string&e){if(!data.valid()||!host.validate_key_item||!host.grant_key_item||!host.validate_skill||!host.learn_skill)return reject(e,"Basement effect host missing");for(const auto&k:data.key_items())if(k.grant&&!host.validate_key_item(k,e))return false;for(const auto&s:data.skills())if(!host.validate_skill(s,e))return false;data_=&data;host_=std::move(host);e.clear();return true;}
bool BasementProgressionConsumer::grant_key_item(uint32_t id,std::string&e){const auto*k=data_?data_->key_item(id):nullptr;if(!k||!k->grant)return reject(e,"Basement unknown grant instruction");return host_.grant_key_item(*k,e);}
bool BasementProgressionConsumer::learn_skill(uint32_t id,std::string&e){const auto*s=data_?data_->skill(id):nullptr;if(!s)return reject(e,"Basement unknown learn instruction");return host_.learn_skill(*s,e);}
}
