#include "encore/basement_actor_assets.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iterator>
#include <set>
namespace encore::upstream {namespace {
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
float f32(const uint8_t*p){uint32_t u=u32(p);float f;std::memcpy(&f,&u,4);return f;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=(i>=16&&i<20)?0:p[i];for(int b=0;b<8;++b)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
bool utf8(const uint8_t*p,size_t n){for(size_t i=0;i<n;){unsigned c=p[i++];if(c<128)continue;unsigned count=c>=0xc2&&c<=0xdf?1:c>=0xe0&&c<=0xef?2:c>=0xf0&&c<=0xf4?3:0;if(!count||i+count>n)return false;unsigned cp=c&((1u<<(6-count))-1);for(unsigned k=0;k<count;++k){unsigned q=p[i++];if((q&0xc0)!=0x80)return false;cp=cp*64+(q&63);}if((count==1&&cp<128)||(count==2&&cp<2048)||(count==3&&cp<65536)||(cp>=0xd800&&cp<=0xdfff)||cp>0x10ffff)return false;}return true;}
bool path(std::string_view p,std::string_view prefix,std::string_view suffix){return p.size()>prefix.size()+suffix.size()&&p.substr(0,prefix.size())==prefix&&p.substr(p.size()-suffix.size())==suffix&&p.find("..") ==p.npos&&p.find('\\')==p.npos;}
}
const BasementActorResource*BasementActorData::resource(uint32_t id)const{for(const auto&r:resources_)if(r.id==id)return&r;return nullptr;}
const BasementActorAnimation*BasementActorData::animation(uint32_t id)const{for(const auto&a:animations_)if(a.id==id)return&a;return nullptr;}
bool BasementActorData::load_file(const char*name,std::string&e){if(!name){e="Basement sprite path missing";return false;}std::ifstream f(name,std::ios::binary);if(!f){e="Basement sprite pack unavailable";return false;}f.seekg(0,std::ios::end);const auto n=f.tellg();if(n<160||n>1024*1024){e="Basement sprite file size";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)){e="Basement sprite file read";return false;}return load(b.data(),b.size(),e);}
bool BasementActorData::load(const uint8_t*p,size_t n,std::string&e){
 auto fail=[&](const char*s){e=s;return false;};if(!p||n<160||n>1024*1024)return fail("Basement sprite size");if(std::memcmp(p,"ENCBANM1",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+20)!=1||u32(p+24)!=1||u32(p+28)!=6||u32(p+16)!=crc(p,n))return fail("Basement sprite header/version/CRC");for(size_t i=52;i<64;++i)if(p[i])return fail("Basement sprite reserved header");
 std::array<uint32_t,6>offset{},count{};constexpr uint32_t stride[]={1,64,28,8,16,20};size_t end=160;for(size_t i=0;i<6;++i){const auto*d=p+64+i*16;offset[i]=u32(d+4);count[i]=u32(d+8);const uint64_t size=uint64_t(count[i])*stride[i];if(u32(d)!=i+1||u32(d+12)!=stride[i]||offset[i]!=((end+3)&~size_t(3))||offset[i]>n||size>n-offset[i])return fail("Basement sprite directory");for(;end<offset[i];++end)if(p[end])return fail("Basement sprite padding");end=offset[i]+size;}
 if(end!=n||!count[0]||count[0]>65536||count[1]!=2||count[2]!=3||!count[3]||count[3]>1024||count[4]!=count[1]||count[5]!=1)return fail("Basement sprite counts/trailing data");const auto*s=p+offset[0];if(s[0]||s[count[0]-1]||!utf8(s,count[0]))return fail("Basement sprite UTF8");std::set<uint32_t>starts{0};for(uint32_t i=0;i+1<count[0];++i)if(!s[i])starts.insert(i+1);auto text=[&](uint32_t id,std::string&out){if(!starts.count(id))return false;out=std::string(reinterpret_cast<const char*>(s+id));return true;};
 BasementActorData next;const char*hex="0123456789abcdef";for(size_t i=32;i<52;++i){next.commit_+=hex[p[i]>>4];next.commit_+=hex[p[i]&15];}std::set<uint32_t>ids;
 for(uint32_t i=0;i<count[1];++i){const auto*r=p+offset[1]+i*64;const auto*g=p+offset[4]+i*16;BasementActorResource a;a.id=u32(r);a.width=u32(r+12);a.height=u32(r+16);a.columns=u32(r+20);a.rows=u32(r+24);a.position={f32(g),f32(g+4)};a.offset={f32(g+8),f32(g+12)};std::copy(r+32,r+64,a.sha256.begin());if(!a.id||a.id==0xffffffff||!ids.insert(a.id).second||!text(u32(r+4),a.path)||!text(u32(r+8),a.source)||!path(a.path,"graphics/story/basement/",".t3x")||!path(a.source,"Graphics/",".png")||!a.width||!a.height||a.width>4096||a.height>4096||!a.columns||!a.rows||a.width%a.columns||a.height%a.rows||uint64_t(a.columns)*a.rows>65536||!text(u32(r+28),a.primary_path)||(!a.primary_path.empty()&&!path(a.primary_path,"graphics/actors/",".t3x"))||std::all_of(a.sha256.begin(),a.sha256.end(),[](uint8_t v){return!v;}))return fail("Basement sprite resource");for(uint32_t j=0;j<4;++j)if(!std::isfinite(f32(g+4*j))||std::abs(f32(g+4*j))>=1e6)return fail("Basement sprite transform");next.resources_.push_back(a);}
 ids.clear();uint32_t owned=0;for(uint32_t i=0;i<count[2];++i){const auto*r=p+offset[2]+i*28;BasementActorAnimation a;a.id=u32(r);a.resource_id=u32(r+8);a.length=f32(r+24);const uint32_t first=u32(r+12),len=u32(r+16);const auto*res=next.resource(a.resource_id);if(!a.id||a.id==0xffffffff||!ids.insert(a.id).second||!text(u32(r+4),a.name)||a.name.empty()||!res||first!=owned||!len||len>count[3]-owned||u32(r+20)!=1||!std::isfinite(a.length)||a.length<=0||a.length>3600)return fail("Basement sprite animation");for(uint32_t k=0;k<len;++k){const auto*q=p+offset[3]+(first+k)*8;BasementActorKey key{f32(q),u32(q+4)};if(!std::isfinite(key.time)||key.time<0||key.time>=a.length||(!k&&key.time)||(k&&key.time<=a.keys.back().time)||key.frame>=res->columns*res->rows)return fail("Basement sprite key");a.keys.push_back(key);}owned+=len;next.animations_.push_back(std::move(a));}if(owned!=count[3])return fail("Basement sprite orphan keys");const auto*audio=p+offset[5];next.present_resource_id_=u32(audio+4);next.present_animation_id_=u32(audio+8);next.present_sound_stop_=f32(audio+16);const auto*present_animation=next.animation(next.present_animation_id_);if(!text(u32(audio),next.present_sound_)||next.present_sound_.find("Audio/")!=0||next.present_sound_.find("..")!=next.present_sound_.npos||!next.resource(next.present_resource_id_)||!present_animation||present_animation->resource_id!=next.present_resource_id_||f32(audio+12)!=0||!std::isfinite(next.present_sound_stop_)||next.present_sound_stop_<=0||next.present_sound_stop_>3600)return fail("Basement Present audio track");next.valid_=true;*this=std::move(next);e.clear();return true;
}
uint32_t BasementActorData::frame(uint32_t id,double elapsed)const{const auto*a=animation(id);if(!valid_||!a||!std::isfinite(elapsed)||elapsed<0)return 0;uint32_t frame=a->keys.front().frame;for(const auto&k:a->keys){if(k.time>elapsed)break;frame=k.frame;}return frame;}
bool begin_basement_actor(const BasementActorData&d,uint32_t id,BasementActorPlayback&s,std::string&e){if(!d.valid()||!d.animation(id)){e="Unknown checked special actor animation";return false;}s={id,0,true};e.clear();return true;}
bool advance_basement_actor(const BasementActorData&d,double delta,BasementActorPlayback&s,std::string&e){if(!std::isfinite(delta)||delta<0||delta>double(.1f)){e="Special actor delta rejected";return false;}if(!s.visible){e.clear();return true;}const auto*a=d.animation(s.animation_id);if(!d.valid()||!a||!std::isfinite(s.elapsed)||s.elapsed<0){e="Special actor playback rejected";return false;}s.elapsed=std::min(double(a->length),s.elapsed+double(float(delta)));e.clear();return true;}
}
