#include "encore/battle_data.hpp"
#include "encore/content.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <set>
namespace encore::upstream {
namespace {
constexpr uint32_t count_sections=12,max_bytes=1024*1024;
constexpr uint32_t strides[]={1,60,92,24,24,20,64,16,32,60,16,36};
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|(uint32_t(p[1])<<8)|(uint32_t(p[2])<<16)|(uint32_t(p[3])<<24);}
uint32_t stride_for(uint32_t version,uint32_t section){return version==2&&section==10?116:strides[section-1];}
uint16_t u16(const uint8_t*p){return uint16_t(p[0])|(uint16_t(p[1])<<8);}
float f32(const uint8_t*p){auto b=u32(p);float f;std::memcpy(&f,&b,4);return f;}
int32_t i32(const uint8_t*p){auto b=u32(p);int32_t n;std::memcpy(&n,&b,4);return n;}
BattleValue value(const uint8_t*p){return {f32(p),f32(p+4),f32(p+8),f32(p+12)};}
bool finite(BattleValue v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::isfinite(v.z)&&std::isfinite(v.w);}
uint32_t crc(const uint8_t*p,size_t n,const encore::PreparationControl* control=nullptr){uint32_t c=~0u;for(size_t i=0;i<n;++i){if(!(i&4095)&&control&&control->stopped())return 0;c^=(i>=16&&i<20)?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&(0u-(c&1)));}return ~c;}
bool utf8(const uint8_t*p,size_t n){for(size_t i=0;i<n;){uint32_t c=p[i++];if(c<0x80)continue;unsigned extra;uint32_t low;if(c>=0xc2&&c<=0xdf){extra=1;low=0x80;c&=31;}else if(c>=0xe0&&c<=0xef){extra=2;low=0x800;c&=15;}else if(c>=0xf0&&c<=0xf4){extra=3;low=0x10000;c&=7;}else return false;if(extra>n-i)return false;while(extra--){auto b=p[i++];if((b&0xc0)!=0x80)return false;c=(c<<6)|(b&63);}if(c<low||c>0x10ffff||(c>=0xd800&&c<=0xdfff))return false;}return true;}
}
uint32_t BattleView::count(BattleSection s)const{auto i=uint32_t(s);return bytes_&&i>=1&&i<=count_sections?u32(bytes_+64+(i-1)*16+8):0;}
const uint8_t*BattleView::record(BattleSection s,uint32_t i)const{auto k=uint32_t(s);if(!bytes_||k<1||k>count_sections||i>=count(s))return nullptr;auto d=bytes_+64+(k-1)*16;return bytes_+u32(d+4)+size_t(i)*stride_for(u32(bytes_+8),k);}
std::string_view BattleView::string(uint32_t offset)const{const auto*p=record(BattleSection::Strings,offset);if(!p)return {};size_t n=count(BattleSection::Strings)-offset;const auto*end=static_cast<const uint8_t*>(std::memchr(p,0,n));return end?std::string_view(reinterpret_cast<const char*>(p),size_t(end-p)):std::string_view{};}
BattleResource BattleView::resource(uint32_t i)const{BattleResource r;auto*p=record(BattleSection::Resources,i);if(!p)return r;r.id=u32(p);r.path=u32(p+4);r.kind=u32(p+8);r.width=u32(p+12);r.height=u32(p+16);r.columns=u32(p+20);r.rows=u32(p+24);std::memcpy(r.sha256,p+28,32);return r;}
BattleLayout BattleView::layout(uint32_t i)const{BattleLayout r;auto*p=record(BattleSection::Layouts,i);if(!p)return r;r.id=u32(p);r.kind=u32(p+4);r.role=u32(p+8);r.resource=u32(p+12);r.frame=u32(p+16);r.text=u32(p+20);r.flags=u32(p+24);r.binding=u32(p+28);r.rect=value(p+32);r.color=value(p+48);r.depth=f32(p+64);for(unsigned n=0;n<4;++n)r.margins[n]=u32(p+68+n*4);r.display_anchor={f32(p+84),f32(p+88)};return r;}
BattleTrack BattleView::track(uint32_t i)const{BattleTrack r;auto*p=record(BattleSection::Tracks,i);if(p)r={u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20)};return r;}
BattleKey BattleView::key(uint32_t i)const{BattleKey r;auto*p=record(BattleSection::Keys,i);if(p)r={f32(p),f32(p+4),value(p+8)};return r;}
BattleValue BattleView::parameter(BattleParameter key)const{for(uint32_t i=0;i<count(BattleSection::Parameters);++i){auto*p=record(BattleSection::Parameters,i);if(u32(p)==uint32_t(key))return value(p+4);}return {};}
BattleParticipant BattleView::participant(uint32_t i)const{BattleParticipant r;auto*p=record(BattleSection::Participants,i);if(!p)return r;r.id=u32(p);r.name=u32(p+4);r.kind=u32(p+8);r.flags=u32(p+12);r.level=i32(p+16);r.hp=i32(p+20);r.maxhp=i32(p+24);r.pp=i32(p+28);r.maxpp=i32(p+32);r.offense=i32(p+36);r.defense=i32(p+40);r.speed=i32(p+44);r.iq=i32(p+48);r.guts=i32(p+52);r.xp=i32(p+56);r.cash=i32(p+60);return r;}
BattleMenu BattleView::menu(uint32_t i)const{BattleMenu r;auto*p=record(BattleSection::Menus,i);if(p)r={u32(p),u32(p+4),u32(p+8),u32(p+12)};return r;}
BattleMetadata BattleView::metadata()const{BattleMetadata r;auto*p=record(BattleSection::Metadata,0);if(p)r={u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20),u32(p+24),u32(p+28)};return r;}
BattleBackground BattleView::background(uint32_t i)const{BattleBackground r;auto*p=record(BattleSection::Backgrounds,i);if(!p)return r;r.resource=u32(p);r.flags=u32(p+4);r.width=f32(p+8);r.height=f32(p+12);r.opacity=f32(p+16);r.effect=f32(p+20);r.effect_scale=f32(p+24);r.barrel={f32(p+28),f32(p+32)};r.oscillation_amplitude={f32(p+36),f32(p+40)};r.oscillation_frequency={f32(p+44),f32(p+48)};r.oscillation_speed={f32(p+52),f32(p+56)};if(u32(bytes_+8)==2){r.move={f32(p+60),f32(p+64)};r.ping_pong_speed={f32(p+68),f32(p+72)};r.compression_amplitude={f32(p+76),f32(p+80)};r.compression_frequency={f32(p+84),f32(p+88)};r.compression_speed={f32(p+92),f32(p+96)};r.palette_resource=u32(p+100);r.palette_speed=f32(p+104);r.palette_frames=u32(p+108);r.palette_fixed_row=u32(p+112);}return r;}
BattleEvent BattleView::event(uint32_t i)const{BattleEvent r;auto*p=record(BattleSection::Events,i);if(p)r={f32(p),u32(p+4),u32(p+8),u32(p+12)};return r;}
BattleGlyph BattleView::glyph(uint32_t i)const{BattleGlyph r;auto*p=record(BattleSection::Glyphs,i);if(p)r={u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20),f32(p+24),f32(p+28),f32(p+32)};return r;}
bool BattleData::load(const uint8_t*input,size_t size,std::string&error,const encore::PreparationControl* control){
 auto fail=[&](const char*s){error=s;return false;};
 if(!input||size<256||size>max_bytes)return fail("Battle pack size rejected");
 if(std::memcmp(input,"ENCBTL01",8)||(u32(input+8)!=1&&u32(input+8)!=2)||u32(input+12)!=size||u32(input+20)!=count_sections||u32(input+24)!=1||u32(input+28)!=1)return fail("Battle pack schema/capability rejected");
 for(unsigned i=52;i<64;++i)if(input[i])return fail("Battle reserved header bytes set");
 const auto checksum=crc(input,size,control);if(control&&control->stopped())return fail("Checked pack preparation cancelled");
 if(checksum!=u32(input+16))return fail("Battle pack CRC mismatch");
 size_t end=256;
 for(uint32_t s=1;s<=count_sections;++s){auto*d=input+64+(s-1)*16;const uint32_t off=u32(d+4),n=u32(d+8),bytes=u32(d+12);if(u16(d)!=s||u16(d+2)!=stride_for(u32(input+8),s)||uint64_t(n)*stride_for(u32(input+8),s)!=bytes)return fail("Battle directory rejected");if(!n){if(off||bytes)return fail("Battle empty section rejected");continue;}if(off%4||off<end||off>size||bytes>size-off)return fail("Battle section span rejected");for(size_t j=end;j<off;++j)if(input[j])return fail("Battle padding rejected");end=size_t(off)+bytes;}
 if(end!=size)return fail("Battle trailing bytes rejected");
 BattleView v;v.bytes_=input;v.size_=size;
 auto num=[&](BattleSection s){return v.count(s);};
 if(!num(BattleSection::Strings)||num(BattleSection::Strings)>65536||num(BattleSection::Resources)>128||!num(BattleSection::Layouts)||num(BattleSection::Layouts)>256||num(BattleSection::Tracks)>512||num(BattleSection::Keys)>4096||num(BattleSection::Parameters)!=uint32_t(BattleParameter::Count)-1||num(BattleSection::Participants)!=2||!num(BattleSection::Menus)||num(BattleSection::Menus)>16||num(BattleSection::Metadata)!=1||!num(BattleSection::Backgrounds)||num(BattleSection::Backgrounds)>4||num(BattleSection::Events)>64||num(BattleSection::Glyphs)>1024)return fail("Battle section capacity rejected");
 auto*pool=v.record(BattleSection::Strings,0);auto pool_size=num(BattleSection::Strings);if(pool[0]||pool[pool_size-1]||!utf8(pool,pool_size))return fail("Battle strings rejected");
 auto str=[&](uint32_t n){return n<pool_size&&(n==0||pool[n-1]==0)&&v.string(n).size()<=4096;};
 for(auto section:{BattleSection::Resources,BattleSection::Layouts,BattleSection::Participants,BattleSection::Menus}){std::set<uint32_t>ids;for(uint32_t i=0;i<num(section);++i){auto id=u32(v.record(section,i));if(!id||!ids.insert(id).second)return fail("Battle duplicate/zero ID");}}
 for(uint32_t i=0;i<num(BattleSection::Resources);++i){auto r=v.resource(i);if(!str(r.path)||v.string(r.path).empty()||r.kind<1||r.kind>3||!r.width||r.width>8192||!r.height||r.height>8192||!r.columns||!r.rows||r.columns>256||r.rows>256||(r.kind==1&&(r.width%r.columns||r.height%r.rows)))return fail("Battle resource rejected");auto path=v.string(r.path);if(path.front()=='/'||path.find("..")!=path.npos||path.find(':')!=path.npos||path.find('\\')!=path.npos)return fail("Battle resource path rejected");}
 for(uint32_t i=0;i<num(BattleSection::Layouts);++i){auto r=v.layout(i);if(r.kind<1||r.kind>5||r.role>uint32_t(BattleRole::TransitionMask)||!finite(r.rect)||!finite(r.color)||!std::isfinite(r.depth)||r.rect.z<=0||r.rect.w<=0||r.rect.z>8192||r.rect.w>8192||r.color.x<0||r.color.x>1||r.color.y<0||r.color.y>1||r.color.z<0||r.color.z>1||r.color.w<0||r.color.w>1||r.flags&~7u||!str(r.text)||!std::isfinite(r.display_anchor.x)||!std::isfinite(r.display_anchor.y)||r.display_anchor.x<0||r.display_anchor.x>1||r.display_anchor.y<0||r.display_anchor.y>1)return fail("Battle layout rejected");if(r.kind!=uint32_t(BattleDrawKind::Rectangle)){if(r.resource>=num(BattleSection::Resources))return fail("Battle layout resource rejected");auto tex=v.resource(r.resource);if(r.frame>=uint64_t(tex.columns)*tex.rows)return fail("Battle frame rejected");}}
 std::set<uint32_t>params;for(uint32_t i=0;i<num(BattleSection::Parameters);++i){auto*p=v.record(BattleSection::Parameters,i);auto k=u32(p);if(!k||k>=uint32_t(BattleParameter::Count)||!params.insert(k).second||!finite(value(p+4)))return fail("Battle parameter rejected");}
 auto canvas=v.parameter(BattleParameter::CanvasSize);if(canvas.x<1||canvas.y<1||canvas.x>1024||canvas.y>1024)return fail("Battle canvas rejected");for(auto k:{BattleParameter::SceneDuration,BattleParameter::MaskDuration,BattleParameter::MenuDuration}){auto t=v.parameter(k).x;if(t<=0||t>60)return fail("Battle duration rejected");}
 for(uint32_t i=0;i<num(BattleSection::Tracks);++i){auto t=v.track(i);if(t.target>=num(BattleSection::Layouts)||t.property<1||t.property>10||t.clock>8||!t.count||t.count>256||t.first>num(BattleSection::Keys)||t.count>num(BattleSection::Keys)-t.first||t.update>1)return fail("Battle track rejected");float prior=-1;for(uint32_t j=0;j<t.count;++j){auto k=v.key(t.first+j);if(!std::isfinite(k.time)||k.time<0||k.time<=prior||k.time>60||!std::isfinite(k.ease)||std::abs(k.ease)>100||!finite(k.value))return fail("Battle key rejected");if(t.property==uint32_t(BattleProperty::Frame)){const auto r=v.resource(v.layout(t.target).resource);if(k.value.x<0||k.value.x>=float(uint64_t(r.columns)*r.rows)||std::floor(k.value.x)!=k.value.x)return fail("Battle animation frame rejected");}
 if((t.property==uint32_t(BattleProperty::Alpha)||t.property==uint32_t(BattleProperty::FlashModifier))&&(k.value.x<0||k.value.x>1))return fail("Battle animation alpha rejected");
 if(t.property==uint32_t(BattleProperty::Visible)&&k.value.x!=0&&k.value.x!=1)return fail("Battle animation visibility rejected");
 if(t.property==uint32_t(BattleProperty::Scale)&&(k.value.x<=0||k.value.y<=0||k.value.x>16||k.value.y>16))return fail("Battle animation scale rejected");
 prior=k.time;}}
 for(uint32_t i=0;i<num(BattleSection::Participants);++i){auto p=v.participant(i);if(!str(p.name)||p.kind!=i+1||p.flags||p.level<1||p.level>65535||p.maxhp<1||p.hp<0||p.hp>p.maxhp||p.maxpp<0||p.pp<0||p.pp>p.maxpp)return fail("Battle participant rejected");}
 for(uint32_t i=0;i<num(BattleSection::Menus);++i){auto m=v.menu(i);if(!str(m.label)||m.layout>=num(BattleSection::Layouts)||m.flags&~1u)return fail("Battle menu rejected");}
 const auto meta=v.metadata();if(!meta.room_battle_id||!str(meta.enemy_name)||!meta.encounter_audio||meta.mask_resource>=num(BattleSection::Resources)||meta.flags&~3u||meta.reserved)return fail("Battle metadata rejected");
 for(uint32_t i=0;i<num(BattleSection::Backgrounds);++i){auto b=v.background(i);auto*p=v.record(BattleSection::Backgrounds,i);if(b.resource>=num(BattleSection::Resources)||b.flags&~(u32(input+8)==2?15u:3u)||b.width<1||b.height<1||b.width>8192||b.height>8192||b.opacity<0||b.opacity>1||b.effect_scale<=0)return fail("Battle background rejected");for(unsigned j=8;j<60;j+=4)if(!std::isfinite(f32(p+j)))return fail("Battle background scalar rejected");if(u32(input+8)==2){for(unsigned j=60;j<100;j+=4)if(!std::isfinite(f32(p+j)))return fail("Battle extended background scalar rejected");if(!std::isfinite(b.palette_speed)||b.palette_frames>4096)return fail("Battle palette scalar rejected");if(b.flags&4u){if(b.palette_resource>=num(BattleSection::Resources)||v.resource(b.palette_resource).kind!=2)return fail("Battle palette resource rejected");if(b.flags&8u){if(b.palette_frames||b.palette_fixed_row>=v.resource(b.palette_resource).height)return fail("Battle fixed palette row rejected");}else if(!b.palette_frames||b.palette_fixed_row!=0xffffffffu)return fail("Battle undefined palette divisor rejected");}else if(b.palette_resource!=0xffffffffu||b.palette_speed||b.palette_frames||b.palette_fixed_row!=0xffffffffu||(b.flags&8u))return fail("Battle unused palette rejected");}}
 float previous=-1;for(uint32_t i=0;i<num(BattleSection::Events);++i){auto e=v.event(i);if(!std::isfinite(e.time)||e.time<previous||e.time<0||e.time>v.parameter(BattleParameter::SceneDuration).x||e.kind<1||e.kind>5||e.flags||e.target)return fail("Battle event rejected");previous=e.time;}
 std::set<uint32_t>glyphs;for(uint32_t i=0;i<num(BattleSection::Glyphs);++i){auto g=v.glyph(i);if(!glyphs.insert(g.codepoint).second||g.codepoint>0x10ffff||g.resource>=num(BattleSection::Resources)||!std::isfinite(g.advance)||!std::isfinite(g.offset_x)||!std::isfinite(g.offset_y))return fail("Battle glyph rejected");auto r=v.resource(g.resource);if(g.u>r.width||g.v>r.height||g.w>r.width-g.u||g.h>r.height-g.v)return fail("Battle glyph rectangle rejected");}
 if(control&&control->stopped())return fail("Checked pack preparation cancelled");
 std::vector<uint8_t>copy(input,input+size);bytes_.swap(copy);error.clear();return true;
}
bool BattleData::load_file(const char*path,std::string&error){std::vector<uint8_t>b;if(!encore::read_file(path,b,max_bytes,error))return false;return load(b.data(),b.size(),error);}
}
