#include "encore/field_butterfly.hpp"
#include <algorithm>
#include <cmath>
namespace encore::upstream {namespace {
bool point_ok(Vec2 p){return std::isfinite(p.x)&&std::isfinite(p.y)&&std::abs(p.x)<=1e6&&std::abs(p.y)<=1e6;}
bool delta_ok(double v){return std::isfinite(v)&&v>=0&&v<=double(.1f);}
float loop_time(float time,float length){float v=std::fmod(time,length);return v==0&&time!=0?length:v;}
float ease(float x,float curve){double n=x,c=curve;if(c>0)return float(c<1?1-std::pow(1-n,1/c):std::pow(n,c));if(c<0)return float(n<.5?std::pow(n*2,-c)*.5:(1-std::pow(1-(n-.5)*2,-c))*.5+.5);return 0;}
Vec2 normalize(Vec2 v){const float length=std::sqrt(float(v.x*v.x+v.y*v.y));return length==0?Vec2{}:Vec2{v.x/length,v.y/length};}
Vec2 toward(Vec2 from,Vec2 target,float distance){Vec2 v{target.x-from.x,target.y-from.y};float length=std::sqrt(float(v.x*v.x+v.y*v.y));if(length<=distance||length<.00001f)return target;return{from.x+v.x/length*distance,from.y+v.y/length*distance};}
}
const FieldButterflyState*FieldButterflyRuntime::state(uint32_t id)const{for(const auto&s:states_)if(s.id==id)return&s;return nullptr;}
FieldButterflyState*FieldButterflyRuntime::get(uint32_t id,std::string&e){for(auto&s:states_)if(s.id==id){if(!s.ready||!s.alive){e="Butterfly source instance not live Ready";return nullptr;}return&s;}e="Unknown Butterfly source identity";return nullptr;}
Vec2 FieldButterflyRuntime::world_position(uint32_t id)const{auto*s=state(id);auto*b=data_?data_->binding(id):nullptr;if(!s||!b)return{};return{b->parent_origin.x+s->position.x*b->parent_scale,b->parent_origin.y+s->position.y*b->parent_scale};}
Vec2 FieldButterflyRuntime::area_center(uint32_t id)const{auto*s=state(id);auto*b=data_?data_->binding(id):nullptr;if(!s||!b)return{};auto world=world_position(id);return{world.x+(s->sprite_position.x+b->area_center.x)*b->parent_scale,world.y+(s->sprite_position.y+b->area_center.y)*b->parent_scale};}
bool FieldButterflyRuntime::publish(FieldButterflyState&s,std::string&e){if(!point_ok(s.position)||!point_ok(s.velocity)||!point_ok(s.input)||!point_ok(s.sprite_position)||!point_ok(s.sprite_offset)||!point_ok(world_position(s.id))||!point_ok(area_center(s.id))){e="Butterfly source transform bound";return false;}return host_.publish(*data_->binding(s.id),s,e);}
bool FieldButterflyRuntime::initialize(const FieldButterflyData&d,FieldButterflyHost h,std::string&e){if(!d.valid()||!h.admit_ready||!h.body_snapshot||!h.publish){e="Butterfly typed source Host incomplete";return false;}FieldButterflyRuntime next;next.data_=&d;next.host_=std::move(h);for(const auto&b:d.bindings()){FieldButterflyState s;s.id=b.id;s.position=b.position;s.sprite_position=b.sprite_position;s.sprite_offset=b.sprite_offset;s.frame=b.frame;s.flip=b.flip;next.states_.push_back(s);}*this=std::move(next);e.clear();return true;}
bool FieldButterflyRuntime::ready(uint32_t id,SourceRandom&random,std::string&e){if(!data_){e="Butterfly source unbound";return false;}auto i=std::find_if(states_.begin(),states_.end(),[&](const auto&s){return s.id==id;});auto*b=data_->binding(id);if(i==states_.end()||!b||i->ready||!i->alive){e="Butterfly Ready source lifecycle";return false;}if(!host_.admit_ready(*b,e))return false;i->asset=random.randi()%data_->modulus();i->start=i->position;i->process=false;i->visible=false;i->ready=true;return publish(*i,e);}
bool FieldButterflyRuntime::apply(FieldButterflyState&s,const FieldButterflyTrack&t,float time,bool seek,float from,float raw_to,float length,std::string&e){if(t.keys.empty()){e="Butterfly source animation track owner";return false;}auto write=[&](Vec2 v){switch(t.role){case 1:if(v.x<0||v.x>=data_->frames()||std::floor(v.x)!=v.x){e="Butterfly source frame";return false;}s.frame=uint32_t(v.x);return true;case 2:s.flip=v.x!=0;return true;case 3:s.sprite_position=v;return true;case 4:s.sprite_offset=v;return true;default:e="Butterfly unknown source track";return false;}};
 if(t.discrete&&!seek){auto range=[&](float begin,float end){for(const auto&k:t.keys)if(k.time>=begin&&k.time<end)if(!write(k.value))return false;return true;};if(raw_to>length){if(!range(from,length)||!range(0,time))return false;}else if(!range(from,time==length&&from!=length?length*1.001f:time))return false;return true;}
 size_t index=t.keys.size()-1;for(size_t j=0;j<t.keys.size();++j)if(t.keys[j].time<=time)index=j;if(t.discrete||t.keys.size()==1)return write(t.keys[index].value);size_t next=(index+1)%t.keys.size();auto a=t.keys[index],b=t.keys[next];float begin=a.time,end=b.time;if(time<t.keys.front().time)begin-=length;else if(next==0)end+=length;const float denominator=end-begin;if(denominator<=0)return write(a.value);const float weight=ease((time-begin)/denominator,a.transition);return write({a.value.x+(b.value.x-a.value.x)*weight,a.value.y+(b.value.y-a.value.y)*weight});
}
bool FieldButterflyRuntime::animate(FieldButterflyState&s,uint32_t role,float delta,bool seek,std::string&e){auto*c=data_->clip(role);if(!c){e="Butterfly source clip role";return false;}auto&clock=role==1?s.fly_time:s.orbit_time;const float from=clock,raw=seek?clock:float(clock+delta),time=loop_time(raw,c->length);clock=time;for(const auto&t:c->tracks)if(!apply(s,t,time,seek||delta==0,from,raw,c->length,e))return false;return publish(s,e);}
bool FieldButterflyRuntime::screen_enter(uint32_t id,SourceRandom&random,std::string&e){auto*s=get(id,e);if(!s)return false;s->fly_playing=s->orbit_playing=true;s->fly_time=float(random.randf()*data_->fly_seek());if(!animate(*s,1,0,true,e))return false;s->orbit_time=float(random.randf()*data_->orbit_seek());if(!animate(*s,2,0,true,e))return false;s->process=true;s->visible=true;return publish(*s,e);}
bool FieldButterflyRuntime::screen_exit(uint32_t id,std::string&e){auto*s=get(id,e);if(!s)return false;s->fly_playing=s->orbit_playing=false;s->fly_time=s->orbit_time=0;s->process=s->visible=false;return publish(*s,e);}
bool FieldButterflyRuntime::body_enter(uint32_t id,uint32_t body,std::string&e){auto*s=get(id,e);if(!s)return false;FieldButterflyBody actor;if(!host_.body_snapshot(body,actor,e))return false;if(!actor.party_member_player||!actor.walking){e.clear();return true;}if(!point_ok(actor.world)){e="Butterfly actual actor position";return false;}auto*b=data_->binding(id);auto world=world_position(id);Vec2 sprite{world.x+s->sprite_position.x*b->parent_scale,world.y+s->sprite_position.y*b->parent_scale};s->returning=false;auto vector=normalize({actor.world.x-sprite.x,actor.world.y-sprite.y});s->input={-vector.x,-vector.y};s->flip=!(actor.world.x<sprite.x);return publish(*s,e);}
bool FieldButterflyRuntime::body_exit(uint32_t id,uint32_t body,std::string&e){auto*s=get(id,e);if(!s)return false;FieldButterflyBody actor;if(!host_.body_snapshot(body,actor,e))return false;auto world=world_position(id);if(actor.global_player&&(world.x!=s->start.x||world.y!=s->start.y)){if(s->waiters.size()>=4096){e="Butterfly source timer coroutine structural bound";return false;}s->timer_left=data_->binding(id)->timer_wait;s->timer_running=true;s->waiters.push_back(0);}e.clear();return true;}
bool FieldButterflyRuntime::idle_leaf(uint32_t leaf,double delta,bool can_process,std::string&e){if(!data_||!delta_ok(delta)){e="Butterfly source idle delta";return false;}for(const auto&b:data_->bindings()){const uint32_t role=leaf==b.timer_id?0:leaf==b.fly_id?1:leaf==b.orbit_id?2:99;if(role==99)continue;auto*s=get(b.id,e);if(!s)return false;if(!can_process){e.clear();return true;}if(role==0&&s->timer_running){s->timer_left-=double(float(delta));if(s->timer_left<0){s->timer_running=false;auto waiters=std::move(s->waiters);s->waiters.clear();for(auto phase:waiters){if(phase==0){s->input={};s->timer_left=b.timer_wait;s->timer_running=true;s->waiters.push_back(1);}else if(phase==1)s->returning=true;else{e="Butterfly source coroutine phase";return false;}}return publish(*s,e);}}else if((role==1&&s->fly_playing)||(role==2&&s->orbit_playing))return animate(*s,role,float(float(delta)*(role==1?b.fly_speed:b.orbit_speed)),false,e);e.clear();return true;}e="Unknown Butterfly source internal leaf";return false;}
bool FieldButterflyRuntime::idle_process(uint32_t id,double delta,bool can_process,std::string&e){if(!delta_ok(delta)){e="Butterfly source process delta";return false;}auto*s=get(id,e);if(!s)return false;if(!can_process||!s->process){e.clear();return true;}auto*b=data_->binding(id);const float dt=float(delta);if(s->input.x!=0||s->input.y!=0){s->velocity={s->input.x*data_->speed(),s->input.y*data_->speed()};auto world=world_position(id);world={world.x+s->velocity.x*dt,world.y+s->velocity.y*dt};s->position={(world.x-b->parent_origin.x)/b->parent_scale,(world.y-b->parent_origin.y)/b->parent_scale};}auto old=world_position(id);if(s->returning){s->position=toward(s->position,s->start,float(data_->speed()*dt));auto current=world_position(id);s->flip=!(old.x<current.x);if(current.x==s->start.x&&current.y==s->start.y)s->returning=false;}return publish(*s,e);}
bool FieldButterflyRuntime::exit_tree(uint32_t id,std::string&e){auto*s=get(id,e);if(!s)return false;s->alive=false;s->visible=s->process=s->timer_running=s->fly_playing=s->orbit_playing=false;s->waiters.clear();return publish(*s,e);}
}
