#include "encore/field_npc.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <utility>
namespace encore::upstream {
namespace {
bool finite(Vec2 p){return std::isfinite(p.x)&&std::isfinite(p.y)&&std::abs(p.x)<=1000000&&std::abs(p.y)<=1000000;}
Vec2 direction(Vec2 a,Vec2 b){const double x=double(b.x)-a.x,y=double(b.y)-a.y,length=std::sqrt(x*x+y*y);return length?Vec2{float(x/length),float(y/length)}:Vec2{};}
Vec2 rounded(Vec2 p){return {std::round(p.x),std::round(p.y)};}
float sign(float f){return f>0?1.f:f<0?-1.f:0.f;}
uint32_t closest(const FieldNpcMotion&m,Vec2 point){uint32_t index=0;double distance=std::numeric_limits<double>::infinity();for(uint32_t i=0;i<m.directions.size();++i){const auto p=m.directions[i].vector;const double dx=double(p.x)-point.x,dy=double(p.y)-point.y,d=dx*dx+dy*dy;if(d<distance){index=i;distance=d;}}return index;}
}
bool FieldNpcRuntime::fail(const char*e){error_=e;return false;}
float FieldNpcRuntime::parameter(FieldNpcParameter p)const{return data_->parameter(p);}
const FieldNpcDescriptor&FieldNpcRuntime::descriptor(const FieldNpcInstance&v)const{return data_->npcs()[v.index];}
FieldNpcInstance*FieldNpcRuntime::instance(uint32_t id){for(auto&v:npcs_)if(v.id==id&&!v.destroyed)return &v;fail("Unknown/destroyed Field NPC identity");return nullptr;}
bool FieldNpcRuntime::context(uint32_t id,FieldNpcContext&out){return host_.context(id,out,error_)&&(finite(out.player)||fail("Field NPC host player position rejected"));}
bool FieldNpcRuntime::ready_context(uint32_t id,FieldNpcReadyContext&out){
 if(host_.ready_context)return host_.ready_context(id,out,error_);
 FieldNpcContext legacy;if(!context(id,legacy))return false;
 out.ancestor_visible=legacy.ancestor_visible;out.debug_build=legacy.debug_build;return true;
}
bool FieldNpcRuntime::flag(const std::string&name,bool&out){if(name.empty()){out=true;return true;}return host_.flag(name,out,error_);}
bool FieldNpcRuntime::appear(const FieldNpcDescriptor&d,bool&out){bool on=true,off=false;if(!flag(d.appear,on))return false;if(!d.disappear.empty()&&!flag(d.disappear,off))return false;out=on&&!off;return true;}
bool FieldNpcRuntime::present(FieldNpcInstance&v,FieldNpcPresentation op){return host_.present(v.id,op,descriptor(v),v,error_);}
bool FieldNpcRuntime::initialize(const FieldNpcData*d,SourceRandom*r,FieldNpcHost h,std::string&e){
 if(!d||!d->valid()||!r||!h.context||!h.flag||!h.seen||!h.mark_seen||!h.admit_program||!h.open_program||!h.telepathy_effect||!h.begin_talker||!h.close_commands||!h.cached_raycast||!h.move_and_slide||!h.present||!h.timer){e="Field NPC requires checked data/shared RNG and complete source program/scene/collision/presentation/timer hosts";return false;}
 FieldNpcRuntime next;next.data_=d;next.random_=r;next.host_=std::move(h);for(uint32_t i=0;i<d->npcs().size();++i){FieldNpcInstance v;v.id=d->npcs()[i].id;v.index=i;next.npcs_.push_back(v);for(const auto&c:d->npcs()[i].connections)if(c.mode==1){e="Field NPC sync AnimationTree transition capability not admitted";return false;}}*this=std::move(next);e.clear();return true;
}
bool FieldNpcRuntime::select(FieldNpcInstance&v,bool thoughts,const FieldNpcDialogue*&selected){
 selected=nullptr;const auto&d=descriptor(v);size_t i=0;while(i<d.dialogues.size()){const auto&first=d.dialogues[i];const auto group=first.group;const bool kind=first.thoughts;size_t end=i+1;while(end<d.dialogues.size()&&d.dialogues[end].group==group&&d.dialogues[end].thoughts==kind)++end;
  if(kind==thoughts){bool enabled=false;if(!flag(first.flag,enabled))return false;if(enabled){for(size_t at=i;at<end;++at){bool seen=false;if(!host_.seen(v.id,d.dialogues[at],seen,error_))return false;if(!seen||d.dialogues[at].last){selected=&d.dialogues[at];break;}}}}
  i=end;
 }return true;
}
bool FieldNpcRuntime::has_dialog(uint32_t id,bool thoughts,bool&out){auto*v=instance(id);if(!v)return false;const FieldNpcDialogue*d=nullptr;if(!select(*v,thoughts,d))return false;out=d!=nullptr&&!d->program.empty();return true;}
bool FieldNpcRuntime::visibility_changed(uint32_t id){auto*v=instance(id);if(!v)return false;FieldNpcReadyContext ctx;if(!ready_context(id,ctx))return false;bool dialog=false;if(!has_dialog(id,false,dialog))return false;const bool actual=v->visible&&ctx.ancestor_visible;v->collision_enabled=actual;v->interact_enabled=actual&&dialog;v->physics=actual;return present(*v,FieldNpcPresentation::Visibility);}
bool FieldNpcRuntime::recheck_flags(uint32_t id){auto*v=instance(id);if(!v)return false;if(!appear(descriptor(*v),v->visible))return false;return visibility_changed(id);}
bool FieldNpcRuntime::ready(uint32_t id){auto*v=instance(id);if(!v||v->ready)return fail("Field NPC duplicate/unknown Ready rejected");const auto&d=descriptor(*v);if(had_ready_&&d.ready_ordinal<=last_ready_)return fail("Field NPC source Ready order rejected");last_ready_=d.ready_ordinal;had_ready_=true;FieldNpcReadyContext ctx;if(!ready_context(id,ctx))return false;v->position=d.position;v->input=d.direction;v->geometry=d.geometry;
 if(d.has(FieldNpcFlag::Debug)&&!ctx.debug_build){v->queued_free=true;if(!present(*v,FieldNpcPresentation::QueueFree))return false;}
 v->ready=true;if(!recheck_flags(id))return false;
 for(const auto&event:d.event_positions){if(event.flag.empty())continue;bool enabled=false;if(!flag(event.flag,enabled))return false;if(enabled)v->position=event.position;}
 v->start_position=v->new_position=v->position;if(v->input.x==0&&v->input.y==0)v->input={parameter(FieldNpcParameter::InitialDownX),parameter(FieldNpcParameter::InitialDownY)};v->blend=v->input;
 if(d.extended_interact){auto&shape=v->geometry[1];if(v->input.y!=0){const auto old=shape.value.y;shape.value.y*=1+parameter(FieldNpcParameter::ExtentVertical)*d.extended_interact;shape.offset.y+=(shape.value.y-old)*sign(v->input.y)*shape.scale.y;}else if(v->input.x!=0){const auto old=shape.value.x;shape.value.x*=1+parameter(FieldNpcParameter::ExtentHorizontal)*d.extended_interact;shape.offset.x+=(shape.value.x-old)*sign(v->input.x)*shape.scale.x;}}
 if(!present(*v,FieldNpcPresentation::Create)||!motion(*v,d.idle))return false;v->current_motion=v->pending_motion;v->pending_motion=UINT32_MAX;v->direction_index=closest(d.motions[v->current_motion],v->blend);v->frame=d.motions[v->current_motion].directions[v->direction_index].keys.front().frame;
 return visibility_changed(id)&&present(*v,FieldNpcPresentation::Frame);
}
bool FieldNpcRuntime::screen_entered(uint32_t id){auto*v=instance(id);if(!v||!v->ready)return fail("Field NPC screen event before Ready");FieldNpcContext ctx;if(!context(id,ctx))return false;if(ctx.cutscene)return true;bool enabled=false;if(!appear(descriptor(*v),enabled))return false;if(enabled){v->visible=true;if(!visibility_changed(id))return false;}
 const auto&d=descriptor(*v);if(d.has(FieldNpcFlag::Wander)){const auto wait=random_->rand_range(parameter(FieldNpcParameter::ReadyTimerMin),d.walk_frequency);if(!host_.timer(id,FieldNpcTimer::SetWanderWait,wait,0,error_)||!host_.timer(id,FieldNpcTimer::StartWander,wait,0,error_))return false;v->wander_running=true;}return true;
}
bool FieldNpcRuntime::screen_exited(uint32_t id){auto*v=instance(id);if(!v||!v->ready)return fail("Field NPC screen event before Ready");FieldNpcContext ctx;if(!context(id,ctx))return false;if(ctx.cutscene)return true;bool enabled=false;if(!appear(descriptor(*v),enabled))return false;if(enabled){v->visible=false;if(!visibility_changed(id))return false;}if(descriptor(*v).has(FieldNpcFlag::Wander)){v->wander_running=false;return host_.timer(id,FieldNpcTimer::StopWander,0,0,error_);}return true;}
bool FieldNpcRuntime::investigate(uint32_t id,bool thoughts){auto*v=instance(id);if(!v||!v->ready)return fail("Field NPC investigation before Ready");const FieldNpcDialogue*selected=nullptr;if(!select(*v,thoughts,selected))return false;if(!selected||!host_.admit_program(selected->program,error_))return fail("Field NPC selected Programme is pending/unadmitted");FieldNpcContext ctx;if(!context(id,ctx))return false;const auto&d=descriptor(*v);
 if(!thoughts&&(!host_.close_commands(error_)||!host_.begin_talker(id,error_)))return false;v->pause_for_interact=true;
 if(!thoughts||d.has(FieldNpcFlag::TurnTelepathy))v->new_position=v->position;
 if(d.has(thoughts?FieldNpcFlag::TurnTelepathy:FieldNpcFlag::TurnInteract)){v->input=direction(v->position,ctx.player);v->blend=v->input;if(!present(*v,FieldNpcPresentation::Blend))return false;}
 if(!host_.mark_seen(id,*selected,error_)||!host_.open_program(id,selected->program,thoughts,d,error_))return false;return !thoughts||host_.telepathy_effect(id,true,error_);
}
bool FieldNpcRuntime::interact(uint32_t id){return investigate(id,false);}bool FieldNpcRuntime::telepathy(uint32_t id){return investigate(id,true);}
bool FieldNpcRuntime::return_timer(FieldNpcInstance&v){if(!next_waiter_||next_waiter_==UINT64_MAX)return fail("Field NPC SceneTreeTimer identity exhausted");const auto receipt=next_waiter_++;v.return_waiters.push_back(receipt);return host_.timer(v.id,FieldNpcTimer::ReturnDirection,parameter(FieldNpcParameter::ReturnDelay),receipt,error_);}
bool FieldNpcRuntime::stop_interaction(uint32_t id){auto*v=instance(id);if(!v)return false;v->talking=false;v->pause_for_interact=false;v->mute=false;return descriptor(*v).has(FieldNpcFlag::Staring)||return_timer(*v);}
bool FieldNpcRuntime::view_entered(uint32_t id,bool player){auto*v=instance(id);if(!v)return false;if(player&&descriptor(*v).has(FieldNpcFlag::Staring))v->looking=true;return true;}
bool FieldNpcRuntime::view_exited(uint32_t id,bool player){auto*v=instance(id);if(!v)return false;const auto&d=descriptor(*v);if(!player||!d.has(FieldNpcFlag::Staring))return true;v->looking=false;return d.has(FieldNpcFlag::Wander)||return_timer(*v);}
bool FieldNpcRuntime::near_entered(uint32_t id,bool player){auto*v=instance(id);if(!v)return false;if(player)v->player_nearby=true;return true;}bool FieldNpcRuntime::near_exited(uint32_t id,bool player){auto*v=instance(id);if(!v)return false;if(player)v->player_nearby=false;return true;}
bool FieldNpcRuntime::return_direction_timeout(uint32_t id,uint64_t receipt){auto*v=instance(id);if(!v)return false;const auto at=std::find(v->return_waiters.begin(),v->return_waiters.end(),receipt);if(!receipt||at==v->return_waiters.end())return fail("Field NPC unknown/duplicate SceneTreeTimer completion");v->return_waiters.erase(at);if(!v->looking&&!v->pause_for_interact){v->input=descriptor(*v).direction;if(v->input.x==0&&v->input.y==0)v->input={parameter(FieldNpcParameter::InitialDownX),parameter(FieldNpcParameter::InitialDownY)};}return true;}
bool FieldNpcRuntime::move(FieldNpcInstance&v){if(v.player_nearby){v.new_position=v.position;return true;}const auto&d=descriptor(v);for(size_t work=0;work<4096;++work){auto target=v.position;if(random_->randi()%uint32_t(parameter(FieldNpcParameter::AxisModulus))==1)target.x=float(random_->rand_range(v.start_position.x-d.wander_radius/2,v.start_position.x+d.wander_radius/2));else target.y=float(random_->rand_range(v.start_position.y-d.wander_radius/2,v.start_position.y+d.wander_radius/2));target=rounded(target);bool collider=false;if(!host_.cached_raycast(v.id,{target.x-v.position.x,target.y-v.position.y},collider,error_))return false;if(std::abs(target.x-v.position.x)>parameter(FieldNpcParameter::MinimumMove)||std::abs(target.y-v.position.y)>parameter(FieldNpcParameter::MinimumMove)){if(!collider){v.new_position=target;v.input=direction(v.position,target);}return true;}}return fail("Field NPC recursive wander exceeded defensive work bound");}
bool FieldNpcRuntime::wander_timeout(uint32_t id){auto*v=instance(id);if(!v||!v->ready)return fail("Field NPC Wander Timer before Ready");FieldNpcContext ctx;if(!context(id,ctx))return false;const auto&d=descriptor(*v);if(d.has(FieldNpcFlag::Wander)&&!v->looking&&!v->pause_for_interact&&!ctx.player_paused&&!move(*v))return false;const auto wait=random_->rand_range(d.walk_frequency-parameter(FieldNpcParameter::TimerDeviation),d.walk_frequency+parameter(FieldNpcParameter::TimerDeviation));if(wait<=0)return fail("Field NPC nonpositive source timer assignment requires admission");return host_.timer(id,FieldNpcTimer::SetWanderWait,wait,0,error_);}
bool FieldNpcRuntime::motion(FieldNpcInstance&v,const std::string&name){const auto&d=descriptor(v);for(uint32_t i=0;i<d.motions.size();++i)if(d.motions[i].name==name){v.pending_motion=i==v.current_motion?UINT32_MAX:i;return present(v,FieldNpcPresentation::Motion);}return true;/* source travel to absent state is a checked no-op */}
bool FieldNpcRuntime::physics_step(uint32_t id,float dt){auto*v=instance(id);if(!v||!v->ready||!std::isfinite(dt)||dt<0||dt>60)return fail("Field NPC physics admission/delta rejected");if(!v->physics)return true;FieldNpcContext ctx;if(!context(id,ctx))return false;const auto&d=descriptor(*v);v->blend=v->input;if(!present(*v,FieldNpcPresentation::Blend))return false;const auto old=v->position;
 if(d.has(FieldNpcFlag::Wander)&&!v->pause_for_interact&&!ctx.player_paused&&!ctx.in_battle){const auto difference=std::max(std::ceil(std::abs(d.speed*dt)),parameter(FieldNpcParameter::MovementDifferenceFloor));if(!v->talking&&(std::abs(v->new_position.x-v->position.x)>difference||std::abs(v->new_position.y-v->position.y)>difference)&&!v->looking&&!v->player_nearby){v->input=direction(v->position,v->new_position);Vec2 position=v->position,velocity{};if(!host_.move_and_slide(id,{v->input.x*d.speed,v->input.y*d.speed},dt,position,velocity,error_)||!finite(position)||!finite(velocity))return fail("Field NPC source move_and_slide rejected");v->position=position;v->velocity=velocity;if(std::abs(old.x-position.x)>parameter(FieldNpcParameter::MotionThreshold)||std::abs(old.y-position.y)>parameter(FieldNpcParameter::MotionThreshold)){if(!motion(*v,d.walk))return false;}else{if(!motion(*v,d.idle))return false;v->position=rounded(v->position);}}
  else{v->new_position=v->position;if(!motion(*v,d.idle))return false;v->position=rounded(v->position);}}
 else if(!motion(*v,d.idle))return false;
 if(v->looking&&!v->talking&&(std::abs(old.x-v->position.x)<parameter(FieldNpcParameter::LookThreshold)||std::abs(old.y-v->position.y)<parameter(FieldNpcParameter::LookThreshold)))v->input=direction(v->position,ctx.player);
 if(ctx.stack_empty){v->talking=false;v->pause_for_interact=false;}else if(v->talking&&!v->mute){if(!motion(*v,d.talk))return false;}else if(ctx.current_talker){if(!motion(*v,d.talk_idle))return false;}else if(!motion(*v,d.idle))return false;return present(*v,FieldNpcPresentation::Pose);
}
bool FieldNpcRuntime::idle_animations(uint32_t id,double dt){auto*v=instance(id);if(!v||!v->ready||!std::isfinite(dt)||dt<0||dt>60)return fail("Field NPC idle animation delta/admission rejected");const auto&d=descriptor(*v);if(v->current_motion>=d.motions.size())return fail("Field NPC current animation state rejected");const auto&old=d.motions[v->current_motion];if(v->direction_index>=old.directions.size())return fail("Field NPC animation direction rejected");
 const auto index=closest(old,v->blend);if(v->pending_motion!=UINT32_MAX){if(v->pending_motion>=d.motions.size())return fail("Field NPC pending animation state rejected");uint32_t mode=0;for(const auto&c:d.connections)if(c.from==old.name&&c.to==d.motions[v->pending_motion].name)mode=c.mode;
  if(mode==1)return fail("Field NPC unadmitted sync animation transition");if(mode==0||float(old.directions[v->direction_index].duration)-float(v->animation_time)<=float(dt)){v->current_motion=v->pending_motion;v->pending_motion=UINT32_MAX;v->direction_index=closest(d.motions[v->current_motion],v->blend);v->animation_time=0;return present(*v,FieldNpcPresentation::Motion);}}
 if(index!=v->direction_index){v->direction_index=index;v->animation_time=0;}else v->animation_time=float(float(v->animation_time)+float(dt));const auto&clip=old.directions[v->direction_index];v->animation_time=old.loop?std::fmod(v->animation_time,clip.duration):std::min(v->animation_time,double(clip.duration));for(const auto&key:clip.keys){if(key.time==0||key.time<float(v->animation_time))v->frame=key.frame;else break;}return present(*v,FieldNpcPresentation::Frame);
}
bool FieldNpcRuntime::set_talking(uint32_t id,bool value){auto*v=instance(id);if(!v)return false;v->talking=value;return true;}bool FieldNpcRuntime::set_mute(uint32_t id,bool value){auto*v=instance(id);if(!v)return false;v->mute=value;return true;}
bool FieldNpcRuntime::set_direction(uint32_t id,Vec2 value){auto*v=instance(id);if(!v||!finite(value))return fail("Field NPC direction rejected");v->input=value;v->blend=rounded(value);return present(*v,FieldNpcPresentation::Blend);}
bool FieldNpcRuntime::teleport(uint32_t id,Vec2 value){auto*v=instance(id);if(!v||!finite(value))return fail("Field NPC teleport rejected");v->position=value;return present(*v,FieldNpcPresentation::Pose);}
bool FieldNpcRuntime::tree_exiting(uint32_t id,bool persistent){auto*v=instance(id);if(!v)return false;if(persistent)return true;v->wander_running=false;return host_.timer(id,FieldNpcTimer::StopWander,0,0,error_);}
bool FieldNpcRuntime::destroy(uint32_t id){auto*v=instance(id);if(!v)return false;v->destroyed=true;v->physics=false;v->return_waiters.clear();return true;}
}
