#include "encore/field_openable_door.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <unordered_set>
namespace encore::upstream {
namespace {
uint32_t word(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;while(n--){c^=*p++;for(unsigned i=0;i<8;++i)c=(c>>1)^((c&1)?0xedb88320u:0u);}return ~c;}
struct Reader {const uint8_t*p;size_t n,at=128;bool ok=true;
 uint32_t integer(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=word(p+at);at+=4;return v;}
 float scalar(){auto v=integer();float f;std::memcpy(&f,&v,4);if(!std::isfinite(f)||std::abs(f)>=1000000)ok=false;return f;}
 Vec2 vec(){float x=scalar(),y=scalar();return {x,y};}
 bool boolean(){auto v=integer();if(v>1)ok=false;return v!=0;}
 std::string text(){auto length=integer();if(!ok||length>65536||at>n||length>n-at){ok=false;return {};}std::string s(reinterpret_cast<const char*>(p+at),length);at+=length;size_t count=0;if(s.find('\0')!=s.npos||!utf8_count(s,count))ok=false;return s;}
 std::array<uint8_t,32>hash(){std::array<uint8_t,32>h{};if(!ok||at>n||n-at<32){ok=false;return h;}std::copy_n(p+at,32,h.begin());at+=32;if(std::all_of(h.begin(),h.end(),[](uint8_t v){return !v;}))ok=false;return h;}
};
bool path(std::string_view s){if(s.empty()||s.front()=='/'||s.back()=='/'||s.find('\\')!=s.npos)return false;size_t b=0;while(b<s.size()){auto e=s.find('/',b);if(e==s.npos)e=s.size();auto v=s.substr(b,e-b);if(v.empty()||v=="."||v=="..")return false;b=e+1;}return true;}
}
const FieldOpenableDescriptor*FieldOpenableDoorData::record(uint32_t id)const{for(const auto&n:records_)if(n.id==id)return &n;return nullptr;}
const FieldOpenableClip*FieldOpenableDoorData::clip(uint32_t p,FieldOpenableClipRole role)const{if(p>=profiles_.size())return nullptr;for(const auto&c:profiles_[p])if(c.role==role)return &c;return nullptr;}
const FieldOpenableTexture*FieldOpenableDoorData::texture(uint32_t i)const{return i<textures_.size()?&textures_[i]:nullptr;}
const FieldOpenableSound*FieldOpenableDoorData::sound(std::string_view name)const{for(const auto&s:sounds_)if(s.source==name)return &s;return nullptr;}
const FieldOpenableDialogue*FieldOpenableDoorData::dialogue(std::string_view name)const{for(const auto&d:dialogues_)if(d.program==name)return &d;return nullptr;}
bool FieldOpenableDoorData::source_hash(std::string_view name,std::array<uint8_t,32>&h)const{auto p=sources_.find(std::string(name));if(p==sources_.end())return false;h=p->second;return true;}
bool FieldOpenableDoorData::load_file(const char*p,const FieldIdentity&id,std::string&e){if(!p||!*p){e="OpenableDoor path rejected";return false;}FILE*f=std::fopen(p,"rb");if(!f){e="Cannot open OpenableDoor resource";return false;}if(std::fseek(f,0,SEEK_END)){std::fclose(f);e="OpenableDoor seek rejected";return false;}long size=std::ftell(f);if(size<128||size>4*1024*1024||std::fseek(f,0,SEEK_SET)){std::fclose(f);e="OpenableDoor file size rejected";return false;}std::vector<uint8_t>b(static_cast<size_t>(size));auto got=std::fread(b.data(),1,b.size(),f);bool closed=std::fclose(f)==0;if(got!=b.size()||!closed){e="OpenableDoor read rejected";return false;}return load(b.data(),b.size(),id,e);}
bool FieldOpenableDoorData::load(const uint8_t*p,size_t n,const FieldIdentity&id,std::string&e){auto fail=[&](const char*s){e=s;return false;};if(!p||n<128||n>4*1024*1024)return fail("OpenableDoor size rejected");if(std::memcmp(p,"ENCFOPN1",8)||(word(p+8)!=1&&word(p+8)!=2)||word(p+12)!=128||word(p+16)!=n||word(p+24)!=0x454e0020||word(p+28)!=3||!word(p+32)||word(p+32)>10000||word(p+36)!=id.scene_id||!id.scene_id||std::memcmp(p+40,id.upstream_commit.data(),20)||std::memcmp(p+60,id.source_sha256.data(),32)||word(p+124))return fail("OpenableDoor identity/version rejected");if(crc(p+128,n-128)!=word(p+20))return fail("OpenableDoor CRC rejected");Reader r{p,n};FieldOpenableDoorData d;d.identity_=id;d.scene_=r.text();d.script_=r.text();d.none_=r.text();d.bash_=r.text();d.initial_unlocked_=r.boolean();d.child_height_=r.scalar();for(float&v:d.shake_)v=r.scalar();d.run_y_=r.scalar();if(!r.ok||!path(d.scene_)||!path(d.script_)||d.none_.empty()||!path(d.bash_)||d.child_height_<0||d.shake_[0]<0||d.shake_[1]<0)return fail("OpenableDoor source profile rejected");auto profiles=r.integer();if(!r.ok||!profiles||profiles>100)return fail("OpenableDoor profile count rejected");for(uint32_t j=0;j<profiles;++j){std::vector<FieldOpenableClip>clips;auto count=r.integer();if(count!=3)return fail("OpenableDoor clip count rejected");std::unordered_set<uint32_t>roles;for(uint32_t k=0;k<count;++k){FieldOpenableClip c;auto role=r.integer();c.role=static_cast<FieldOpenableClipRole>(role);c.name=r.text();c.length=r.scalar();c.loop=r.boolean();auto tracks=r.integer();if(!r.ok||role<1||role>3||!roles.insert(role).second||c.name.empty()||c.length<=0||!tracks||tracks>4||(role==2)!=c.loop)return fail("OpenableDoor source clip rejected");std::unordered_set<uint32_t>props;for(uint32_t t=0;t<tracks;++t){FieldOpenableTrack track;auto prop=r.integer();track.property=static_cast<FieldOpenableProperty>(prop);track.update=r.integer();track.value=r.boolean();if(!r.ok||prop<1||prop>4||track.update>1||!props.insert(prop).second)return fail("OpenableDoor source track rejected");c.tracks.push_back(track);}clips.push_back(std::move(c));}d.profiles_.push_back(std::move(clips));}
 auto textures=r.integer();if(!r.ok||!textures||textures>10000)return fail("OpenableDoor texture count rejected");std::unordered_set<uint32_t>textureids;for(uint32_t i=0;i<textures;++i){FieldOpenableTexture t;t.id=r.integer();t.source=r.text();t.path=r.text();for(float&v:t.region)v=r.scalar();t.source_sha=r.hash();t.output_sha=r.hash();if(!r.ok||!t.id||!textureids.insert(t.id).second||!path(t.source)||!path(t.path)||t.path.substr(0,17)!="graphics/objects/"||t.path.size()<5||t.path.substr(t.path.size()-4)!=".t3x"||t.region[0]<0||t.region[1]<0||t.region[2]<=0||t.region[3]<=0||t.region[2]>1024||t.region[3]>1024)return fail("OpenableDoor source texture rejected");for(float v:t.region)if(std::floor(v)!=v)return fail("OpenableDoor atlas pixels rejected");d.textures_.push_back(std::move(t));}
 auto sounds=r.integer();if(!r.ok||!sounds||sounds>1000)return fail("OpenableDoor sound count rejected");std::unordered_set<uint32_t>soundids;std::unordered_set<std::string>soundnames;for(uint32_t i=0;i<sounds;++i){FieldOpenableSound s;s.id=r.integer();s.source=r.text();s.pcm=r.text();s.sha=r.hash();if(!r.ok||!s.id||!soundids.insert(s.id).second||!soundnames.insert(s.source).second||!path(s.source)||!path(s.pcm)||s.pcm.substr(0,6)!="sound/"||s.pcm.size()<5||s.pcm.substr(s.pcm.size()-4)!=".pcm")return fail("OpenableDoor sound binding rejected");d.sounds_.push_back(std::move(s));}
 auto dialogues=r.integer();if(!r.ok||!dialogues||dialogues>1000)return fail("OpenableDoor dialogue count rejected");std::unordered_set<std::string>programs;for(uint32_t i=0;i<dialogues;++i){FieldOpenableDialogue a;a.program=r.text();a.source=r.text();a.key=r.text();a.en=r.text();a.zh_cn=r.text();a.source_sha=r.hash();if(!r.ok||!path(a.source)||!path(a.program)||a.key.empty()||a.en.empty()||a.zh_cn.empty()||!programs.insert(a.program).second)return fail("OpenableDoor source dialogue rejected");d.dialogues_.push_back(std::move(a));}
 std::unordered_set<uint32_t>ids,children;std::unordered_set<std::string>nodes;uint32_t prev=0;for(uint32_t i=0;i<word(p+32);++i){FieldOpenableDescriptor a;a.id=r.integer();a.ready=r.integer();a.node=r.text();for(auto&v:a.children)v=r.integer();a.texture=r.integer();a.profile=r.integer();a.flags=r.integer();a.offset=r.vec();a.initial_sprite_position=r.vec();a.sprite_offset=r.vec();a.sprite_scale=r.vec();for(auto&v:a.positions)v=r.vec();a.timer_wait=r.scalar();a.gain_db=r.scalar();a.bus=r.text();a.key=r.text();a.flag=r.text();a.activate=r.text();a.deactivate=r.text();a.sound=r.text();a.end_sound=r.text();for(auto&v:a.dialogs)v=r.text();if(!r.ok||!a.id||!ids.insert(a.id).second||!path(a.node)||!nodes.insert(a.node).second||(i&&a.ready<=prev)||a.texture>=textures||a.profile>=profiles||a.flags>127||a.sprite_scale.x==0||a.sprite_scale.y==0||a.timer_wait<=0||a.timer_wait>3600||a.bus.empty()||a.gain_db< -80||a.gain_db>80)return fail("OpenableDoor descriptor rejected");prev=a.ready;for(auto v:a.children)if(!v||v==a.id||!children.insert(v).second)return fail("OpenableDoor source child identity rejected");for(const auto&v:a.dialogs)if(!d.dialogue(v))return fail("OpenableDoor dialogue reference rejected");for(const auto&v:{a.sound,a.end_sound})if(v!=d.none_&&!d.sound(v))return fail("OpenableDoor sound reference rejected");d.records_.push_back(std::move(a));}
 auto proofs=r.integer();if(!r.ok||!proofs||proofs>10000)return fail("OpenableDoor source proof capacity rejected");for(uint32_t i=0;i<proofs;++i){auto name=r.text();auto h=r.hash();if(!r.ok||!path(name)||!d.sources_.emplace(name,h).second)return fail("OpenableDoor source proof rejected");}if(word(p+8)==2){auto count=r.integer();if(count!=2)return fail("OpenableDoor Area connection count rejected");std::set<uint32_t>roles;std::set<std::string>methods;for(uint32_t i=0;i<count;++i){FieldOpenableAreaConnection a;a.role=r.integer();a.signal=r.text();a.method=r.text();if(!r.ok||a.role<1||a.role>2||!roles.insert(a.role).second||!methods.insert(a.method).second||(a.role==1&&a.signal!="body_entered")||(a.role==2&&a.signal!="body_exited")||a.method.empty()||a.method.size()>128||a.signal.size()>128||!std::all_of(a.method.begin(),a.method.end(),[](char c){return (c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='_';}))return fail("OpenableDoor Area connection rejected");d.area_connections_.push_back(std::move(a));}}if(!r.ok||r.at!=n)return fail("OpenableDoor truncated/trailing bytes rejected");std::array<uint8_t,32>h{};if(!d.source_hash(d.scene_,h)||h!=id.source_sha256||!d.source_hash(d.script_,d.script_sha_)||!d.sound(d.bash_))return fail("OpenableDoor scene/script/bash proof rejected");for(const auto&t:d.textures_)if(!d.source_hash(t.source,h)||h!=t.source_sha)return fail("OpenableDoor texture source SHA rejected");for(const auto&s:d.sounds_)if(!d.source_hash(s.source,h)||h!=s.sha)return fail("OpenableDoor sound source SHA rejected");for(const auto&a:d.dialogues_)if(!d.source_hash(a.source,h)||h!=a.source_sha)return fail("OpenableDoor dialogue source SHA rejected");d.valid_=true;*this=std::move(d);e.clear();return true;
}
}
