#include "encore/field_cash_box.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <set>
namespace encore::upstream {namespace {
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=i>=16&&i<20?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int(c&1)));}return~c;}
bool path(const std::string&s){return !s.empty()&&s.size()<1024&&s[0]!='/'&&s.find(':')==std::string::npos&&s.find('\\')==std::string::npos&&s.find("..") ==std::string::npos;}
struct Reader {const uint8_t*p;size_t n,at=64;bool ok=true;
 uint32_t number(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=u32(p+at);at+=4;return v;}
 float scalar(){auto v=number();float f;std::memcpy(&f,&v,4);if(!std::isfinite(f)||std::abs(f)>1000000)ok=false;return f;}
 double precise(){if(!ok||at>n||n-at<8){ok=false;return 0;}double v;std::memcpy(&v,p+at,8);at+=8;if(!std::isfinite(v))ok=false;return v;}
 bool boolean(){auto v=number();if(v>1)ok=false;return v==1;}
 std::string text(){auto k=number();if(!ok||k>8192||at>n||k>n-at){ok=false;return{};}std::string s(reinterpret_cast<const char*>(p+at),k);at+=k;size_t i=0;uint32_t cp;while(i<s.size())if(!encore::utf8_next(s,i,cp)||cp<32){ok=false;break;}return s;}
 bool hash(std::array<uint8_t,32>&a){if(!ok||at>n||n-at<32){ok=false;return false;}std::copy_n(p+at,32,a.begin());at+=32;if(std::all_of(a.begin(),a.end(),[](uint8_t b){return b==0;}))ok=false;return ok;}
};}
bool FieldCashBoxData::source_hash(const std::string&p,std::array<uint8_t,32>&h)const{auto i=sources_.find(p);if(i==sources_.end())return false;h=i->second;return true;}
bool FieldCashBoxData::load_file(const char*p,std::string&e){if(!p){e="Cash box file absent";return false;}std::ifstream f(p,std::ios::binary);if(!f){e="Cash box resource unavailable";return false;}f.seekg(0,std::ios::end);auto n=f.tellg();if(n<64||n>1024*1024){e="Cash box size rejected";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)){e="Cash box read failed";return false;}return load(b.data(),b.size(),e);}
bool FieldCashBoxData::load(const uint8_t*p,size_t n,std::string&e){auto fail=[&](const char*s){e=s;return false;};if(!p||n<64||n>1024*1024||std::memcmp(p,"ENCCASH1",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+16)!=crc(p,n)||u32(p+20)!=1||u32(p+24)!=1||u32(p+28)!=2||!u32(p+52)||u32(p+52)>1024||u32(p+56)||u32(p+60))return fail("Cash box schema/capability/rules/CRC rejected");FieldCashBoxData d;std::copy_n(p+32,20,d.pin_.begin());if(std::all_of(d.pin_.begin(),d.pin_.end(),[](uint8_t b){return!b;}))return fail("Cash box pin absent");Reader r{p,n};d.script_=r.text();d.font_=r.text();d.units_item_=r.text();d.units_scope_flags_=r.number();d.viewport_={float(r.number()),float(r.number())};d.pixel_snap_=r.boolean();d.threshold_=r.precise();for(auto&c:d.colors_)c=r.number();for(auto&key:d.symbols_)for(auto&lang:key)lang=r.text();auto tc=r.number();if(!r.ok||!path(d.script_)||!path(d.font_)||d.units_item_.empty()||d.units_scope_flags_!=1||d.viewport_.x<=0||d.viewport_.x>4096||d.viewport_.y<=0||d.viewport_.y>4096||d.threshold_<=0||d.threshold_>1||tc!=5)return fail("Cash box font/viewport/palette scope rejected");std::set<std::string>paths;
 for(uint32_t i=0;i<tc;++i){FieldCashTexture t;t.source=r.text();t.path=r.text();t.width=r.number();t.height=r.number();t.flavor=r.boolean();t.bytes=r.number();r.hash(t.sha);if(!r.ok||!path(t.source)||!path(t.path)||!paths.insert(t.path).second||!t.width||!t.height||t.width>1024||t.height>1024||!t.bytes||t.bytes>16*1024*1024)return fail("Cash box actual atlas identity rejected");d.textures_.push_back(std::move(t));}
 for(uint32_t mode=0;mode<2;++mode){auto&b=d.boxes_[mode];b.source=r.text();b.mode=r.number();b.layer=r.number();b.timer_connected=r.boolean();b.timer_seconds=r.scalar();auto sc=r.number();if(!r.ok||!path(b.source)||b.mode!=mode||b.layer>128||b.timer_seconds<=0||b.timer_seconds>60||sc!=mode+1)return fail("Cash box policy/style scope rejected");
  for(uint32_t j=0;j<sc;++j){FieldCashStyle s;s.texture=r.number();for(auto*a:{&s.content,&s.patch,&s.expand,&s.region})for(auto&v:*a)v=r.scalar();if(!r.ok||s.texture>=tc||!d.textures_[s.texture].flavor)return fail("Cash box StyleBox palette binding rejected");for(auto*a:{&s.content,&s.patch,&s.expand})for(float v:*a)if(v<0||v>1024)return fail("Cash box StyleBox margins rejected");if(s.region[0]<0||s.region[1]<0||s.region[2]<=0||s.region[3]<=0||s.region[0]+s.region[2]>d.textures_[s.texture].width||s.region[1]+s.region[3]>d.textures_[s.texture].height||s.patch[0]+s.patch[2]>s.region[2]||s.patch[1]+s.patch[3]>s.region[3])return fail("Cash box StyleBox crop rejected");b.styles.push_back(s);}
  auto nc=r.number();if(nc!=(mode?5u:7u))return fail("Cash box source tree coverage rejected");unsigned amounts=0;std::set<std::string>nodes;
  for(uint32_t j=0;j<nc;++j){FieldCashNode a;a.path=r.text();a.parent=r.number();a.kind=r.number();a.amount=r.boolean();a.label_role=r.number();a.style=r.number();a.texture=r.number();a.hflags=r.number();a.vflags=r.number();a.align=r.number();a.valign=r.number();a.alignment=r.number();a.expand=r.boolean();a.stretch_mode=r.number();for(auto&v:a.rect)v=r.scalar();a.minimum={r.scalar(),r.scalar()};a.separation=r.scalar();a.text=r.text();if(!r.ok||!path(a.path)||!nodes.insert(a.path).second||(j?(a.parent>=j||(a.parent<j&&b.nodes[a.parent].kind!=1&&b.nodes[a.parent].kind!=2)):a.parent!=UINT32_MAX)||a.kind<1||a.kind>5||a.label_role>3||(a.amount!=(a.label_role==1))||(a.label_role&&a.kind!=3)||a.hflags>15||a.vflags>15||a.align>2||a.valign>2||a.alignment>2||a.stretch_mode>6||a.minimum.x<0||a.minimum.y<0||a.separation<0||a.rect[2]<a.rect[0]||a.rect[3]<a.rect[1]||(a.amount&&a.kind!=3))return fail("Cash box source Control rejected");if(a.kind==1){if(a.style>=sc||a.texture!=b.styles[a.style].texture)return fail("Cash box panel style rejected");}else if(a.style!=UINT32_MAX)return fail("Cash box stray style rejected");if(a.kind==5){if(a.texture>=tc||d.textures_[a.texture].flavor||(a.stretch_mode!=0&&a.stretch_mode!=4))return fail("Cash box icon shader rejected");}else if(a.kind!=1&&a.texture!=UINT32_MAX)return fail("Cash box stray image rejected");amounts+=a.amount;b.nodes.push_back(std::move(a));}
  if(amounts!=1||b.nodes[0].kind!=1||b.nodes[1].kind!=2||b.nodes[1].parent!=0)return fail("Cash box layout root rejected");
  for(auto&clip:b.clips){clip.length=r.scalar();auto kc=r.number();if(!r.ok||clip.length<=0||clip.length>60||!kc||kc>256)return fail("Cash box clip length rejected");float last=-1;for(uint32_t j=0;j<kc;++j){FieldCashKey k;k.time=r.scalar();k.ease=r.scalar();k.value=r.scalar();if(!r.ok||k.time<0||k.time>clip.length||k.time<=last||k.ease==0)return fail("Cash box source continuous key rejected");last=k.time;clip.keys.push_back(k);}if(clip.keys[0].time!=0)return fail("Cash box initial animation key absent");}
 }
 auto count=r.number();if(count!=u32(p+52))return fail("Cash box proof coverage rejected");for(uint32_t i=0;i<count;++i){auto s=r.text();std::array<uint8_t,32>h{};if(!path(s)||!r.hash(h)||!d.sources_.emplace(s,h).second)return fail("Cash box source proof rejected");}if(!r.ok||r.at!=n)return fail("Cash box trailing data rejected");std::array<uint8_t,32>h{};if(!d.source_hash(d.script_,h)||!d.source_hash(d.font_,h))return fail("Cash box source script/font absent");for(const auto&b:d.boxes_)if(!d.source_hash(b.source,h))return fail("Cash box source scene absent");for(const auto&t:d.textures_)if(!d.source_hash(t.source,h)||!d.source_hash(t.source+".import",h))return fail("Cash box texture/import proof absent");d.valid_=true;*this=std::move(d);e.clear();return true;
}
}
