#include "encore/field_present.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <set>
namespace encore::upstream {namespace {
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=i>=16&&i<20?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
struct Reader {const uint8_t*p;size_t n,at=64;bool ok=true;uint32_t integer(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=u32(p+at);at+=4;return v;}float scalar(){auto v=integer();float f;std::memcpy(&f,&v,4);if(!std::isfinite(f)||std::abs(f)>1e6)ok=false;return f;}Vec2 point(){return{scalar(),scalar()};}BattleValue rect(){return{scalar(),scalar(),scalar(),scalar()};}std::string text(){auto len=integer();if(!ok||len>8192||at>n||len>n-at){ok=false;return{};}std::string s(reinterpret_cast<const char*>(p+at),len);at+=len;size_t i=0;uint32_t cp;while(i<s.size())if(!encore::utf8_next(s,i,cp)||cp<32){ok=false;break;}return s;}bool hash(std::array<uint8_t,32>&out){if(!ok||at>n||n-at<32){ok=false;return false;}bool any=false;for(unsigned i=0;i<32;++i){any|=p[at+i]!=0;out[i]=p[at+i];}at+=32;return ok&=any;}};
bool path(std::string_view p){return!p.empty()&&p.front()!='/'&&p.back()!='/'&&p.find("..") ==p.npos&&p.find(':')==p.npos&&p.find('\\')==p.npos;}
}
bool FieldPresentData::source_hash(std::string_view path_,std::array<uint8_t,32>&out)const{auto i=sources_.find(std::string(path_));if(i==sources_.end())return false;out=i->second;return true;}
const FieldPresentBinding*FieldPresentData::binding(uint32_t id)const{for(const auto&b:bindings_)if(b.id==id)return&b;return nullptr;}
const FieldPresentItem*FieldPresentData::item(std::string_view id)const{for(const auto&b:items_)if(b.key==id)return&b;return nullptr;}
bool FieldPresentData::load_file(const char*p,std::string&e){if(!p){e="Present pack path absent";return false;}std::ifstream f(p,std::ios::binary);if(!f){e="Present pack unavailable";return false;}f.seekg(0,std::ios::end);auto n=f.tellg();if(n<64||n>4*1024*1024){e="Present file size";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)){e="Present file read";return false;}return load(b.data(),b.size(),e);}
bool FieldPresentData::load(const uint8_t*p,size_t n,std::string&e){auto fail=[&](const char*m){e=m;return false;};if(!p||n<64||n>4*1024*1024)return fail("Present pack size");if(std::memcmp(p,"ENCPRE01",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+20)!=1||u32(p+24)!=1||!u32(p+28)||u32(p+28)>4096||u32(p+16)!=crc(p,n))return fail("Present header/version/capability/rules/CRC");for(size_t i=52;i<64;++i)if(p[i])return fail("Present reserved header");FieldPresentData d;std::copy(p+32,p+52,d.pin_.begin());if(std::all_of(d.pin_.begin(),d.pin_.end(),[](uint8_t b){return!b;}))return fail("Present source pin absent");Reader r{p,n};d.scene_=r.text();d.scene_name_=r.text();d.empty_message_=r.text();d.width_=r.integer();d.height_=r.integer();d.frames_=r.integer();d.box_source_=r.text();d.box_path_=r.text();d.sound_=r.text();if(!r.ok||!path(d.scene_)||d.scene_name_.empty()||!path(d.empty_message_)||!d.width_||!d.height_||d.width_>4096||d.height_>4096||!d.frames_||d.frames_>1024||d.width_%d.frames_||!path(d.box_source_)||!path(d.box_path_)||!path(d.sound_))return fail("Present source art/scene binding");d.box_bytes_=r.integer();d.box_crc_=r.integer();d.sparkle_bytes_=r.integer();d.sparkle_crc_=r.integer();d.sparkle_width_=r.integer();d.sparkle_height_=r.integer();if(!r.ok||d.box_bytes_>16*1024*1024||bool(d.box_bytes_)!=bool(d.box_crc_)||!d.sparkle_bytes_||d.sparkle_bytes_>16*1024*1024||!d.sparkle_crc_||!d.sparkle_width_||!d.sparkle_height_||d.sparkle_width_>4096||d.sparkle_height_>4096)return fail("Present art fingerprint");auto count=r.integer();if(!count||count>4096)return fail("Present item count");std::set<std::string>names;for(uint32_t i=0;i<count;++i){FieldPresentItem item;item.key=r.text();item.source=r.text();auto key=r.integer();item.keyitem=key;item.doses=r.integer();if(!r.ok||item.key.empty()||!names.insert(item.key).second||!path(item.source)||key>1||!item.doses||item.doses>65535)return fail("Present item source policy");d.items_.push_back(std::move(item));}
 for(auto&c:d.clips_){c.name=r.text();c.length=r.scalar();count=r.integer();if(!r.ok||c.name.empty()||c.length<=0||c.length>60||!count||count>64)return fail("Present animation topology");float last=-1;for(uint32_t i=0;i<count;++i){FieldPresentKey k;k.time=r.scalar();k.role=r.integer();k.value=r.integer();if(!r.ok||k.time<0||k.time<last||k.time>c.length||k.role<1||k.role>2||(k.role==1&&k.value>=d.frames_)||(k.role==2&&k.value>1))return fail("Present animation source track/key");last=k.time;c.keys.push_back(k);}}
 d.sparkle_speed_=r.scalar();d.sparkle_scale_=r.scalar();d.low_=r.scalar();d.high_=r.scalar();count=r.integer();d.sparkle_path_=r.text();if(!r.ok||d.sparkle_speed_<=0||d.sparkle_speed_>1024||d.sparkle_scale_<=0||d.sparkle_scale_>1024||d.low_<0||d.high_<d.low_||d.high_>=65536||!count||count>1024||!path(d.sparkle_path_))return fail("Present Sparkles RNG/clock");for(uint32_t i=0;i<count;++i){PresentSparklesFrame f{r.integer(),r.integer(),r.integer(),r.integer()};if(!r.ok||!f.width||!f.height||f.width>4096||f.height>4096||f.width>d.sparkle_width_||f.height>d.sparkle_height_||f.x>d.sparkle_width_-f.width||f.y>d.sparkle_height_-f.height)return fail("Present Sparkles atlas rect");d.sparkle_frames_.push_back(f);}
 count=r.integer();if(count!=u32(p+28))return fail("Present object count");std::set<uint32_t>ids,ready;names.clear();uint32_t previous=0;for(uint32_t i=0;i<count;++i){FieldPresentBinding h;h.id=r.integer();h.ready_ordinal=r.integer();h.sparkles_id=r.integer();h.sparkles_ready=r.integer();h.prompt_id=r.integer();h.tint_id=r.integer();h.fetcher_id=r.integer();h.flags=r.integer();h.initial_frame=r.integer();h.opened_frame=r.integer();h.collision_layer=r.integer();h.interaction_layer=r.integer();h.node=r.text();h.flag=r.text();h.item=r.text();h.dialogue=r.text();h.full=r.text();h.empty=r.text();h.position=r.point();h.scale=r.point();h.sprite_position=r.point();h.sparkles_position=r.point();h.collision=r.rect();h.interaction=r.rect();if(!r.ok||!h.id||!h.sparkles_id||!h.prompt_id||!h.tint_id||!h.fetcher_id||h.flags>31||!ids.insert(h.id).second||!ids.insert(h.sparkles_id).second||!ready.insert(h.ready_ordinal).second||!ready.insert(h.sparkles_ready).second||(i&&h.ready_ordinal<=previous)||h.sparkles_ready>=h.ready_ordinal||h.initial_frame>=d.frames_||h.opened_frame>=d.frames_||!h.collision_layer||!h.interaction_layer||!path(h.node)||!names.insert(h.node).second||h.flag.empty()||(!h.item.empty()&&!d.item(h.item))||!path(h.dialogue)||!path(h.full)||(!h.empty.empty()&&!path(h.empty))||h.scale.x<=0||h.scale.y<=0||h.collision.z<=0||h.collision.w<=0||h.interaction.z<=0||h.interaction.w<=0)return fail("Present instance/source geometry");previous=h.ready_ordinal;d.bindings_.push_back(std::move(h));}
 count=r.integer();if(count>4096)return fail("Present typed pending count");for(uint32_t i=0;i<count;++i){FieldPresentPending h;h.id=r.integer();h.ready_ordinal=r.integer();h.node=r.text();h.script=r.text();if(!r.ok||!h.id||!ids.insert(h.id).second||!path(h.node)||!path(h.script))return fail("Present pending source identity");d.pending_.push_back(std::move(h));}
 count=r.integer();if(!count||count>2048)return fail("Present source receipts");names.clear();for(uint32_t i=0;i<count;++i){auto s=r.text();if(!r.ok||!path(s)||!names.insert(s).second||!r.hash(d.sources_[s]))return fail("Present source hash receipt");}if(!names.count(d.scene_)||!names.count(d.box_source_)||!names.count(d.sound_))return fail("Present source closure");for(const auto&i:d.items_)if(!names.count(i.source))return fail("Present item source closure");if(!r.ok||r.at!=n)return fail("Present trailing bytes");d.valid_=true;*this=std::move(d);e.clear();return true;
}
}
