#include "encore/field_sparkles.hpp"
#include "encore/field_present.hpp"
#include "encore/field_dropped.hpp"
#include <algorithm>
#include <cmath>
namespace encore::upstream {
bool FieldSparklesRuntime::fail(const char*s){error_=s;poisoned_=true;return false;}
FieldSparklesInstance*FieldSparklesRuntime::get(uint32_t id){auto it=instances_.find(id);if(poisoned_||!data_||it==instances_.end()){fail("Sparkles unknown/invalidated instance");return nullptr;}return &it->second;}
const FieldSparklesInstance*FieldSparklesRuntime::instance(uint32_t id)const{auto it=instances_.find(id);return it==instances_.end()?nullptr:&it->second;}
float FieldSparklesRuntime::duration(const FieldSparklesInstance&s)const{auto*a=data_->animation(s.profile);float speed=a->speed*s.speed_scale;return speed>0?float(1.0/double(speed)):0;}
void FieldSparklesRuntime::reset_timeout(FieldSparklesInstance&s){if(s.playing){s.timeout=duration(s);s.is_over=false;}}
bool FieldSparklesRuntime::publish(FieldSparklesInstance&s){if(!host_.publish(s.id,s,error_)){poisoned_=true;return false;}return true;}
bool FieldSparklesRuntime::emit(FieldSparklesInstance&s,FieldSparklesSignal signal){const auto id=s.id;const bool outer=dispatching_.insert(id).second;if(!host_.emit(id,signal,error_)){if(outer)dispatching_.erase(id);poisoned_=true;return false;}if(outer)dispatching_.erase(id);return !poisoned_;}
bool FieldSparklesRuntime::observe(uint32_t id,FieldSparklesObservation&o){if(!host_.observe(id,o,error_)){poisoned_=true;return false;}if(!o.alive||!o.ancestors_admitted||!o.listeners_admitted)return fail("Sparkles actual lifetime/ancestor/signal consumer rejected");return true;}
bool FieldSparklesRuntime::initialize(const FieldSparklesData&d,SourceRandom&r,FieldSparklesHost h,FieldPresentRuntime&p,FieldDroppedRuntime&drop,std::string&e){if(data_||!d.valid()||!h.bind||!h.observe||!h.publish||!h.emit||!p.content()||!drop.content()){e="Sparkles requires actual scene/signal/render/single-owner backend";return false;}if(!validate_sparkles_owner_bridge(d,*p.content(),*drop.content(),e)||!h.bind(d,e))return false;data_=&d;random_=&r;present_=&p;dropped_=&drop;host_=std::move(h);error_.clear();e.clear();return true;}
bool FieldSparklesRuntime::create(uint32_t id){if(!data_||poisoned_||had_ready_||created_.count(id))return fail("Sparkles create order/identity rejected");auto*n=data_->record(id);if(!n)return fail("Sparkles source instance absent");created_.insert(id);if(n->owner!=FieldSparklesOwner::Self){error_.clear();return true;}FieldSparklesInstance s;s.id=id;s.profile=n->profile;s.frame=n->frame;s.speed_scale=n->speed_scale;s.playing=n->flags&1;s.visible=n->flags&2;reset_timeout(s);instances_.emplace(id,s);return publish(instances_.at(id));}
bool FieldSparklesRuntime::ready(uint32_t id){if(!data_||poisoned_||!created_.count(id))return fail("Sparkles Ready before create");auto*n=data_->record(id);if((had_ready_&&n->ready<=last_ready_)||borrowed_ready_.count(id))return fail("Sparkles Ready repeated/out of source order");FieldSparklesObservation o;if(!observe(id,o))return false;if(n->owner!=FieldSparklesOwner::Self){bool ok=n->owner==FieldSparklesOwner::Present?present_->ready_sparkles(id,*random_,error_):dropped_->ready_sparkles(id,*random_,error_);if(!ok){poisoned_=true;return false;}borrowed_ready_.insert(id);had_ready_=true;last_ready_=n->ready;error_.clear();return true;}auto*s=get(id);if(!s)return false;if(s->ready)return fail("Sparkles Ready repeated");double sample=random_->rand_range(data_->random_low(),data_->random_high());if(!std::isfinite(sample)||sample<0||sample>=65536)return fail("Sparkles RNG result rejected");s->ready=true;had_ready_=true;last_ready_=n->ready;if(std::min(uint32_t(sample),uint32_t(data_->animation(s->profile)->frames.size()-1))==s->frame){return publish(*s);}return set_frame(id,int32_t(sample));}
bool FieldSparklesRuntime::set_frame(uint32_t id,int32_t value){auto*s=get(id);if(!s)return false;auto*a=data_->animation(s->profile);uint32_t v=uint32_t(std::max(int32_t(0),std::min(value,int32_t(a->frames.size()-1))));if(v==s->frame){error_.clear();return true;}s->frame=v;reset_timeout(*s);if(!publish(*s))return false;return emit(*s,FieldSparklesSignal::FrameChanged);}
bool FieldSparklesRuntime::speed_scale(uint32_t id,float value){auto*s=get(id);if(!s)return false;if(!std::isfinite(value)||value<0||value>1024)return fail("Sparkles speed input rejected");float speed=data_->animation(s->profile)->speed*value;if(!std::isfinite(speed)||speed>1024)return fail("Sparkles speed budget rejected");float elapsed=duration(*s)-s->timeout;s->speed_scale=value;reset_timeout(*s);s->timeout-=elapsed;return publish(*s);}
bool FieldSparklesRuntime::play(uint32_t id,bool backwards){auto*s=get(id);if(!s)return false;s->backwards=backwards;s->is_over=false;if(!s->playing){s->playing=true;reset_timeout(*s);}return publish(*s);}
bool FieldSparklesRuntime::stop(uint32_t id){auto*s=get(id);if(!s)return false;if(s->playing){s->playing=false;reset_timeout(*s);}return publish(*s);}
bool FieldSparklesRuntime::visibility(uint32_t id,bool value){auto*s=get(id);if(!s)return false;s->visible=value;return publish(*s);}
bool FieldSparklesRuntime::idle_frame(uint32_t id,float delta){auto*s=get(id);if(!s)return false;if(!s->ready||!std::isfinite(delta)||delta<0||delta>1)return fail("Sparkles idle interval/Ready rejected");FieldSparklesObservation o;if(!observe(id,o))return false;if(!s->playing||!o.can_process||!o.update_pending){error_.clear();return true;}float remaining=delta;while(remaining){auto*a=data_->animation(s->profile);if(a->speed*s->speed_scale==0)return true;if(s->timeout<=0){s->timeout=duration(*s);bool end=(!s->backwards&&s->frame>=a->frames.size()-1)||(s->backwards&&s->frame==0);bool finish=false;if(end){if(a->loop){s->frame=s->backwards?uint32_t(a->frames.size()-1):0;finish=true;}else{s->frame=s->backwards?0:uint32_t(a->frames.size()-1);if(!s->is_over){s->is_over=true;finish=true;}}}else if(s->backwards)--s->frame;else ++s->frame;if(finish&&!emit(*s,FieldSparklesSignal::AnimationFinished))return false;if(!publish(*s)||!emit(*s,FieldSparklesSignal::FrameChanged))return false;}float process=std::min(s->timeout,remaining);if(!std::isfinite(process)||process<0)return fail("Sparkles reentrant clock became invalid");remaining-=process;s->timeout-=process;}error_.clear();return true;}
bool FieldSparklesRuntime::destroy(uint32_t id){if(!data_||poisoned_||!created_.count(id))return fail("Sparkles destroy identity rejected");auto*n=data_->record(id);if(n->owner==FieldSparklesOwner::Present){auto*s=present_->state(n->parent_id);if(s&&s->alive)return fail("Sparkles Present child requires actual owner exit first");}else if(n->owner==FieldSparklesOwner::Dropped){auto*s=dropped_->state(n->parent_id);if(s&&s->alive)return fail("Sparkles Dropped child requires actual owner exit first");}else{if(dispatching_.count(id))return fail("Sparkles immediate signal deletion requires admitted lifecycle backend");instances_.erase(id);}created_.erase(id);borrowed_ready_.erase(id);error_.clear();return true;}
bool FieldSparklesRuntime::draw(uint32_t id,FieldSparklesDraw&out){FieldSparklesInstance state;if(!snapshot(id,state))return false;auto*s=&state;if(!s->ready)return fail("Sparkles draw before Ready");FieldSparklesObservation o;if(!observe(id,o))return false;if(!o.material_admitted)return fail("Sparkles actual ancestor material rejected");for(auto v:o.world)if(!std::isfinite(v.x)||!std::isfinite(v.y)||std::abs(v.x)>=1e6||std::abs(v.y)>=1e6)return fail("Sparkles actual transform rejected");if(o.world[0].y!=0||o.world[1].x!=0||o.world[0].x==0||o.world[1].y==0)return fail("Sparkles rotated/sheared live GPU transform unsupported");for(float v:o.canvas_color)if(!std::isfinite(v)||v<0||v>1)return fail("Sparkles actual ancestor color rejected");auto*n=data_->record(id);auto*a=data_->animation(s->profile);FieldSparklesDraw d;d.id=id;d.frame=a->frames[s->frame];d.local_origin=n->offset;if(n->flags&4){d.local_origin.x-=d.frame.width*.5f;d.local_origin.y-=d.frame.height*.5f;}if(n->flags&8){d.local_origin.x=std::floor(d.local_origin.x);d.local_origin.y=std::floor(d.local_origin.y);}d.world_origin={o.world[2].x+d.local_origin.x*o.world[0].x,o.world[2].y+d.local_origin.y*o.world[1].y};d.world_scale={o.world[0].x,o.world[1].y};d.color=o.canvas_color;d.visible=s->visible&&o.visible_in_tree;d.pixel_snap=n->flags&8;out=d;error_.clear();return true;}
}
