#include "encore/field_game_camera.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <utility>
namespace encore::upstream {namespace {
bool finite(Vec2 v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::abs(v.x)<1000000&&std::abs(v.y)<1000000;}
bool equal(Vec2 a,Vec2 b){return a.x==b.x&&a.y==b.y;}
Vec2 add(Vec2 a,Vec2 b){return {a.x+b.x,a.y+b.y};}
Vec2 transform(const std::array<Vec2,3>&m,Vec2 p){return {m[0].x*p.x+m[1].x*p.y+m[2].x,m[0].y*p.x+m[1].y*p.y+m[2].y};}
float interpolate(float initial,float change,float time,float duration,uint32_t transition,uint32_t ease){
 // Native Tween equations (float real_t), currently admitted LINEAR/SINE.
 if(!transition)return change*time/duration+initial;
 const float pi=float(std::acos(-1.0));
 switch(ease){case 0:return -change*std::cos(time/duration*(pi/2))+change+initial;case 1:return change*std::sin(time/duration*(pi/2))+initial;case 2:return -change/2*(std::cos(pi*time/duration)-1)+initial;default:if(time<duration/2)return interpolate(initial,change/2,time*2,duration,transition,1);return interpolate(initial+change/2,change/2,time*2-duration,duration,transition,0);}
}
}
bool FieldGameCameraRuntime::fail(const char*s){error_=s;poisoned_=true;return false;}
FieldGameCameraState*FieldGameCameraRuntime::get(uint32_t id,bool ready){auto i=states_.find(id);if(poisoned_||!data_||i==states_.end()||!i->second.alive||(ready&&!i->second.ready)){fail("GameCamera source lifetime/Ready rejected");return nullptr;}return &i->second;}
const FieldGameCameraState*FieldGameCameraRuntime::state(uint32_t id)const{auto i=states_.find(id);return i==states_.end()?nullptr:&i->second;}
bool FieldGameCameraRuntime::observe(uint32_t id,FieldGameCameraObservation&o){if(!host_.observe(id,o,error_)){poisoned_=true;return false;}if(!o.alive||!o.ancestors_admitted||!o.listeners_admitted||!o.native_geometry_admitted||o.physics_interpolation_enabled)return fail("GameCamera actual ancestor/listener/geometry admission rejected");return true;}
bool FieldGameCameraRuntime::publish(FieldGameCameraState&s){if(!finite(s.position)||!finite(s.offset)||!finite(s.base)||!finite(s.shake)||!finite(s.camarea))return fail("GameCamera state overflow rejected");if(!host_.publish(s.id,s,error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::initialize(const FieldGameCameraData&d,SourceRandom&r,FieldGameCameraHost h,std::string&e){if(data_&&!states_.empty()){e="GameCamera live owner reinitialize rejected";return false;}if(!d.valid()||!h.bind||!h.observe||!h.publish||!h.publish_canvas||!h.scope||!h.arrow_visible||!h.animation_signal||!h.current_camera_snapshot||!h.make_current||!h.set_global_current){e="GameCamera Ready/native source host required";return false;}if(!h.bind(d,e))return false;data_=&d;random_=&r;host_=std::move(h);states_.clear();pending_source_constructor_.clear();tweens_.clear();shakers_.clear();next_=1;had_ready_=poisoned_=false;last_ready_=0;error_.clear();e.clear();return true;}
bool FieldGameCameraRuntime::create(uint32_t id,bool source_constructor){if(!data_||poisoned_||states_.count(id))return fail("GameCamera create rejected");auto*d=data_->record(id);if(!d)return fail("GameCamera source identity rejected");FieldGameCameraState s;s.id=id;s.position=d->position;s.offset=d->offset;s.current=d->flags&1;s.limits=d->limits;states_.emplace(id,s);
 if(source_constructor){pending_source_constructor_.insert(id);return true;}return publish(states_.at(id))&&native_update(id);}
bool FieldGameCameraRuntime::ready(uint32_t id){auto*s=get(id,false);if(!s)return false;auto*d=data_->record(id);FieldGameCameraObservation o;if(s->ready||(had_ready_&&d->ready<=last_ready_)||!observe(id,o)||!o.native_children_ready)return fail("GameCamera native postorder Ready rejected");if(pending_source_constructor_.count(id)){if(!publish(*s)||!native_update(id))return false;pending_source_constructor_.erase(id);}s->ready=true;had_ready_=true;last_ready_=d->ready;if(o.parent_is_global_player&&(!host_.connect_player||!host_.connect_player(id,[this,id]{return scoping_stop(id);},[this,id]{return player_pause(id);},error_))){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::native_update(uint32_t id){auto*s=get(id,false);if(!s)return false;if(!s->current)return true;FieldGameCameraObservation o;if(!observe(id,o))return false;
 // All14 original instances use the audited no-drag/no-smoothing/zoom1 case.
 // No unsupported parent rotation/scale or synthetic viewport is admitted.
 if(!finite(o.viewport)||o.viewport.x<=0||o.viewport.y<=0||!equal(o.parent_world[0],{1,0})||!equal(o.parent_world[1],{0,1})||!finite(o.parent_world[2]))return fail("GameCamera native viewport/parent transform unsupported");
 Vec2 global=transform(o.parent_world,s->position),origin{global.x-o.viewport.x*.5f,global.y-o.viewport.y*.5f};
 if(origin.x<s->limits[1])origin.x=float(s->limits[1]);
 if(origin.x+o.viewport.x>s->limits[2])origin.x=float(s->limits[2])-o.viewport.x;
 if(origin.y+o.viewport.y>s->limits[3])origin.y=float(s->limits[3])-o.viewport.y;
 if(origin.y<s->limits[0])origin.y=float(s->limits[0]);
 s->canvas_origin=add(origin,s->offset);s->screen_center={s->canvas_origin.x+o.viewport.x*.5f,s->canvas_origin.y+o.viewport.y*.5f};
 if(!finite(s->canvas_origin)||!finite(s->screen_center))return fail("GameCamera native canvas overflow");
 if(!host_.publish_canvas(id,s->canvas_origin,s->screen_center,error_)){poisoned_=true;return false;}return true;
}
bool FieldGameCameraRuntime::set_position(uint32_t id,Vec2 p,bool global){auto*s=get(id,false);if(!s||!finite(p))return fail("GameCamera position rejected");if(global){FieldGameCameraObservation o;if(!observe(id,o))return false;float determinant=o.parent_world[0].x*o.parent_world[1].y-o.parent_world[1].x*o.parent_world[0].y;if(!std::isfinite(determinant)||determinant==0)return fail("GameCamera inverse parent transform rejected");Vec2 v{p.x-o.parent_world[2].x,p.y-o.parent_world[2].y};p={(o.parent_world[1].y*v.x-o.parent_world[1].x*v.y)/determinant,(-o.parent_world[0].y*v.x+o.parent_world[0].x*v.y)/determinant};}s->position=p;return publish(*s)&&native_update(id);}
bool FieldGameCameraRuntime::set_limit(uint32_t id,FieldCameraLimit l,int32_t v){auto*s=get(id,false);if(!s||uint32_t(l)>3)return fail("GameCamera limit rejected");s->limits[size_t(l)]=v;return publish(*s)&&native_update(id);}
bool FieldGameCameraRuntime::adjust_camareas(uint32_t id,int64_t delta,int64_t&result){auto*s=get(id,false);if(!s)return false;if((delta>0&&s->camareas>std::numeric_limits<int64_t>::max()-delta)||(delta<0&&s->camareas<std::numeric_limits<int64_t>::min()-delta))return fail("GameCamera camareas overflow");s->camareas+=delta;result=s->camareas;return publish(*s);}
bool FieldGameCameraRuntime::set_camarea_offset(uint32_t id,Vec2 off){auto*s=get(id);if(!s||!finite(off))return fail("GameCamera camarea offset rejected");s->camarea=off;return set_position(id,off);}
bool FieldGameCameraRuntime::get_offset_with_camerea_offset(uint32_t id,Vec2&out){auto*s=get(id);if(!s)return false;out=add(s->position,s->camarea);return finite(out)||fail("GameCamera offset getter overflow");}
bool FieldGameCameraRuntime::reset(uint32_t id){return get(id)!=nullptr;} // Source loop reassigns its local variable only.
bool FieldGameCameraRuntime::idle(uint32_t id,float delta){auto*s=get(id);FieldGameCameraObservation o;if(!s||!std::isfinite(delta)||delta<0||!observe(id,o))return false;if(o.can_process&&o.scope_visible&&!host_.scope(data_->record(id)->arrows_id,FieldScopeOperation::GlobalPosition,s->screen_center,error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::physics(uint32_t id,float delta){auto*s=get(id);FieldGameCameraObservation o;if(!s||!std::isfinite(delta)||delta<0||!observe(id,o))return false;if(!o.can_process)return true;s->offset=!o.in_battle&&o.player_state!=data_->player_states()[0]?add(s->base,s->shake):s->base;if(!publish(*s)||!native_update(id))return false;if(!o.player_damaged&&o.current_camera==id&&o.player_state==data_->player_states()[0]){if(o.scope_just_pressed&&!scoping_start(id))return false;if(o.scope_just_released&&!scoping_stop(id))return false;if(!observe(id,o))return false;if(o.scope_pressed&&o.player_state!=data_->player_states()[1]&&!scoping_process(id))return false;}return true;}
bool FieldGameCameraRuntime::input(uint32_t id){if(!get(id))return false;if(!host_.scope(data_->record(id)->arrows_id,FieldScopeOperation::Input,{},error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::play_animation(FieldGameCameraState&s,uint32_t role){if(!role||role>3)return fail("GameCamera animation role rejected");if(s.animation_role!=role||s.animation_time==data_->animation_lengths()[role-1])s.animation_time=0;s.animation_role=role;s.animation_playing=true;if(!host_.animation_signal(data_->record(s.id)->animation_id,role,true,error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::animation_idle(uint32_t node,float delta){if(!data_||poisoned_||!std::isfinite(delta)||delta<0)return fail("GameCamera animation idle rejected");const FieldGameCameraDescriptor*d=nullptr;for(const auto&r:data_->records())if(r.animation_id==node){d=&r;break;}if(!d)return fail("GameCamera native animation identity rejected");auto*s=get(d->id,false);FieldGameCameraObservation o;if(!s||!observe(node,o))return false;if(!o.can_process||!s->animation_playing)return true;float candidate=s->animation_time+delta;if(!std::isfinite(candidate))return fail("GameCamera animation overflow");float length=data_->animation_lengths()[s->animation_role-1];bool ended=candidate>=length&&s->animation_time<length;s->animation_time=std::min(candidate,length);if(ended){s->animation_playing=false;if(delta&&!host_.animation_signal(node,s->animation_role,false,error_)){poisoned_=true;return false;}}return true;}
bool FieldGameCameraRuntime::scoping_start(uint32_t id){if(!host_.info_plates_hide)return fail("Camera scope native owner unavailable");auto*s=get(id);if(!s)return false;if(!host_.info_plates_hide(error_)){poisoned_=true;return false;}if(!set_position(id,s->screen_center,true)||!play_animation(*s,1))return false;if(!host_.scope(data_->record(id)->arrows_id,FieldScopeOperation::Show,{},error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::scoping_stop(uint32_t id){if(!host_.player_exit_camera)return fail("Camera scope native owner unavailable");auto*s=get(id);if(!s)return false;if(!host_.scope(data_->record(id)->arrows_id,FieldScopeOperation::Hide,{},error_)||!play_animation(*s,2)||!host_.player_exit_camera(error_)){poisoned_=true;return false;}uint64_t token;return return_offset(id,float(tuning(FieldCameraTuning::ScopeReturn)),token);}
bool FieldGameCameraRuntime::player_pause(uint32_t id){if(!get(id))return false;if(!host_.scope(data_->record(id)->arrows_id,FieldScopeOperation::Hide,{},error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::scoping_process(uint32_t id){auto*s=get(id);FieldGameCameraObservation o;if(!s||!observe(id,o)||!finite(o.controls))return fail("GameCamera actual source controls rejected");Vec2 center=s->screen_center,dir{};double limit=tuning(FieldCameraTuning::Limit),vertical=tuning(FieldCameraTuning::ScopeVertical),horizontal=tuning(FieldCameraTuning::ScopeHorizontal);bool up=s->base.y>-limit&&center.y-vertical>s->limits[0],down=s->base.y<limit&&center.y+vertical<s->limits[3],left=s->base.x>-limit&&center.x-horizontal>s->limits[1],right=s->base.x<limit&&center.x+horizontal<s->limits[2];auto arrows=data_->record(id)->arrows_id;for(auto item:{std::pair<Vec2,bool>{{0,-1},up},{{0,1},down},{{-1,0},left},{{1,0},right}})if(!host_.arrow_visible(arrows,item.first,item.second,error_)){poisoned_=true;return false;}if(o.controls.y<0&&up)dir.y=-1;else if(o.controls.y>0&&down)dir.y=1;if(o.controls.x<0&&left)dir.x=-1;else if(o.controls.x>0&&right)dir.x=1;s->base={s->base.x+float(dir.x*tuning(FieldCameraTuning::ScopeSpeed)),s->base.y+float(dir.y*tuning(FieldCameraTuning::ScopeSpeed))};return publish(*s);}
bool FieldGameCameraRuntime::set_current(uint32_t id){auto*s=get(id);if(!s)return false;FieldGameCameraState previous;if(!host_.current_camera_snapshot(id,previous,error_)){poisoned_=true;return false;}
 // Source copies each property in BOTTOM,LEFT,RIGHT,TOP order. Each native
 // setter may update the old current camera, including self reassignment.
 for(auto l:{FieldCameraLimit::Bottom,FieldCameraLimit::Left,FieldCameraLimit::Right,FieldCameraLimit::Top}){if(!host_.current_camera_snapshot(id,previous,error_)||!set_limit(id,l,previous.limits[size_t(l)])){poisoned_=true;return false;}}
 if(!host_.current_camera_snapshot(id,previous,error_)){poisoned_=true;return false;}s->camareas=previous.camareas;if(!set_position(id,previous.screen_center,true))return false;for(auto&entry:states_)entry.second.current=false;s->current=true;if(!host_.make_current(id,error_)||!native_update(id)||!host_.set_global_current(id,error_)){poisoned_=true;return false;}return publish(*s);
}
bool FieldGameCameraRuntime::property(FieldGameCameraState&s,FieldCameraProperty p,Vec2 v){if(!finite(v))return fail("GameCamera tween property overflow");if(p==FieldCameraProperty::Position)return set_position(s.id,v);if(p==FieldCameraProperty::GlobalPosition)return set_position(s.id,v,true);if(p==FieldCameraProperty::BaseOffset)s.base=v;else if(p==FieldCameraProperty::ShakeOffset)s.shake=v;else return fail("GameCamera unknown tween property");return publish(s);}
bool FieldGameCameraRuntime::read_property(FieldGameCameraState&s,FieldCameraProperty p,Vec2&v){if(p==FieldCameraProperty::Position)v=s.position;else if(p==FieldCameraProperty::BaseOffset)v=s.base;else if(p==FieldCameraProperty::ShakeOffset)v=s.shake;else if(p==FieldCameraProperty::GlobalPosition){FieldGameCameraObservation o;if(!observe(s.id,o))return false;v=transform(o.parent_world,s.position);}else return fail("GameCamera property source rejected");return finite(v)||fail("GameCamera property overflow");}
bool FieldGameCameraRuntime::kill_shared(FieldGameCameraState&s,bool running_only){if(!s.shared_tween)return true;auto i=tweens_.find(s.shared_tween);if(i==tweens_.end())return fail("GameCamera shared tween identity lost");if(running_only&&!i->second.running)return true;i->second.alive=i->second.running=false;if(!host_.kill_tween||!host_.kill_tween(i->first,error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::tween(FieldGameCameraState&s,std::vector<FieldCameraTweenTrack>tracks,float duration,uint32_t transition,uint32_t ease,uint32_t continuation,uint64_t&token){if(!host_.register_tween||!host_.kill_tween||!host_.tween_signal||!host_.coroutine_completed||!host_.await_idle_frame||!host_.cancel_idle_frame||!host_.stopped_shaking)return fail("Camera requested source Tween/coroutine owner unavailable");if(!std::isfinite(duration)||std::abs(duration)>=1000000||transition>1||ease>3||tracks.empty()||tracks.size()>2||!next_)return fail("GameCamera unsupported source Tween request");FieldCameraTweenState t;t.token=next_++;t.camera=s.id;t.transition=transition;t.ease=ease;t.duration=duration;t.continuation=continuation;t.tracks=std::move(tracks);for(auto&track:t.tracks){if(!finite(track.target)||!read_property(s,track.property,track.initial))return false;}token=t.token;tweens_.emplace(token,t);if(!host_.register_tween(s.id,token,[this,token](float delta){return step_tween(token,delta);},error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::move_camera(uint32_t id,Vec2 pos,float time,uint64_t&token,uint32_t transition,uint32_t ease){auto*s=get(id);if(!s||!finite(pos)||!std::isfinite(time)||!kill_shared(*s,true))return false;token=0;if(time<=0)return set_position(id,pos,true);FieldCameraTweenTrack track{FieldCameraProperty::GlobalPosition,pos,s->screen_center,true};if(!tween(*s,{track},time,transition,ease,1,token))return false;tweens_.at(token).tracks[0].initial=track.initial;s->shared_tween=token;return publish(*s);}
bool FieldGameCameraRuntime::move_offset(uint32_t id,Vec2 target,float time,uint64_t&token){auto*s=get(id);if(!s||!finite(target)||!kill_shared(*s,true))return false;Vec2 center=s->screen_center;auto clamp=[](float v,float low,float high){return v<low?low:v>high?high:v;};target.x=clamp(target.x,float(s->limits[1])-center.x,float(s->limits[2])-center.x);target.y=clamp(target.y,float(s->limits[0])-center.y,float(s->limits[3])-center.y);if(!tween(*s,{{FieldCameraProperty::BaseOffset,target,{},false}},time,1,1,0,token))return false;s->shared_tween=token;return publish(*s);}
bool FieldGameCameraRuntime::return_camera(uint32_t id,float time,uint64_t&token){auto*s=get(id);if(!s||!kill_shared(*s,false)||!tween(*s,{{FieldCameraProperty::Position,s->camarea,{},false}},time,1,1,2,token))return false;s->shared_tween=token;return publish(*s);}
bool FieldGameCameraRuntime::return_offset(uint32_t id,float time,uint64_t&token){auto*s=get(id);if(!s||!kill_shared(*s,false)||!tween(*s,{{FieldCameraProperty::BaseOffset,{}, {},false},{FieldCameraProperty::Position,s->camarea,{},false}},time,1,1,3,token))return false;s->shared_tween=token;return publish(*s);}
bool FieldGameCameraRuntime::complete_tween(FieldCameraTweenState&t){auto*s=get(t.camera);if(!s)return false;if(t.continuation==2&&!set_position(s->id,s->camarea))return false;if(t.continuation==3){if(!set_position(s->id,s->camarea))return false;s->base={};if(!publish(*s))return false;}if(t.continuation==4){auto i=shakers_.find(t.continuation_owner);if(i==shakers_.end()||!i->second.alive)return fail("GameCamera shake continuation owner rejected");i->second.awaiting_idle=true;auto token=i->first;if(!host_.await_idle_frame(token,[this,token]{return resume_shake_idle(token);},error_)){poisoned_=true;return false;}return true;}if(t.continuation&&!host_.coroutine_completed(t.token,error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::step_tween(uint64_t token,float delta){auto i=tweens_.find(token);if(poisoned_||i==tweens_.end()||!std::isfinite(delta)||delta<0)return fail("GameCamera actual Tween token/delta rejected");auto&t=i->second;if(!t.alive||!t.running)return true;auto*s=get(t.camera);FieldGameCameraObservation o;if(!s||!observe(s->id,o))return false;if(!o.can_process)return true;if(!t.started){for(auto&tr:t.tracks)if(!tr.explicit_initial&&!read_property(*s,tr.property,tr.initial))return false;t.started=true;t.elapsed=0;}if(delta==0)return true;float candidate=t.elapsed+delta;if(!std::isfinite(candidate))return fail("GameCamera Tween time overflow");t.elapsed=candidate;bool done=t.elapsed>=t.duration;
 for(size_t index=0;index<t.tracks.size();++index){auto&tr=t.tracks[index];Vec2 value=tr.target;if(!done){float time=std::min(t.elapsed,t.duration);value={interpolate(tr.initial.x,tr.target.x-tr.initial.x,time,t.duration,t.transition,t.ease),interpolate(tr.initial.y,tr.target.y-tr.initial.y,time,t.duration,t.transition,t.ease)};}if(!property(*s,tr.property,value))return false;if(done){if(!host_.tween_signal(token,uint32_t(index),false,error_)){poisoned_=true;return false;}if(t.continuation==1||t.continuation==2){if(!complete_tween(t))return false;t.continuation=0;}}}
 if(done){t.alive=t.running=false;if(!host_.tween_signal(token,0,true,error_)){poisoned_=true;return false;}return complete_tween(t);}return true;
}
bool FieldGameCameraRuntime::shake_camera(uint32_t id,uint64_t&token){return shake_camera(id,tuning(FieldCameraTuning::ShakeMagnitude),tuning(FieldCameraTuning::ShakeLength),data_->shake_direction(),tuning(FieldCameraTuning::ShakeInterval),tuning(FieldCameraTuning::ShakeWeight),true,token);}
bool FieldGameCameraRuntime::shake_camera(uint32_t id,double magnitude,double length,Vec2 direction,double interval,double weight,bool diminish,uint64_t&token){if(!host_.create_shaker||!host_.shaker_finished||!host_.queue_free_shaker||!host_.register_tween||!host_.kill_tween||!host_.tween_signal||!host_.coroutine_completed||!host_.await_idle_frame||!host_.cancel_idle_frame||!host_.stopped_shaking)return fail("Camera requested source Shaker/native job owner unavailable");auto*s=get(id);FieldGameCameraObservation o;if(!s||!observe(id,o))return false;token=0;if(o.scope_visible)return true;if(!std::isfinite(magnitude)||!std::isfinite(length)||!std::isfinite(interval)||!std::isfinite(weight)||interval<=0||!finite(direction)||std::abs(magnitude)>=1000000||std::abs(length)>=1000000||std::abs(weight)>=1000000||!next_)return fail("GameCamera source shake parameters rejected");double count=std::trunc(length/interval);if(!std::isfinite(count)||std::abs(count)>std::numeric_limits<int32_t>::max()||(diminish&&count==0))return fail("GameCamera source shake division/overflow rejected");FieldCameraShakerState sh;sh.token=next_++;sh.camera=id;sh.magnitude=magnitude;sh.length=length;sh.direction=sh.dir=direction;sh.interval=interval;sh.weight=weight;sh.diminish=diminish;sh.shakes_left=int64_t(count);sh.reduction=diminish?magnitude/count:0;sh.old_offset=s->shake;sh.side=tuning(FieldCameraTuning::ShakeSide);sh.side_amplitude=data_->shake_side_amplitude();s->shaking=true;if(!publish(*s))return false;token=sh.token;shakers_.emplace(token,sh);if(!host_.create_shaker(id,token,[this,token](float delta){return shaker_physics(token,delta);},error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::shaker_physics(uint64_t token,float delta){auto i=shakers_.find(token);if(poisoned_||i==shakers_.end()||!i->second.alive||!i->second.child_alive||i->second.stopped||!std::isfinite(delta)||delta<0)return fail("Shaker actual source physics rejected");auto&sh=i->second;auto*s=get(sh.camera);if(!s)return false;if(!sh.playing)return true;if(sh.shakes_left<=0)return stop_shaker(token);double timer=sh.timer+double(delta);if(!std::isfinite(timer))return fail("Shaker timer overflow");sh.timer=timer;if(sh.timer>=sh.interval){--sh.shakes_left;sh.side=-sh.side;sh.timer-=sh.interval;double side=sh.side*(sh.side==1?sh.side_amplitude.y:sh.side_amplitude.x),mag=std::max(sh.magnitude,tuning(FieldCameraTuning::ShakeMinimum));if(sh.magnitude<=tuning(FieldCameraTuning::ShakeSmall)&&sh.side==-1)mag=0;Vec2 multiplier;if(!equal(sh.direction,{}))multiplier={float(side),float(side)};else{multiplier={1,1};Vec2 previous=sh.dir;while(equal(sh.dir,previous)){double x=random_->rand_range(-1,1);double y=random_->rand_range(-1,1);sh.dir={float(std::round(x)),float(std::round(y))};}}
 Vec2 offset{(multiplier.x*sh.dir.x)*float(mag)+sh.old_offset.x,(multiplier.y*sh.dir.y)*float(mag)+sh.old_offset.y};Vec2 value=sh.shakes_left>int64_t(tuning(FieldCameraTuning::ShakeLast))?offset:sh.old_offset;if(sh.magnitude>tuning(FieldCameraTuning::ShakeDirect))value={s->shake.x+float((value.x-s->shake.x)*float(sh.weight)),s->shake.y+float((value.y-s->shake.y)*float(sh.weight))};s->shake=value;if(!publish(*s))return false;}
 // Original reduction occurs EVERY playing physics frame, outside step condition.
 if(sh.diminish){double candidate=sh.magnitude-sh.reduction;if(!std::isfinite(candidate))return fail("Shaker magnitude overflow");sh.magnitude=candidate;}return true;
}
bool FieldGameCameraRuntime::pause_shaker(uint64_t token){auto i=shakers_.find(token);if(poisoned_||i==shakers_.end()||!i->second.alive||!i->second.child_alive||i->second.stopped)return fail("Shaker pause lifetime rejected");i->second.playing=false;return true;}
bool FieldGameCameraRuntime::set_shake_side_amplitude(uint64_t token,Vec2 v){auto i=shakers_.find(token);if(poisoned_||i==shakers_.end()||!i->second.alive||!i->second.child_alive||!finite(v))return fail("Shaker side amplitude rejected");i->second.side_amplitude=v;return true;}
bool FieldGameCameraRuntime::stop_shaker(uint64_t token){auto i=shakers_.find(token);if(poisoned_||i==shakers_.end()||!i->second.alive||!i->second.child_alive||i->second.stopped)return fail("Shaker stop lifetime rejected");auto&sh=i->second;auto*s=get(sh.camera);if(!s)return false;s->shake=sh.old_offset;sh.playing=false;sh.stopped=true;if(!publish(*s)||!host_.shaker_finished(token,error_)){poisoned_=true;return false;}
 // Actual source coroutine creates a separate tween, never overwrites the
 // shared move/return tween. Its final idle_frame wait survives node pauses.
 uint64_t final_token;if(!tween(*s,{{FieldCameraProperty::ShakeOffset,{}, {},false}},float(tuning(FieldCameraTuning::ShakeFinalTime)),0,2,4,final_token))return false;tweens_.at(final_token).continuation_owner=token;if(!host_.queue_free_shaker(token,error_)){poisoned_=true;return false;}return true;
}
bool FieldGameCameraRuntime::shaker_deleted(uint64_t token){auto i=shakers_.find(token);if(poisoned_||i==shakers_.end()||!i->second.child_alive)return fail("Shaker actual deferred deletion rejected");i->second.child_alive=false;return true;}
bool FieldGameCameraRuntime::resume_shake_idle(uint64_t token){auto i=shakers_.find(token);if(poisoned_||i==shakers_.end()||!i->second.alive||!i->second.awaiting_idle)return fail("Shaker idle continuation rejected");auto*s=get(i->second.camera);if(!s)return false;i->second.awaiting_idle=false;i->second.alive=false;s->shaking=false;if(!publish(*s)||!host_.stopped_shaking(s->id,error_)||!host_.coroutine_completed(token,error_)){poisoned_=true;return false;}return true;}
bool FieldGameCameraRuntime::exit_tree(uint32_t id){auto*s=get(id,false);if(!s)return false;for(auto&entry:tweens_)if(entry.second.camera==id&&entry.second.alive){entry.second.alive=entry.second.running=false;if(!host_.kill_tween||!host_.kill_tween(entry.first,error_)){poisoned_=true;return false;}}for(auto&entry:shakers_)if(entry.second.camera==id&&entry.second.alive){if(entry.second.awaiting_idle&&(!host_.cancel_idle_frame||!host_.cancel_idle_frame(entry.first,error_))){poisoned_=true;return false;}entry.second.alive=entry.second.playing=false;}s->alive=false;return true;}
bool FieldGameCameraRuntime::native_current_changed(uint32_t id, bool current) {
  auto *s = get(id, false);
  if (!s) return false;
  s->current = current;
  return true;
}

}
