#include "encore/field_cash_box.hpp"
#include "encore/battle_entry.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
namespace encore::upstream {
bool FieldCashBoxRuntime::fail(std::string&e,const char*s){error_=s;poisoned_=true;e=error_;return false;}
bool FieldCashBoxRuntime::effect(bool ok,std::string&e){if(ok)return true;error_=e.empty()?"Cash box source host rejected":e;poisoned_=true;e=error_;return false;}
float FieldCashBoxRuntime::sample(const FieldCashClip&c,float time)const{size_t i=0;while(i+1<c.keys.size()&&c.keys[i+1].time<=time)++i;auto&a=c.keys[i];if(i+1==c.keys.size()||time<=a.time)return a.value;auto&b=c.keys[i+1];return a.value+(b.value-a.value)*battle_ease((time-a.time)/(b.time-a.time),a.ease);}
bool FieldCashBoxRuntime::initialize(const FieldCashBoxData&d,FieldCashBoxHost h,bool chinese,std::string&e){if(!d.valid()||!h.bind||!h.read_amount||!h.measure){e="Cash box complete source host required";return false;}if(!h.bind(d,e))return false;data_=&d;host_=std::move(h);chinese_=chinese;poisoned_=false;error_.clear();states_={};for(size_t i=0;i<2;++i){states_[i].y=sample(d.box(i).clips[2],0);for(const auto&n:d.box(i).nodes)if(n.amount)states_[i].text=n.text;}std::vector<FieldCashDraw>commands;for(size_t i=0;i<2;++i)if(!draw_commands(i,uint32_t(d.viewport().x),uint32_t(d.viewport().y),commands,e)){data_=nullptr;return false;}e.clear();return true;}
bool FieldCashBoxRuntime::update(uint64_t id,std::string&e){if(!data_||poisoned_||id<1||id>2)return fail(e,"Cash box persistent identity rejected");int64_t value=0;if(!effect(host_.read_amount(id==2,value,e),e))return false;if(id==2&&value<0)return fail(e,"Cash box source int/phone unit range rejected");auto&s=states_[id-1];s.amount=value;s.text=std::to_string(value);std::vector<FieldCashDraw>commands;if(!effect(draw_commands(id==2,uint32_t(data_->viewport().x),uint32_t(data_->viewport().y),commands,e),e))return false;e.clear();return true;}
bool FieldCashBoxRuntime::open(bool units,uint64_t&id,std::string&e){id=units?2:1;if(!update(id,e))return false;auto&s=states_[id-1];if(!s.open){s.collapsed=true;s.clip=0;s.time=0;s.animating=true;s.open=true;}e.clear();return true;}
bool FieldCashBoxRuntime::close(uint64_t id,std::string&e){if(!data_||poisoned_||id<1||id>2)return fail(e,"Cash box close identity rejected");auto&s=states_[id-1];if(s.open){s.clip=1;s.time=0;s.animating=true;s.open=false;}e.clear();return true;}
bool FieldCashBoxRuntime::open_and_close(bool units,std::string&e){uint64_t id;if(!open(units,id,e))return false;auto&s=states_[id-1];s.timer_left=data_->box(units).timer_seconds;s.timer=true;e.clear();return true;}
bool FieldCashBoxRuntime::set_language(bool chinese,std::string&e){if(!data_||poisoned_)return fail(e,"Cash box not admitted");chinese_=chinese;std::vector<FieldCashDraw>v;for(size_t i=0;i<2;++i)if(!effect(draw_commands(i,uint32_t(data_->viewport().x),uint32_t(data_->viewport().y),v,e),e))return false;e.clear();return true;}
bool FieldCashBoxRuntime::idle_frame(float dt,bool process,std::string&e){if(!data_||poisoned_||!std::isfinite(dt)||dt<0||dt>60)return fail(e,"Cash box process delta rejected");if(!process){e.clear();return true;}for(size_t i=0;i<2;++i){auto&s=states_[i];const auto&b=data_->box(i);if(s.animating){s.time=std::min(s.time+dt,b.clips[s.clip].length);s.y=sample(b.clips[s.clip],s.time);if(s.time>=b.clips[s.clip].length)s.animating=false;}if(s.timer){s.timer_left-=dt;if(s.timer_left<0){s.timer=false;if(b.timer_connected&&!close(i+1,e))return false;}}}e.clear();return true;}
bool FieldCashBoxRuntime::draw_commands(bool units,uint32_t width,uint32_t height,std::vector<FieldCashDraw>&out,std::string&e)const{
 out.clear();if(!data_||poisoned_||!width||!height||width>4096||height>4096){e="Cash box view/source unavailable";return false;}const auto&b=data_->box(units);const auto&s=states_[units?1:0];const auto count=b.nodes.size();std::vector<Vec2>mins(count);std::vector<std::string>texts(count);std::vector<std::array<float,4>>rects(count);
 for(size_t i=count;i-->0;){const auto&n=b.nodes[i];Vec2 m=n.minimum;if(n.kind==3){std::string text=n.amount?s.text:n.text;if(n.label_role==2)text=data_->symbol(false,chinese_);else if(n.label_role==3)text=data_->symbol(true,chinese_);Vec2 measured;if(!host_.measure(data_->font(),text,measured,e)||!std::isfinite(measured.x)||!std::isfinite(measured.y)||measured.x<0||measured.y<=0){if(e.empty())e="Cash box actual source font metrics rejected";return false;}m={std::max(m.x,measured.x),std::max(m.y,measured.y)};texts[i]=std::move(text);}else if(n.kind==5&&!n.expand){auto&t=data_->textures()[n.texture];m={std::max(m.x,float(t.width)),std::max(m.y,float(t.height))};}else if(n.kind==1||n.kind==2){Vec2 children{};unsigned child_count=0;for(size_t j=i+1;j<count;++j)if(b.nodes[j].parent==i){if(n.kind==2){children.x+=mins[j].x;children.y=std::max(children.y,mins[j].y);}else{children.x=std::max(children.x,mins[j].x);children.y=std::max(children.y,mins[j].y);}++child_count;}if(n.kind==1){auto&st=b.styles[n.style];children.x+=st.content[0]+st.content[2];children.y+=st.content[1]+st.content[3];}else if(child_count)children.x+=n.separation*(child_count-1);m={std::max(m.x,children.x),std::max(m.y,children.y)};}mins[i]=m;}
 auto&root=b.nodes[0];const float w=s.collapsed?float(mins[0].x):std::max(float(mins[0].x),root.rect[2]-root.rect[0]);const float h=std::max(float(mins[0].y),root.rect[3]-root.rect[1]);const float right=root.rect[2]+float(width)-float(data_->viewport().x);rects[0]={right-w,s.y,right,s.y+h};
 auto fit=[&](size_t child,std::array<float,4>rect){auto&n=b.nodes[child];if(!(n.hflags&1)){float size=float(mins[child].x),delta=rect[2]-rect[0]-size;if(n.hflags&8)rect[0]+=delta;else if(n.hflags&4)rect[0]+=std::floor(delta/2);rect[2]=rect[0]+size;}if(!(n.vflags&1)){float size=float(mins[child].y),delta=rect[3]-rect[1]-size;if(n.vflags&8)rect[1]+=delta;else if(n.vflags&4)rect[1]+=std::floor(delta/2);rect[3]=rect[1]+size;}rects[child]=rect;};
 for(size_t i=0;i<count;++i){const auto&n=b.nodes[i];auto r=rects[i];std::vector<size_t>children;for(size_t j=i+1;j<count;++j)if(b.nodes[j].parent==i)children.push_back(j);if(n.kind==1){const auto&st=b.styles[n.style];auto inner=r;inner[0]+=st.content[0];inner[1]+=st.content[1];inner[2]-=st.content[2];inner[3]-=st.content[3];for(auto j:children)fit(j,inner);out.push_back({1,n.style,r,{}});}else if(n.kind==2){
   // Audited source HBox uses unit stretch ratios in these two scenes. Its
   // size/minimums are integer-truncated, with source fractional carry.
   const int available=int(r[2]-r[0]);std::vector<int>sizes;int minimum=0,expanding_min=0;unsigned expanding=0;for(auto j:children){int m=int(mins[j].x);sizes.push_back(m);minimum+=m;if(b.nodes[j].hflags&2){expanding_min+=m;++expanding;}}const int gaps=children.empty()?0:int(n.separation)*(int(children.size())-1);int stretch=expanding_min+std::max(0,available-gaps-minimum);std::vector<bool>active;for(auto j:children)active.push_back(bool(b.nodes[j].hflags&2));bool changed=true;while(changed&&expanding){changed=false;for(size_t j=0;j<children.size();++j)if(active[j]&&float(stretch)/expanding<sizes[j]){active[j]=false;stretch-=sizes[j];--expanding;changed=true;break;}}
   float carry=0;for(size_t j=0;j<children.size();++j)if(active[j]){float size=float(stretch)/expanding;int whole=int(size);carry+=size-whole;if(carry>=1){++whole;carry-=1;}sizes[j]=whole;}float x=r[0];if(!expanding){int extra=available-gaps-minimum;if(n.alignment==1)x+=std::floor(extra/2.f);else if(n.alignment==2)x+=extra;}for(size_t j=0;j<children.size();++j){fit(children[j],{x,r[1],x+sizes[j],r[3]});x+=sizes[j]+int(n.separation);}
  }else if(n.kind==3){Vec2 measured;if(!host_.measure(data_->font(),texts[i],measured,e))return false;float dx=float(r[2]-r[0]-measured.x),dy=float(r[3]-r[1]-measured.y);if(n.align==1)r[0]+=std::floor(dx/2);else if(n.align==2)r[0]+=dx;if(n.valign==1)r[1]+=std::floor(dy/2);else if(n.valign==2)r[1]+=dy;r[2]=r[0]+float(measured.x);r[3]=r[1]+float(measured.y);out.push_back({3,uint32_t(i),r,texts[i]});}else if(n.kind==5){if(n.stretch_mode==4){auto&t=data_->textures()[n.texture];float iw=t.width,ih=t.height;r[0]+=(r[2]-r[0]-iw)/2;r[1]+=(r[3]-r[1]-ih)/2;r[2]=r[0]+iw;r[3]=r[1]+ih;}else if(!n.expand){auto&t=data_->textures()[n.texture];r[2]=r[0]+t.width;r[3]=r[1]+t.height;}out.push_back({5,n.texture,r,{}});}
 }e.clear();return true;
}
}
