#include "encore/field_dead_bush.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <set>
namespace encore::upstream {namespace{
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=i>=16&&i<20?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
bool path(std::string_view s){return!s.empty()&&s.front()!='/'&&s.back()!='/'&&s.find("..") ==s.npos&&s.find(':')==s.npos&&s.find('\\')==s.npos;}
bool relative(std::string_view s){return s.empty()||(s.front()!='/'&&s.find(':')==s.npos&&s.find('\\')==s.npos);}
struct Reader{const uint8_t*p;size_t n,at=64;bool ok=true;uint32_t number(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=u32(p+at);at+=4;return v;}float scalar(){auto v=number();float f;std::memcpy(&f,&v,4);if(!std::isfinite(f)||std::abs(f)>1000000)ok=false;return f;}Vec2 vec(){return{scalar(),scalar()};}std::string text(){auto len=number();if(!ok||len>8192||at>n||len>n-at){ok=false;return{};}std::string s(reinterpret_cast<const char*>(p+at),len);at+=len;size_t i=0;uint32_t cp;while(i<s.size())if(!encore::utf8_next(s,i,cp)||cp<32){ok=false;break;}return s;}bool hash(std::array<uint8_t,32>&out){if(!ok||at>n||n-at<32){ok=false;return false;}std::copy_n(p+at,32,out.begin());at+=32;if(std::all_of(out.begin(),out.end(),[](uint8_t v){return!v;}))ok=false;return ok;}};
}
const FieldBushDescriptor*FieldBushData::record(uint32_t id)const{for(const auto&r:records_)if(r.id==id)return&r;return nullptr;}
const FieldBushClip*FieldBushData::clip(FieldBushClipRole role)const{for(const auto&c:clips_)if(c.role==role)return&c;return nullptr;}
bool FieldBushData::source_hash(std::string_view p,std::array<uint8_t,32>&out)const{auto i=sources_.find(std::string(p));if(i==sources_.end())return false;out=i->second;return true;}
bool FieldBushData::load_file(const char*path,std::string&e){if(!path){e="DeadBush resource path absent";return false;}std::ifstream f(path,std::ios::binary);if(!f){e="DeadBush resource unavailable";return false;}f.seekg(0,std::ios::end);auto n=f.tellg();if(n<64||n>4*1024*1024){e="DeadBush file size";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)){e="DeadBush file read";return false;}return load(b.data(),b.size(),e);}
bool FieldBushData::load(const uint8_t*p,size_t n,std::string&e){auto reject=[&](const char*s){e=s;return false;};if(!p||n<64||n>4*1024*1024)return reject("DeadBush resource size");if(std::memcmp(p,"ENCDBSH1",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+16)!=crc(p,n)||u32(p+20)!=1||u32(p+24)!=1||!u32(p+28)||u32(p+28)>4096||!u32(p+52)||!u32(p+56)||u32(p+56)>1024||u32(p+60))return reject("DeadBush header/schema/capability/rules/CRC");FieldBushData next;next.scene_id_=u32(p+52);std::copy_n(p+32,20,next.pin_.begin());if(std::all_of(next.pin_.begin(),next.pin_.end(),[](uint8_t v){return!v;}))return reject("DeadBush source pin absent");Reader r{p,n};if(!r.hash(next.scene_)||!r.hash(next.script_))return reject("DeadBush scene/script proof absent");next.width_=r.number();next.height_=r.number();next.texture_source_=r.text();next.texture_path_=r.text();if(!r.hash(next.texture_)||!next.width_||!next.height_||next.width_>1024||next.height_>1024||!path(next.texture_source_)||!path(next.texture_path_))return reject("DeadBush checked source atlas");next.sound_.id=r.number();next.sound_.gain_db=r.scalar();next.sound_.source=r.text();next.sound_.pcm=r.text();next.sound_.bus=r.text();next.roots_frame_=r.number();next.vibration_device_=r.number();for(auto&v:next.vibration_)v=r.scalar();next.vibration_gate_=r.text();auto vibration_default=r.number();next.vibration_default_=vibration_default!=0;next.bat_flag_=r.text();if(!r.ok||!next.sound_.id||next.sound_.gain_db<-120||next.sound_.gain_db>24||!path(next.sound_.source)||!path(next.sound_.pcm)||next.sound_.bus.empty()||next.vibration_[0]<0||next.vibration_[0]>1||next.vibration_[1]<0||next.vibration_[1]>1||next.vibration_[2]<0||next.vibration_[2]>60||next.vibration_gate_.empty()||vibration_default>1||next.bat_flag_.empty())return reject("DeadBush source audio/vibration/flags");auto count=r.number();if(count!=2)return reject("DeadBush dialogue branch coverage");std::set<std::string>names;for(uint32_t i=0;i<count;++i){FieldBushDialogue d;d.program=r.text();d.key=r.text();d.en=r.text();d.zh_cn=r.text();if(!r.ok||!path(d.program)||!names.insert(d.program).second||d.key.empty()||d.en.empty()||d.zh_cn.empty())return reject("DeadBush source dialogue branch");next.dialogues_.push_back(std::move(d));}
 count=r.number();if(count!=5)return reject("DeadBush typed animation coverage");std::set<uint32_t>ids;names.clear();for(uint32_t i=0;i<count;++i){FieldBushClip c;auto role=r.number();c.role=FieldBushClipRole(role);c.length=r.scalar();c.name=r.text();auto tracks=r.number();if(!r.ok||role<1||role>5||!ids.insert(role).second||c.length<=0||c.length>86400||c.name.empty()||!names.insert(c.name).second||!tracks||tracks>5)return reject("DeadBush animation identity/length");std::set<uint32_t>used;for(uint32_t j=0;j<tracks;++j){FieldBushTrack t;auto property=r.number();t.property=FieldBushProperty(property);t.update=r.number();auto keys=r.number();if(!r.ok||property<1||property>5||!used.insert(property).second||t.update>1||!keys||keys>1024||(t.update==0&&keys!=1))return reject("DeadBush source track/update");float previous=-1;for(uint32_t k=0;k<keys;++k){FieldBushKey key;key.time=r.scalar();key.value=r.number();if(!r.ok||key.time<0||key.time<previous||key.time>c.length||(property==1?key.value>=1048576:key.value>1))return reject("DeadBush source track key");previous=key.time;t.keys.push_back(key);}c.tracks.push_back(std::move(t));}next.clips_.push_back(std::move(c));}
 ids.clear();names.clear();uint32_t previous=0;bool had=false;for(uint32_t i=0;i<u32(p+28);++i){FieldBushDescriptor d;d.id=r.number();d.parent_id=r.number();d.ready_ordinal=r.number();d.sprite_id=r.number();d.prompt_id=r.number();d.body_shape_id=r.number();d.hit_shape_id=r.number();d.interact_shape_id=r.number();d.new_parent_id=r.number();d.called_id=r.number();auto call=r.number();d.call_kind=FieldBushDeferredKind(call);d.flags=r.number();d.columns=r.number();d.rows=r.number();d.frame=r.number();d.hit_layer=r.number();d.hit_mask=r.number();auto monitor=r.number();d.hit_monitorable=monitor!=0;d.notifier_id=r.number();d.sprite_position=r.vec();d.sprite_offset=r.vec();d.sprite_scale=r.vec();d.notifier_rect_position=r.vec();d.notifier_rect_size=r.vec();d.notifier_position=r.vec();d.notifier_scale=r.vec();d.node=r.text();d.new_parent_path=r.text();d.called_path=r.text();d.call_method=r.text();d.flag=r.text();d.disappear_flag=r.text();if(!r.ok||!d.id||!ids.insert(d.id).second||!d.parent_id||!d.sprite_id||!d.prompt_id||!d.body_shape_id||!d.hit_shape_id||!d.interact_shape_id||!d.new_parent_id||!d.notifier_id||d.notifier_rect_size.x<=0||d.notifier_rect_size.y<=0||d.notifier_scale.x==0||d.notifier_scale.y==0||call>1||d.flags>511||monitor>1||!d.columns||!d.rows||d.columns>1024||d.rows>1024||d.frame>=d.columns*d.rows||next.roots_frame_>=d.columns*d.rows||next.width_%d.columns||next.height_%d.rows||!path(d.node)||!names.insert(d.node).second||!relative(d.new_parent_path)||!relative(d.called_path)||(had&&d.ready_ordinal<=previous)||d.ready_ordinal==UINT32_MAX||(bool(d.called_id)!=!d.called_path.empty())||(bool(call)!=!d.call_method.empty())||(call&&!d.called_id)||((d.flags&32)&&(d.new_parent_id!=d.parent_id||!d.new_parent_path.empty())))return reject("DeadBush descriptor/Ready/geometry/deferred source");previous=d.ready_ordinal;had=true;for(const auto&c:next.clips_)for(const auto&t:c.tracks)if(t.property==FieldBushProperty::Frame)for(const auto&key:t.keys)if(key.value>=d.columns*d.rows)return reject("DeadBush animation outside actual sprite grid");next.records_.push_back(std::move(d));}
 count=r.number();if(count!=u32(p+56))return reject("DeadBush source receipt coverage");for(uint32_t i=0;i<count;++i){auto name=r.text();std::array<uint8_t,32>hash{};if(!r.ok||!path(name)||!r.hash(hash)||!next.sources_.emplace(name,hash).second)return reject("DeadBush source receipt/hash");}if(!r.ok||r.at!=n)return reject("DeadBush trailing source data");std::array<uint8_t,32>hash{};if(!next.source_hash(next.texture_source_,hash)||!next.source_hash(next.texture_source_+".import",hash)||!next.source_hash(next.sound_.source,hash)||!next.source_hash(next.sound_.source+".import",hash))return reject("DeadBush assets outside reviewed source closure");bool scene=false,script=false;for(const auto&s:next.sources_){scene|=s.second==next.scene_;script|=s.second==next.script_;}if(!scene||!script)return reject("DeadBush scene/script outside source closure");next.valid_=true;*this=std::move(next);e.clear();return true;
}
}
