#include "encore/field_door.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <unordered_map>
#include <unordered_set>
namespace encore::upstream {
namespace {
constexpr uint32_t begin=296,strides[]={0,8,1,192,36,24,44,40,40,4};
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
float f32(const uint8_t*p){auto n=u32(p);float v;std::memcpy(&v,&n,4);return v;}Vec2 vec(const uint8_t*p){return {f32(p),f32(p+4)};}
FieldGeometryTransform transform(const uint8_t*p){return {vec(p),vec(p+8),vec(p+16)};}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;while(n--){c^=*p++;for(unsigned j=0;j<8;++j)c=(c>>1)^((c&1)?0xedb88320u:0u);}return ~c;}
bool finite(float v){return std::isfinite(v)&&std::abs(v)<1000000;}bool finite(Vec2 v){return finite(v.x)&&finite(v.y);}
bool path(std::string_view s){if(s.empty()||s.front()=='/'||s.back()=='/'||s.find('\\')!=s.npos)return false;size_t b=0;while(b<s.size()){auto e=s.find('/',b);if(e==s.npos)e=s.size();auto p=s.substr(b,e-b);if(p.empty()||p=="."||p=="..")return false;b=e+1;}return true;}
bool direction(Vec2 d){return d.x!=0||d.y!=0;}
}
uint32_t FieldDoorData::count(uint32_t k)const{return valid()&&k>=1&&k<=u32(bytes_.data()+20)?u32(bytes_.data()+128+24*(k-1)+4):0;}
const uint8_t*FieldDoorData::record(uint32_t k,uint32_t i)const{return i<count(k)?bytes_.data()+u32(bytes_.data()+128+24*(k-1)+12)+size_t(i)*strides[k]:nullptr;}
std::string_view FieldDoorData::string(uint32_t i)const{auto r=record(1,i);return r?std::string_view(reinterpret_cast<const char*>(record(2,u32(r))),u32(r+4)):std::string_view{};}
FieldIdentity FieldDoorData::identity()const{FieldIdentity id;if(valid()){id.scene_id=u32(bytes_.data()+36);std::copy_n(bytes_.data()+40,20,id.upstream_commit.begin());std::copy_n(bytes_.data()+60,32,id.source_sha256.begin());}return id;}
std::string_view FieldDoorData::source_scene()const{return valid()?string(u32(bytes_.data()+124)):std::string_view{};}
uint32_t FieldDoorData::door_count()const{return count(3);}
FieldDoorDescriptor FieldDoorData::door(uint32_t i)const{FieldDoorDescriptor n;auto r=record(3,i);if(!r)return n;uint32_t*ints[]={&n.id,&n.ready,&n.node,&n.marker,&n.audio,&n.shape,&n.layer,&n.mask,&n.flags,&n.pause_mode,&n.target_name,&n.target_path,&n.sound,&n.end_sound,&n.in_anim,&n.out_anim,&n.flag};for(unsigned j=0;j<17;++j)*ints[j]=u32(r+4*j);r+=68;n.target=vec(r);n.direction=vec(r+8);n.in_speed=f32(r+16);n.out_speed=f32(r+20);n.music_fade=f32(r+24);for(unsigned j=0;j<4;++j){n.in_color[j]=f32(r+28+4*j);n.out_color[j]=f32(r+44+4*j);}n.body_transform=transform(r+60);n.marker_transform=transform(r+84);n.shape_offset=vec(r+108);n.extents=vec(r+116);return n;}
bool FieldDoorData::find(uint32_t id,FieldDoorDescriptor&out)const{for(uint32_t i=0;i<door_count();++i){auto n=door(i);if(n.id==id){out=n;return true;}}return false;}
FieldDoorAudio FieldDoorData::audio(uint32_t id)const{for(uint32_t i=0;i<count(6);++i){auto r=record(6,i);if(u32(r)==id){FieldDoorAudio a{u32(r),u32(r+4),u32(r+8),{}};std::copy_n(r+12,32,a.sha.begin());return a;}}return {};}
bool FieldDoorData::source_hash(std::string_view name,std::array<uint8_t,32>&h)const{for(uint32_t i=0;i<count(4);++i){auto r=record(4,i);if(string(u32(r))==name){std::copy_n(r+4,32,h.begin());return true;}}return false;}
std::string_view FieldDoorData::script()const{auto r=record(5,0);return r?string(u32(r)):std::string_view{};}
std::array<uint8_t,32>FieldDoorData::script_sha()const{std::array<uint8_t,32>h{};source_hash(script(),h);return h;}
std::string_view FieldDoorData::none()const{auto r=record(5,0);return r?string(u32(r+16)):std::string_view{};}float FieldDoorData::ground_offset()const{auto r=record(5,0);return r?f32(r+20):0;}
uint32_t FieldDoorData::capability()const{return valid()?u32(bytes_.data()+32):0;}
std::string_view FieldDoorData::body_method()const{auto p=record(9,0);return p?string(u32(p)):std::string_view{};}
bool FieldDoorData::house_continuation()const{return valid()&&u32(bytes_.data()+8)>=2&&count(8)==1;}
std::string_view FieldDoorData::old_region()const{auto p=record(8,0);return p?string(u32(p)):std::string_view{};}
std::string_view FieldDoorData::old_root_name()const{auto p=record(8,0);return p?string(u32(p+4)):std::string_view{};}
std::string_view FieldDoorData::area_left_signal()const{auto p=record(8,0);return p?string(u32(p+8)):std::string_view{};}
std::string_view FieldDoorData::door_signal(FieldDoorSignal s)const{auto p=record(8,0);auto role=uint32_t(s);return p&&role<3?string(u32(p+12+role*4)):std::string_view{};}
std::string_view FieldDoorData::scene_changed_signal()const{auto p=record(8,0);return p?string(u32(p+24)):std::string_view{};}
bool FieldDoorData::empty_destination_parameters()const{auto p=record(8,0);return p&&u32(p+32)==1;}
bool FieldDoorData::old_area_has_listeners()const{auto p=record(8,0);return p&&u32(p+36)!=0;}
bool FieldDoorData::load(const uint8_t*p,size_t n,const FieldIdentity&id,std::string&e){if(!p||n<begin||n>4*1024*1024){e="Door source size rejected";return false;}return admit(std::vector<uint8_t>(p,p+n),id,e);}
bool FieldDoorData::load_file(const char*p,const FieldIdentity&id,std::string&e){if(!p||!*p){e="Door path rejected";return false;}FILE*f=std::fopen(p,"rb");if(!f){e="Cannot open Door resource";return false;}if(std::fseek(f,0,SEEK_END)){std::fclose(f);e="Door seek failed";return false;}long n=std::ftell(f);if(n<static_cast<long>(begin)||n>4*1024*1024||std::fseek(f,0,SEEK_SET)){std::fclose(f);e="Door file size rejected";return false;}std::vector<uint8_t>b(static_cast<size_t>(n));auto got=std::fread(b.data(),1,b.size(),f);bool closed=std::fclose(f)==0;if(got!=b.size()||!closed){e="Door read failed";return false;}return admit(std::move(b),id,e);}
bool FieldDoorData::admit(std::vector<uint8_t>&&b,const FieldIdentity&id,std::string&e){auto fail=[&](const char*s){e=s;return false;};auto p=b.data();auto size=b.size();const uint32_t version=u32(p+8);const bool extended=version>=2;const uint32_t sections=version==3?9:extended?8:7;const size_t payload=128+24*sections;if(size<payload)return fail("Door directory truncated");if(std::memcmp(p,"ENCFDOR1",8)||(version<1||version>3)||u32(p+12)!=128||u32(p+16)!=size||u32(p+20)!=sections||u32(p+28)!=0x454e001f||u32(p+32)!=(version==3?5u:extended?4u:3u)||!id.scene_id||u32(p+36)!=id.scene_id||std::memcmp(p+40,id.upstream_commit.data(),20)||std::memcmp(p+60,id.source_sha256.data(),32))return fail("Door identity/version rejected");if(crc(p+payload,size-payload)!=u32(p+24))return fail("Door CRC rejected");uint64_t end=payload;for(uint32_t k=1;k<=sections;++k){auto r=p+128+24*(k-1);uint64_t bytes=uint64_t(u32(r+4))*strides[k];if(u32(r)!=k||u32(r+8)!=strides[k]||u32(r+12)!=end||u32(r+16)!=bytes||u32(r+20)||bytes>size-end)return fail("Door section rejected");end+=bytes;}if(end!=size)return fail("Door trailing bytes rejected");FieldDoorData c;c.bytes_=std::move(b);if(!c.count(1)||!c.count(2)||!c.count(3)||c.count(3)>10000||!c.count(4)||c.count(5)!=1||c.count(6)!=c.count(3)||c.count(7)>c.count(3))return fail("Door source capacity rejected");uint32_t string_end=0;for(uint32_t i=0;i<c.count(1);++i){auto r=c.record(1,i);uint32_t first=u32(r),n=u32(r+4);if(first!=string_end||first>=c.count(2)||n>=c.count(2)-first)return fail("Door string span rejected");auto q=c.record(2,first);if(q[n]||std::memchr(q,0,n))return fail("Door string bytes rejected");string_end=first+n+1;}if(string_end!=c.count(2)||u32(c.bytes_.data()+124)>=c.count(1)||!path(c.source_scene()))return fail("Door source scene rejected");
 std::unordered_map<std::string_view,std::array<uint8_t,32>>proof;for(uint32_t i=0;i<c.count(4);++i){auto r=c.record(4,i);std::array<uint8_t,32>h{};std::copy_n(r+4,32,h.begin());if(u32(r)>=c.count(1)||!path(c.string(u32(r)))||std::all_of(h.begin(),h.end(),[](uint8_t v){return !v;})||!proof.emplace(c.string(u32(r)),h).second)return fail("Door source proof rejected");}auto root=proof.find(c.source_scene());if(root==proof.end()||root->second!=id.source_sha256)return fail("Door root proof rejected");auto profile=c.record(5,0);for(unsigned j=0;j<4;++j)if(u32(profile+4*j)>=c.count(1)||proof.find(c.string(u32(profile+4*j)))==proof.end())return fail("Door script closure rejected");if(u32(profile+16)>=c.count(1)||c.none().empty()||!finite(c.ground_offset())||c.ground_offset()<0)return fail("Door source tuning rejected");
 std::unordered_set<uint32_t>ids,children,audios,targets;std::unordered_set<std::string_view>nodes;uint32_t prev=0;for(uint32_t i=0;i<c.door_count();++i){auto n=c.door(i);if(!n.id||!ids.insert(n.id).second||!n.marker||!n.audio||!n.shape||n.marker==n.audio||n.marker==n.shape||n.audio==n.shape||!children.insert(n.marker).second||!children.insert(n.audio).second||!children.insert(n.shape).second||n.flags>511||n.pause_mode>2||(i&&n.ready<=prev))return fail("Door node/Ready flags rejected");prev=n.ready;uint32_t strings[]={n.node,n.target_name,n.target_path,n.sound,n.end_sound,n.in_anim,n.out_anim,n.flag};for(auto s:strings)if(s>=c.count(1))return fail("Door string reference rejected");if(!path(c.string(n.node))||!nodes.insert(c.string(n.node)).second||c.string(n.in_anim).empty()||!finite(n.target)||!finite(n.direction)||!finite(n.in_speed)||!finite(n.out_speed)||n.in_speed<=0||n.out_speed<=0||!finite(n.music_fade)||n.music_fade<0||!finite(n.shape_offset)||!finite(n.extents)||n.extents.x<=0||n.extents.y<=0)return fail("Door source properties rejected");for(auto t:{n.body_transform,n.marker_transform})if(!finite(t.x)||!finite(t.y)||!finite(t.origin)||t.x.x*t.y.y-t.x.y*t.y.x==0)return fail("Door source transform rejected");for(auto color:{n.in_color,n.out_color})for(float v:color)if(!finite(v)||v<0||v>1)return fail("Door fade color rejected");auto target=c.string(n.target_path);if(c.string(n.target_name).empty()!=target.empty()||(!target.empty()&&(!path(target)||proof.find(target)==proof.end())))return fail("Door target proof rejected");for(auto s:{n.sound,n.end_sound}){auto sound=c.string(s);if(!sound.empty()&&sound!=c.none()&&(!path(sound)||proof.find(sound)==proof.end()))return fail("Door audio source rejected");}auto a=c.audio(n.audio);if(a.id!=n.audio)return fail("Door onready audio missing");}
 for(uint32_t i=0;i<c.count(6);++i){auto r=c.record(6,i);if(!audios.insert(u32(r)).second||!children.count(u32(r))||u32(r+4)>=c.count(1)||u32(r+8)>=c.count(1)||c.string(u32(r+8)).empty())return fail("Door onready audio binding rejected");auto h=proof.find(c.string(u32(r+4)));if(h==proof.end()||std::memcmp(h->second.data(),r+12,32))return fail("Door initial audio proof rejected");}
 for(uint32_t i=0;i<c.count(7);++i){auto r=c.record(7,i);FieldDoorDescriptor n;if(!targets.insert(u32(r)).second||!c.find(u32(r),n)||n.target_path!=u32(r+4))return fail("Door target record rejected");auto h=proof.find(c.string(n.target_path));if(h==proof.end()||std::memcmp(h->second.data(),r+8,32))return fail("Door destination SHA rejected");}for(uint32_t i=0;i<c.door_count();++i){auto n=c.door(i);if(!c.string(n.target_path).empty()&&!targets.count(n.id))return fail("Door target record missing");}if(extended&&c.count(8)){if(c.count(8)!=1||c.door_count()!=1)return fail("Door continuation closure count rejected");const auto q=c.record(8,0);for(unsigned j=0;j<8;++j)if(u32(q+4*j)>=c.count(1)||c.string(u32(q+4*j)).empty())return fail("Door continuation binding rejected");if(u32(q+32)!=1||u32(q+36)!=0)return fail("Door continuation destination/listener capability rejected");auto h=proof.find(c.string(u32(q+28)));if(h==proof.end())return fail("Door continuation AreaRoom source missing");}if(version==2&&c.count(8)!=1)return fail("Door legacy continuation missing");if(version==3){auto q=c.record(9,0);if(c.count(9)!=1||!q||u32(q)>=c.count(1)||c.body_method().empty()||c.body_method().find_first_not_of("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_")!=std::string_view::npos)return fail("Door source body method rejected");}bytes_=std::move(c.bytes_);e.clear();return true;
}
bool FieldDoorRuntime::initialize(const FieldDoorData&d,FieldDoorHost h,std::string&e){if(data_){e="Door runtime already initialized";return false;}if(!d.valid()||!h.observe||!h.resolve_onready||!h.connect_body||!h.prepare_destination||!h.release_candidate||!h.pause_player||!h.set_entering||!h.flag_exists||!h.write_flag||!h.music_changers||!h.stop_music||!h.play_audio||!h.fade||!h.emit||!h.marker_world||!h.set_player_global_position||!h.persistent||!h.schedule_deferred||!h.clear_enemies||!h.scene_step||!h.emit_scene_changed||!h.camera_current_and_visible||!h.fade_cut||!h.direction_and_input||!h.update_party||!h.unpause_player||!h.queue_free||!h.set_respawn){e="Door actual lifecycle/transition Host incomplete";return false;}data_=&d;host_=std::move(h);e.clear();return true;}
bool FieldDoorRuntime::poison(std::string&e){phase_=FieldDoorPhase::Poisoned;if(e.empty())e="Door source lifecycle operation failed";return false;}
bool FieldDoorRuntime::ready(uint32_t id,std::string&e){FieldDoorDescriptor n;if(!data_||phase_==FieldDoorPhase::Poisoned||!data_->find(id,n)||std::find(ready_.begin(),ready_.end(),id)!=ready_.end()||(had_ready_&&n.ready<=last_ready_)){e="Door Ready source/order rejected";return false;}if(!host_.resolve_onready(n,data_->audio(n.audio),e)||!host_.connect_body(id,[this,id](uint64_t body,std::string&error){return body_entered(id,body,error);},e))return poison(e);ready_.push_back(id);last_ready_=n.ready;had_ready_=true;e.clear();return true;}
bool FieldDoorRuntime::select(uint32_t id,uint64_t player,const FieldDoorContext&context,std::string&e){if(!data_||!player||std::find(ready_.begin(),ready_.end(),id)==ready_.end()||!data_->find(id,active_)){e="Door live source instance not Ready";return false;}if(phase_!=FieldDoorPhase::Idle&&phase_!=FieldDoorPhase::Done){e="Door source coroutine already active";return false;}player_=player;candidate_={};return prepare(context,e);}
bool FieldDoorRuntime::prepare(const FieldDoorContext&context,std::string&e){bool next_same=data_->string(active_.target_name).empty()||context.current_scene_name==data_->string(active_.target_name);if(candidate_.token&&(next_same||context.in_cutscene)){if(!host_.release_candidate(candidate_,false,e))return false;candidate_={};}same_=next_same;if(!same_&&!context.in_cutscene&&!candidate_.token){if(!host_.prepare_destination(active_,candidate_,e))return false;std::array<uint8_t,32>h{};if(!data_->source_hash(data_->string(active_.target_path),h)||!candidate_.token||candidate_.path!=data_->string(active_.target_path)||candidate_.pin!=data_->identity().upstream_commit||candidate_.source_sha!=h){std::string release;host_.release_candidate(candidate_,false,release);candidate_={};e="Door destination candidate identity/admission rejected";return false;}}e.clear();return true;}
bool FieldDoorRuntime::body_entered(uint32_t id,uint64_t body,std::string&e){if(!data_||phase_==FieldDoorPhase::Poisoned){e="Door runtime unavailable";return false;}FieldDoorContext c;if(!host_.observe(c,e))return false;if(body!=c.player||c.entering){e.clear();return true;}if(phase_==FieldDoorPhase::BodyIdle){FieldDoorDescriptor n;if(!data_->find(id,n)||std::find(ready_.begin(),ready_.end(),id)==ready_.end()){e="Door body signal source not Ready";return false;}if(!host_.pause_player(body,false,true,e))return poison(e);body_waiters_.push_back({id,body});e.clear();return true;}if(!select(id,body,c,e))return false;if(!host_.pause_player(body,false,true,e))return poison(e);phase_=FieldDoorPhase::BodyIdle;e.clear();return true;}
bool FieldDoorRuntime::enter(uint32_t id,uint64_t player,std::string&e){if(!data_||phase_==FieldDoorPhase::Poisoned){e="Door runtime unavailable";return false;}FieldDoorContext c;if(!host_.observe(c,e))return false;if(c.entering){e.clear();return true;}if(!player)player=c.player;if(!select(id,player,c,e))return false;return start(e);}
bool FieldDoorRuntime::start(std::string&e){FieldDoorContext c;if(!host_.observe(c,e))return poison(e);if(c.entering){if(candidate_.token&&!host_.release_candidate(candidate_,false,e))return poison(e);candidate_={};phase_=FieldDoorPhase::Idle;e.clear();return true;}if(!prepare(c,e))return poison(e);if(!host_.set_entering(true,e))return poison(e);if(c.in_cutscene){if(candidate_.token&&!host_.release_candidate(candidate_,false,e))return poison(e);candidate_={};phase_=FieldDoorPhase::Done;e.clear();return true;}
 // The source intentionally leaves entering_door true in the cutscene branch.
 if(!same_&&!candidate_.token){e="Door destination lost admission before transition";return poison(e);}auto flag=data_->string(active_.flag);if(!flag.empty()){bool exists=false;if(!host_.flag_exists(flag,exists,e))return poison(e);if(exists&&!host_.write_flag(flag,(active_.flags&128)!=0,e))return poison(e);}if(!same_&&(active_.flags&256)){std::vector<uint64_t>music;if(!host_.music_changers(music,e))return poison(e);for(auto id:music)if(!id||!host_.stop_music(id,active_.music_fade,e))return poison(e);}if(!audio(active_.sound,e))return poison(e);phase_=FieldDoorPhase::FadeIn;if(!host_.fade(true,data_->string(active_.in_anim),active_.in_color,active_.in_speed,e))return poison(e);e.clear();return true;}
bool FieldDoorRuntime::audio(uint32_t key,std::string&e){auto s=data_->string(key);if(s.empty()||s==data_->none()){e.clear();return true;}std::array<uint8_t,32>h{};if(!data_->source_hash(s,h)){e="Door sound source absent";return false;}return host_.play_audio(active_.audio,s,h,e);}
bool FieldDoorRuntime::after_warp(std::string&e){if((active_.flags&64)&&!host_.camera_current_and_visible(player_,e))return poison(e);if(!host_.fade_cut(e))return poison(e);if(direction(active_.direction)&&!host_.direction_and_input(player_,active_.direction,e))return poison(e);phase_=FieldDoorPhase::PartyIdle;e.clear();return true;}
bool FieldDoorRuntime::fade_in_done(std::string&e){if(phase_!=FieldDoorPhase::FadeIn){e="Door unexpected fade_in_done";return false;}if(!host_.emit(active_.id,FieldDoorSignal::Entered,e))return poison(e);if(same_){Vec2 p;if(!host_.marker_world(active_.marker,p,e)||!finite(p))return poison(e);p.y-=data_->ground_offset();if(!host_.set_player_global_position(player_,p,e)||!host_.emit(active_.id,FieldDoorSignal::MovedPlayer,e))return poison(e);return after_warp(e);}if(!host_.persistent(active_.id,true,e)||!host_.schedule_deferred(active_.id,e))return poison(e);phase_=FieldDoorPhase::Deferred;if(!host_.clear_enemies(e))return poison(e);e.clear();return true;}
bool FieldDoorRuntime::deferred_commit(std::string&e){if(phase_!=FieldDoorPhase::Deferred||!candidate_.token){e="Door unexpected deferred SceneTree commit";return false;}Vec2 position=active_.target;position.y-=data_->ground_offset();for(uint32_t s=uint32_t(FieldDoorSceneStep::DetachPlayer);s<=uint32_t(FieldDoorSceneStep::UpdateKeyIndicator);++s)if(!host_.scene_step(static_cast<FieldDoorSceneStep>(s),candidate_,player_,position,{},e))return poison(e);phase_=FieldDoorPhase::TreeChanged;e.clear();return true;}
bool FieldDoorRuntime::tree_changed(std::string&e){if(phase_!=FieldDoorPhase::TreeChanged){e="Door unexpected tree_changed";return false;}phase_=FieldDoorPhase::SceneIdle;e.clear();return true;}
bool FieldDoorRuntime::idle_frame(std::string&e){if(phase_==FieldDoorPhase::BodyIdle){auto waiters=std::move(body_waiters_);body_waiters_.clear();if(!start(e))return false;for(const auto&w:waiters)if(!enter(w.first,w.second,e))return poison(e);return true;}if(phase_==FieldDoorPhase::SceneIdle){Vec2 p=active_.target;p.y-=data_->ground_offset();if(!host_.scene_step(FieldDoorSceneStep::EnablePlayerCollisions,candidate_,player_,p,{},e)||!host_.emit_scene_changed(e))return poison(e);return after_warp(e);}if(phase_==FieldDoorPhase::PartyIdle){if(!host_.update_party(player_,e))return poison(e);auto anim=data_->string(active_.out_anim);if(anim.empty())anim=data_->string(active_.in_anim);phase_=FieldDoorPhase::FadeMostly;if(!host_.fade(false,anim,active_.out_color,active_.out_speed,e))return poison(e);e.clear();return true;}e="Door idle event has no source continuation";return false;}
bool FieldDoorRuntime::fade_out_mostly_done(std::string&e){if(phase_!=FieldDoorPhase::FadeMostly){e="Door unexpected fade_out_mostly_done";return false;}if(!audio(active_.end_sound,e))return poison(e);FieldDoorContext c;if(!host_.observe(c,e))return poison(e);if(!c.in_cutscene&&(active_.flags&32)){if(direction(active_.direction)&&!host_.direction_and_input(player_,active_.direction,e))return poison(e);if(!host_.unpause_player(player_,e))return poison(e);}if(!same_){if(!host_.persistent(active_.id,false,e)||!host_.queue_free(active_.id,e))return poison(e);}if((active_.flags&8)&&!host_.set_respawn(e))return poison(e);if(!host_.set_entering(false,e)||!host_.emit(active_.id,FieldDoorSignal::Done,e))return poison(e);if(candidate_.token&&!host_.release_candidate(candidate_,true,e))return poison(e);candidate_={};phase_=FieldDoorPhase::Done;e.clear();return true;}
bool FieldDoorRuntime::special_guest(uint32_t,std::string&e){e="Door _special_guest requires unimplemented original AoOni dynamic backend";return false;}
}
