#include "encore/field_openable_door.hpp"
#include <algorithm>
#include <cmath>
namespace encore::upstream {
bool FieldOpenableDoorRuntime::fail(const char*s){error_=s;return false;}bool FieldOpenableDoorRuntime::callback(bool ok){if(!ok)poisoned_=true;return ok;}
bool FieldOpenableDoorRuntime::initialize(const FieldOpenableDoorData&d,FieldOpenableHost h,std::string&e){if(data_){e="OpenableDoor source runtime already initialized";return false;}if(!d.valid()||!h.bind||!h.connect_area||!h.connect_flags||!h.read_flag||!h.write_flag||!h.emit_flags||!h.observe||!h.overlapping_bodies||!h.sprite_texture||!h.publish||!h.property||!h.defer_disabled||!h.prompt_assign_enabled||!h.prompt_hide||!h.audio_stream||!h.audio_playing||!h.camera_shake||!h.party_inventories||!h.inventory_find||!h.item_name||!h.item_owner||!h.inventory_drop||!h.set_global_item||!h.open_dialogue){e="OpenableDoor source Host incomplete";return false;}if(!h.bind(d,e))return false;data_=&d;host_=std::move(h);e.clear();return true;}
const FieldOpenableInstance*FieldOpenableDoorRuntime::instance(uint32_t id)const{auto p=instances_.find(id);return p==instances_.end()?nullptr:&p->second;}
FieldOpenableInstance*FieldOpenableDoorRuntime::get(uint32_t id,bool ready){if(!data_||poisoned_){fail("OpenableDoor unavailable/partial callback failed");return nullptr;}auto s=instances_.find(id);if(s==instances_.end()||(ready&&!s->second.ready)){fail("OpenableDoor source instance missing/not Ready");return nullptr;}return &s->second;}
bool FieldOpenableDoorRuntime::publish(FieldOpenableInstance&s){return callback(host_.publish(s.id,s,error_));}
bool FieldOpenableDoorRuntime::create(uint32_t id,bool source_constructor){if(!data_||poisoned_||instances_.count(id))return fail("OpenableDoor create unavailable/duplicate");auto d=data_->record(id);if(!d)return fail("OpenableDoor unknown source NodeID");auto t=data_->texture(d->texture);if(!t)return fail("OpenableDoor source texture missing");FieldOpenableInstance s;s.id=id;s.unlocked=data_->initial_unlocked();s.blocked=(d->flags&1)!=0;s.locked=(d->flags&2)!=0;s.sprite_visible=(d->flags&16)!=0;s.body_disabled=(d->flags&32)!=0;s.nonplayer_disabled=(d->flags&64)!=0;s.positions=d->positions;s.sprite_position=d->initial_sprite_position;instances_.emplace(id,s);
 if(source_constructor){pending_source_constructor_.insert(id);return true;}
 // Source exported sprite property invokes _set_texture during instancing,
 // before postorder Ready. The isolated script-free export's null is not used.
 if(!callback(host_.sprite_texture(d->children[0],*t,error_))){return false;}return callback(host_.connect_area(d->children[1],[this,id](uint64_t b){return body_entered(id,b);},[this,id](uint64_t b){return body_exited(id,b);},error_));}
bool FieldOpenableDoorRuntime::play(FieldOpenableInstance&s,FieldOpenableClipRole role){auto d=data_->record(s.id);auto c=data_->clip(d->profile,role);if(!c)return fail("OpenableDoor native clip absent");if(s.clip!=role||s.elapsed==c->length)s.elapsed=0;s.clip=role;s.playing=true;s.started=true;return true;}
bool FieldOpenableDoorRuntime::ready(uint32_t id){auto s=get(id,false);if(!s||s->ready)return fail("OpenableDoor Ready duplicate/missing");auto d=data_->record(id);if(had_ready_&&d->ready<=last_ready_)return fail("OpenableDoor Ready order rejected");if(pending_source_constructor_.count(id)){auto*t=data_->texture(d->texture);if(!t)return fail("OpenableDoor source texture missing");if(!callback(host_.sprite_texture(d->children[0],*t,error_))||!callback(host_.connect_area(d->children[1],[this,id](uint64_t b){return body_entered(id,b);},[this,id](uint64_t b){return body_exited(id,b);},error_)))return false;pending_source_constructor_.erase(id);}s->sprite_position=d->offset;for(auto&p:s->positions)p.y=d->offset.y+data_->child_height();if(!publish(*s)||!update_state(id))return false;if(!callback(host_.connect_flags(id,[this,id](){return update_state(id);},error_))||!play(*s,FieldOpenableClipRole::Normal))return false;s->ready=true;had_ready_=true;last_ready_=d->ready;return true;}
bool FieldOpenableDoorRuntime::deferred(FieldOpenableInstance&s,bool disabled){auto d=data_->record(s.id);return callback(host_.defer_disabled(d->children[5],disabled,[this,id=s.id,disabled](){auto instance=get(id,false);return instance&&apply(*instance,FieldOpenableProperty::BodyDisabled,disabled);},error_));}
bool FieldOpenableDoorRuntime::lock(uint32_t id){auto s=get(id,false);if(!s)return false;auto d=data_->record(id);if(!deferred(*s,false)||!callback(host_.prompt_assign_enabled(d->children[9],true,error_)))return false;s->unlocked=false;return true;}
bool FieldOpenableDoorRuntime::unlock(uint32_t id){auto s=get(id,false);if(!s)return false;auto d=data_->record(id);if(!deferred(*s,true)||!callback(host_.prompt_assign_enabled(d->children[9],false,error_)))return false;s->unlocked=true;return true;}
bool FieldOpenableDoorRuntime::update_state(uint32_t id){auto s=get(id,false);if(!s)return false;auto d=data_->record(id);if(!d->key.empty()||s->blocked||(d->flags&8)||s->locked){if(!lock(id))return false;}else if(!unlock(id))return false;if(!d->flag.empty()){bool present=false,value=false;if(!callback(host_.read_flag(d->flag,present,value,error_)))return false;if(present){s->unlocked=value;if(!callback(host_.prompt_assign_enabled(d->children[9],!value,error_)))return false;}}return true;}
bool FieldOpenableDoorRuntime::valid_body(uint32_t id,uint64_t excluded,bool&value){auto d=data_->record(id);std::vector<FieldOpenableBody>bodies;if(!callback(host_.overlapping_bodies(d->children[1],bodies,error_)))return false;value=false;for(const auto&b:bodies){if(!b.id)return fail("OpenableDoor actual overlapping body identity absent");if(b.id!=excluded&&b.actual_party_object)value=true;}return true;}
bool FieldOpenableDoorRuntime::assign_audio(FieldOpenableInstance&s,std::string_view source,bool play_audio){auto d=data_->record(s.id);auto a=data_->sound(source);if(!a)return fail("OpenableDoor source audio load failed/unsupported");if(!callback(host_.audio_stream(d->children[10],*a,d->gain_db,d->bus,error_)))return false;return !play_audio||callback(host_.audio_playing(d->children[10],true,error_));}
bool FieldOpenableDoorRuntime::open(uint32_t id){auto s=get(id);if(!s)return false;auto d=data_->record(id);if(!play(*s,FieldOpenableClipRole::Action)||!callback(host_.prompt_hide(d->children[9],error_))||!callback(host_.prompt_assign_enabled(d->children[9],false,error_)))return false;if(d->sound==data_->none())return true;FieldOpenableObservation o;if(!callback(host_.observe(id,o,error_)))return false;return assign_audio(*s,s->blocked&&!s->unlocked?data_->bash():d->sound,!o.entering_door);}
bool FieldOpenableDoorRuntime::close(uint32_t id){auto s=get(id);return s&&assign_audio(*s,data_->record(id)->end_sound,true);}
bool FieldOpenableDoorRuntime::body_entered(uint32_t id,uint64_t body){auto s=get(id);if(!s||!body)return fail("OpenableDoor body event before Ready/identity missing");auto d=data_->record(id);if(s->locked&&!d->flag.empty()){bool present=false,value=false;if(!callback(host_.read_flag(d->flag,present,value,error_)))return false;if(!present)return fail("OpenableDoor locked source flags index absent");if(value){if(!unlock(id))return false;s->locked=false;}}
 bool valid=false;if(!valid_body(id,0,valid))return false;if(valid&&std::max(0.0f,s->timer_left)==0&&s->unlocked&&s->playing&&s->clip==FieldOpenableClipRole::Normal&&!(d->flags&8))if(!open(id))return false;
 FieldOpenableObservation o;if(!callback(host_.observe(id,o,error_)))return false;if(s->blocked&&o.player_running&&o.player_direction.y==data_->run_y()&&!s->unlocked){const auto&q=data_->shake();if(!callback(host_.camera_shake(q[0],q[1],{q[2],q[3]},error_))||!open(id)||!unlock(id))return false;s->blocked=false;if(!d->flag.empty()){bool present=false,value=false;if(!callback(host_.read_flag(d->flag,present,value,error_)))return false;if(present&&!callback(host_.write_flag(d->flag,true,error_)))return false;}}return true;}
bool FieldOpenableDoorRuntime::body_exited(uint32_t id,uint64_t body){auto s=get(id);if(!s||!body)return fail("OpenableDoor body exit before Ready/identity missing");FieldOpenableObservation o;if(!callback(host_.observe(id,o,error_)))return false;if(o.player_paused)return play(*s,FieldOpenableClipRole::Normal);bool valid=false;if(!valid_body(id,body,valid))return false;if(!valid&&s->unlocked){s->timer_left=data_->record(id)->timer_wait;s->timer_running=true;}return true;}
bool FieldOpenableDoorRuntime::timer_timeout(uint32_t id){auto s=get(id);if(!s)return false;bool valid=false;if(!valid_body(id,0,valid))return false;if(valid)return true;if(!play(*s,FieldOpenableClipRole::Normal))return false;auto d=data_->record(id);FieldOpenableObservation o;if(!callback(host_.observe(id,o,error_)))return false;if(d->end_sound!=data_->none()&&!o.player_paused&&!close(id))return false;if(d->flags&8){if(!lock(id)||!close(id))return false;}return true;}
bool FieldOpenableDoorRuntime::apply(FieldOpenableInstance&s,FieldOpenableProperty property,bool value){auto d=data_->record(s.id);uint32_t child=0;switch(property){case FieldOpenableProperty::SpriteVisible:child=d->children[0];s.sprite_visible=value;break;case FieldOpenableProperty::BodyDisabled:child=d->children[5];s.body_disabled=value;break;case FieldOpenableProperty::NonPlayerDisabled:child=d->children[6];s.nonplayer_disabled=value;break;case FieldOpenableProperty::AudioPlaying:child=d->children[10];break;default:return fail("OpenableDoor unknown source property");}return callback(host_.property(child,property,value,error_));}
bool FieldOpenableDoorRuntime::idle_frame(uint32_t id,float dt){auto s=get(id);if(!s)return false;if(!std::isfinite(dt)||dt<0||dt>60)return fail("OpenableDoor source process delta rejected");FieldOpenableObservation o;if(!callback(host_.observe(id,o,error_)))return false;if(o.animation_process&&s->playing){auto d=data_->record(id);auto c=data_->clip(d->profile,s->clip);if(!c)return fail("OpenableDoor playing source clip absent");float total=s->elapsed+dt;if(!std::isfinite(total))return fail("OpenableDoor animation clock overflow");bool crossed=s->elapsed==0&&dt!=0;if(c->loop&&total>=c->length)crossed=true;for(const auto&t:c->tracks)if((t.update==0||crossed)&&!apply(*s,t.property,t.value))return false;if(c->loop)s->elapsed=std::fmod(total,c->length);else{s->elapsed=std::min(total,c->length);if(total>=c->length)s->playing=false;}s->started=false;if(!publish(*s))return false;}
 if(o.timer_process&&s->timer_running){float next=s->timer_left-dt;if(!std::isfinite(next))return fail("OpenableDoor Timer clock overflow");s->timer_left=next;if(next<0){s->timer_left=-1;s->timer_running=false;if(!timer_timeout(id))return false;}}return true;}
bool FieldOpenableDoorRuntime::use_key(FieldOpenableInstance&s,uint64_t item){if(!item)return fail("OpenableDoor key Item identity missing");auto d=data_->record(s.id);if(!callback(host_.write_flag(d->flag,true,error_))||!open(s.id)||!unlock(s.id))return false;if(d->flags&4){uint64_t owner=0;if(!callback(host_.item_owner(item,owner,error_)))return false;if(owner){bool removed=false;if(!callback(host_.inventory_drop(owner,item,removed,error_)))return false;}}return true;}
bool FieldOpenableDoorRuntime::dialogue(FieldOpenableInstance&s,uint32_t index){auto d=data_->record(s.id);if(index>=d->dialogs.size())return fail("OpenableDoor dialogue role unknown");auto a=data_->dialogue(d->dialogs[index]);if(!a)return fail("OpenableDoor source dialogue absent");return callback(host_.open_dialogue(s.id,*a,error_));}
bool FieldOpenableDoorRuntime::interact(uint32_t id){auto s=get(id);if(!s)return false;if(s->unlocked)return true;auto d=data_->record(id);for(unsigned i=0;i<2;++i){const auto&key=i?d->deactivate:d->activate;if(!key.empty()){bool present=false,value=false;if(!callback(host_.read_flag(key,present,value,error_)))return false;if(present&&(!callback(host_.write_flag(key,i==0,error_))||!callback(host_.emit_flags(error_))))return false;}}if(s->blocked)return dialogue(*s,0);std::vector<uint64_t>inventories;uint64_t keys=0;if(!callback(host_.party_inventories(inventories,keys,error_)))return false;if(!keys)return fail("OpenableDoor actual key inventory absent");inventories.push_back(keys);uint64_t item=0;for(auto inv:inventories){if(!inv)return fail("OpenableDoor actual party inventory absent");if(!callback(host_.inventory_find(inv,d->key,item,error_)))return false;if(item)break;}if(!item)return dialogue(*s,2);if(!use_key(*s,item)||!callback(host_.set_global_item(item,error_)))return false;return dialogue(*s,1);}
bool FieldOpenableDoorRuntime::interact_item(uint32_t id,uint64_t item){auto s=get(id);if(!s)return false;if(s->unlocked)return true;if(!item)return fail("OpenableDoor source Item missing");auto d=data_->record(id);std::string name;if(!callback(host_.item_name(item,name,error_)))return false;if(name!=d->key||s->blocked)return dialogue(*s,0);if(!use_key(*s,item)||!callback(host_.set_global_item(item,error_)))return false;return dialogue(*s,1);}
}
