#include "encore/field_birds.hpp"
#include <algorithm>
#include <cmath>
#include <utility>
namespace encore::upstream {namespace {
bool finite(Vec2 v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::abs(v.x)<1000000&&std::abs(v.y)<1000000;}
bool approximate(float a,float b){return a==b||std::abs(a-b)<std::max(0.00001f,0.00001f*std::abs(a));}
int find(const std::vector<FieldBirdKey>&k,float t){int low=0,high=int(k.size())-1,m=0;while(low<=high){m=(low+high)/2;if(approximate(t,k[m].time))return m;if(t<k[m].time)high=m-1;else low=m+1;}if(k[m].time>t)--m;return m;}
float fpos(float x,float y){float r=std::fmod(x,y);if(r<0)r+=y;return r;}
float eased(float x,float c){double a=std::max(0.0,std::min(1.0,double(x))),b=c;if(b>0)return float(b<1?1-std::pow(1-a,1/b):std::pow(a,b));if(b<0)return float(a<.5?std::pow(a*2,-b)*.5:(1-std::pow(1-(a-.5)*2,-b))*.5+.5);return 0;}
Vec2 transform(const std::array<Vec2,3>&m,Vec2 p){return {m[0].x*p.x+m[1].x*p.y+m[2].x,m[0].y*p.x+m[1].y*p.y+m[2].y};}
}
bool FieldBirdRuntime::fail(const char*s){error_=s;poisoned_=true;return false;}
FieldBirdState*FieldBirdRuntime::get(uint32_t id,bool ready){auto i=states_.find(id);if(poisoned_||!data_||i==states_.end()||!i->second.alive||(ready&&!i->second.ready)){fail("Bird lifetime/Ready rejected");return nullptr;}return &i->second;}
const FieldBirdState*FieldBirdRuntime::state(uint32_t id)const{auto i=states_.find(id);return i==states_.end()?nullptr:&i->second;}
bool FieldBirdRuntime::initialize(const FieldBirdData&d,SourceRandom&r,FieldBirdHost h,std::string&e){
 if(!d.valid()||!h.bind||!h.observe||!h.connect||!h.body_snapshot||!h.texture||!h.publish||!h.animation_signal||!h.timer_timeout){e="Bird host callbacks incomplete";return false;}
 if(!h.bind(d,e))return false;
 data_=&d;random_=&r;host_=std::move(h);states_.clear();last_ready_=0;had_ready_=false;poisoned_=false;error_.clear();e.clear();return true;
}
bool FieldBirdRuntime::observe(uint32_t id,FieldBirdObservation&o){if(!host_.observe(id,o,error_)){poisoned_=true;return false;}if(!o.alive||!o.ancestors_admitted||!o.source_signals_admitted||!o.disabled_body_shape||!o.clear_floor_state||!o.material_admitted||!finite(o.parent[0])||!finite(o.parent[1])||!finite(o.parent[2])||o.parent[0].y||o.parent[1].x||o.parent[0].x<=0||o.parent[0].x!=o.parent[1].y)return fail("Bird live parent/body/material/signal admission rejected");for(float c:o.canvas_color)if(!std::isfinite(c)||c<0||c>1)return fail("Bird live canvas color rejected");return true;}
bool FieldBirdRuntime::publish(FieldBirdState&s){if(!finite(s.position)||!finite(s.sprite_offset)||!finite(s.velocity)||!finite(s.input)||!std::isfinite(s.speed)||!std::isfinite(s.animation_time)||!std::isfinite(s.timer_left))return fail("Bird state overflow rejected");if(!host_.publish(s.id,s,error_)){poisoned_=true;return false;}return true;}
bool FieldBirdRuntime::create(uint32_t id){if(poisoned_||!data_||states_.count(id))return fail("Bird create rejected");auto*d=data_->record(id);if(!d)return fail("Bird source node rejected");FieldBirdState s;s.id=id;s.frame=d->frame;s.z_index=d->initial_z;s.visible=(d->flags&8)!=0;s.flip=(d->flags&1)!=0;s.position=d->position;s.sprite_offset=d->sprite_offset;states_.emplace(id,s);
 if(!host_.connect(*d,[this,id](uint64_t b){return body_enter(id,b);},[this,id](){return screen_enter(id);},[this,id](){return screen_exit(id);},[this,id](FieldBirdClipRole c){return animation_finished(id,c);},error_)){poisoned_=true;return false;}return publish(states_.at(id));
}
bool FieldBirdRuntime::prepare(FieldBirdState&s){auto&z=data_->rules();s.skin=random_->randi()%z.skin_mod;auto*skin=data_->skin(s.skin);if(!skin||!host_.texture(data_->record(s.id)->children[0],*skin,error_)){poisoned_=true;return false;}if(!play(s.id,FieldBirdClipRole::Idle))return false;float pos=float(random_->randf()*double(z.seek_factor));if(!seek(s.id,pos,true))return false;s.flip=random_->randi()%z.facing_mod==z.facing_value;s.speed=float(double(z.speed_base)+random_->randi()%z.speed_mod);s.input={};s.start=s.position;return publish(s);}
bool FieldBirdRuntime::ready(uint32_t id){auto*s=get(id,false);if(!s)return false;auto*d=data_->record(id);if(s->ready||(had_ready_&&d->ready<=last_ready_))return fail("Bird source Ready order rejected");FieldBirdObservation o;if(!observe(id,o))return false;s->ready=true;last_ready_=d->ready;had_ready_=true;if(!prepare(*s))return false;s->process=false;s->visible=false;return publish(*s);}
bool FieldBirdRuntime::play(uint32_t id,FieldBirdClipRole role){auto*s=get(id);if(!s)return false;auto*d=data_->record(id);auto*c=data_->clip(d->profile,role);if(!c)return fail("Bird unknown animation rejected");if(s->clip!=role||s->animation_time==c->length)s->animation_time=0;s->clip=role;s->seeked=false;s->started=true;s->animation_playing=true;if(!host_.animation_signal(d->children[4],true,role,error_)){poisoned_=true;return false;}return publish(*s);}
bool FieldBirdRuntime::seek(uint32_t id,float time,bool update){auto*s=get(id);if(!s)return false;if(!std::isfinite(time)||time<0||time>=1000000||!data_->clip(data_->record(id)->profile,s->clip))return fail("Bird animation seek rejected");s->animation_time=time;s->seeked=true;if(update)return animate(*s,0);return publish(*s);}
bool FieldBirdRuntime::screen_enter(uint32_t id){auto*s=get(id);if(!s)return false;FieldBirdObservation o;if(!observe(id,o))return false;if(std::max(float(s->timer_left),0.0f)==0){s->visible=true;s->process=true;if(!publish(*s)||!prepare(*s))return false;}return true;}
bool FieldBirdRuntime::screen_exit(uint32_t id){auto*s=get(id);if(!s)return false;FieldBirdObservation o;if(!observe(id,o))return false;s->position=s->start;s->visible=false;if(!publish(*s)||!prepare(*s))return false;s->process=false;s->visible=false;return publish(*s);}
bool FieldBirdRuntime::body_enter(uint32_t id,uint64_t body){auto*s=get(id);if(!s)return false;FieldBirdObservation o;if(!observe(id,o))return false;FieldBirdBody b;if(!host_.body_snapshot(body,b,error_)){poisoned_=true;return false;}if(!finite(b.local_position))return fail("Bird body local position rejected");if(b.global_player){bool right=b.local_position.x<=s->position.x;if(!play(id,FieldBirdClipRole::Fly))return false;s->z_index=data_->rules().flight_z;s->input=right?data_->rules().right:data_->rules().left;s->flip=!right;}s->timer_left=data_->record(id)->timer_wait;s->timer_running=true;return publish(*s);}
bool FieldBirdRuntime::animation_finished(uint32_t id,FieldBirdClipRole role){auto*s=get(id);if(!s)return false;if(!data_->clip(data_->record(id)->profile,role))return fail("Bird finished unknown animation rejected");
 // The source's `anim_name == "hop" or "hop right"` is always truthy.
 if(!play(id,FieldBirdClipRole::Idle))return false;
 if(role==FieldBirdClipRole::Idle){bool flipped=s->flip;s->flip=!flipped;if(!play(id,flipped?FieldBirdClipRole::HopRight:FieldBirdClipRole::Hop))return false;}return publish(*s);
}
bool FieldBirdRuntime::write(FieldBirdState&s,FieldBirdProperty p,Vec2 v){if(!finite(v))return fail("Bird animated value overflow rejected");switch(p){case FieldBirdProperty::Offset:s.sprite_offset=v;break;case FieldBirdProperty::Frame:if(v.x<0||v.x>=data_->columns()*data_->rows()||std::floor(v.x)!=v.x)return fail("Bird frame rejected");s.frame=uint32_t(v.x);break;case FieldBirdProperty::RootZ:if(v.x< -4096||v.x>4096||std::floor(v.x)!=v.x)return fail("Bird depth rejected");s.z_index=int32_t(v.x);break;default:return fail("Bird unknown animation property rejected");}return true;}
bool FieldBirdRuntime::apply(FieldBirdState&s,const FieldBirdClip&c,const FieldBirdTrack&t,float time,float delta){auto&k=t.keys;
 auto interpolate=[&](){if(k.size()==1)return write(s,t.property,k[0].value);int at=find(k,time),next=0;float weight=0;if(c.loop){float span=0,from=0;if(at>=0){next=at+1<int(k.size())?at+1:0;span=next? k[next].time-k[at].time:(c.length-k[at].time)+k[next].time;from=time-k[at].time;}else{at=int(k.size())-1;float end=std::max(c.length-k[at].time,0.0f);span=end+k[0].time;from=end+time;}if(std::abs(span)>=0.00001f)weight=from/span;}else{if(at<0)return true;next=at+1<int(k.size())?at+1:at;float span=k[next].time-k[at].time;if(std::abs(span)>=0.00001f)weight=(time-k[at].time)/span;}if(t.update==1||k[at].transition==0||at==next)return write(s,t.property,k[at].value);if(k[at].transition!=1)weight=eased(weight,k[at].transition);Vec2 a=k[at].value,b=k[next].value;return write(s,t.property,{a.x+(b.x-a.x)*weight,a.y+(b.y-a.y)*weight});};
 if(t.update==0||delta==0)return interpolate();
 auto range=[&](float from,float to){if(from!=c.length&&to==c.length)to=c.length*1.001f;int last=find(k,to);if(last>=0&&from==to&&k[last].time==from)return write(s,t.property,k[last].value);if(last>=0&&k[last].time>=to)--last;int first=find(k,from);if(first<0||k[first].time<from)++first;for(int i=first;i<=last;++i)if(!write(s,t.property,k[i].value))return false;return true;};
 float from=time-delta,to=time;if(from>to)std::swap(from,to);if(c.loop){from=fpos(from,c.length);to=fpos(to,c.length);if(from>to)return range(from,c.length)&&range(0,to);}else{from=std::clamp(from,0.0f,c.length);to=std::clamp(to,0.0f,c.length);}return range(from,to);
}
bool FieldBirdRuntime::animate(FieldBirdState&s,float delta){auto*d=data_->record(s.id);auto*c=data_->clip(d->profile,s.clip);if(!c)return fail("Bird animation clock has no clip");float step=delta*d->animation_speed,old=s.animation_time,raw=old+step;if(!std::isfinite(step)||!std::isfinite(raw)||std::abs(raw)>=1000000)return fail("Bird animation clock overflow rejected");bool end=false,notify=false;float next=raw;if(c->loop){next=fpos(raw,c->length);if(next==0&&raw!=0)next=c->length;}else{next=std::clamp(raw,0.0f,c->length);step=next-old;end=next==c->length&&old<=c->length;notify=end&&old<c->length;}s.animation_time=next;for(const auto&t:c->tracks)if(!apply(s,*c,t,next,step))return false;s.started=false;if(delta!=0)s.seeked=false;if(!publish(s))return false;if(end){auto role=s.clip;s.animation_playing=false;if(!publish(s))return false;if(notify&&!host_.animation_signal(d->children[4],false,role,error_)){poisoned_=true;return false;}}return true;}
bool FieldBirdRuntime::idle_leaf(uint32_t leaf,double delta,bool can,bool paused){if(!data_||poisoned_||!std::isfinite(delta)||delta<0||delta>=1000000)return fail("Bird internal idle delta rejected");for(const auto&d:data_->records()){if(leaf!=d.children[4]&&leaf!=d.children[6])continue;auto*s=get(d.id);if(!s)return false;FieldBirdObservation o;if(!observe(d.id,o))return false;if(!can)return true;if(leaf==d.children[4])return s->animation_playing?animate(*s,float(delta)):true;if(paused||!s->timer_running)return true;s->timer_left-=delta;if(s->timer_left<0){s->timer_left=-1;s->timer_running=false;if(!publish(*s))return false;if(!host_.timer_timeout(leaf,error_)){poisoned_=true;return false;}}return publish(*s);}return fail("Bird unknown internal leaf rejected");}
bool FieldBirdRuntime::idle_process(uint32_t id,double delta,bool can){auto*s=get(id);if(!s)return false;if(!std::isfinite(delta)||delta<0||delta>=1000000)return fail("Bird process delta rejected");FieldBirdObservation o;if(!observe(id,o))return false;if(!can||!s->process)return true;if(s->input.x!=0||s->input.y!=0){s->velocity={s->input.x*s->speed,s->input.y*s->speed};
 // Source body has only a disabled CircleShape. Godot test_body_motion with
 // zero active shapes returns complete world motion. Cached floor/platform
 // state and actual shape disable are admitted on each live observation.
 Vec2 world=transform(o.parent,s->position);float dt=float(delta);world.x+=s->velocity.x*dt;world.y+=s->velocity.y*dt;s->position={(world.x-o.parent[2].x)/o.parent[0].x,(world.y-o.parent[2].y)/o.parent[1].y};}
 if(!o.notifier_on_screen&&std::max(float(s->timer_left),0.0f)==0){s->visible=true;}
 return publish(*s);
}
bool FieldBirdRuntime::exit_tree(uint32_t id){auto*s=get(id,false);if(!s)return false;s->alive=false;s->process=false;s->animation_playing=false;s->timer_running=false;s->visible=false;return publish(*s);}
bool FieldBirdRuntime::draw(uint32_t id,FieldBirdDraw&out){auto*s=get(id);if(!s)return false;FieldBirdObservation o;if(!observe(id,o))return false;auto*d=data_->record(id);auto*skin=data_->skin(s->skin);if(!skin)return fail("Bird draw skin rejected");float w=float(skin->width/data_->columns()),h=float(skin->height/data_->rows());Vec2 offset=s->sprite_offset;if(d->flags&2){offset.x-=w/2;offset.y-=h/2;}if(data_->pixel_snap()){offset.x=std::floor(offset.x);offset.y=std::floor(offset.y);}Vec2 local{s->position.x+d->sprite_position.x+offset.x,s->position.y+d->sprite_position.y+offset.y};FieldBirdDraw r;r.id=id;r.skin=s->skin;r.frame=s->frame;r.z_index=s->z_index;r.visible=s->visible&&o.ancestors_visible&&(d->flags&4);r.flip=s->flip;r.pixel_snap=data_->pixel_snap();r.origin=transform(o.parent,local);r.scale={o.parent[0].x,o.parent[1].y};for(size_t i=0;i<4;++i)r.color[i]=o.canvas_color[i]*d->modulate[i]*d->sprite_modulate[i]*d->sprite_self_modulate[i];if(!finite(r.origin)||!finite(r.scale))return fail("Bird draw overflow rejected");out=r;return true;}
}
