#include "encore/field_dandelion.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <unordered_map>
#include <unordered_set>
namespace encore::upstream {
namespace {
constexpr uint32_t begin=368,strides[]={0,8,1,96,88,84,12,20,36,20,72};
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
float real(const uint8_t*p){auto n=u32(p);float v;std::memcpy(&v,&n,4);return v;}Vec2 vec(const uint8_t*p){return {real(p),real(p+4)};}
FieldGeometryTransform tr(const uint8_t*p){return {vec(p),vec(p+8),vec(p+16)};}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;while(n--){c^=*p++;for(unsigned j=0;j<8;++j)c=(c>>1)^((c&1)?0xedb88320u:0u);}return ~c;}
bool path(std::string_view s){if(s.empty()||s.front()=='/'||s.back()=='/'||s.find('\\')!=s.npos)return false;size_t b=0;while(b<s.size()){auto e=s.find('/',b);if(e==s.npos)e=s.size();auto p=s.substr(b,e-b);if(p.empty()||p=="."||p=="..")return false;b=e+1;}return true;}
bool finite(float n){return std::isfinite(n)&&std::abs(n)<1000000;}bool finite(Vec2 p){return finite(p.x)&&finite(p.y);}
}
uint32_t FieldDandelionData::count(uint32_t k)const{return valid()&&k>=1&&k<=10?u32(bytes_.data()+128+24*(k-1)+4):0;}
const uint8_t*FieldDandelionData::record(uint32_t k,uint32_t i)const{return i<count(k)?bytes_.data()+u32(bytes_.data()+128+24*(k-1)+12)+size_t(i)*strides[k]:nullptr;}
std::string_view FieldDandelionData::string(uint32_t i)const{auto r=record(1,i);return r?std::string_view(reinterpret_cast<const char*>(record(2,u32(r))),u32(r+4)):std::string_view{};}
FieldIdentity FieldDandelionData::identity()const{FieldIdentity id;if(valid()){id.scene_id=u32(bytes_.data()+36);std::copy_n(bytes_.data()+40,20,id.upstream_commit.begin());std::copy_n(bytes_.data()+60,32,id.source_sha256.begin());}return id;}
std::string_view FieldDandelionData::source_scene()const{return valid()?string(u32(bytes_.data()+124)):std::string_view{};}
uint32_t FieldDandelionData::spawner_count()const{return count(3);}uint32_t FieldDandelionData::parameter_count()const{return count(6);}uint32_t FieldDandelionData::ramp_count()const{return count(7);}
FieldDandelionSpawner FieldDandelionData::spawner(uint32_t i)const{FieldDandelionSpawner n;auto r=record(3,i);if(r){n.id=u32(r);n.ready=u32(r+4);n.node=u32(r+8);n.parent=u32(r+12);n.sprite=u32(r+16);n.notifier=u32(r+20);n.parent_transform=tr(r+24);n.position=vec(r+48);n.notifier_transform=tr(r+56);n.visibility_origin=vec(r+80);n.visibility_size=vec(r+88);}return n;}
FieldDandelionProfile FieldDandelionData::profile()const{FieldDandelionProfile p;auto r=record(4,0);if(r){uint32_t*a[]={&p.id,&p.layer,&p.mask,&p.flags,&p.sprite_texture,&p.seed_texture,&p.columns,&p.rows,&p.idle,&p.blown,&p.source};for(unsigned j=0;j<11;++j)*a[j]=u32(r+4*j);p.collision_offset=vec(r+44);p.extents=vec(r+52);p.sprite_offset=vec(r+60);p.sprite_position=vec(r+68);p.particle_position=vec(r+76);p.gravity_multiplier=real(r+84);}return p;}
FieldDandelionTexture FieldDandelionData::texture(uint32_t i)const{FieldDandelionTexture t;auto r=record(5,i);if(r){t.id=u32(r);t.source=u32(r+4);t.path=u32(r+8);t.width=u32(r+12);t.height=u32(r+16);std::copy_n(r+20,32,t.source_sha.begin());std::copy_n(r+52,32,t.output_sha.begin());}return t;}
FieldDandelionParameter FieldDandelionData::parameter(uint32_t i)const{auto r=record(6,i);return r?FieldDandelionParameter{u32(r),u32(r+4),real(r+8)}:FieldDandelionParameter{};}
std::array<float,5>FieldDandelionData::ramp(uint32_t i)const{std::array<float,5>a{};auto r=record(7,i);if(r)for(unsigned j=0;j<5;++j)a[j]=real(r+j*4);return a;}
std::array<uint32_t,5>FieldDandelionData::material()const{std::array<uint32_t,5>a{};auto r=record(9,0);if(r)for(unsigned j=0;j<5;++j)a[j]=u32(r+j*4);return a;}
std::string_view FieldDandelionData::spawner_script()const{auto r=record(10,0);return r?string(u32(r)):std::string_view{};}std::string_view FieldDandelionData::plant_script()const{auto r=record(10,0);return r?string(u32(r+4)):std::string_view{};}
std::array<uint8_t,32>FieldDandelionData::spawner_sha()const{std::array<uint8_t,32>a{};auto r=record(10,0);if(r)std::copy_n(r+8,32,a.begin());return a;}std::array<uint8_t,32>FieldDandelionData::plant_sha()const{std::array<uint8_t,32>a{};auto r=record(10,0);if(r)std::copy_n(r+40,32,a.begin());return a;}
bool FieldDandelionData::load(const uint8_t*p,size_t n,const FieldIdentity&id,std::string&e){if(!p||n<begin||n>4*1024*1024){e="Dandelion source size rejected";return false;}return admit(std::vector<uint8_t>(p,p+n),id,e);}
bool FieldDandelionData::load_file(const char*p,const FieldIdentity&id,std::string&e){if(!p||!*p){e="Dandelion path rejected";return false;}FILE*f=std::fopen(p,"rb");if(!f){e="Cannot open dandelion resource";return false;}if(std::fseek(f,0,SEEK_END)){std::fclose(f);e="Dandelion seek rejected";return false;}long n=std::ftell(f);if(n<static_cast<long>(begin)||n>4*1024*1024||std::fseek(f,0,SEEK_SET)){std::fclose(f);e="Dandelion size rejected";return false;}std::vector<uint8_t>b(static_cast<size_t>(n));size_t got=std::fread(b.data(),1,b.size(),f);bool closed=std::fclose(f)==0;if(got!=b.size()||!closed){e="Dandelion read rejected";return false;}return admit(std::move(b),id,e);}
bool FieldDandelionData::admit(std::vector<uint8_t>&&b,const FieldIdentity&id,std::string&e){auto fail=[&](const char*s){e=s;return false;};auto p=b.data();size_t size=b.size();if(std::memcmp(p,"ENCFDAN1",8)||u32(p+8)!=1||u32(p+12)!=128||u32(p+16)!=size||u32(p+20)!=10||u32(p+28)!=0x454e001d||u32(p+32)!=3||!id.scene_id||u32(p+36)!=id.scene_id||std::memcmp(p+40,id.upstream_commit.data(),20)||std::memcmp(p+60,id.source_sha256.data(),32))return fail("Dandelion identity/version rejected");if(crc(p+begin,size-begin)!=u32(p+24))return fail("Dandelion CRC rejected");uint64_t end=begin;for(uint32_t k=1;k<=10;++k){auto d=p+128+24*(k-1);uint64_t n=u32(d+4),bytes=n*strides[k];if(u32(d)!=k||u32(d+8)!=strides[k]||u32(d+12)!=end||u32(d+16)!=bytes||u32(d+20)||bytes>size-end)return fail("Dandelion section rejected");end+=bytes;}if(end!=size)return fail("Dandelion trailing bytes rejected");FieldDandelionData c;c.bytes_=std::move(b);if(!c.count(1)||!c.count(2)||!c.count(3)||c.count(3)>10000||c.count(4)!=1||c.count(5)!=2||c.count(6)>1000||c.count(7)>1000||!c.count(8)||c.count(9)!=1||c.count(10)!=1)return fail("Dandelion capacity rejected");uint32_t string_end=0;for(uint32_t i=0;i<c.count(1);++i){auto r=c.record(1,i);uint32_t first=u32(r),n=u32(r+4);if(first!=string_end||first>=c.count(2)||n>=c.count(2)-first)return fail("Dandelion string span rejected");auto q=c.record(2,first);if(q[n]||std::memchr(q,0,n))return fail("Dandelion string bytes rejected");string_end=first+n+1;}if(string_end!=c.count(2)||u32(c.bytes_.data()+124)>=c.count(1)||!path(c.source_scene()))return fail("Dandelion scene path rejected");
 std::unordered_map<std::string_view,std::array<uint8_t,32>>sources;for(uint32_t i=0;i<c.count(8);++i){auto r=c.record(8,i);if(u32(r)>=c.count(1)||!path(c.string(u32(r))))return fail("Dandelion source path rejected");std::array<uint8_t,32>h{};std::copy_n(r+4,32,h.begin());if(std::all_of(h.begin(),h.end(),[](uint8_t v){return !v;})||!sources.emplace(c.string(u32(r)),h).second)return fail("Dandelion source proof rejected");}auto root=sources.find(c.source_scene());if(root==sources.end()||root->second!=id.source_sha256)return fail("Dandelion scene proof rejected");auto sr=c.record(10,0);for(unsigned j=0;j<2;++j){uint32_t key=u32(sr+4*j);if(key>=c.count(1))return fail("Dandelion script index rejected");auto it=sources.find(c.string(key));if(it==sources.end()||std::memcmp(it->second.data(),sr+8+32*j,32))return fail("Dandelion script source rejected");}
 std::unordered_set<uint32_t>ids;std::unordered_set<std::string_view>nodes;uint32_t ready=0;for(uint32_t i=0;i<c.count(3);++i){auto n=c.spawner(i);if(!n.id||!ids.insert(n.id).second||!n.parent||!n.sprite||!n.notifier||n.node>=c.count(1)||!path(c.string(n.node))||!nodes.insert(c.string(n.node)).second||(i&&n.ready<=ready)||!finite(n.position)||!finite(n.visibility_origin)||!finite(n.visibility_size)||n.visibility_size.x<=0||n.visibility_size.y<=0)return fail("Dandelion source spawner rejected");ready=n.ready;for(auto t:{n.parent_transform,n.notifier_transform})if(!finite(t.x)||!finite(t.y)||!finite(t.origin)||t.x.x*t.y.y-t.x.y*t.y.x==0)return fail("Dandelion transform rejected");}
 auto f=c.profile();if(!f.id||f.source>=c.count(1)||!path(c.string(f.source))||sources.find(c.string(f.source))==sources.end()||f.flags>7||f.sprite_texture>=c.count(5)||f.seed_texture>=c.count(5)||!f.columns||!f.rows||f.columns>1024||f.rows>1024||f.idle>=f.columns*f.rows||f.blown>=f.columns*f.rows||f.idle==f.blown||!finite(f.extents)||f.extents.x<=0||f.extents.y<=0||!finite(f.collision_offset)||!finite(f.sprite_offset)||!finite(f.sprite_position)||!finite(f.particle_position)||!finite(f.gravity_multiplier))return fail("Dandelion prototype rejected");for(uint32_t i=0;i<c.count(5);++i){auto t=c.texture(i);auto source=sources.find(c.string(t.source));auto output=c.string(t.path);if(!t.id||t.source>=c.count(1)||t.path>=c.count(1)||!t.width||!t.height||t.width>1024||t.height>1024||source==sources.end()||source->second!=t.source_sha||std::all_of(t.output_sha.begin(),t.output_sha.end(),[](uint8_t v){return !v;})||!path(output)||output.substr(0,15)!="graphics/world/"||output.size()<5||output.substr(output.size()-4)!=".t3x")return fail("Dandelion texture source rejected");}auto t=c.texture(f.sprite_texture);if(t.width%f.columns||t.height%f.rows)return fail("Dandelion sprite frame geometry rejected");std::unordered_set<std::string_view>parameters;for(uint32_t i=0;i<c.count(6);++i){auto n=c.parameter(i);if(n.name>=c.count(1)||c.string(n.name).empty()||!parameters.insert(c.string(n.name)).second||n.kind>2||!finite(n.value)||(n.kind==1&&n.value!=0&&n.value!=1)||(n.kind==2&&std::floor(n.value)!=n.value))return fail("Dandelion native parameter rejected");}float prev=-1;for(uint32_t i=0;i<c.count(7);++i){auto n=c.ramp(i);for(float v:n)if(!finite(v)||v<0||v>1)return fail("Dandelion ramp value rejected");if(n[0]<=prev)return fail("Dandelion ramp order rejected");prev=n[0];}auto mat=c.material();if(mat[0]>4||mat[1]>2||!mat[2]||!mat[3]||mat[2]>1024||mat[3]>1024||mat[4]>3)return fail("Dandelion particle material rejected");bytes_=std::move(c.bytes_);e.clear();return true;
}
bool FieldDandelionRuntime::initialize(const FieldDandelionData&d,FieldDandelionHost h,std::string&e){if(data_){e="Dandelion source instance already initialized";return false;}if(!d.valid()||!h.queue_source_sprite||!h.instance||!h.add_child||!h.abort_unparented||!h.sprite_frame||!h.particle_backend_admitted||!h.emit_particles||!h.player_direction){e="Dandelion actual factory Host incomplete";return false;}data_=&d;host_=std::move(h);spawners_.assign(d.spawner_count(),State{});instances_.clear();had_ready_=false;last_ready_=0;e.clear();return true;}
bool FieldDandelionRuntime::index(uint32_t id,size_t&i,std::string&e)const{if(!data_){e="Dandelion runtime unavailable";return false;}for(i=0;i<spawners_.size();++i)if(data_->spawner(static_cast<uint32_t>(i)).id==id)return true;e="Dandelion source NodeID rejected";return false;}
bool FieldDandelionRuntime::ready(uint32_t id,std::string&e){size_t i;if(!index(id,i,e))return false;auto&state=spawners_[i];auto n=data_->spawner(static_cast<uint32_t>(i));if(state.ready||state.poisoned||(had_ready_&&n.ready<=last_ready_)){e="Dandelion Ready order/duplicate rejected";return false;}if(!host_.queue_source_sprite(n.sprite,e)){state.poisoned=true;return false;}state.ready=true;last_ready_=n.ready;had_ready_=true;e.clear();return true;}
bool FieldDandelionRuntime::screen_entered(uint32_t id,std::string&e){size_t i;if(!index(id,i,e))return false;auto&s=spawners_[i];if(!s.ready||s.poisoned){e="Dandelion source screen event before Ready/after failed factory";return false;}if(s.current){e.clear();return true;}auto n=data_->spawner(static_cast<uint32_t>(i));auto p=data_->profile();uint64_t instance=0;if(!host_.instance(*data_,p,n.position,instance,e)){s.poisoned=true;return false;}bool duplicate=false;for(const auto&v:instances_)if(v.id==instance)duplicate=true;if(!instance||duplicate){e="Dandelion factory identity rejected";s.poisoned=true;return false;}Vec2 world;if(!host_.add_child(instance,n.parent,world,e)){std::string cleanup;host_.abort_unparented(instance,cleanup);s.poisoned=true;return false;}if(!finite(world)){e="Dandelion actual parent transform nonfinite";s.poisoned=true;return false;}instances_.push_back(FieldDandelionInstance{instance,id,p.idle,true,n.position,world});s.current=instance;e.clear();return true;}
bool FieldDandelionRuntime::screen_exited(uint32_t id,std::string&e){size_t i;if(!index(id,i,e))return false;auto&s=spawners_[i];if(!s.ready||s.poisoned){e="Dandelion exit before Ready/after failed factory";return false;}if(!s.current){e="Source DandelionSpawner screen_exited calls queue_free on null (inverted source guard)";return false;}e.clear();return true;}
bool FieldDandelionRuntime::body_entered(uint64_t id,bool player,std::string&e){if(!data_){e="Dandelion runtime unavailable";return false;}FieldDandelionInstance*it=nullptr;for(auto&v:instances_)if(v.id==id){it=&v;break;}if(!it){e="Dandelion dynamic source instance unknown";return false;}auto p=data_->profile();if(!player||it->frame!=p.idle){e.clear();return true;}if(!data_->particle_emission_admitted()){e="Dandelion resource certifies Ready/factory only; CPUParticles emission remains pending";return false;}bool admitted=false;if(!host_.particle_backend_admitted(id,admitted,e))return false;if(!admitted){e="Dandelion CPUParticles2D emission backend pending";return false;}Vec2 direction;if(!host_.player_direction(direction,e)||!finite(direction)){if(e.empty())e="Dandelion actual player direction rejected";return false;}if(!host_.sprite_frame(id,p.blown,e))return false;it->frame=p.blown;return host_.emit_particles(id,*data_,{direction.x*p.gravity_multiplier,direction.y*p.gravity_multiplier},e);}
}
