#include "encore/field_emotes.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <set>
namespace encore::upstream {namespace {
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=i>=16&&i<20?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
struct Reader {const uint8_t*p;size_t n,at=64;bool ok=true;uint32_t integer(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=u32(p+at);at+=4;return v;}float scalar(){auto v=integer();float f;std::memcpy(&f,&v,4);if(!std::isfinite(f)||std::abs(f)>1000000)ok=false;return f;}Vec2 vec(){return{scalar(),scalar()};}std::string text(){auto len=integer();if(!ok||len>8192||at>n||len>n-at){ok=false;return{};}std::string v(reinterpret_cast<const char*>(p+at),len);at+=len;size_t i=0;uint32_t cp;while(i<v.size())if(!encore::utf8_next(v,i,cp)||cp<32){ok=false;break;}return v;}bool hash(std::array<uint8_t,32>&out){if(!ok||at>n||n-at<32){ok=false;return false;}bool any=false;for(unsigned i=0;i<32;++i)any|=p[at+i]!=0;std::copy_n(p+at,32,out.begin());at+=32;ok&=any;return any;}};
bool path(std::string_view p){return!p.empty()&&p.front()!='/'&&p.back()!='/'&&p.find("..") ==p.npos&&p.find(':')==p.npos&&p.find('\\')==p.npos;}
bool relative(std::string_view p){return p.empty()||(p.front()!='/'&&p.find(':')==p.npos&&p.find('\\')==p.npos);}
}
bool FieldEmoteData::source_hash(const std::string&p,std::array<uint8_t,32>&out)const{auto i=sources_.find(p);if(i==sources_.end())return false;out=i->second;return true;}
const FieldEmoteDescriptor*FieldEmoteData::record(uint32_t id)const{for(const auto&r:records_)if(r.id==id)return&r;return nullptr;}
const FieldEmoteClip*FieldEmoteData::clip(uint32_t id)const{for(const auto&r:clips_)if(r.id==id)return&r;return nullptr;}
const FieldEmoteClip*FieldEmoteData::clip(const std::string&name)const{for(const auto&r:clips_)if(r.name==name)return&r;return nullptr;}
const FieldEmoteSound*FieldEmoteData::sound(uint32_t id)const{for(const auto&r:sounds_)if(r.id==id)return&r;return nullptr;}
bool FieldEmoteData::load_file(const char*name,std::string&e){if(!name){e="Emotes pack path absent";return false;}std::ifstream f(name,std::ios::binary);if(!f){e="Emotes pack unavailable";return false;}f.seekg(0,std::ios::end);auto n=f.tellg();if(n<64||n>4*1024*1024){e="Emotes pack file size";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)){e="Emotes pack file read";return false;}return load(b.data(),b.size(),e);}
bool FieldEmoteData::load(const uint8_t*p,size_t n,std::string&e){auto reject=[&](const char*t){e=t;return false;};if(!p||n<64||n>4*1024*1024)return reject("Emotes pack size");if(std::memcmp(p,"ENCEMO01",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+20)!=1||u32(p+24)!=1||!u32(p+28)||u32(p+28)>4096||!u32(p+52)||!u32(p+56)||u32(p+56)>512||u32(p+60)||u32(p+16)!=crc(p,n))return reject("Emotes header/version/capability/rule/CRC");FieldEmoteData next;std::copy(p+32,p+52,next.pin_.begin());if(std::all_of(next.pin_.begin(),next.pin_.end(),[](uint8_t b){return!b;}))return reject("Emotes source pin absent");next.scene_=u32(p+52);Reader r{p,n};next.bubble_gap_=r.scalar();next.default_sound_=r.integer();next.width_=r.integer();next.height_=r.integer();next.texture_source_=r.text();next.texture_path_=r.text();next.bus_=r.text();if(!r.ok||next.bubble_gap_<0||next.bubble_gap_>1024||!next.width_||!next.height_||next.width_>16384||next.height_>16384||!path(next.texture_source_)||!path(next.texture_path_)||next.bus_.empty())return reject("Emotes source atlas/bubble/bus");auto count=r.integer();if(!count||count>128)return reject("Emotes sounds count");std::set<uint32_t>ids;
 for(uint32_t i=0;i<count;++i){FieldEmoteSound s;s.id=r.integer();s.gain_db=r.scalar();s.source=r.text();s.pcm=r.text();if(!r.ok||!s.id||!ids.insert(s.id).second||!path(s.source)||!path(s.pcm)||s.gain_db<-120||s.gain_db>24)return reject("Emotes source sound binding");next.sounds_.push_back(std::move(s));}if(!next.sound(next.default_sound_))return reject("Emotes default stream outside source sounds");count=r.integer();if(!count||count>128)return reject("Emotes clips count");ids.clear();std::set<std::string>names;
 for(uint32_t i=0;i<count;++i){FieldEmoteClip a;a.id=r.integer();auto sensitive=r.integer();a.direction_sensitive=sensitive;a.length=r.scalar();a.name=r.text();auto tracks=r.integer();if(!r.ok||!a.id||!ids.insert(a.id).second||sensitive>1||a.length<=0||a.length>86400||a.name.empty()||!names.insert(a.name).second||!tracks||tracks>8)return reject("Emotes source clip identity/duration");std::set<uint32_t>roles;
  for(uint32_t j=0;j<tracks;++j){FieldEmoteTrack t;auto prop=r.integer();t.property=FieldEmoteProperty(prop);t.update=r.integer();auto keys=r.integer();if(!r.ok||prop<1||prop>4||!roles.insert(prop).second||t.update>2||(t.update==2&&prop!=2)||(t.update==0&&prop!=2&&keys!=1)||!keys||keys>1024)return reject("Emotes source track/update");float last=-1;for(uint32_t k=0;k<keys;++k){FieldEmoteKey q;q.time=r.scalar();if(prop==2)q.vector=r.vec();else{q.integer=r.integer();if(r.integer())return reject("Emotes scalar key reserved field");}if(!r.ok||q.time<0||q.time<last||q.time>a.length||(prop==1&&q.integer>=1048576)||(prop==3&&!next.sound(q.integer))||(prop==4&&q.integer>1))return reject("Emotes source track key/bounds");last=q.time;t.keys.push_back(q);}a.tracks.push_back(std::move(t));}next.clips_.push_back(std::move(a));
 }
 ids.clear();uint32_t last=0;bool had=false;for(uint32_t i=0;i<u32(p+28);++i){FieldEmoteDescriptor d;d.id=r.integer();d.parent_id=r.integer();d.ready_ordinal=r.integer();d.object_id=r.integer();d.direction_id=r.integer();d.columns=r.integer();d.rows=r.integer();d.frame=r.integer();d.flags=r.integer();auto z=r.integer();std::memcpy(&d.z_index,&z,4);d.position=r.vec();d.offset=r.vec();d.scale=r.vec();d.node=r.text();d.object_path=r.text();if(!r.ok||!d.id||!ids.insert(d.id).second||!d.parent_id||d.flags>3||!d.columns||!d.rows||d.columns>1024||d.rows>1024||d.frame>=d.columns*d.rows||next.width_%d.columns||next.height_%d.rows||std::abs(int64_t(d.z_index))>4096||!path(d.node)||!relative(d.object_path)||bool(d.object_id)!=!d.object_path.empty()||d.ready_ordinal==UINT32_MAX||(had&&d.ready_ordinal<=last))return reject("Emotes source descriptor/Ready/geometry");last=d.ready_ordinal;had=true;for(const auto&a:next.clips_)for(const auto&t:a.tracks)if(t.property==FieldEmoteProperty::Frame)for(const auto&k:t.keys)if(k.integer>=d.columns*d.rows)return reject("Emotes clip frame outside source grid");next.records_.push_back(std::move(d));}
 count=r.integer();if(count!=u32(p+56))return reject("Emotes source receipt count");names.clear();for(uint32_t i=0;i<count;++i){auto name=r.text();std::array<uint8_t,32>hash{};if(!r.ok||!path(name)||!names.insert(name).second||!r.hash(hash))return reject("Emotes source receipt/hash");next.sources_.emplace(name,hash);}if(!r.ok||r.at!=n)return reject("Emotes trailing data");if(!names.count(next.texture_source_))return reject("Emotes texture outside source closure");for(const auto&s:next.sounds_)if(!names.count(s.source)||!names.count(s.source+".import"))return reject("Emotes audio outside source closure");next.valid_=true;*this=std::move(next);e.clear();return true;
}
}
