#include "encore/field_scene_data.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <unordered_map>
#include <unordered_set>
namespace encore::upstream {
namespace {
constexpr uint32_t strides[]={0,8,1,56,16,16,48,8,8,4,12,36,4};
constexpr uint32_t none=0xffffffffu,begin=416;
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
float real(const uint8_t*p){const auto v=u32(p);float n;std::memcpy(&n,&v,4);return n;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;while(n--){c^=*p++;for(unsigned j=0;j<8;++j)c=(c>>1)^((c&1)?0xedb88320u:0u);}return ~c;}
bool path(std::string_view s){if(s==".")return true;if(s.empty()||s.front()=='/'||s.back()=='/'||s.find('\\')!=s.npos)return false;size_t b=0;while(b<s.size()){auto e=s.find('/',b);if(e==s.npos)e=s.size();auto p=s.substr(b,e-b);if(p.empty()||p=="."||p=="..")return false;b=e+1;}return true;}
}
uint32_t FieldSceneData::count(uint32_t k)const{return valid()&&k>=1&&k<=12?u32(bytes_.data()+128+(k-1)*24+4):0;}
const uint8_t*FieldSceneData::record(uint32_t k,uint32_t i)const{return i<count(k)?bytes_.data()+u32(bytes_.data()+128+(k-1)*24+12)+size_t(i)*strides[k]:nullptr;}
std::string_view FieldSceneData::string(uint32_t i)const{auto r=record(1,i);return r?std::string_view(reinterpret_cast<const char*>(record(2,u32(r))),u32(r+4)):std::string_view{};}
FieldIdentity FieldSceneData::identity()const{FieldIdentity id;if(valid()){id.scene_id=u32(bytes_.data()+36);std::copy_n(bytes_.data()+40,20,id.upstream_commit.begin());std::copy_n(bytes_.data()+60,32,id.source_sha256.begin());}return id;}
std::string_view FieldSceneData::source_scene()const{return valid()?string(u32(bytes_.data()+124)):std::string_view{};}
uint32_t FieldSceneData::ready_count()const{return count(3);}uint32_t FieldSceneData::landmark_count()const{return count(4);}uint32_t FieldSceneData::flaggable_count()const{return count(5);}uint32_t FieldSceneData::override_count()const{return count(7);}uint32_t FieldSceneData::visit_count()const{return count(8);}
FieldSceneReady FieldSceneData::ready(uint32_t i)const{FieldSceneReady n;auto r=record(3,i);if(!r)return n;n.id=u32(r);n.node=u32(r+4);n.name=u32(r+8);n.ordinal=u32(r+12);n.role=static_cast<FieldSceneRole>(u32(r+16));n.profile=u32(r+20);std::copy_n(r+24,32,n.sha.begin());n.script=u32(record(12,i));return n;}
FieldSceneLandmark FieldSceneData::landmark(uint32_t i)const{FieldSceneLandmark n;auto r=record(4,i);if(r){n.id=u32(r);n.appear=u32(r+4);n.disappear=u32(r+8);n.delete_if_hidden=(u32(r+12)&1)!=0;n.initial_visible=(u32(r+12)&2)!=0;}return n;}
FieldSceneFlaggable FieldSceneData::flaggable(uint32_t i)const{FieldSceneFlaggable n;auto r=record(5,i);if(r){n.id=u32(r);n.key=u32(r+4);n.flags=u32(r+8);n.leaf_script=u32(r+12);}return n;}
FieldSceneArea FieldSceneData::area()const{FieldSceneArea n;auto r=record(6,0);if(r){n.id=u32(r);n.name=u32(r+4);n.region=u32(r+8);n.sub_area=u32(r+12)!=0;n.magicant=u32(r+16);n.flying_flag=u32(r+20);n.map_offset={real(r+24),real(r+28)};for(unsigned j=0;j<4;++j)n.background[j]=real(r+32+4*j);}return n;}
FieldSceneDebug FieldSceneData::debug(uint32_t i)const{FieldSceneDebug n;auto r=record(10,i);if(r){n.id=u32(r);n.position={real(r+4),real(r+8)};}return n;}
std::pair<std::string_view,std::string_view>FieldSceneData::map_override(uint32_t i)const{auto r=record(7,i);return r?std::make_pair(string(u32(r)),string(u32(r+4))):std::pair<std::string_view,std::string_view>{};}
std::pair<std::string_view,std::string_view>FieldSceneData::visit(uint32_t i)const{auto r=record(8,i);return r?std::make_pair(string(u32(r)),string(u32(r+4))):std::pair<std::string_view,std::string_view>{};}
bool FieldSceneData::normal_flag_exists(std::string_view key)const{for(uint32_t i=0;i<count(9);++i)if(string(u32(record(9,i)))==key)return true;return false;}
bool FieldSceneData::load(const uint8_t*p,size_t n,const FieldIdentity&id,std::string&e){if(!p||n<begin||n>4*1024*1024){e="Field lifecycle size rejected";return false;}return admit(std::vector<uint8_t>(p,p+n),id,e);}
bool FieldSceneData::load_file(const char*p,const FieldIdentity&id,std::string&e){if(!p||!*p){e="Field lifecycle path rejected";return false;}FILE*f=std::fopen(p,"rb");if(!f){e="Cannot open field lifecycle";return false;}if(std::fseek(f,0,SEEK_END)){std::fclose(f);e="Field lifecycle seek rejected";return false;}long n=std::ftell(f);if(n<static_cast<long>(begin)||n>4*1024*1024||std::fseek(f,0,SEEK_SET)){std::fclose(f);e="Field lifecycle file size rejected";return false;}std::vector<uint8_t>b(static_cast<size_t>(n));size_t got=std::fread(b.data(),1,b.size(),f);bool close=std::fclose(f)==0;if(got!=b.size()||!close){e="Field lifecycle read rejected";return false;}return admit(std::move(b),id,e);}
bool FieldSceneData::source_hash(std::string_view p,std::array<uint8_t,32>&out)const{for(uint32_t i=0;i<count(11);++i){auto r=record(11,i);if(string(u32(r))==p){std::copy_n(r+4,32,out.begin());return true;}}return false;}
bool FieldSceneData::admit(std::vector<uint8_t>&&b,const FieldIdentity&id,std::string&e){auto fail=[&](const char*s){e=s;return false;};auto p=b.data();size_t size=b.size();if(std::memcmp(p,"ENCFSCN1",8)||u32(p+8)!=1||u32(p+12)!=128||u32(p+16)!=size||u32(p+20)!=12||u32(p+28)!=0x454e001c||(u32(p+32)<1||u32(p+32)>3)||!id.scene_id||u32(p+36)!=id.scene_id||std::memcmp(p+40,id.upstream_commit.data(),20)||std::memcmp(p+60,id.source_sha256.data(),32))return fail("Field lifecycle identity/version rejected");if(crc(p+begin,size-begin)!=u32(p+24))return fail("Field lifecycle CRC rejected");uint64_t end=begin;for(uint32_t k=1;k<=12;++k){auto d=p+128+24*(k-1);uint64_t n=u32(d+4),bytes=n*strides[k];if(u32(d)!=k||u32(d+8)!=strides[k]||u32(d+12)!=end||u32(d+16)!=bytes||u32(d+20)||bytes>size-end)return fail("Field lifecycle directory rejected");end+=bytes;}if(end!=size)return fail("Field lifecycle trailing bytes rejected");FieldSceneData c;c.bytes_=std::move(b);if(!c.count(1)||!c.count(2)||!c.ready_count()||c.ready_count()>10000||c.count(6)!=1||c.count(10)>10000||c.count(12)!=c.ready_count()||!c.count(11))return fail("Field lifecycle capacity rejected");uint32_t string_end=0;for(uint32_t i=0;i<c.count(1);++i){auto r=c.record(1,i);uint32_t first=u32(r),n=u32(r+4);if(first!=string_end||first>=c.count(2)||n>=c.count(2)-first)return fail("Field lifecycle string span rejected");auto q=c.record(2,first);if(q[n]||std::memchr(q,0,n))return fail("Field lifecycle string bytes rejected");string_end=first+n+1;}if(string_end!=c.count(2)||u32(c.bytes_.data()+124)>=c.count(1)||!path(c.source_scene())||c.source_scene().size()<5||c.source_scene().substr(c.source_scene().size()-5)!=".tscn")return fail("Field lifecycle scene path rejected");
 std::unordered_map<std::string_view,std::array<uint8_t,32>>sources;for(uint32_t i=0;i<c.count(11);++i){auto r=c.record(11,i);if(u32(r)>=c.count(1)||!path(c.string(u32(r))))return fail("Field lifecycle source path rejected");std::array<uint8_t,32>h{};std::copy_n(r+4,32,h.begin());if(std::all_of(h.begin(),h.end(),[](uint8_t v){return !v;})||!sources.emplace(c.string(u32(r)),h).second)return fail("Field lifecycle source proof rejected");}auto source=sources.find(c.source_scene());if(source==sources.end()||source->second!=id.source_sha256)return fail("Field lifecycle scene proof rejected");
 std::unordered_set<uint32_t>ids,profiles;std::unordered_set<std::string_view>paths;uint32_t previous=0;for(uint32_t i=0;i<c.ready_count();++i){auto n=c.ready(i);uint32_t role=uint32_t(n.role);if(!n.id||!ids.insert(n.id).second||n.node>=c.count(1)||n.name>=c.count(1)||n.script>=c.count(1)||!path(c.string(n.node))||!paths.insert(c.string(n.node)).second||c.string(n.name).empty()||(role>22||(role>15&&u32(c.bytes_.data()+32)<3&&(role!=18||u32(c.bytes_.data()+32)!=2)))||(i&&n.ordinal<=previous)||std::all_of(n.sha.begin(),n.sha.end(),[](uint8_t v){return !v;}))return fail("Field lifecycle Ready roster rejected");previous=n.ordinal;auto leaf=sources.find(c.string(n.script));if(leaf==sources.end()||leaf->second!=n.sha)return fail("Field lifecycle leaf source rejected");uint32_t section=role==7?4:(role==8||role==20||role==21)?5:role==9?6:role==10?10:0;if(n.role==FieldSceneRole::AreaRoom&&c.string(n.node)!=".")return fail("Field lifecycle AreaRoom root rejected");if((n.role==FieldSceneRole::FlaggableDerived||n.role==FieldSceneRole::Present||n.role==FieldSceneRole::DroppedItem)&&n.profile<c.count(5)&&c.string(u32(c.record(5,n.profile)+12))!=c.string(n.script))return fail("Field lifecycle derived source rejected");if(section){if(n.profile>=c.count(section)||u32(c.record(section,n.profile))!=n.id||!profiles.insert((section<<24)|n.profile).second)return fail("Field lifecycle profile identity rejected");}else if(n.profile!=none)return fail("Field lifecycle unexpected profile rejected");}
 if(c.ready(c.ready_count()-1).role!=FieldSceneRole::AreaRoom)return fail("Field lifecycle root Ready order rejected");
 if(profiles.size()!=c.count(4)+c.count(5)+c.count(6)+c.count(10))return fail("Field lifecycle orphan profiles rejected");
 for(uint32_t i=0;i<c.count(4);++i){auto r=c.record(4,i);if(u32(r+4)>=c.count(1)||u32(r+8)>=c.count(1)||u32(r+12)>3)return fail("Field lifecycle landmark rejected");}for(uint32_t i=0;i<c.count(5);++i){auto r=c.record(5,i);if(u32(r+4)>=c.count(1)||u32(r+8)>15||u32(r+12)>=c.count(1))return fail("Field lifecycle flaggable rejected");}
 auto a=c.area();auto ar=c.record(6,0);if(u32(ar+12)>1||a.id!=id.scene_id||a.name>=c.count(1)||a.region>=c.count(1)||a.magicant>=c.count(1)||a.flying_flag>=c.count(1)||c.string(a.name).empty()||c.string(a.magicant).empty()||!c.normal_flag_exists(c.string(a.flying_flag))||!std::isfinite(a.map_offset.x)||!std::isfinite(a.map_offset.y))return fail("Field lifecycle AreaRoom rejected");for(float color:a.background)if(!std::isfinite(color)||color<0||color>1)return fail("Field lifecycle AreaRoom color rejected");for(uint32_t k:{7u,8u,9u}){std::unordered_set<std::string_view>keys;for(uint32_t i=0;i<c.count(k);++i){auto r=c.record(k,i);if(u32(r)>=c.count(1)||c.string(u32(r)).empty()||!keys.insert(c.string(u32(r))).second||(k!=9&&(u32(r+4)>=c.count(1)||c.string(u32(r+4)).empty())))return fail("Field lifecycle rule table rejected");if(k==8&&!c.normal_flag_exists(c.string(u32(r+4))))return fail("Field lifecycle visit flag rejected");}}
 for(uint32_t i=0;i<c.count(10);++i){auto r=c.record(10,i);if(!std::isfinite(real(r+4))||!std::isfinite(real(r+8)))return fail("Field lifecycle DebugStart position rejected");}bytes_=std::move(c.bytes_);e.clear();return true;
}
}
