#include "encore/field_dropped.hpp"
#include <algorithm>
#include <cmath>
namespace encore::upstream {namespace {
bool delta_valid(double v){return std::isfinite(v)&&v>=0&&v<=double(.1f);}
bool point_valid(Vec2 v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::abs(v.x)<=1e6&&std::abs(v.y)<=1e6;}
float quart_out(float t){float q=t-1;return -(q*q*q*q-1);}
float elastic_out(float t,float initial,float final,float duration){if(t==0)return initial;if(t==duration)return final;const float normalized=t/duration,period=duration*.3f,shift=period/4;const float difference=float(final-initial);return float(difference*std::pow(2.0,-10*normalized)*std::sin((normalized*duration-shift)*(2*std::acos(-1.0))/period)+difference+initial);}
}
bool validate_dropped_present_bridge(const FieldPresentData&p,const FieldDroppedData&d,std::string&e){if(!p.valid()||!d.valid()||p.source_pin()!=d.source_pin()||p.scene()!=d.scene()||p.pending().size()!=d.bindings().size()){e="Dropped/Present source owner bridge mismatch";return false;}for(const auto&b:d.bindings()){auto record=std::find_if(p.pending().begin(),p.pending().end(),[&](const auto&pending){return pending.id==b.id;});if(record==p.pending().end()||record->node!=b.node||record->ready_ordinal!=b.ready_ordinal||record->script!=d.script()){e="Dropped/Present pending source identity rejected";return false;}if(p.binding(b.id)){e="Dropped duplicate active Present owner";return false;}}e.clear();return true;}
const FieldDroppedState*FieldDroppedRuntime::state(uint32_t id)const{for(const auto&s:states_)if(s.id==id)return&s;return nullptr;}
FieldDroppedState*FieldDroppedRuntime::mutable_state(uint32_t id){for(auto&s:states_)if(s.id==id)return&s;return nullptr;}
bool FieldDroppedRuntime::initialize(const FieldDroppedData&d,FieldDroppedHost h,std::string&e){if(!d.valid()||!h.admit_ready||!h.admit_interaction||!h.read_flag||!h.write_flag||!h.inventory_space||!h.player_paused||!h.select_item||!h.prompt_enabled||!h.prompt_force_show||!h.prompt_visible||!h.prompt_press||!h.prompt_connect_hide_free||!h.prompt_queue_free||!h.prompt_reparent||!h.prompt_position||!h.player_position||!h.publish_position||!h.publish_scale||!h.register_collect_tween||!h.dialogue||!h.queue_free){e="Dropped requires complete typed live source Host";return false;}FieldDroppedRuntime next;next.data_=&d;next.host_=std::move(h);for(const auto&b:d.bindings()){FieldDroppedState s;s.id=b.id;s.position=b.position;s.scale=b.scale;s.blink_speed=d.rules().initial_speed;next.states_.push_back(std::move(s));}*this=std::move(next);e.clear();return true;}
bool FieldDroppedRuntime::ready_sparkles(uint32_t id,SourceRandom&random,std::string&e){if(!data_){e="Dropped unbound";return false;}for(const auto&b:data_->bindings())if(b.sparkles_id==id){auto*s=mutable_state(b.id);if(!s||!s->alive||s->child_ready||s->parent_ready){e="Dropped Sparkles Ready lifecycle";return false;}auto draw=random.rand_range(data_->random_low(),data_->random_high());if(!std::isfinite(draw)||draw<0||draw>=65536){e="Dropped Sparkles draw range";return false;}s->sparkles_frame=std::min(uint32_t(draw),uint32_t(data_->sparkles_frames().size()-1));s->sparkles_timeout=float(1.0/double(float(data_->sparkles_speed()*data_->sparkles_scale())));s->child_ready=true;e.clear();return true;}e="Unknown Dropped Sparkles source child";return false;}
bool FieldDroppedRuntime::queue(FieldDroppedState&s,std::string&e){if(!host_.queue_free(s.id,e))return false;s.queued=true;return true;}
bool FieldDroppedRuntime::ready_item(uint32_t id,std::string&e){auto*s=mutable_state(id);auto*b=data_?data_->binding(id):nullptr;if(!s||!b||!s->alive||!s->child_ready||s->parent_ready){e="Dropped parent Ready source lifecycle";return false;}if(!host_.admit_ready(*b,e))return false;if(!b->can_pickup()&&!host_.prompt_enabled(b->prompt_id,false,e))return false;s->visible=false;bool collected=false;if(!host_.read_flag(*b,collected,e))return false;s->parent_ready=true;if(collected)return queue(*s,e);s->show_wait=true;e.clear();return true;}
bool FieldDroppedRuntime::collect(FieldDroppedState&s,const FieldDroppedBinding&b,std::string&e){if(!host_.prompt_force_show(b.prompt_id,e))return false;bool visible=false;if(!host_.prompt_visible(b.prompt_id,visible,e))return false;if(!visible){if(!host_.prompt_queue_free(b.prompt_id,e))return false;}else{if(!host_.prompt_press(b.prompt_id,e)||!host_.prompt_connect_hide_free(b.prompt_id,e)||!host_.prompt_reparent(b,e)||!host_.prompt_position(b.prompt_id,{b.local_position.x+b.prompt_offset.x,b.local_position.y+b.prompt_offset.y},e))return false;}if(s.collects.size()>=4096){e="Dropped source collection structural limit";return false;}FieldDroppedCollect c;if(!host_.player_position(c.target,e)||!point_valid(c.target)||!host_.register_collect_tween(s.id,c.order,e)||!c.order){if(e.empty())e="Dropped collection target/tween order";return false;}for(const auto&state:states_)for(const auto&job:state.collects)if(job.order==c.order){e="Dropped duplicate scene tween order";return false;}s.collects.push_back(c);return true;}
bool FieldDroppedRuntime::interact(uint32_t id,std::string&e){auto*s=mutable_state(id);auto*b=data_?data_->binding(id):nullptr;if(!s||!b||!s->alive||!s->parent_ready){e="Dropped interaction source lifecycle";return false;}if(!b->can_pickup()){e.clear();return true;}if(!host_.admit_interaction(*b,e))return false;bool opened=false;if(!host_.read_flag(*b,opened,e))return false;if(opened){if(!b->empty.empty())return host_.dialogue(data_->empty_message(),e);e.clear();return true;}auto*item=data_->item(b->item);if(!item){e="Dropped item source definition absent";return false;}bool space=false;if(!host_.inventory_space(space,e))return false;
 if(space||item->keyitem){if(!host_.select_item(*item,true,e)||!collect(*s,*b,e)||!host_.write_flag(*b,true,e)||!host_.dialogue(b->dialogue,e))return false;}
 else{if(s->rotations.size()>=4096){e="Dropped source rotation structural limit";return false;}s->rotations.push_back({});if(!host_.select_item(*item,false,e)||!host_.dialogue(b->full,e))return false;}
 // DroppedItem._check_item resumes after inherited source dialogue call and
 // activates every existing legacy Tween, without resetting their clocks.
 s->tween_active=true;e.clear();return true;
}
bool FieldDroppedRuntime::disappear(uint32_t id,std::string&e){auto*s=mutable_state(id);if(!data_||!s||!s->alive||!s->parent_ready){e="Dropped disappear source lifecycle";return false;}if(s->disappear_waiters.size()>=4096){e="Dropped timer coroutine structural limit";return false;}s->timer_wait=data_->rules().timers[0];s->timer_left=s->timer_wait;s->timer_running=true;bool paused=false;if(!host_.player_paused(paused,e))return false;if(paused)s->timer_paused=true;s->disappear_waiters.push_back(0);e.clear();return true;}
bool FieldDroppedRuntime::player_pause(bool paused,std::string&e){if(!data_){e="Dropped pause unbound";return false;}for(auto&s:states_)if(s.alive&&s.parent_ready)s.timer_paused=paused;e.clear();return true;}
bool FieldDroppedRuntime::idle_signal(std::string&e){if(!data_){e="Dropped idle signal unbound";return false;}for(auto&s:states_)if(s.alive&&s.show_wait){s.show_wait=false;s.visible=true;}e.clear();return true;}
bool FieldDroppedRuntime::timer(FieldDroppedState&s,std::string&e){auto pending=std::move(s.disappear_waiters);s.disappear_waiters.clear();for(auto phase:pending){if(phase>=4){e="Dropped unknown timer coroutine";return false;}if(phase==3){if(!queue(s,e))return false;continue;}if(phase==0){s.blink_playing=true;s.blink_time=0;}else s.blink_speed=data_->rules().speeds[phase-1];s.timer_wait=data_->rules().timers[phase+1];s.timer_left=s.timer_wait;s.timer_running=true;s.disappear_waiters.push_back(phase+1);}return true;}
bool FieldDroppedRuntime::idle_node(uint32_t id,double delta,bool processing,std::string&e){if(!data_||!delta_valid(delta)){e="Dropped idle node delta/source";return false;}for(const auto&b:data_->bindings()){
 unsigned role=id==b.sparkles_id?1:id==b.tween_id?2:id==b.timer_id?3:id==b.animation_id?4:0;if(!role)continue;auto*s=mutable_state(b.id);if(!s||!s->alive){e.clear();return true;}if((role==1&&!s->child_ready)||(role!=1&&!s->parent_ready)){e="Dropped idle node not source Ready";return false;}if(!processing){e.clear();return true;}
 if(role==1){float left=float(delta);while(left){if(s->sparkles_timeout<=0){s->sparkles_timeout=float(1.0/double(float(data_->sparkles_speed()*data_->sparkles_scale())));s->sparkles_frame=s->sparkles_frame>=data_->sparkles_frames().size()-1?0:s->sparkles_frame+1;}auto step=std::min(left,s->sparkles_timeout);left-=step;s->sparkles_timeout-=step;}}
 else if(role==2&&s->tween_active){for(auto&rotation:s->rotations)if(!rotation.finished){const float next=float(rotation.elapsed+float(delta));rotation.elapsed=std::min(next,data_->rules().rotation_duration);rotation.finished=next>data_->rules().rotation_duration;s->sprite_rotation=elastic_out(rotation.elapsed,data_->rules().rotation_from,data_->rules().rotation_to,data_->rules().rotation_duration);}s->rotations.erase(std::remove_if(s->rotations.begin(),s->rotations.end(),[](const auto&j){return j.finished;}),s->rotations.end());if(s->rotations.empty())s->tween_active=false;}
 else if(role==3&&s->timer_running&&!s->timer_paused){s->timer_left-=double(float(delta));if(s->timer_left<0){s->timer_left+=s->timer_wait;if(!timer(*s,e))return false;}}
 else if(role==4&&s->blink_playing){const float advance=float(float(delta)*s->blink_speed);{s->blink_time=std::fmod(float(s->blink_time+advance),data_->rules().blink_length);for(const auto&key:data_->rules().blink_keys)if(key.time<=s->blink_time)s->sprite_visible=key.visible;}}
 e.clear();return true;
 }e="Unknown Dropped idle leaf source ID";return false;
}
bool FieldDroppedRuntime::collect_step(uint32_t id,uint64_t order,double delta,bool processing,std::string&e){auto*s=mutable_state(id);if(!data_||!s||!s->parent_ready||!delta_valid(delta)){e="Dropped collection source clock";return false;}auto j=std::find_if(s->collects.begin(),s->collects.end(),[&](const auto&job){return job.order==order;});if(j==s->collects.end()){e="Unknown Dropped source collection tween";return false;}if(!s->alive||j->finished||!processing){e.clear();return true;}if(!j->started){j->started=true;j->from=s->position;}j->elapsed=float(j->elapsed+float(delta));const auto&r=data_->rules();if(!j->position_done&&j->elapsed>=r.position_delay){const auto time=std::min(float(j->elapsed-r.position_delay),r.position_duration);j->position_done=time>=r.position_duration;const float w=j->position_done?1:quart_out(time/r.position_duration);s->position=j->position_done?j->target:Vec2{j->from.x+(j->target.x-j->from.x)*w,j->from.y+(j->target.y-j->from.y)*w};if(!point_valid(s->position)||!host_.publish_position(id,s->position,e))return false;}if(!j->scale_done){const float time=std::min(j->elapsed,r.scale_duration),normal=time/r.scale_duration,w=normal*normal;j->scale_done=time>=r.scale_duration;s->scale=j->scale_done?r.scale_to:Vec2{r.scale_from.x+(r.scale_to.x-r.scale_from.x)*w,r.scale_from.y+(r.scale_to.y-r.scale_from.y)*w};if(!point_valid(s->scale)||!host_.publish_scale(id,s->scale,e))return false;}if(j->position_done&&j->scale_done){j->finished=true;if(!queue(*s,e))return false;}e.clear();return true;}
bool FieldDroppedRuntime::area_left(bool region_changed,std::string&e){(void)region_changed;if(!data_){e="Dropped area source unbound";return false;}for(const auto&s:states_)if(s.alive&&s.parent_ready){const auto&b=*data_->binding(s.id);if(b.reset_area()&&!host_.write_flag(b,false,e))return false;}e.clear();return true;}
bool FieldDroppedRuntime::exit_tree(uint32_t id,std::string&e){auto*s=mutable_state(id);auto*b=data_?data_->binding(id):nullptr;if(!s||!b||!s->alive){e="Dropped exit source lifecycle";return false;}if(b->reset_consumed()&&!host_.write_flag(*b,false,e))return false;s->alive=false;s->show_wait=s->timer_running=s->blink_playing=s->tween_active=false;s->collects.clear();s->rotations.clear();s->disappear_waiters.clear();e.clear();return true;}
}
