#include "encore/field_payphone.hpp"
#include <cmath>
namespace encore::upstream {
bool FieldPayphoneRuntime::fail(const char*s){error_=s;return false;}bool FieldPayphoneRuntime::effect(bool ok){if(!ok){poisoned_=true;if(error_.empty())error_="Payphone required source effect rejected";}return ok;}
bool FieldPayphoneRuntime::initialize(const FieldPayphoneData&d,FieldPayphoneHost h,std::string&e){if(!d.valid()||!h.bind||!h.read_flag||!h.connect_flags||!h.visibility||!h.queue_free||!h.find_card||!h.lookup_card||!h.reduce_or_drop||!h.read_cash||!h.add_cash||!h.set_stream||!h.play_idle||!h.set_location||!h.box_open||!h.box_update||!h.box_close||!h.audio_play||!h.open_dialogue){e="Payphone actual source consumers incomplete";return false;}if(!h.bind(d,e))return false;data_=&d;host_=std::move(h);instances_.clear();waiters_.clear();poisoned_=had_ready_=false;last_ready_=0;error_.clear();e.clear();return true;}
FieldPayphoneInstance*FieldPayphoneRuntime::get(uint32_t id,bool ready){if(!data_||poisoned_){fail("Payphone runtime unavailable");return nullptr;}auto i=instances_.find(id);if(i==instances_.end()||(ready&&!i->second.ready)||i->second.deleted){fail("Payphone source instance unavailable");return nullptr;}return&i->second;}
const FieldPayphoneInstance*FieldPayphoneRuntime::instance(uint32_t id)const{auto i=instances_.find(id);return i==instances_.end()?nullptr:&i->second;}
bool FieldPayphoneRuntime::create(uint32_t id){if(!data_||poisoned_||!data_->record(id)||instances_.count(id))return fail("Payphone source factory identity rejected");FieldPayphoneInstance s;s.id=id;instances_.emplace(id,s);return true;}
bool FieldPayphoneRuntime::flags_updated(uint32_t id){auto s=get(id,false);if(!s)return false;auto d=data_->record(id);bool shown=true,present=false,value=false;if(!d->appear.empty()){if(!effect(host_.read_flag(d->appear,present,value,error_)))return false;shown=present&&value;}if(!d->disappear.empty()){if(!effect(host_.read_flag(d->disappear,present,value,error_)))return false;shown=shown&&!(present&&value);}s->visible=shown;if(!effect(host_.visibility(id,shown,error_)))return false;if(!shown){if(!effect(host_.queue_free(id,error_)))return false;s->queued=true;}return true;}
bool FieldPayphoneRuntime::ready(uint32_t id){auto s=get(id,false);auto d=data_?data_->record(id):nullptr;if(!s||!d||s->ready||(had_ready_&&d->ready_ordinal<=last_ready_))return fail("Payphone source Ready order rejected");if(!flags_updated(id)||!effect(host_.connect_flags(id,[this,id]{return flags_updated(id);},error_)))return false;s->ready=true;last_ready_=d->ready_ordinal;had_ready_=true;return true;}
bool FieldPayphoneRuntime::dialogue(const FieldPayphoneDescriptor&d,std::string&out){out=d.dialogue;for(const auto&b:d.dispatch){if(b.flag.empty())continue;bool present=false,value=false;if(!effect(host_.read_flag(b.flag,present,value,error_)))return false;if(present&&value)out=b.program;}return true;}
bool FieldPayphoneRuntime::use(uint32_t id,const FieldPayphoneCard&card){auto s=get(id);if(!s)return false;auto d=data_->record(id);const bool present=!card.name.empty();if(!present&&(card.uid||card.doses))return fail("Payphone null item identity malformed");if(present&&(card.name!=data_->card_name()||!card.doses||card.doses>data_->card_max_doses()))return fail("Payphone actual PhoneCard UID/doses rejected");if(!effect(host_.set_stream(d->audio_id,data_->sound(),error_))||!effect(host_.play_idle(id,data_->idle_frame(),error_))||!effect(host_.set_location(d->location,error_)))return false;uint64_t box=0;if(!effect(host_.box_open(present,box,error_)))return false;if(!box){poisoned_=true;return fail("Payphone source amount box identity absent");}waiters_.push_back({box,data_->update_seconds(),true});if(present){std::string program;if(!effect(host_.audio_play(d->audio_id,error_))||!dialogue(*d,program)||!effect(host_.open_dialogue(id,program,error_)))return false;return effect(host_.reduce_or_drop(card.uid,data_->card_step(),error_));}int64_t cash=0;if(!effect(host_.read_cash(cash,error_)))return false;if(cash>=data_->cash_cost()){std::string program;if(!effect(host_.audio_play(d->audio_id,error_))||!dialogue(*d,program)||!effect(host_.open_dialogue(id,program,error_)))return false;return effect(host_.add_cash(-int64_t(data_->cash_cost()),error_));}return effect(host_.open_dialogue(id,data_->no_money_program(),error_));}
bool FieldPayphoneRuntime::interact(uint32_t id){if(!get(id))return false;FieldPayphoneCard card;if(!effect(host_.find_card(data_->card_name(),card,error_)))return false;return use(id,card);}
bool FieldPayphoneRuntime::interact_item(uint32_t id,uint64_t uid){if(!get(id))return false;FieldPayphoneCard card;if(!effect(host_.lookup_card(uid,card,error_)))return false;if(card.name.empty()||card.uid!=uid)return fail("Payphone selected UID ownership rejected");if(card.name!=data_->record(id)->item)return true;return use(id,card);}
bool FieldPayphoneRuntime::idle_frame(float dt){if(!data_||poisoned_||!std::isfinite(dt)||dt<0||dt>60)return fail("Payphone source SceneTree timer delta rejected");for(auto i=waiters_.begin();i!=waiters_.end();){i->left-=dt;if(i->left>=0){++i;continue;}if(i->update){if(!effect(host_.box_update(i->box,error_)))return false;i->update=false;i->left=data_->close_seconds();++i;}else{if(!effect(host_.box_close(i->box,error_)))return false;i=waiters_.erase(i);}}return true;}
bool FieldPayphoneRuntime::commit_deleted(uint32_t id){auto s=get(id,false);if(!s||!s->queued||s->deleted)return fail("Payphone source deferred deletion not queued");s->deleted=true;return true;}
}
