#include "encore/field_camera_arrows.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <set>
namespace encore::upstream {namespace {
uint32_t word(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;while(n--){c^=*p++;for(unsigned i=0;i<8;++i)c=(c>>1)^((c&1)?0xedb88320u:0u);}return ~c;}
struct Reader {const uint8_t*p;size_t n,at=128;bool ok=true;
 uint32_t integer(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=word(p+at);at+=4;return v;}
 int32_t signed_integer(){auto v=integer();int32_t out;std::memcpy(&out,&v,4);return out;}
 float scalar(){auto v=integer();float f;std::memcpy(&f,&v,4);if(!std::isfinite(f)||std::abs(f)>=1000000)ok=false;return f;}
 Vec2 vector(){float x=scalar(),y=scalar();return {x,y};}
 bool boolean(){auto v=integer();if(v>1)ok=false;return v!=0;}
 std::string text(){auto length=integer();if(!ok||length>65536||at>n||length>n-at){ok=false;return{};}std::string s(reinterpret_cast<const char*>(p+at),length);at+=length;size_t count=0;if(s.find('\0')!=s.npos||!utf8_count(s,count))ok=false;return s;}
 std::array<uint8_t,32>hash(){std::array<uint8_t,32>h{};if(!ok||at>n||n-at<32){ok=false;return h;}std::copy_n(p+at,32,h.begin());at+=32;if(std::all_of(h.begin(),h.end(),[](uint8_t v){return !v;}))ok=false;return h;}
};
bool path(std::string_view s){if(s.empty()||s.front()=='/'||s.back()=='/'||s.find('\\')!=s.npos||s.find(':')!=s.npos)return false;size_t b=0;while(b<s.size()){auto e=s.find('/',b);if(e==s.npos)e=s.size();auto v=s.substr(b,e-b);if(v.empty()||v=="."||v=="..")return false;b=e+1;}return true;}
}
const FieldArrowRoot*FieldCameraArrowsData::record(uint32_t id)const{for(const auto&r:roots_)if(r.id==id)return &r;return nullptr;}
const FieldArrowSprite*FieldCameraArrowsData::sprite(uint32_t id)const{for(const auto&r:sprites_)if(r.id==id)return &r;return nullptr;}
const FieldArrowPlayer*FieldCameraArrowsData::player(uint32_t id)const{for(const auto&r:players_)if(r.id==id)return &r;return nullptr;}
const FieldArrowPlayer*FieldCameraArrowsData::player_for_target(uint32_t id)const{for(const auto&r:players_)if(r.target_root==id)return &r;return nullptr;}
const FieldArrowClip*FieldCameraArrowsData::clip(uint32_t profile,uint32_t role)const{if(profile>=profiles_.size())return nullptr;for(const auto&r:profiles_[profile])if(r.role==role)return &r;return nullptr;}
bool FieldCameraArrowsData::source_hash(std::string_view p,std::array<uint8_t,32>&h)const{auto it=sources_.find(std::string(p));if(it==sources_.end())return false;h=it->second;return true;}
bool FieldCameraArrowsData::load_file(const char*p,const FieldIdentity&id,std::string&e){if(!p||!*p){e="Camera arrows path rejected";return false;}FILE*f=std::fopen(p,"rb");if(!f){e="Cannot open Camera arrows";return false;}if(std::fseek(f,0,SEEK_END)){std::fclose(f);e="Camera arrows seek rejected";return false;}long n=std::ftell(f);if(n<128||n>4*1024*1024||std::fseek(f,0,SEEK_SET)){std::fclose(f);e="Camera arrows size rejected";return false;}std::vector<uint8_t>b(static_cast<size_t>(n));auto got=std::fread(b.data(),1,b.size(),f);bool closed=std::fclose(f)==0;if(got!=b.size()||!closed){e="Camera arrows read rejected";return false;}return load(b.data(),b.size(),id,e);}
bool FieldCameraArrowsData::load(const uint8_t*p,size_t n,const FieldIdentity&id,std::string&e){
 auto reject=[&](const char*s){e=s;return false;};
 if(!p||n<128||n>4*1024*1024)return reject("Camera arrows size rejected");
 if(std::memcmp(p,"ENCFARR1",8)||word(p+8)!=1||word(p+12)!=128||word(p+16)!=n||word(p+24)!=0x454e0030||word(p+28)!=3||!word(p+32)||word(p+32)>10000||!id.scene_id||word(p+36)!=id.scene_id||std::memcmp(p+40,id.upstream_commit.data(),20)||std::memcmp(p+60,id.source_sha256.data(),32)||word(p+124))return reject("Camera arrows identity/version/capability rejected");
 if(crc(p+128,n-128)!=word(p+20)||std::all_of(p+92,p+124,[](uint8_t v){return !v;}))return reject("Camera arrows CRC/IR rejected");
 FieldCameraArrowsData d;d.identity_=id;Reader r{p,n};d.scene_=r.text();d.script_=r.text();d.pixel_snap_=r.boolean();std::set<std::pair<int,int>>directions;
 for(auto&v:d.directions_){v=r.vector();if(!r.ok||std::abs(v.x)+std::abs(v.y)!=1||std::floor(v.x)!=v.x||std::floor(v.y)!=v.y||!directions.emplace(int(v.x),int(v.y)).second)return reject("Camera arrows direction identity rejected");}
 auto&a=d.asset_;a.source=r.text();a.path=r.text();a.width=r.integer();a.height=r.integer();a.bytes=r.integer();a.crc=r.integer();a.source_sha=r.hash();a.output_sha=r.hash();if(!r.ok||!path(d.scene_)||!path(d.script_)||!path(a.source)||!path(a.path)||a.path.substr(0,9)!="graphics/"||a.path.size()<5||a.path.substr(a.path.size()-4)!=".t3x"||!a.width||!a.height||a.width>1024||a.height>1024||!a.bytes||a.bytes>16*1024*1024)return reject("Camera arrows atlas/path rejected");
 auto&program=d.program_;program.source=r.text();program.path=r.text();program.bytes=r.integer();program.crc=r.integer();program.source_sha=r.hash();program.output_sha=r.hash();if(!r.ok||!path(program.source)||!path(program.path)||program.path.substr(0,8)!="shaders/"||program.path.size()<7||program.path.substr(program.path.size()-6)!=".shbin"||!program.bytes||program.bytes>1024*1024)return reject("Camera arrows GPU program rejected");
 auto frames=r.integer();if(!r.ok||!frames||frames>4096)return reject("Camera arrows frame count rejected");for(uint32_t i=0;i<frames;++i){std::array<float,4>f{};for(auto&v:f){v=r.scalar();if(std::floor(v)!=v||v<0)r.ok=false;}if(!r.ok||f[2]<=0||f[3]<=0||f[0]>a.width||f[1]>a.height||f[2]>a.width-f[0]||f[3]>a.height-f[1])return reject("Camera arrows atlas bounds rejected");d.frames_.push_back(f);}
 auto profiles=r.integer();if(!r.ok||!profiles||profiles>256)return reject("Camera arrows profile count rejected");for(uint32_t j=0;j<profiles;++j){auto count=r.integer();if(!r.ok||count!=3)return reject("Camera arrows clip roster rejected");std::vector<FieldArrowClip>out;std::set<std::string>names;
  for(uint32_t i=0;i<count;++i){FieldArrowClip c;c.role=r.integer();c.name=r.text();c.length=r.scalar();c.loop=r.boolean();auto tracks=r.integer();if(!r.ok||c.role!=i+1||c.name.empty()||!names.insert(c.name).second||c.length<=0||c.length>65536||c.loop||!tracks||tracks>32)return reject("Camera arrows clip rejected");std::set<std::pair<uint32_t,uint32_t>>targets;
   for(uint32_t k=0;k<tracks;++k){FieldArrowTrack t;t.target=r.integer();auto property=r.integer();t.property=static_cast<FieldArrowProperty>(property);t.update=r.integer();auto keys=r.integer();if(!r.ok||t.target>4||property<1||property>5||!targets.emplace(t.target,property).second||t.update>1||!keys||keys>4096||((property==1||property==3||property==5)&&t.update==0&&keys!=1))return reject("Camera arrows track rejected");float previous=-1;
    for(uint32_t a=0;a<keys;++a){FieldArrowKey key;key.time=r.scalar();key.transition=r.scalar();key.value=r.vector();if(!r.ok||key.time<0||key.time>c.length||key.time<=previous||((property==1||property==3||property==5)&&(key.value.y!=0||std::floor(key.value.x)!=key.value.x))||(property==1&&(key.value.x<0||key.value.x>=frames))||((property==3||property==5)&&(key.value.x<0||key.value.x>1)))return reject("Camera arrows key rejected");previous=key.time;t.keys.push_back(key);}c.tracks.push_back(std::move(t));}out.push_back(std::move(c));}d.profiles_.push_back(std::move(out));}
 auto sprites=r.integer(),players=r.integer();auto roots=word(p+32);if(!r.ok||sprites!=roots*4||players!=roots*5)return reject("Camera arrows topology count rejected");std::set<uint32_t>ids;std::set<std::string>nodes;uint32_t previous=0;
 auto color=[&](std::array<float,4>&v){for(auto&c:v){c=r.scalar();if(c<0||c>1)r.ok=false;}};
 for(uint32_t i=0;i<roots;++i){FieldArrowRoot a;a.id=r.integer();a.ready=r.integer();a.parent_id=r.integer();for(auto&v:a.arrows)v=r.integer();a.visible=r.boolean();a.z_relative=r.boolean();a.pause=r.integer();a.z=r.signed_integer();a.priority=r.signed_integer();a.position=r.vector();color(a.modulate);color(a.self_modulate);a.node=r.text();if(!r.ok||!a.id||!a.parent_id||a.id==a.parent_id||!ids.insert(a.id).second||!nodes.insert(a.node).second||!path(a.node)||(i&&a.ready<=previous)||a.pause>2||a.z< -4096||a.z>4096)return reject("Camera arrows root/order rejected");previous=a.ready;d.roots_.push_back(std::move(a));}
 for(uint32_t i=0;i<sprites;++i){FieldArrowSprite a;a.id=r.integer();a.root_id=r.integer();a.ready=r.integer();a.direction=r.integer();a.frame=r.integer();a.flags=r.integer();a.pause=r.integer();a.priority=r.signed_integer();a.position=r.vector();a.offset=r.vector();a.scale=r.vector();a.rotation=r.scalar();a.speed_scale=r.scalar();a.animation_speed=r.scalar();color(a.modulate);color(a.self_modulate);auto*root=d.record(a.root_id);if(!r.ok||!a.id||!ids.insert(a.id).second||!root||a.direction>3||root->arrows[a.direction]!=a.id||a.ready>=root->ready||a.frame>=frames||a.flags>7||a.pause>2||a.scale.x<=0||a.scale.y<=0||a.speed_scale<=0||a.animation_speed<=0||a.speed_scale*a.animation_speed>1024)return reject("Camera arrows source sprite rejected");d.sprites_.push_back(std::move(a));}
 std::set<uint32_t>assigned;for(uint32_t i=0;i<players;++i){FieldArrowPlayer a;a.id=r.integer();a.ready=r.integer();a.target_root=r.integer();a.kind=r.integer();a.profile=r.integer();a.pause=r.integer();a.priority=r.signed_integer();a.speed=r.scalar();auto*root=d.record(a.target_root);auto*sprite=d.sprite(a.target_root);if(!r.ok||!a.id||!ids.insert(a.id).second||!assigned.insert(a.target_root).second||a.kind>1||a.profile>=profiles||a.pause>2||a.speed<=0||a.speed>1024||(a.kind==0?(!root||a.ready>=root->ready):(!sprite||a.ready>=sprite->ready)))return reject("Camera arrows source AnimationPlayer rejected");for(const auto&c:d.profiles_[a.profile])for(const auto&t:c.tracks){uint32_t prop=uint32_t(t.property);if(a.kind==1?(t.target!=0||prop>3):(t.target==0?prop!=5:(prop!=1&&prop!=3&&prop!=4)))return reject("Camera arrows unsupported target mechanism rejected");}d.players_.push_back(std::move(a));}
 auto proofs=r.integer();if(!r.ok||!proofs||proofs>10000)return reject("Camera arrows proof count rejected");for(uint32_t i=0;i<proofs;++i){auto name=r.text();auto h=r.hash();if(!r.ok||!path(name)||!d.sources_.emplace(name,h).second)return reject("Camera arrows proof rejected");}
 std::array<uint8_t,32>h{};if(!r.ok||r.at!=n||!d.source_hash(d.scene_,h)||h!=id.source_sha256||!d.source_hash(d.script_,d.script_sha_)||!d.source_hash(d.asset_.source,h)||h!=d.asset_.source_sha)return reject("Camera arrows source/trailing rejected");d.valid_=true;*this=std::move(d);e.clear();return true;
}
}
