#include "encore/field_emotes.hpp"
#include <algorithm>
#include <cmath>
#include <utility>
namespace encore::upstream {namespace {bool finite(Vec2 v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::abs(v.x)<=1000000&&std::abs(v.y)<=1000000;}}
bool FieldEmoteRuntime::fail(const char*e){error_=e;return false;}
bool FieldEmoteRuntime::initialize(const FieldEmoteData&data,FieldEmoteHost host,std::string&e){if(!data.valid()||!host.resolve_object||!host.resolve_direction||!host.texture_geometry||!host.direction||!host.publish||!host.sound_stream||!host.sound_playing||!host.animation_finished){e="Emotes source data/typed Host incomplete";return false;}data_=&data;host_=std::move(host);instances_.clear();error_.clear();last_ready_=0;had_ready_=false;e.clear();return true;}
const FieldEmoteInstance*FieldEmoteRuntime::instance(uint32_t id)const{auto i=instances_.find(id);return i==instances_.end()?nullptr:&i->second;}
FieldEmoteInstance*FieldEmoteRuntime::get(uint32_t id){auto i=instances_.find(id);if(i==instances_.end()||!i->second.ready){fail("Emotes operation before source Ready");return nullptr;}return&i->second;}
bool FieldEmoteRuntime::publish(FieldEmoteInstance&s){return host_.publish(s.id,s,error_);}
bool FieldEmoteRuntime::create(uint32_t id){if(!data_||instances_.count(id))return fail("Emotes duplicate/uninitialized creation");const auto*d=data_->record(id);if(!d)return fail("Emotes unknown source identity");FieldEmoteInstance s;s.id=id;s.position=d->position;s.offset=d->offset;s.scale=d->scale;s.frame=d->frame;s.visible=(d->flags&1)!=0;s.sound_id=data_->default_sound();instances_.emplace(id,s);return true;}
bool FieldEmoteRuntime::ready(uint32_t id){auto i=instances_.find(id);if(i==instances_.end()||i->second.ready)return fail("Emotes source Ready missing/duplicate");const auto*d=data_->record(id);if(had_ready_&&d->ready_ordinal<=last_ready_)return fail("Emotes Ready violates actual postorder");bool exists=false;uint32_t object=0;if(!host_.resolve_object(*d,exists,object,error_))return false;if((exists&&(!d->object_id||object!=d->object_id))||(!exists&&object))return fail("Emotes source nullable object identity mismatch");auto&s=i->second;s.object=object;s.ready=true;last_ready_=d->ready_ordinal;had_ready_=true;return publish(s);}
bool FieldEmoteRuntime::set_bubble_offset(uint32_t id){auto*s=get(id);if(!s)return false;if(!s->object)return fail("Source emotes bubble setter has null object");uint32_t height=0,rows=0;if(!host_.texture_geometry(s->object,height,rows,error_))return false;if(!height||height>16384||!rows||rows>1024)return fail("Source emotes texture geometry rejected");
 // Both source operands are integer properties: Godot performs integer division
 // before adding the source gap. Do not substitute floating atlas cell geometry.
 s->position.y=-(float(height/rows)+data_->bubble_gap());return publish(*s);}
bool FieldEmoteRuntime::sprite_changed(uint32_t sprite){bool connected=false;for(const auto&d:data_->records())if(d.object_id==sprite&&d.object_id){connected=true;if(!set_bubble_offset(d.id))return false;}return connected?true:fail("Sprite changed has no admitted source emotes receiver");}
bool FieldEmoteRuntime::play(uint32_t id,const std::string&name){if(!data_)return fail("Emotes runtime not initialized");auto*c=data_->clip(name);return c?play(id,c->id):fail("Emotes unadmitted source animation name");}
bool FieldEmoteRuntime::play(uint32_t id,uint32_t clip){auto*s=get(id);if(!s)return false;const auto*a=data_->clip(clip);if(!a)return fail("Emotes unknown source clip");const auto*d=data_->record(id);
 // AnimationPlayer assigned-name semantics retain the clock on repeated play,
 // resetting only on another assigned clip or when the old clip already ended.
 if(s->clip_id!=clip||s->elapsed==a->length){s->elapsed=0;}s->clip_id=clip;s->playing=true;s->started=true;
 if(a->direction_sensitive){uint32_t source=0;if(!d->direction_id)return fail("Source directional emote has no get_direction ancestor");if(!host_.resolve_direction(*d,source,error_))return false;if(source!=d->direction_id)return fail("Emotes direction ancestor identity mismatch");Vec2 direction{};if(!host_.direction(source,direction,error_))return false;if(!finite(direction))return fail("Emotes source direction vector rejected");s->direction_source=source;if(direction.x<0)s->scale.x=-1;}
 else s->scale.x=1;
 if(!publish(*s)){return false;}
 return !host_.native_animation||host_.native_animation(id,clip,1,error_);/* synchronous source animation_started; no track update yet */
}
bool FieldEmoteRuntime::apply(FieldEmoteInstance&s,const FieldEmoteTrack&t,const FieldEmoteKey&k){switch(t.property){case FieldEmoteProperty::Frame:{const auto*d=data_->record(s.id);if(k.integer>=d->columns*d->rows)return fail("Emotes source frame outside grid");if(host_.native_frame&&!host_.native_frame(s.id,k.integer,error_))return false;s.frame=k.integer;return true;}case FieldEmoteProperty::Offset:if(!finite(k.vector))return fail("Emotes offset interpolation rejected");s.offset=k.vector;return true;case FieldEmoteProperty::Stream:{const auto*sound=data_->sound(k.integer);if(!sound)return fail("Emotes source audio stream lost");if(!host_.sound_stream(s.id,*sound,error_))return false;s.sound_id=k.integer;s.sound_playing=false;return true;}case FieldEmoteProperty::Playing:{const auto*sound=data_->sound(s.sound_id);if(!sound)return fail("Emotes source current stream lost");if(!host_.sound_playing(s.id,*sound,k.integer!=0,error_))return false;s.sound_playing=k.integer!=0;return true;}}return fail("Emotes unknown source property");}
bool FieldEmoteRuntime::interpolate(FieldEmoteInstance&s,const FieldEmoteTrack&t,float time,bool started){const auto&keys=t.keys;if(t.update==2){if(started||!s.capture_valid){s.capture_offset=s.offset;s.capture_valid=true;}size_t first=0;if(keys.front().time==0){if(keys.size()==1)return true;first=1;}if(time<keys[first].time){float c=time/keys[first].time;FieldEmoteKey value;value.vector={s.capture_offset.x+(keys[first].vector.x-s.capture_offset.x)*c,s.capture_offset.y+(keys[first].vector.y-s.capture_offset.y)*c};return apply(s,t,value);}}
 if(keys.size()==1){return apply(s,t,keys.front());}size_t index=0;if(time<keys.front().time)return true;while(index+1<keys.size()&&keys[index+1].time<=time)++index;auto value=keys[index];if(t.update!=1&&t.property==FieldEmoteProperty::Offset&&index+1<keys.size()){auto next=keys[index+1];float distance=next.time-value.time;const float c=distance<=0?0:(time-value.time)/distance;value.vector={value.vector.x+(next.vector.x-value.vector.x)*c,value.vector.y+(next.vector.y-value.vector.y)*c};}return apply(s,t,value);
}
bool FieldEmoteRuntime::idle_frame(uint32_t id,float dt){auto*s=get(id);if(!s)return false;if(!std::isfinite(dt)||dt<0||dt>60)return fail("Emotes source idle delta rejected");if(!s->playing)return true;const auto*a=data_->clip(s->clip_id);if(!a)return fail("Emotes playing source clip lost");const float from=s->elapsed,to=std::min(a->length,float(from+dt));const float delta=to-from;
 for(const auto&t:a->tracks){if(t.update==1&&delta!=0){const float until=from!=a->length&&to==a->length?a->length*1.001f:to;for(const auto&k:t.keys)if(k.time>=from&&k.time<until){if(!apply(*s,t,k))return false;}}else if(!interpolate(*s,t,to,s->started))return false;}
 s->elapsed=to;s->started=false;if(!publish(*s))return false;if(to==a->length){s->playing=false;if(from<a->length){if(host_.native_animation&&!host_.native_animation(id,a->id,2,error_))return false;if(!host_.animation_finished(id,*a,error_))return false;}}return true;
}
bool FieldEmoteRuntime::seek(uint32_t id,float time,bool update){auto*s=get(id);if(!s)return false;const auto*a=data_->clip(s->clip_id);if(!a||!std::isfinite(time)||time<0||time>a->length)return fail("Emotes source seek rejected");s->elapsed=time;if(update){for(const auto&t:a->tracks)if(!interpolate(*s,t,time,false))return false;return publish(*s);}return true;}
bool FieldEmoteRuntime::stop(uint32_t id,bool reset){auto*s=get(id);if(!s)return false;s->playing=false;if(reset)s->elapsed=0;return !host_.native_animation||host_.native_animation(id,s->clip_id,3,error_);/* value tracks do not reset their target properties */}
bool FieldEmoteRuntime::visibility(uint32_t id,bool visible){auto*s=get(id);if(!s)return false;s->visible=visible;return publish(*s);}
bool FieldEmoteRuntime::audio_finished(uint32_t id){auto*s=get(id);if(!s)return false;s->sound_playing=false;return true;}
bool FieldEmoteRuntime::is_playing(uint32_t id)const{const auto*s=instance(id);return s&&s->ready&&s->playing;}
bool FieldEmoteRuntime::destroy(uint32_t id){auto*s=get(id);if(!s)return false;if(s->sound_playing){const auto*sound=data_->sound(s->sound_id);if(!sound||!host_.sound_playing(id,*sound,false,error_))return false;}instances_.erase(id);return true;}
}
