#include "encore/field_butterfly.hpp"
#include "encore/utf8.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <set>
namespace encore::upstream {namespace {
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=i>=16&&i<20?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
struct Reader{const uint8_t*p;size_t n,at=64;bool ok=true;uint32_t integer(){if(!ok||at>n||n-at<4){ok=false;return 0;}auto v=u32(p+at);at+=4;return v;}float scalar(){auto u=integer();float v;std::memcpy(&v,&u,4);if(!std::isfinite(v)||std::abs(v)>1e6)ok=false;return v;}double real(){if(!ok||at>n||n-at<8){ok=false;return 0;}uint64_t bits=uint64_t(u32(p+at))|uint64_t(u32(p+at+4))<<32;at+=8;double v;std::memcpy(&v,&bits,8);if(!std::isfinite(v)||std::abs(v)>1e6)ok=false;return v;}Vec2 point(){return{scalar(),scalar()};}BattleValue rect(){return{scalar(),scalar(),scalar(),scalar()};}std::string text(){auto len=integer();if(!ok||len>8192||at>n||len>n-at){ok=false;return{};}std::string v(reinterpret_cast<const char*>(p+at),len);at+=len;size_t i=0;uint32_t cp;while(i<v.size())if(!encore::utf8_next(v,i,cp)||cp<32){ok=false;break;}return v;}bool hash(std::array<uint8_t,32>&out){if(!ok||at>n||n-at<32){ok=false;return false;}bool any=false;for(unsigned i=0;i<32;++i){any|=p[at+i]!=0;out[i]=p[at+i];}at+=32;return ok&=any;}};
bool path(std::string_view p){return!p.empty()&&p.front()!='/'&&p.back()!='/'&&p.find("..") ==p.npos&&p.find(':')==p.npos&&p.find('\\')==p.npos;}
}
bool FieldButterflyData::source_hash(std::string_view path_,std::array<uint8_t,32>&out)const{auto i=sources_.find(std::string(path_));if(i==sources_.end())return false;out=i->second;return true;}
const FieldButterflyBinding*FieldButterflyData::binding(uint32_t id)const{for(const auto&v:bindings_)if(v.id==id)return&v;return nullptr;}
const FieldButterflyAsset*FieldButterflyData::asset(uint32_t index)const{for(const auto&v:assets_)if(v.index==index)return&v;return nullptr;}
const FieldButterflyClip*FieldButterflyData::clip(uint32_t role)const{for(const auto&v:clips_)if(v.role==role)return&v;return nullptr;}
bool FieldButterflyData::load_file(const char*p,std::string&e){if(!p){e="Butterfly file path absent";return false;}std::ifstream f(p,std::ios::binary);if(!f){e="Butterfly file unavailable";return false;}f.seekg(0,std::ios::end);auto n=f.tellg();if(n<64||n>4*1024*1024){e="Butterfly file size";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)){e="Butterfly file read";return false;}return load(b.data(),b.size(),e);}
bool FieldButterflyData::load(const uint8_t*p,size_t n,std::string&e){auto reject=[&](const char*m){e=m;return false;};if(!p||n<64||n>4*1024*1024)return reject("Butterfly pack size");if(std::memcmp(p,"ENCFLY01",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+20)!=1||u32(p+24)!=1||!u32(p+28)||u32(p+28)>4096||u32(p+16)!=crc(p,n))return reject("Butterfly header/version/capability/rules/CRC");for(size_t i=52;i<64;++i)if(p[i])return reject("Butterfly reserved header");FieldButterflyData d;std::copy(p+32,p+52,d.pin_.begin());if(std::all_of(d.pin_.begin(),d.pin_.end(),[](uint8_t b){return!b;}))return reject("Butterfly source pin absent");Reader r{p,n};d.scene_=r.text();d.script_=r.text();d.modulus_=r.integer();d.frames_=r.integer();auto snap=r.integer();d.pixel_snap_=snap!=0;d.speed_=r.scalar();d.fly_seek_=r.real();d.orbit_seek_=r.real();if(!r.ok||snap>1||!path(d.scene_)||!path(d.script_)||!d.modulus_||d.modulus_>256||!d.frames_||d.frames_>1024||d.speed_<=0||d.speed_>65535||d.fly_seek_<0||d.fly_seek_>3600||d.orbit_seek_<0||d.orbit_seek_>3600)return reject("Butterfly source motion/RNG rules");auto count=r.integer();if(count!=2)return reject("Butterfly animation capability");std::set<uint32_t>ids;std::set<std::string>names;for(uint32_t i=0;i<count;++i){FieldButterflyClip c;c.role=r.integer();c.name=r.text();c.length=r.scalar();auto tracks=r.integer();if(!r.ok||c.role<1||c.role>2||!ids.insert(c.role).second||c.name.empty()||!names.insert(c.name).second||c.length<=0||c.length>60||!tracks||tracks>16)return reject("Butterfly source clips");std::set<uint32_t>roles;for(uint32_t j=0;j<tracks;++j){FieldButterflyTrack t;t.role=r.integer();auto discrete=r.integer();t.discrete=discrete!=0;auto keys=r.integer();if(!r.ok||t.role<1||t.role>4||!roles.insert(t.role).second||discrete>1||t.discrete!=(t.role<=2)||!keys||keys>4096)return reject("Butterfly source track capability");float last=-1;for(uint32_t k=0;k<keys;++k){FieldButterflyKey v;v.time=r.scalar();v.transition=r.scalar();v.value=r.point();if(!r.ok||v.time<0||v.time<=last||v.time>c.length||std::abs(v.transition)>1024||(t.role==1&&(v.value.x<0||v.value.x>=d.frames_||std::floor(v.value.x)!=v.value.x||v.value.y!=0))||(t.role==2&&((v.value.x!=0&&v.value.x!=1)||v.value.y!=0)))return reject("Butterfly source animation key");last=v.time;t.keys.push_back(v);}c.tracks.push_back(std::move(t));}d.clips_.push_back(std::move(c));}
 count=r.integer();if(count!=d.modulus_)return reject("Butterfly texture/RNG modulus mismatch");ids.clear();names.clear();for(uint32_t i=0;i<count;++i){FieldButterflyAsset a;a.index=r.integer();a.width=r.integer();a.height=r.integer();a.bytes=r.integer();a.crc=r.integer();a.source=r.text();a.path=r.text();if(!r.ok||a.index>=d.modulus_||!ids.insert(a.index).second||!a.width||a.width>4096||a.width%d.frames_||!a.height||a.height>4096||!a.bytes||a.bytes>16*1024*1024||!a.crc||!path(a.source)||!path(a.path)||!names.insert(a.path).second)return reject("Butterfly source texture receipt");d.assets_.push_back(std::move(a));}
 count=r.integer();if(count!=u32(p+28))return reject("Butterfly source object count");ids.clear();names.clear();std::set<uint32_t>ordinals;uint32_t previous=0;for(uint32_t i=0;i<count;++i){FieldButterflyBinding b;b.id=r.integer();b.ready_ordinal=r.integer();b.timer_id=r.integer();b.timer_ordinal=r.integer();b.fly_id=r.integer();b.fly_ordinal=r.integer();b.orbit_id=r.integer();b.orbit_ordinal=r.integer();b.area_id=r.integer();b.notifier_id=r.integer();b.enabler_id=r.integer();b.frame=r.integer();auto flip=r.integer();b.flip=flip!=0;b.area_layer=r.integer();b.area_mask=r.integer();b.area_flags=r.integer();b.node=r.text();b.parent_scale=r.scalar();b.timer_wait=r.scalar();b.fly_speed=r.scalar();b.orbit_speed=r.scalar();b.area_radius=r.scalar();b.position=r.point();b.parent_origin=r.point();b.sprite_position=r.point();b.sprite_offset=r.point();b.color=r.rect();b.area_center=r.point();b.notifier=r.rect();b.enabler=r.rect();if(!r.ok||flip>1||b.area_flags>3||!path(b.node)||!names.insert(b.node).second||b.frame>=d.frames_||b.parent_scale<=0||b.parent_scale>1024||b.timer_wait<=0||b.timer_wait>3600||b.fly_speed<0||b.fly_speed>1024||b.orbit_speed<0||b.orbit_speed>1024||b.area_radius<=0||b.area_radius>65535||b.notifier.z<=0||b.notifier.w<=0||b.enabler.z<=0||b.enabler.w<=0||(i&&b.ready_ordinal<=previous))return reject("Butterfly source instance policy/geometry");for(float v:{b.color.x,b.color.y,b.color.z,b.color.w})if(v<0||v>1)return reject("Butterfly source sprite color");for(auto id:{b.id,b.timer_id,b.fly_id,b.orbit_id,b.area_id,b.notifier_id,b.enabler_id})if(!id||!ids.insert(id).second)return reject("Butterfly source child identity");for(auto at:{b.ready_ordinal,b.timer_ordinal,b.fly_ordinal,b.orbit_ordinal})if(!ordinals.insert(at).second)return reject("Butterfly source Ready ordinal duplicate");for(auto at:{b.timer_ordinal,b.fly_ordinal,b.orbit_ordinal})if(at>=b.ready_ordinal)return reject("Butterfly source child-before-parent Ready");previous=b.ready_ordinal;d.bindings_.push_back(std::move(b));}
 count=r.integer();if(!count||count>2048)return reject("Butterfly source receipt count");names.clear();for(uint32_t i=0;i<count;++i){auto s=r.text();if(!r.ok||!path(s)||!names.insert(s).second||!r.hash(d.sources_[s]))return reject("Butterfly source receipt hash");}if(!names.count(d.scene_)||!names.count(d.script_))return reject("Butterfly source closure");for(const auto&a:d.assets_)if(!names.count(a.source))return reject("Butterfly art source closure");if(!r.ok||r.at!=n)return reject("Butterfly trailing bytes");d.valid_=true;*this=std::move(d);e.clear();return true;
}
}
