#include "encore/field_camera_area.hpp"
#include <cmath>
#include <limits>
#include <utility>
namespace encore::upstream {namespace {
bool finite(Vec2 v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::abs(v.x)<1000000&&std::abs(v.y)<1000000;}
}
bool FieldCameraAreaRuntime::fail(const char*s){poisoned_=true;error_=s;return false;}
FieldCameraAreaState*FieldCameraAreaRuntime::get(uint32_t id,bool ready){auto i=states_.find(id);if(poisoned_||!data_||i==states_.end()||!i->second.alive||(ready&&!i->second.ready)){fail("Camarea lifetime/Ready rejected");return nullptr;}return &i->second;}
const FieldCameraAreaState*FieldCameraAreaRuntime::state(uint32_t id)const{auto i=states_.find(id);return i==states_.end()?nullptr:&i->second;}
bool FieldCameraAreaRuntime::initialize(const FieldCameraAreaData&d,FieldCameraAreaHost h,std::string&e){
 if(!d.valid()||!h.bind||!h.connect||!h.resolve_reference||!h.observe||!h.is_global_player||!h.adjust_camareas||!h.set_limit||!h.current_limits||!h.set_camarea_offset||!h.await_idle_frame||!h.cancel_idle_frame){e="Camarea host incomplete";return false;}
 if(!h.bind(d,e))return false;
 data_=&d;host_=std::move(h);states_.clear();awaits_.clear();next_await_=1;last_ready_=0;had_ready_=false;poisoned_=false;error_.clear();e.clear();return true;
}
bool FieldCameraAreaRuntime::create(uint32_t id){if(!data_||poisoned_||states_.count(id))return fail("Camarea create rejected");auto*d=data_->record(id);if(!d)return fail("Camarea source node rejected");FieldCameraAreaState s;s.id=id;states_.emplace(id,s);if(!host_.connect(*d,[this,id](uint64_t b){return body_enter(id,b);},[this,id](uint64_t b){return body_exit(id,b);},error_)){poisoned_=true;return false;}return true;}
bool FieldCameraAreaRuntime::observe(FieldCameraAreaState&s,FieldCameraAreaObservation&o){if(!host_.observe(s.id,s.cached_reference_id,o,error_)){poisoned_=true;return false;}if(!o.alive||!o.ancestors_admitted||!o.signals_admitted||!o.shape_admitted||o.reference_id!=s.cached_reference_id||(s.cached_reference_id&&!o.reference_alive)||(!s.cached_reference_id&&o.reference_alive)||!finite(o.local_scale)||!finite(o.shape_extents)||!finite(o.shape_global_position)||!finite(o.reference_size)||!finite(o.viewport_size)||o.local_scale.x<=0||o.local_scale.y<=0||o.shape_extents.x<=0||o.shape_extents.y<=0||o.viewport_size.x<=0||o.viewport_size.y<=0||(s.cached_reference_id&&(o.reference_size.x<0||o.reference_size.y<0)))return fail("Camarea live geometry/reference admission rejected");for(float v:o.reference_margins)if(!std::isfinite(v)||std::abs(v)>=1000000)return fail("Camarea reference margins rejected");return true;}
bool FieldCameraAreaRuntime::ready(uint32_t id){auto*s=get(id,false);if(!s)return false;auto*d=data_->record(id);if(s->ready||(had_ready_&&d->ready<=last_ready_))return fail("Camarea source Ready order rejected");uint32_t reference=0;if(!host_.resolve_reference(id,d->reference_path,reference,error_)){poisoned_=true;return false;}if(reference&&reference!=d->reference_id)return fail("Camarea resolved unreviewed reference");s->cached_reference_id=reference;FieldCameraAreaObservation o;if(!observe(*s,o))return false;s->ready=true;had_ready_=true;last_ready_=d->ready;return true;}
bool FieldCameraAreaRuntime::limit(FieldCameraLimit k,double value){if(!std::isfinite(value)||value<std::numeric_limits<int32_t>::min()||value>std::numeric_limits<int32_t>::max())return fail("Camarea native int limit overflow rejected");if(!host_.set_limit(k,static_cast<int32_t>(value),error_)){poisoned_=true;return false;}return true;}
bool FieldCameraAreaRuntime::reset(){for(uint32_t i=0;i<4;++i)if(!limit(static_cast<FieldCameraLimit>(i),data_->reset_limits()[i]))return false;if(!host_.set_camarea_offset({},error_)){poisoned_=true;return false;}return true;}
bool FieldCameraAreaRuntime::body_enter(uint32_t id,uint64_t body){auto*s=get(id);if(!s)return false;bool player=false;if(!host_.is_global_player(body,player,error_)){poisoned_=true;return false;}if(!player)return true;FieldCameraAreaObservation o;if(!observe(*s,o))return false;int64_t count=0;if(!host_.adjust_camareas(1,count,error_)){poisoned_=true;return false;}s->inside=true;if(!reset())return false;if(next_await_==0||awaits_.size()>=10000)return fail("Camarea pending continuation limit rejected");uint64_t token=next_await_++;awaits_.emplace(token,id);if(!host_.await_idle_frame(token,[this,token](){return resume_idle(token);},error_)){poisoned_=true;return false;}return true;}
bool FieldCameraAreaRuntime::body_exit(uint32_t id,uint64_t body){auto*s=get(id);if(!s)return false;bool player=false;if(!host_.is_global_player(body,player,error_)){poisoned_=true;return false;}if(!player)return true;FieldCameraAreaObservation o;if(!observe(*s,o))return false;int64_t count=0;if(!host_.adjust_camareas(-1,count,error_)){poisoned_=true;return false;}s->inside=false;return count==0?reset():true;}
bool FieldCameraAreaRuntime::size(const FieldCameraAreaObservation&o,Vec2&out){Vec2 v=o.reference_id?o.reference_size:Vec2{o.shape_extents.x*2*o.local_scale.x,o.shape_extents.y*2*o.local_scale.y};v.x=std::round(v.x);v.y=std::round(v.y);if(!finite(v)||v.x<0||v.y<0)return fail("Camarea source size overflow rejected");out=v;return true;}
bool FieldCameraAreaRuntime::get_size(uint32_t id,Vec2&out){auto*s=get(id);if(!s)return false;FieldCameraAreaObservation o;return observe(*s,o)&&size(o,out);}
bool FieldCameraAreaRuntime::get_area_global_position(uint32_t id,Vec2&out){auto*s=get(id);if(!s)return false;FieldCameraAreaObservation o;if(!observe(*s,o))return false;out=o.shape_global_position;return true;}
bool FieldCameraAreaRuntime::resume_idle(uint64_t token){auto i=awaits_.find(token);if(poisoned_||i==awaits_.end())return fail("Camarea unknown idle continuation rejected");auto id=i->second;awaits_.erase(i);auto*s=get(id);if(!s)return false;
 // Exit only changes the shared `inside` variable. It does not cancel prior
 // source coroutines; exit then reenter before idle resumes BOTH old/new waits.
 if(!s->inside)return true;
 FieldCameraAreaObservation o;Vec2 extent;if(!observe(*s,o)||!size(o,extent))return false;if(extent.y<o.viewport_size.y)extent.y=o.viewport_size.y;if(extent.x<o.viewport_size.x)extent.x=o.viewport_size.x;
 if(s->cached_reference_id){if(!limit(FieldCameraLimit::Top,int32_t(o.reference_margins[1]))||!limit(FieldCameraLimit::Left,int32_t(o.reference_margins[0])))return false;}else{if(!limit(FieldCameraLimit::Top,o.shape_global_position.y-extent.y/2)||!limit(FieldCameraLimit::Left,o.shape_global_position.x-extent.x/2))return false;}
 std::array<int32_t,4>current{};if(!host_.current_limits(current,error_)){poisoned_=true;return false;}if(!limit(FieldCameraLimit::Bottom,double(current[0])+extent.y))return false;if(!host_.current_limits(current,error_)){poisoned_=true;return false;}if(!limit(FieldCameraLimit::Right,double(current[1])+extent.x))return false;if(!host_.set_camarea_offset(data_->record(id)->camera_offset,error_)){poisoned_=true;return false;}return true;
}
bool FieldCameraAreaRuntime::exit_tree(uint32_t id){auto*s=get(id,false);if(!s)return false;s->alive=false;for(auto i=awaits_.begin();i!=awaits_.end();){if(i->second!=id){++i;continue;}if(!host_.cancel_idle_frame(i->first,error_)){poisoned_=true;return false;}i=awaits_.erase(i);}return true;}
}
