#include "encore/house_data.hpp"
#include "encore/content.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <set>
namespace encore::upstream {
namespace {
constexpr uint32_t section_count=17,header_bytes=336,max_bytes=1024*1024;
constexpr uint32_t strides[]={1,112,104,24,8,68,28,60,40,24,20,20,32,16,208,44,12};
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|(uint32_t(p[1])<<8)|(uint32_t(p[2])<<16)|(uint32_t(p[3])<<24);}
uint16_t u16(const uint8_t*p){return uint16_t(p[0])|(uint16_t(p[1])<<8);}
float f32(const uint8_t*p){auto b=u32(p);float v;std::memcpy(&v,&b,4);return v;}
double f64(const uint8_t*p){uint64_t b=uint64_t(u32(p))|(uint64_t(u32(p+4))<<32);double v;std::memcpy(&v,&b,8);return v;}
BattleValue value(const uint8_t*p){return {f32(p),f32(p+4),f32(p+8),f32(p+12)};}
bool finite(BattleValue v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::isfinite(v.z)&&std::isfinite(v.w);}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=(i>=16&&i<20)?0:p[i];for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&(0u-(c&1)));}return ~c;}
bool utf8(const uint8_t*p,size_t n){for(size_t i=0;i<n;){uint32_t c=p[i++];if(c<0x80)continue;unsigned extra;uint32_t low;if(c>=0xc2&&c<=0xdf){extra=1;low=0x80;c&=31;}else if(c>=0xe0&&c<=0xef){extra=2;low=0x800;c&=15;}else if(c>=0xf0&&c<=0xf4){extra=3;low=0x10000;c&=7;}else return false;if(extra>n-i)return false;while(extra--){auto b=p[i++];if((b&0xc0)!=0x80)return false;c=(c<<6)|(b&63);}if(c<low||c>0x10ffff||(c>=0xd800&&c<=0xdfff))return false;}return true;}
bool safe_path(std::string_view p){if(p.empty()||p.front()=='/'||p.find(':')!=p.npos||p.find('\\')!=p.npos)return false;size_t a=0;while(a<=p.size()){auto b=p.find('/',a);if(b==p.npos)b=p.size();auto s=p.substr(a,b-a);if(s.empty()||s=="."||s=="..")return false;if(b==p.size())break;a=b+1;}return true;}
Vec2 vec(const uint8_t*p){return {f32(p),f32(p+4)};}
bool finite(Vec2 v){return std::isfinite(v.x)&&std::isfinite(v.y);}
bool unit(Vec2 v){return v.x*v.x+v.y*v.y==1;}
}
uint32_t HouseView::count(HouseSection s)const{auto k=uint32_t(s);return bytes_&&k>=1&&k<=section_count?u32(bytes_+64+(k-1)*16+8):0;}
const uint8_t*HouseView::record(HouseSection s,uint32_t i)const{auto k=uint32_t(s);if(!bytes_||k<1||k>section_count||i>=count(s))return nullptr;return bytes_+u32(bytes_+64+(k-1)*16+4)+size_t(i)*strides[k-1];}
std::string_view HouseView::string(uint32_t o)const{auto*p=record(HouseSection::Strings,o);if(!p)return {};auto*end=static_cast<const uint8_t*>(std::memchr(p,0,count(HouseSection::Strings)-o));return end?std::string_view(reinterpret_cast<const char*>(p),size_t(end-p)):std::string_view{};}
HouseDoor HouseView::door(uint32_t i)const{auto*p=record(HouseSection::Doors,i);return p?HouseDoor{u32(p),u32(p+4),u32(p+8),u32(p+12),vec(p+16),vec(p+24),vec(p+32),vec(p+40),f64(p+48),f64(p+56),f64(p+64),f64(p+72),f64(p+80),f64(p+88),value(p+96)}:HouseDoor{};}
HouseNpc HouseView::npc(uint32_t i)const{auto*p=record(HouseSection::Npcs,i);return p?HouseNpc{u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20),u32(p+24),u32(p+28),vec(p+32),vec(p+40),vec(p+48),vec(p+56),vec(p+64),f32(p+72),f64(p+76),u32(p+84),u32(p+88),u32(p+92),u32(p+96),u32(p+100)}:HouseNpc{};}
HouseSegment HouseView::segment(uint32_t i)const{auto*p=record(HouseSection::Segments,i);return p?HouseSegment{u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20)}:HouseSegment{};}
HouseToken HouseView::token(uint32_t i)const{auto*p=record(HouseSection::Tokens,i);return p?HouseToken{u32(p),u32(p+4)}:HouseToken{};}
HouseInteraction HouseView::interaction()const{auto*p=record(HouseSection::Interaction,0);return p?HouseInteraction{vec(p),f32(p+8),f64(p+12),f64(p+20),f64(p+28),u32(p+36),u32(p+40),u32(p+44),u32(p+48),f64(p+52),f64(p+60)}:HouseInteraction{};}
HouseBoundary HouseView::boundary(uint32_t i)const{auto*p=record(HouseSection::Boundaries,i);return p?HouseBoundary{u32(p),u32(p+4),u32(p+8),vec(p+12),vec(p+20)}:HouseBoundary{};}
BattleResource HouseView::resource(uint32_t i)const{BattleResource r;auto*p=record(HouseSection::Resources,i);if(p){r={u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20),u32(p+24),{}};std::memcpy(r.sha256,p+28,32);}return r;}
HouseClip HouseView::clip(uint32_t i)const{auto*p=record(HouseSection::Clips,i);return p?HouseClip{u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),f64(p+20),u32(p+28),u32(p+32),u32(p+36)}:HouseClip{};}
HouseKey HouseView::key(uint32_t i)const{auto*p=record(HouseSection::Keys,i);return p?HouseKey{f64(p),f32(p+8),vec(p+12),u32(p+20)}:HouseKey{};}
BattleValue HouseView::parameter(HouseParameter key)const{for(uint32_t i=0;i<count(HouseSection::Parameters);++i){auto*p=record(HouseSection::Parameters,i);if(u32(p)==uint32_t(key))return value(p+4);}return {};}
uint32_t HouseView::clip_for(HouseClipRole role,uint32_t profile)const{for(uint32_t i=0;i<count(HouseSection::Clips);++i)if(clip(i).role==uint32_t(role)&&clip(i).profile==profile)return i;return house_no_index;}
HouseOverride HouseView::override_dialogue(uint32_t i)const{auto*p=record(HouseSection::Overrides,i);return p?HouseOverride{u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16)}:HouseOverride{};}
HouseProfile HouseView::profile(uint32_t i)const{auto*p=record(HouseSection::Profiles,i);return p?HouseProfile{u32(p),u32(p+4),vec(p+8),vec(p+16),u32(p+24),u32(p+28)}:HouseProfile{};}
HouseDialogue HouseView::dialogue(uint32_t i)const{auto*p=record(HouseSection::Dialogues,i);return p?HouseDialogue{u32(p),u32(p+4),u32(p+8),u32(p+12)}:HouseDialogue{};}
HouseOpenableDoor HouseView::openable_door(uint32_t i)const{auto*p=record(HouseSection::OpenableDoors,i);return p?HouseOpenableDoor{
 u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20),u32(p+24),u32(p+28),u32(p+32),u32(p+36),u32(p+40),u32(p+44),u32(p+48),u32(p+52),u32(p+56),u32(p+60),u32(p+64),u32(p+68),u32(p+72),u32(p+76),u32(p+80),
 vec(p+84),vec(p+92),vec(p+100),vec(p+108),vec(p+116),vec(p+124),vec(p+132),vec(p+140),vec(p+148),vec(p+156),f32(p+164),f64(p+168),f64(p+176),f64(p+184),f64(p+192),f64(p+200)}:HouseOpenableDoor{};}
HouseStoryTrigger HouseView::story_trigger(uint32_t i)const{auto*p=record(HouseSection::StoryTriggers,i);return p?HouseStoryTrigger{u32(p),u32(p+4),u32(p+8),vec(p+12),vec(p+20),u32(p+28),u32(p+32),u32(p+36),u32(p+40)}:HouseStoryTrigger{};}
HouseStoryCondition HouseView::story_condition(uint32_t i)const{auto*p=record(HouseSection::StoryConditions,i);return p?HouseStoryCondition{u32(p),u32(p+4),u32(p+8)}:HouseStoryCondition{};}
bool HouseData::load(const uint8_t*input,size_t size,std::string&error){
 auto fail=[&](const char*s){error=s;return false;};
 if(!input||size<header_bytes||size>max_bytes)return fail("House pack size rejected");
 if(std::memcmp(input,"ENCHSE01",8)||(u32(input+8)!=4&&u32(input+8)!=5&&u32(input+8)!=6)||u32(input+12)!=size||u32(input+20)!=section_count||u32(input+24)!=u32(input+8)||u32(input+28)!=u32(input+8))return fail("House schema/capabilities/rules rejected");
 for(unsigned i=52;i<64;++i)if(input[i])return fail("House reserved bytes rejected");
 if(crc(input,size)!=u32(input+16))return fail("House CRC mismatch");
 size_t end=header_bytes;
 for(uint32_t i=0;i<section_count;++i){auto*d=input+64+i*16;auto off=u32(d+4),n=u32(d+8),bytes=u32(d+12);if(u16(d)!=i+1||u16(d+2)!=strides[i]||uint64_t(n)*strides[i]!=bytes)return fail("House directory rejected");if(!n){if(off||bytes)return fail("House empty section rejected");continue;}if(off%4||off<end||off>size||bytes>size-off)return fail("House section span rejected");for(size_t j=end;j<off;++j)if(input[j])return fail("House padding rejected");end=size_t(off)+bytes;}
 if(end!=size)return fail("House trailing bytes rejected");
 HouseView v;v.bytes_=input;v.size_=size;auto count=[&](HouseSection s){return v.count(s);};
 auto capacity=[&](HouseSection s,uint32_t lo,uint32_t hi){return count(s)>=lo&&count(s)<=hi;};
 if(!capacity(HouseSection::Strings,1,65536)||!capacity(HouseSection::Doors,1,32)||!capacity(HouseSection::Npcs,1,16)||!capacity(HouseSection::Segments,1,u32(input+8)>=6?128:64)||!capacity(HouseSection::Tokens,1,256)||count(HouseSection::Interaction)!=1||!capacity(HouseSection::Boundaries,0,64)||!capacity(HouseSection::Resources,1,64)||!capacity(HouseSection::Clips,5,256)||!capacity(HouseSection::Keys,1,2048)||count(HouseSection::Parameters)!=uint32_t(HouseParameter::Count)-1||!capacity(HouseSection::Overrides,0,128)||!capacity(HouseSection::Profiles,1,16)||!capacity(HouseSection::Dialogues,1,64)||!capacity(HouseSection::OpenableDoors,1,32)||!capacity(HouseSection::StoryTriggers,1,64)||!capacity(HouseSection::StoryConditions,1,128))return fail("House capacity rejected");
 auto*pool=v.record(HouseSection::Strings,0);auto pool_size=count(HouseSection::Strings);if(pool[0]||pool[pool_size-1]||!utf8(pool,pool_size))return fail("House strings rejected");
 auto str=[&](uint32_t o){return o<pool_size&&(o==0||pool[o-1]==0)&&v.string(o).size()<=4096;};auto path=[&](uint32_t o){return str(o)&&safe_path(v.string(o));};
 auto span=[&](uint32_t first,uint32_t n,HouseSection s){return first<=count(s)&&n<=count(s)-first;};
 for(auto s:{HouseSection::Doors,HouseSection::Npcs,HouseSection::Segments,HouseSection::Boundaries,HouseSection::Resources,HouseSection::Clips,HouseSection::Profiles,HouseSection::Dialogues,HouseSection::OpenableDoors,HouseSection::StoryTriggers}){std::set<uint32_t>ids;for(uint32_t i=0;i<count(s);++i){auto id=u32(v.record(s,i));if(!id||!ids.insert(id).second)return fail("House zero/duplicate ID");}}
 for(uint32_t i=0;i<count(HouseSection::Doors);++i){auto d=v.door(i);if(!path(d.source_path)||!str(d.start_sound)||!str(d.end_sound)||(d.start_sound&&!path(d.start_sound))||(d.end_sound&&!path(d.end_sound)))return fail("House door paths rejected");if(!finite(d.center)||!finite(d.extents)||!finite(d.destination)||!finite(d.direction)||d.extents.x<=0||d.extents.y<=0||d.extents.x>10000||d.extents.y>10000||!unit(d.direction))return fail("House door geometry rejected");for(double f:{d.fade_in_length,d.fade_in_opaque,d.fade_out_length,d.fade_out_mostly,d.fade_in_speed,d.fade_out_speed})if(!std::isfinite(f)||f<=0)return fail("House fade numeric rejected");if(d.fade_in_opaque>d.fade_in_length||d.fade_out_mostly>d.fade_out_length||d.fade_in_length>120||d.fade_out_length>120||d.fade_in_speed>100||d.fade_out_speed>100||!finite(d.color)||d.color.x<0||d.color.x>1||d.color.y<0||d.color.y>1||d.color.z<0||d.color.z>1||d.color.w<0||d.color.w>1)return fail("House fade rejected");}
 std::set<uint32_t>owned_segments,owned_tokens,mapped_room_actors;
 for(uint32_t i=0;i<count(HouseSection::Npcs);++i){auto n=v.npc(i);if(!path(n.source_path)||!n.body_id||n.primary_resource>=count(HouseSection::Resources)||(n.shadow_resource!=house_no_index&&n.shadow_resource>=count(HouseSection::Resources))||(!n.segment_count&&n.first_segment)||!span(n.first_segment,n.segment_count,HouseSection::Segments)||!str(n.seen_key)||(v.string(n.seen_key).empty()==bool(n.segment_count||n.program_index!=house_no_index))||(n.program_index!=house_no_index&&n.program_index>=1024)||n.profile>=count(HouseSection::Profiles)||!path(n.dialogue_path)||v.profile(n.profile).resource!=n.primary_resource||(bool(v.profile(n.profile).flags&2)!=(n.shadow_resource!=house_no_index))||!finite(n.position)||!finite(n.interact_center)||!finite(n.interact_extents)||n.interact_extents.x<=0||n.interact_extents.y<=0||!finite(n.default_direction)||!unit(n.default_direction)||!finite(n.view_center)||!std::isfinite(n.view_radius)||n.view_radius<=0||!std::isfinite(n.return_delay)||n.return_delay<=0||n.return_delay>120||(n.flags&~15u)||(n.room_actor_index!=house_no_index&&(n.room_actor_index>=64||!mapped_room_actors.insert(n.room_actor_index).second)))return fail("House NPC rejected");for(uint32_t j=0;j<n.segment_count;++j){auto index=n.first_segment+j;if(!owned_segments.insert(index).second||v.segment(index).flags!=(j+1==n.segment_count?5u:3u))return fail("House segment ownership/termination rejected");}}
 for(uint32_t i=0;i<count(HouseSection::Dialogues);++i){auto d=v.dialogue(i);if(!path(d.source_path)||!d.segment_count||!span(d.first_segment,d.segment_count,HouseSection::Segments))return fail("House dialogue rejected");for(uint32_t j=0;j<d.segment_count;++j){auto index=d.first_segment+j;if(!owned_segments.insert(index).second||v.segment(index).flags!=(j+1==d.segment_count?5u:3u))return fail("House dialogue ownership/termination rejected");}}
 for(uint32_t i=0;i<count(HouseSection::Segments);++i){auto s=v.segment(i);if(!str(s.speaker)||!str(s.voice)||(s.voice&&!path(s.voice))||!s.token_count||!span(s.first_token,s.token_count,HouseSection::Tokens)||(s.flags!=3&&s.flags!=5))return fail("House segment rejected");for(uint32_t j=0;j<s.token_count;++j)if(!owned_tokens.insert(s.first_token+j).second)return fail("House token ownership rejected");}
 if(owned_segments.size()!=count(HouseSection::Segments)||owned_tokens.size()!=count(HouseSection::Tokens))return fail("House orphan text rejected");
 for(uint32_t i=0;i<count(HouseSection::Tokens);++i){auto t=v.token(i);
  if(t.kind<1||t.kind>(u32(input+8)>=6?9u:u32(input+8)>=5?7u:2u)||!str(t.text))return fail("House text token rejected");
  if(t.kind==1){if(v.string(t.text).empty())return fail("House empty literal");}
  else if(t.kind==3){const auto color=v.string(t.text);if(color.size()!=6)return fail("House color size");for(char ch:color)if(!((ch>='0'&&ch<='9')||(ch>='a'&&ch<='f')||(ch>='A'&&ch<='F')))return fail("House color value");}
  else if(t.kind==8){const auto amount=v.string(t.text);if(amount.empty()||amount.size()>8||amount.front()=='.'||amount.back()=='.')return fail("House delay size");double number=0;bool dot=false,decimal=false;double factor=.1;for(char ch:amount){if(ch=='.'&&!dot){dot=true;continue;}if(ch<'0'||ch>'9')return fail("House delay value");decimal=true;if(dot){number+=(ch-'0')*factor;factor*=.1;}else number=number*10+(ch-'0');}if(!decimal||number<=0||number>3600)return fail("House delay range");}
  else if(t.text)return fail("House unused text token payload");
 }
 auto q=v.interaction();if(!finite(q.ray_origin)||!std::isfinite(q.ray_length)||q.ray_length<=0||q.ray_length>1024||!q.collision_mask||!str(q.bullet_string)||v.string(q.bullet_string).empty()||!str(q.word_separator)||v.string(q.word_separator).empty()||!q.max_player_name_length||q.max_player_name_length>128||!std::isfinite(q.voice_pitch_min)||!std::isfinite(q.voice_pitch_max)||q.voice_pitch_min<=0||q.voice_pitch_min>q.voice_pitch_max||q.voice_pitch_max>10)return fail("House interaction rejected");for(double x:{q.text_seconds,q.accept_multiplier,q.cancel_multiplier})if(!std::isfinite(x)||x<=0||x>10000)return fail("House text timing rejected");
 for(uint32_t i=0;i<count(HouseSection::Boundaries);++i){auto b=v.boundary(i);if(!path(b.source_path)||b.kind<1||b.kind>2||!finite(b.center)||!finite(b.extents)||b.extents.x<=0||b.extents.y<=0)return fail("House boundary rejected");}
 for(uint32_t i=0;i<count(HouseSection::Resources);++i){auto r=v.resource(i);if(!path(r.path)||r.kind<1||r.kind>3||!r.width||r.width>8192||!r.height||r.height>8192||!r.columns||r.columns>256||!r.rows||r.rows>256||(r.kind==1&&(r.width%r.columns||r.height%r.rows)))return fail("House resource rejected");}
 std::set<std::pair<uint32_t,uint32_t>>roles;std::set<uint32_t>owned_keys;
 for(uint32_t i=0;i<count(HouseSection::Clips);++i){auto c=v.clip(i);if(!c.role||c.role>=uint32_t(HouseClipRole::Count)||!roles.insert({c.profile,c.role}).second||(c.resource!=house_no_index&&c.resource>=count(HouseSection::Resources))||!c.key_count||!span(c.first_key,c.key_count,HouseSection::Keys)||!std::isfinite(c.duration)||c.duration<=0||c.duration>120||c.loop>1||c.interpolation>2)return fail("House clip rejected");if(c.role<=uint32_t(HouseClipRole::NpcTalkUp)){if(c.profile>=count(HouseSection::Profiles)||c.resource!=v.profile(c.profile).resource)return fail("House clip profile rejected");}else if(c.profile!=house_no_index)return fail("House UI clip profile rejected");bool frame=c.role<=uint32_t(HouseClipRole::NpcTalkUp)||c.role==uint32_t(HouseClipRole::Cursor);if((frame&&(c.resource>=count(HouseSection::Resources)||c.interpolation!=1))||(!frame&&c.interpolation==1))return fail("House clip role/interpolation rejected");double prior=-1;for(uint32_t j=0;j<c.key_count;++j){auto index=c.first_key+j;auto k=v.key(index);if(!owned_keys.insert(index).second||!std::isfinite(k.time)||k.time<0||k.time<=prior||k.time>c.duration||!std::isfinite(k.ease)||std::abs(k.ease)>100||!finite(k.position))return fail("House key rejected");prior=k.time;if(frame){auto r=v.resource(c.resource);if(k.frame>=uint64_t(r.columns)*r.rows)return fail("House frame rejected");}}}
 if(owned_keys.size()!=count(HouseSection::Keys))return fail("House orphan keys rejected");
 std::set<std::pair<uint32_t,uint32_t>>expected_roles;for(uint32_t role=uint32_t(HouseClipRole::DialogueOpen);role<uint32_t(HouseClipRole::Count);++role)expected_roles.insert({house_no_index,role});
 for(uint32_t i=0;i<count(HouseSection::Profiles);++i){auto p=v.profile(i);if(p.resource>=count(HouseSection::Resources)||!finite(p.sprite_offset)||!finite(p.shadow_offset)||(p.directions!=1&&p.directions!=4)||(p.flags&~7u))return fail("House profile rejected");for(uint32_t j=0;j<p.directions;++j){expected_roles.insert({i,1+j});if(p.flags&4)expected_roles.insert({i,5+j});}}
 if(roles!=expected_roles)return fail("House profile clip coverage rejected");
 std::set<uint32_t>params;for(uint32_t i=0;i<count(HouseSection::Parameters);++i){auto*p=v.record(HouseSection::Parameters,i);auto k=u32(p);if(!k||k>=uint32_t(HouseParameter::Count)||!params.insert(k).second||!finite(value(p+4)))return fail("House parameter rejected");}
 auto npc_return=v.parameter(HouseParameter::NpcInteractionReturn);if(npc_return.x<=0||npc_return.x>120||npc_return.y||npc_return.z||npc_return.w)return fail("House NPC return timing rejected");
 auto fade=v.parameter(HouseParameter::FadeShader);if(fade.x<=0||fade.y<=0||fade.z||fade.w)return fail("House fade shader rejected");auto cuts=v.parameter(HouseParameter::FadeCuts);for(float x:{cuts.x,cuts.y,cuts.z,cuts.w})if(x<0||x>1)return fail("House fade cuts rejected");
 for(auto key:{HouseParameter::DialogueRect,HouseParameter::DialogueClip,HouseParameter::DialogueText,HouseParameter::DialogueBullet,HouseParameter::NameRect,HouseParameter::NameLabel,HouseParameter::CursorGeometry}){auto x=v.parameter(key);if(x.z<=0||x.z>8192||x.w<=0||x.w>8192)return fail("House layout size rejected");}
 for(auto key:{HouseParameter::DialogueMargins,HouseParameter::NameMargins}){auto x=v.parameter(key);for(float a:{x.x,x.y,x.z,x.w})if(a<0||a>8192)return fail("House margins rejected");}
 auto sizing=v.parameter(HouseParameter::NameSizing);if(sizing.x<0||sizing.y<=0||sizing.y>120||sizing.z<=0||sizing.z>100||sizing.w<0)return fail("House name sizing rejected");
 auto metrics=v.parameter(HouseParameter::FontMetrics);if(metrics.x<=0||metrics.x>256||metrics.y<0||metrics.y>256||metrics.z<0||metrics.z>256||metrics.w<0||metrics.w>256)return fail("House font metrics rejected");
 auto display=v.parameter(HouseParameter::DisplayReference);if(display.x<=0||display.x>8192||display.y<=0||display.y>8192||display.z<0||display.z>1||display.w<0||display.w>1)return fail("House display reference rejected");
 for(auto key:{HouseParameter::TextTiming,HouseParameter::TextTagSpeeds}){auto x=v.parameter(key);if(x.x<=0||x.y<=0||x.z<=0||x.w)return fail("House text parameters rejected");}
 std::set<std::pair<uint32_t,uint32_t>>seen;for(uint32_t i=0;i<count(HouseSection::Overrides);++i){auto o=v.override_dialogue(i);if(!str(o.seen_key)||v.string(o.seen_key).empty()||o.npc>=count(HouseSection::Npcs)||!str(o.flag)||v.string(o.flag).empty()||(o.dialogue_index!=house_no_index&&o.dialogue_index>=count(HouseSection::Dialogues))||!path(o.dialogue)||!seen.insert({o.npc,o.flag}).second)return fail("House override rejected");}
 for(uint32_t i=0;i<count(HouseSection::OpenableDoors);++i){auto d=v.openable_door(i);if(!path(d.source_path)||!d.player_body_id||!d.nonplayer_body_id||d.player_body_id==d.nonplayer_body_id||d.sprite_resource>=count(HouseSection::Resources)||!str(d.flag)||!str(d.key)||!str(d.activates_flag)||!str(d.deactivates_flag)||d.blocked_dialogue>=count(HouseSection::Dialogues)||!path(d.locked_dialogue)||!path(d.opened_dialogue)||!str(d.start_sound)||!str(d.end_sound)||(d.start_sound&&!path(d.start_sound))||(d.end_sound&&!path(d.end_sound))||!path(d.ram_sound))return fail("House openable binding/strings rejected");if((d.policy&~15u)||!d.normal_mask||(d.normal_mask&~7u)||(d.normal_values&~d.normal_mask)||!d.action_mask||(d.action_mask&~7u)||(d.action_values&~d.action_mask)||d.timer_flags!=1)return fail("House openable policy/state rejected");for(auto v:{d.position,d.trigger_center,d.trigger_extents,d.interact_center,d.interact_extents,d.collision_center,d.collision_extents,d.sprite_position,d.sprite_offset,d.ram_direction})if(!finite(v))return fail("House openable finite geometry rejected");for(auto v:{d.trigger_extents,d.interact_extents,d.collision_extents})if(v.x<=0||v.y<=0||v.x>10000||v.y>10000)return fail("House openable rectangle rejected");if(!std::isfinite(d.ram_required_y)||d.ram_required_y<-1||d.ram_required_y>1||!std::isfinite(d.ram_strength)||d.ram_strength<=0||d.ram_strength>100)return fail("House openable ram rejected");for(double x:{d.close_delay,d.action_length,d.normal_length,d.ram_duration})if(!std::isfinite(x)||x<=0||x>120)return fail("House openable timing rejected");}
 std::set<uint32_t>owned_conditions;for(uint32_t i=0;i<count(HouseSection::StoryTriggers);++i){auto t=v.story_trigger(i);if(!path(t.source_path)||!path(t.dialogue)||!finite(t.center)||!finite(t.extents)||t.extents.x<=0||t.extents.y<=0||t.extents.x>10000||t.extents.y>10000||!t.condition_count||!span(t.first_condition,t.condition_count,HouseSection::StoryConditions)||(t.disposition!=uint32_t(HouseStoryDisposition::DevelopmentBoundary)&&t.disposition!=uint32_t(HouseStoryDisposition::ExecuteProgram))||(t.disposition==uint32_t(HouseStoryDisposition::DevelopmentBoundary)?t.program_index!=house_no_index:t.program_index>=1024))return fail("House story trigger rejected");for(uint32_t j=0;j<t.condition_count;++j)if(!owned_conditions.insert(t.first_condition+j).second)return fail("House story condition ownership rejected");}
 if(owned_conditions.size()!=count(HouseSection::StoryConditions))return fail("House orphan story conditions rejected");
 for(uint32_t i=0;i<count(HouseSection::StoryConditions);++i){auto c=v.story_condition(i);if(c.kind<1||c.kind>2||!str(c.flag)||v.string(c.flag).empty()||c.value>1)return fail("House story condition rejected");}
 std::vector<uint8_t>next(input,input+size);bytes_.swap(next);error.clear();return true;
}
bool HouseData::load_file(const char*path,std::string&error){std::vector<uint8_t>data;return encore::read_file(path,data,max_bytes,error)&&load(data.data(),data.size(),error);}
}
