#include "encore/storage_menu.hpp"
#include <algorithm>
#include <cmath>
#include <set>
namespace encore::upstream {namespace {
bool fail(std::string&e,const char*s){e=s;return false;}
std::array<int32_t,7>boosts(StorageView v,const InventoryState&inventory){std::array<int32_t,7>b{};for(auto&i:inventory.instances())if(i.equipped)for(uint32_t k=0;k<v.count(StorageSection::Equipment);++k){auto d=v.equipment(k);if(d.definition==i.definition)for(size_t j=0;j<7;++j)b[j]+=d.boosts[j];}return b;}
bool delta_stats(BattleSessionStats&stats,const std::array<int32_t,7>&before,const std::array<int32_t,7>&after){int32_t*values[]={&stats.maxhp,&stats.maxpp,&stats.offense,&stats.defense,&stats.speed,&stats.iq,&stats.guts};for(size_t i=0;i<7;++i){int64_t n=int64_t(*values[i])-before[i]+after[i];if(n<0||n>INT32_MAX||(i==0&&n==0))return false;}for(size_t i=0;i<7;++i)*values[i]=*values[i]-before[i]+after[i];stats.hp=std::min(stats.hp,stats.maxhp);stats.pp=std::min(stats.pp,stats.maxpp);return true;}
}
bool StorageState::restore(ItemView data,uint32_t capacity,const std::vector<ItemInstance>&items,std::string&e){if(!data.valid()||!capacity||capacity>4096||items.size()>capacity)return fail(e,"Storage restore capacity/content rejected");std::set<uint32_t>uids;for(auto&i:items)if(i.definition>=data.count(ItemSection::Definitions)||i.equipped||!i.doses||i.doses>65535||!uids.insert(i.id).second)return fail(e,"Storage restore definition/equipment/doses/UID rejected");auto copy=items;data_=data;capacity_=capacity;items_=std::move(copy);e.clear();return true;}
bool StorageState::append(ItemInstance item,std::string&e){auto next=items_;next.push_back(item);return restore(data_,capacity_,next,e);}
bool StorageState::erase_uid(uint32_t uid,std::string&e){auto at=std::find_if(items_.begin(),items_.end(),[&](const ItemInstance&i){return i.id==uid;});if(!valid()||at==items_.end())return fail(e,"Storage erase UID rejected");items_.erase(at);e.clear();return true;}
bool StorageState::sort(StorageView v,bool chinese,std::string&e){if(!v.bind_items(data_,e))return false;for(auto&i:items_){bool found=false;for(uint32_t j=0;j<v.count(StorageSection::Policies);++j)if(v.policy(j).definition==i.definition)found=true;if(!found)return fail(e,"Storage sort unknown policy");}auto rank=[&](const ItemInstance&i)->uint32_t{for(uint32_t j=0;j<v.count(StorageSection::Policies);++j){auto p=v.policy(j);if(p.definition==i.definition)return chinese?p.rank_zh:p.rank_en;}return 0u;};std::stable_sort(items_.begin(),items_.end(),[&](auto&a,auto&b){return rank(a)>rank(b);});e.clear();return true;}
bool StorageMenu::reject(const char*s){error_=s;return false;}
bool StorageMenu::checked_state(){
 if(!data_.bind_items(inventory_->content(),error_)||!data_.bind_items(storage_->content(),error_)||!storage_->valid()||storage_->capacity()!=uint32_t(data_.parameter(StorageParameter::StorageCapacity)))return reject("Storage checked inventory binding rejected");
 std::set<uint32_t>uids;std::vector<uint32_t>counts(data_.count(StorageSection::Policies));
 auto check=[&](const ItemInstance&i,bool stored){if(!uids.insert(i.id).second||stored&&i.equipped)return false;for(uint32_t j=0;j<data_.count(StorageSection::Policies);++j){auto p=data_.policy(j);if(p.definition!=i.definition)continue;if(i.doses!=p.doses||++counts[j]>p.max_count)return false;if(i.equipped){bool found=false;for(uint32_t k=0;k<data_.count(StorageSection::Equipment);++k)if(data_.equipment(k).definition==i.definition&&(inventory_->content().definition(i.definition).flags&uint32_t(ItemDefinitionFlag::Equipment)))found=true;if(!found)return false;}return true;}return false;};
 for(auto&i:inventory_->instances())if(!check(i,false))return reject("Storage unsupported on-hand item");for(auto&i:storage_->instances())if(!check(i,true))return reject("Storage unsupported stored item");return true;
}
bool StorageMenu::initialize(StorageView data,InventoryState&inventory,StorageState&storage,BattleSessionStats&stats,bool chinese){if(!data.valid()||!inventory.valid()||!storage.valid())return reject("Storage initialize needs checked resources");StorageMenu next;next.data_=data;next.inventory_=&inventory;next.storage_=&storage;next.stats_=&stats;next.chinese_=chinese;if(!next.checked_state())return reject(next.error());*this=std::move(next);return true;}
uint32_t StorageMenu::size()const{return storage_panel_?storage_->size():inventory_->size();}
void StorageMenu::clamp(){const auto n=size(),rows=uint32_t(data_.parameter(StorageParameter::Rows));selection_=n?std::min(selection_,n-1):0;if(selection_<row_offset_)row_offset_=selection_;else if(selection_>=row_offset_+rows)row_offset_=selection_-rows+1;if(!n)row_offset_=0;panel_selection_[storage_panel_?1:0]=selection_;panel_offsets_[storage_panel_?1:0]=row_offset_;const auto panel=storage_panel_?1:0;const float target=float(selection_-row_offset_);if(cursor_target_[panel]!=target){cursor_start_[panel]=cursor_rows_[panel];cursor_target_[panel]=target;cursor_move_time_[panel]=0;}}
void StorageMenu::refresh_panels(){
 // ItemListMenu._update_content(false) keeps each pane's page and visible
 // cursor row, shrinking the page first when a transfer changes its length.
 const auto rows=uint32_t(data_.parameter(StorageParameter::Rows));
 for(size_t i=0;i<2;++i){const auto n=i?storage_->size():inventory_->size();const auto local=panel_selection_[i]>=panel_offsets_[i]?panel_selection_[i]-panel_offsets_[i]:0;panel_offsets_[i]=std::min(panel_offsets_[i],n>rows?n-rows:0);panel_selection_[i]=n?panel_offsets_[i]+std::min(local,n-panel_offsets_[i]-1):0;const float row=float(panel_selection_[i]-panel_offsets_[i]);cursor_rows_[i]=cursor_start_[i]=cursor_target_[i]=row;cursor_move_time_[i]=0;}
 selection_=panel_selection_[storage_panel_?1:0];row_offset_=panel_offsets_[storage_panel_?1:0];
}
bool StorageMenu::open(){if(!inventory_||!checked_state())return false;if(!storage_->sort(data_,chinese_,error_))return false;phase_=StorageMenuPhase::List;storage_panel_=false;selection_=row_offset_=0;question_yes_=true;panel_selection_={};panel_offsets_={};cursor_rows_={};cursor_start_={};cursor_target_={};cursor_move_time_={};cursor_time_=0;question_row_=question_start_=question_target_=question_move_time_=0;return true;}
void StorageMenu::warning(StorageBinding b){warning_=b;phase_=StorageMenuPhase::Warning;warning_time_=data_.parameter(StorageParameter::WarnSeconds);sounds_.push_back(StorageSoundEvent::Restricted);}
bool StorageMenu::equip(uint32_t uid,bool value){auto candidate=*inventory_;auto stats=*stats_;auto before=boosts(data_,candidate);if(!candidate.equip_uid(uid,value,error_)||!delta_stats(stats,before,boosts(data_,candidate)))return reject("Storage equipment stat transition rejected");*inventory_=std::move(candidate);*stats_=std::move(stats);return true;}
bool StorageMenu::store(uint32_t uid){auto inv=*inventory_;auto storage=*storage_;auto stats=*stats_;auto at=std::find_if(inv.instances().begin(),inv.instances().end(),[&](const ItemInstance&i){return i.id==uid;});if(at==inv.instances().end()||!storage.has_space())return reject("Storage deposit preflight failed");auto item=*at;const auto before=boosts(data_,inv);if(!inv.erase_uid(uid,error_))return false;item.equipped=0;if(!storage.append(item,error_)||!storage.sort(data_,chinese_,error_)||!delta_stats(stats,before,boosts(data_,inv)))return reject("Storage deposit transaction rejected");*inventory_=std::move(inv);*storage_=std::move(storage);*stats_=std::move(stats);refresh_panels();return true;}
bool StorageMenu::withdraw(uint32_t uid){auto inv=*inventory_;auto storage=*storage_;auto at=std::find_if(storage.instances().begin(),storage.instances().end(),[&](const ItemInstance&i){return i.id==uid;});if(at==storage.instances().end()||!inv.has_space())return reject("Storage withdrawal preflight failed");const auto item=*at;if(!inv.append(item.definition,item.doses,item.id,error_)||!storage.erase_uid(uid,error_))return false;*inventory_=std::move(inv);*storage_=std::move(storage);refresh_panels();return true;}
std::string StorageMenu::prompt()const{StorageBinding b=warning_;if(phase_==StorageMenuPhase::AskUnequip)b=StorageBinding::UnequipEn;else if(phase_==StorageMenuPhase::AskEquip)b=StorageBinding::EquipEn;else if(phase_!=StorageMenuPhase::Warning)return {};if(chinese_)b=StorageBinding(uint32_t(b)+1);std::string text(data_.binding(b));const std::string token="{item}";auto at=text.find(token);if(at!=text.npos)text.replace(at,token.size(),inventory_->content().string(inventory_->content().definition(pending_definition_).name));return text;}
bool StorageMenu::input(int x,int y,bool confirm,bool cancel){
 if(x<-1||x>1||y<-1||y>1)return reject("Storage input direction rejected");if(!active())return true;
 if(phase_==StorageMenuPhase::Warning){if(confirm||cancel){phase_=StorageMenuPhase::List;warning_time_=0;}return true;}
 if(phase_==StorageMenuPhase::AskUnequip||phase_==StorageMenuPhase::AskEquip){if(!checked_state())return false;if(y&&question_yes_!=(y<0)){question_yes_=y<0;question_start_=question_row_;question_target_=question_yes_?0:1;question_move_time_=0;sounds_.push_back(StorageSoundEvent::Move);}if(cancel||confirm){if(cancel)sounds_.push_back(StorageSoundEvent::Back);if(confirm)sounds_.push_back(StorageSoundEvent::Confirm);if(confirm&&question_yes_){if(phase_==StorageMenuPhase::AskUnequip){if(!store(pending_uid_))return false;sounds_.push_back(StorageSoundEvent::Clear);}else{if(!equip(pending_uid_,true))return false;sounds_.push_back(StorageSoundEvent::Equip);}}phase_=StorageMenuPhase::List;clamp();}return true;}
 if(cancel){sounds_.push_back(StorageSoundEvent::Back);phase_=StorageMenuPhase::Closed;return true;}if(!checked_state())return false;
 if(x&&!y){const bool target=x>0;const auto n=target?storage_->size():inventory_->size();if(n&&target!=storage_panel_){const auto local=selection_-row_offset_;storage_panel_=target;row_offset_=panel_offsets_[target?1:0];selection_=row_offset_+local;clamp();const auto panel=target?1:0;cursor_rows_[panel]=cursor_start_[panel]=cursor_target_[panel]=float(selection_-row_offset_);cursor_move_time_[panel]=0;sounds_.push_back(StorageSoundEvent::Move);}}
 else if(y&&size()){auto n=size();selection_=uint32_t((int64_t(selection_)+y+n)%n);clamp();sounds_.push_back(StorageSoundEvent::Move);}
 if(confirm&&size()){auto item=storage_panel_?storage_->instance(selection_):inventory_->instance(selection_);pending_uid_=item.id;pending_definition_=item.definition;question_yes_=true;question_row_=question_start_=question_target_=question_move_time_=0;
  if(storage_panel_){if(!inventory_->has_space()){warning(StorageBinding::InventoryFullEn);return true;}if(!withdraw(item.id))return false;sounds_.push_back(StorageSoundEvent::Confirm);bool equipment=false;for(uint32_t i=0;i<data_.count(StorageSection::Equipment);++i)if(data_.equipment(i).definition==item.definition&&(inventory_->content().definition(item.definition).flags&uint32_t(ItemDefinitionFlag::Equipment)))equipment=true;if(equipment)phase_=StorageMenuPhase::AskEquip;}
  else{if(!storage_->has_space()){warning(StorageBinding::StorageFullEn);return true;}if(item.equipped){phase_=StorageMenuPhase::AskUnequip;sounds_.push_back(StorageSoundEvent::Confirm);}else{if(!store(item.id))return false;sounds_.push_back(StorageSoundEvent::Confirm);}}
 }return true;
}
uint32_t StorageMenu::cursor_frame()const{const auto index=uint32_t(std::fmod(cursor_time_*data_.parameter(StorageParameter::CursorFps),4.0));return uint32_t(data_.parameter(StorageParameter(uint32_t(StorageParameter::CursorFrame0)+index)));}
bool StorageMenu::idle_frame(double dt){if(!data_.valid()||!std::isfinite(dt)||dt<0||dt>1)return reject("Storage delta rejected");cursor_time_+=dt;const auto length=data_.parameter(StorageParameter::CursorMoveSeconds);auto ease=[&](float elapsed){const float t=std::min(elapsed/length,1.0f);return 1-std::pow(1-t,4.0f);};for(size_t i=0;i<2;++i){cursor_move_time_[i]+=float(dt);cursor_rows_[i]=cursor_start_[i]+(cursor_target_[i]-cursor_start_[i])*ease(cursor_move_time_[i]);}question_move_time_+=float(dt);question_row_=question_start_+(question_target_-question_start_)*ease(question_move_time_);if(phase_==StorageMenuPhase::Warning){warning_time_-=float(dt);if(warning_time_<=0)phase_=StorageMenuPhase::List;}return true;}
}
