#include "encore/storage_data.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <set>
namespace encore::upstream {namespace {
uint32_t u32(const uint8_t*p){return uint32_t(p[0])|uint32_t(p[1])<<8|uint32_t(p[2])<<16|uint32_t(p[3])<<24;}
float real(const uint8_t*p){auto n=u32(p);float f;std::memcpy(&f,&n,4);return f;}
bool reject(std::string&e,const char*s){e=s;return false;}
uint32_t crc(const uint8_t*p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;++i){c^=(i>=16&&i<20)?0:p[i];for(int j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return ~c;}
bool safe_path(std::string_view s){if(std::any_of(s.begin(),s.end(),[](unsigned char c){return c<32||c==127;}))return false;if(s.empty()||s.front()=='/'||s.find('\\')!=s.npos||s.find(':')!=s.npos)return false;size_t at=0;while(at<s.size()){auto end=s.find('/',at);if(end==s.npos)end=s.size();auto part=s.substr(at,end-at);if(part.empty()||part=="."||part=="..")return false;at=end+1;}return s.back()!='/';}
bool utf8(std::string_view s){size_t i=0;while(i<s.size()){uint32_t c=uint8_t(s[i++]);if(c<128){if(c<32)return false;continue;}uint32_t n=0,min=0;if(c>=0xc2&&c<=0xdf){n=1;c&=31;min=128;}else if(c>=0xe0&&c<=0xef){n=2;c&=15;min=2048;}else if(c>=0xf0&&c<=0xf4){n=3;c&=7;min=65536;}else return false;if(i+n>s.size())return false;while(n--){auto b=uint8_t(s[i++]);if((b&0xc0)!=0x80)return false;c=(c<<6)|(b&63);}if(c<min||c>0x10ffff||(c>=0xd800&&c<=0xdfff))return false;}return true;}

}
uint32_t StorageView::count(StorageSection s)const{const auto k=uint32_t(s);return valid()&&k>=1&&k<=7?u32(bytes_+64+(k-1)*16+8):0;}
const uint8_t*StorageView::record(StorageSection s,uint32_t i)const{if(!valid()||i>=count(s))return nullptr;const auto*p=bytes_+64+(uint32_t(s)-1)*16;return bytes_+u32(p+4)+size_t(i)*u32(p+12);}
std::string_view StorageView::string(uint32_t i)const{const auto*p=record(StorageSection::Strings,i);if(!p||(i&&p[-1]))return {};const auto*end=bytes_+u32(bytes_+68)+count(StorageSection::Strings);const auto*q=std::find(p,end,uint8_t(0));return {reinterpret_cast<const char*>(p),size_t(q-p)};}
StoragePolicy StorageView::policy(uint32_t i)const{StoragePolicy v;const auto*p=record(StorageSection::Policies,i);if(p)v={u32(p),u32(p+4),u32(p+8),u32(p+12),u32(p+16),u32(p+20)};return v;}
StorageEquipment StorageView::equipment(uint32_t i)const{StorageEquipment v;const auto*p=record(StorageSection::Equipment,i);if(p){v.definition=u32(p);for(size_t j=0;j<7;++j)v.boosts[j]=int32_t(u32(p+4+j*4));}return v;}
float StorageView::parameter(StorageParameter k)const{for(uint32_t i=0;i<count(StorageSection::Parameters);++i){const auto*p=record(StorageSection::Parameters,i);if(u32(p)==uint32_t(k))return real(p+4);}return 0;}
std::string_view StorageView::binding(StorageBinding k)const{for(uint32_t i=0;i<count(StorageSection::Bindings);++i){const auto*p=record(StorageSection::Bindings,i);if(u32(p)==uint32_t(k))return string(u32(p+4));}return {};}
BattleResource StorageView::resource(uint32_t i)const{BattleResource v;const auto*p=record(StorageSection::Resources,i);if(p){v.id=u32(p);v.path=u32(p+4);v.kind=u32(p+8);v.width=u32(p+12);v.height=u32(p+16);v.columns=u32(p+20);v.rows=u32(p+24);std::memcpy(v.sha256,p+28,32);}return v;}
ItemLayout StorageView::layout(uint32_t i)const{ItemLayout v;const auto*p=record(StorageSection::Layouts,i);if(p){v.id=u32(p);v.role=u32(p+4);v.parent=u32(p+8);v.kind=u32(p+12);v.resource=u32(p+16);v.frame=u32(p+20);v.flags=u32(p+24);v.anchor={real(p+28),real(p+32)};v.rect={real(p+36),real(p+40),real(p+44),real(p+48)};v.color={real(p+52),real(p+56),real(p+60),real(p+64)};for(size_t j=0;j<4;++j)v.patch[j]=u32(p+68+j*4);}return v;}
std::string StorageView::reviewed_commit()const{const char*h="0123456789abcdef";std::string v;if(valid())for(size_t i=32;i<52;++i){v+=h[bytes_[i]>>4];v+=h[bytes_[i]&15];}return v;}
bool StorageView::bind_items(ItemView items,std::string&e)const{
 if(!valid()||!items.valid()||reviewed_commit()!=items.reviewed_commit()||parameter(StorageParameter::InventoryCapacity)!=items.metadata().capacity)return reject(e,"Storage item source/capacity binding rejected");
 for(uint32_t i=0;i<count(StorageSection::Policies);++i){auto p=policy(i);if(p.definition>=items.count(ItemSection::Definitions)||string(p.source)!=items.string(items.definition(p.definition).source))return reject(e,"Storage item identity binding rejected");}
 for(uint32_t i=0;i<count(StorageSection::Equipment);++i){auto p=equipment(i);if(p.definition>=items.count(ItemSection::Definitions))return reject(e,"Storage equipment definition binding rejected");if(!(items.definition(p.definition).flags&uint32_t(ItemDefinitionFlag::Equipment))&&std::any_of(p.boosts.begin(),p.boosts.end(),[](int32_t b){return b!=0;}))return reject(e,"Storage ordinary item boost rejected");if((items.definition(p.definition).flags&uint32_t(ItemDefinitionFlag::Equipment))&&!items.definition(p.definition).can_use)return reject(e,"Storage unsupported receiver equipment rejected");if(p.boosts[0]!=items.definition(p.definition).max_hp_boost||p.boosts[1]!=items.definition(p.definition).max_pp_boost)return reject(e,"Storage equipment HP/PP binding rejected");}
 e.clear();return true;
}
bool StorageData::load(const uint8_t*p,size_t n,std::string&e){
 if(!p||n<176||n>8*1024*1024||std::memcmp(p,"ENCSTG01",8)||u32(p+8)!=1||u32(p+12)!=n||u32(p+20)!=1||u32(p+24)!=1||u32(p+28)!=7||u32(p+16)!=crc(p,n))return reject(e,"Storage header/version/CRC rejected");
 for(size_t i=52;i<64;++i)if(p[i])return reject(e,"Storage reserved header rejected");bool pin=false;for(size_t i=32;i<52;++i)pin|=p[i]!=0;if(!pin)return reject(e,"Storage missing reviewed source pin");
 const uint32_t strides[]={1,24,8,8,60,84,32};size_t end=176;
 for(uint32_t i=0;i<7;++i){const auto*d=p+64+i*16;const auto count=u32(d+8);const size_t aligned=(end+3)&~size_t(3);for(size_t j=end;j<aligned;++j)if(j>=n||p[j])return reject(e,"Storage directory alignment padding rejected");end=aligned;if(u32(d)!=i+1||u32(d+4)!=end||u32(d+12)!=strides[i]||count>65536||size_t(count)*strides[i]>n-end)return reject(e,"Storage directory rejected");end+=size_t(count)*strides[i];}if(end!=n)return reject(e,"Storage trailing bytes rejected");
 StorageView v;v.bytes_=p;v.size_=n;std::set<uint32_t>strings;auto count=v.count(StorageSection::Strings);if(!count||p[u32(p+68)+count-1]!=0)return reject(e,"Storage strings rejected");
 for(uint32_t i=0;i<count;){strings.insert(i);const auto s=v.string(i);if(s.size()>4096||!utf8(s))return reject(e,"Storage UTF-8/control bytes rejected");i+=uint32_t(s.size())+1;}
 auto validstr=[&](uint32_t at){return strings.count(at)!=0&&!v.string(at).empty();};
 std::set<uint32_t>defs,rank_en,rank_zh;
 if(!v.count(StorageSection::Policies)||v.count(StorageSection::Policies)>16)return reject(e,"Storage policy count rejected");
 for(uint32_t i=0;i<v.count(StorageSection::Policies);++i){auto a=v.policy(i);if(!defs.insert(a.definition).second||!validstr(a.source)||!safe_path(v.string(a.source))||!a.doses||a.doses>65535||a.max_count!=1||!a.rank_en||a.rank_en>2000000||!a.rank_zh||a.rank_zh>2000000||!rank_en.insert(a.rank_en).second||!rank_zh.insert(a.rank_zh).second)return reject(e,"Storage item policy rejected");}
 if(v.count(StorageSection::Parameters)!=31||v.count(StorageSection::Bindings)!=23)return reject(e,"Storage parameter/binding count rejected");
 for(uint32_t i=0;i<31;++i){const auto*r=v.record(StorageSection::Parameters,i);if(u32(r)!=i+1||!std::isfinite(real(r+4)))return reject(e,"Storage parameter rejected");}
 auto boundedint=[&](StorageParameter k,float lo,float hi){const auto x=v.parameter(k);return x>=lo&&x<=hi&&x==std::floor(x);};
 if(!boundedint(StorageParameter::StorageCapacity,1,64)||!boundedint(StorageParameter::InventoryCapacity,1,64)||!boundedint(StorageParameter::Rows,1,16)||v.parameter(StorageParameter::RowPitch)<=0||v.parameter(StorageParameter::RowPitch)>64||v.parameter(StorageParameter::WarnSeconds)<=0||v.parameter(StorageParameter::WarnSeconds)>30||v.parameter(StorageParameter::EquippedScoreDelta)>=0||v.parameter(StorageParameter::LoopAround)!=1)return reject(e,"Storage parameter range rejected");
 if(v.parameter(StorageParameter::EquippedScoreDelta)<-2000000||v.parameter(StorageParameter::CursorSeconds)<=0||v.parameter(StorageParameter::CursorSeconds)>10)return reject(e,"Storage cursor parameter rejected");
 for(auto k:{StorageParameter::ReferenceWidth,StorageParameter::ReferenceHeight,StorageParameter::PlatformWidth,StorageParameter::PlatformHeight,StorageParameter::CursorWidth,StorageParameter::CursorHeight})if(v.parameter(k)<=0||v.parameter(k)>8192)return reject(e,"Storage viewport parameter rejected");
 for(auto k:{StorageParameter::CursorX,StorageParameter::CursorY})if(std::abs(v.parameter(k))>128)return reject(e,"Storage cursor offset rejected");
 if(v.parameter(StorageParameter::CursorFps)<=0||v.parameter(StorageParameter::CursorFps)>120||v.parameter(StorageParameter::CursorMoveSeconds)<=0||v.parameter(StorageParameter::CursorMoveSeconds)>10||v.parameter(StorageParameter::TextLineHeight)<=0||v.parameter(StorageParameter::TextLineHeight)>128)return reject(e,"Storage animation/font parameters rejected");
 for(uint32_t k=uint32_t(StorageParameter::CursorFrame0);k<=uint32_t(StorageParameter::CursorFrame3);++k)if(!boundedint(StorageParameter(k),0,2))return reject(e,"Storage animation frame rejected");
 for(uint32_t k=uint32_t(StorageParameter::BoostWeight0);k<=uint32_t(StorageParameter::BoostWeight6);++k)if(v.parameter(StorageParameter(k))<=0||v.parameter(StorageParameter(k))>100)return reject(e,"Storage stat weight rejected");
 if(!boundedint(StorageParameter::CounterCharacterSpacing,-128,128))return reject(e,"Storage counter character spacing rejected");
 for(uint32_t i=0;i<23;++i){const auto*r=v.record(StorageSection::Bindings,i);if(u32(r)!=i+1||!validstr(u32(r+4)))return reject(e,"Storage binding rejected");}
 for(uint32_t k=1;k<=23;++k){auto value=v.binding(StorageBinding(k));if(k==15||(k>=16&&k<=20)||k==22||k==23){if(!safe_path(value))return reject(e,"Storage source binding path rejected");}else if(k==21){size_t at=0,n=0;while((at=value.find("%s",at))!=value.npos){++n;at+=2;}std::string remain(value);while((at=remain.find("%s"))!=remain.npos)remain.erase(at,2);if(n!=2||remain.find('%')!=remain.npos)return reject(e,"Storage counter template rejected");}else{std::string remain(value);size_t at;while((at=remain.find("{item}"))!=remain.npos)remain.erase(at,6);if(remain.find_first_of("[]{}")!=remain.npos)return reject(e,"Storage unsupported text controls");}}
 if(v.count(StorageSection::Equipment)!=v.count(StorageSection::Policies)||v.count(StorageSection::Resources)>64||v.count(StorageSection::Layouts)>128)return reject(e,"Storage resource section capacity rejected");
 std::set<uint32_t>eq;for(uint32_t i=0;i<v.count(StorageSection::Equipment);++i){auto a=v.equipment(i);if(!defs.count(a.definition)||!eq.insert(a.definition).second)return reject(e,"Storage equipment policy rejected");for(auto b:a.boosts)if(b<0||b>65535)return reject(e,"Storage equipment boost rejected");}
 std::set<uint32_t>resource_ids,paths;for(uint32_t i=0;i<v.count(StorageSection::Resources);++i){auto a=v.resource(i);auto s=v.string(a.path);if(!a.id||!resource_ids.insert(a.id).second||!validstr(a.path)||!paths.insert(a.path).second||s.substr(0,9)!="graphics/"||!safe_path(s)||s.size()<4||s.substr(s.size()-4)!=".t3x"||a.kind!=1||!a.width||!a.height||a.width>8192||a.height>8192||!a.columns||!a.rows||a.columns>8192||a.rows>8192||a.width%a.columns||a.height%a.rows||!std::any_of(a.sha256,a.sha256+32,[](uint8_t b){return b!=0;}))return reject(e,"Storage graphics rejected");}
 std::set<uint32_t>layout_ids;for(uint32_t i=0;i<v.count(StorageSection::Layouts);++i){auto a=v.layout(i);if(!a.id||!layout_ids.insert(a.id).second||a.role<1||a.role>27||a.kind<1||a.kind>5||a.flags!=0||(a.parent!=item_no_index&&a.parent>=i)||(a.resource!=item_no_index&&a.resource>=v.count(StorageSection::Resources)))return reject(e,"Storage layout binding rejected");const auto*r=v.record(StorageSection::Layouts,i);for(size_t j=28;j<68;j+=4)if((!std::isfinite(real(r+j))||std::abs(real(r+j))>8192))return reject(e,"Storage layout finite value rejected");if(a.anchor.x<0||a.anchor.x>1||a.anchor.y<0||a.anchor.y>1||a.rect.z<=0||a.rect.w<=0||a.color.x<0||a.color.x>1||a.color.y<0||a.color.y>1||a.color.z<0||a.color.z>1||a.color.w<0||a.color.w>1)return reject(e,"Storage layout range rejected");
 if(a.kind==2||a.kind==4){if(a.resource==item_no_index)return reject(e,"Storage drawn layout missing resource");auto res=v.resource(a.resource);if(a.frame>=res.columns*res.rows)return reject(e,"Storage layout frame rejected");if(a.kind==4&&(uint64_t(a.patch[0])+a.patch[2]>res.width/res.columns||uint64_t(a.patch[1])+a.patch[3]>res.height/res.rows))return reject(e,"Storage ninepatch rejected");}else if(a.resource!=item_no_index||a.frame)return reject(e,"Storage unused layout resource rejected");
 for(auto patch:a.patch)if(patch>8192||(a.kind!=4&&patch))return reject(e,"Storage unused patch rejected");
 if(a.role==8||a.role==9||a.role==15||a.role==16||a.role==20||a.role==21)if(a.parent==item_no_index||(v.layout(a.parent).role!=3&&v.layout(a.parent).role!=4))return reject(e,"Storage pane role owner rejected");}
 std::set<uint32_t>roles;for(uint32_t i=0;i<v.count(StorageSection::Layouts);++i)roles.insert(v.layout(i).role);for(uint32_t role:{2u,3u,4u,5u,6u,7u,8u,9u,10u,11u,12u,13u,15u,17u,18u,19u,20u,21u})if(!roles.count(role))return reject(e,"Storage required layout role missing");
 std::vector<uint8_t>b(p,p+n);bytes_=std::move(b);e.clear();return true;
}
bool StorageData::load_file(const char*path,std::string&e){if(!path)return reject(e,"Storage path missing");FILE*f=std::fopen(path,"rb");if(!f)return reject(e,"Storage file unavailable");std::vector<uint8_t>b;uint8_t block[4096];bool ok=true;for(;;){auto n=std::fread(block,1,sizeof(block),f);if(b.size()+n>8*1024*1024){ok=false;break;}b.insert(b.end(),block,block+n);if(n<sizeof(block)){ok=!std::ferror(f);break;}}if(std::fclose(f))ok=false;if(!ok)return reject(e,"Storage file read rejected");return load(b.data(),b.size(),e);}
}
