// Explicit manual source cases; no automatic execution.
#include "encore/field_camera_area.hpp"
#include <cassert>
#include <functional>
using namespace encore::upstream;
void camarea_manual_cases(const std::vector<uint8_t>&bytes,const FieldIdentity&id){
 FieldCameraAreaData data;std::string e;assert(data.load(bytes.data(),bytes.size(),id,e));auto&d=data.records().front();assert(!data.scene_admitted());auto source=data.script_sha();for(size_t at:{size_t(0),size_t(8),size_t(24),size_t(28),size_t(36),size_t(60),size_t(124),size_t(128)}){auto bad=bytes;bad[at]^=1;assert(!data.load(bad.data(),bad.size(),id,e));assert(data.script_sha()==source);}assert(!data.load(bytes.data(),bytes.size()-1,id,e));
 FieldCameraAreaRuntime runtime;FieldCameraAreaHost host;int64_t count=0;std::array<int32_t,4>limits{};std::map<uint64_t,std::function<bool()>>waits;unsigned resolves=0;std::vector<FieldCameraLimit>writes;Vec2 offset{};
 host.bind=[](const FieldCameraAreaData&,std::string&){return true;};host.connect=[](const FieldCameraAreaDescriptor&,std::function<bool(uint64_t)>,std::function<bool(uint64_t)>,std::string&){return true;};host.resolve_reference=[&](uint32_t,std::string_view p,uint32_t&v,std::string&){assert(p==d.reference_path);v=d.reference_id;++resolves;return true;};host.observe=[&](uint32_t,uint32_t cached,FieldCameraAreaObservation&o,std::string&){o.alive=o.ancestors_admitted=o.signals_admitted=o.shape_admitted=true;o.reference_alive=cached!=0;o.reference_id=cached;o.local_scale=d.scale;o.shape_extents=d.extents;o.shape_global_position=d.shape_world[2];o.reference_size={d.reference_margins[2]-d.reference_margins[0],d.reference_margins[3]-d.reference_margins[1]};o.viewport_size={400,240};o.reference_margins=d.reference_margins;return true;};host.is_global_player=[](uint64_t b,bool&v,std::string&){v=b==1;return true;};host.adjust_camareas=[&](int64_t delta,int64_t&result,std::string&){count+=delta;result=count;return true;};host.set_limit=[&](FieldCameraLimit k,int32_t v,std::string&){limits[uint32_t(k)]=v;writes.push_back(k);return true;};host.current_limits=[&](std::array<int32_t,4>&v,std::string&){v=limits;return true;};host.set_camarea_offset=[&](Vec2 v,std::string&){offset=v;return true;};host.await_idle_frame=[&](uint64_t token,std::function<bool()>f,std::string&){waits.emplace(token,std::move(f));return true;};host.cancel_idle_frame=[&](uint64_t token,std::string&){waits.erase(token);return true;};assert(runtime.initialize(data,host,e));assert(runtime.create(d.id)&&runtime.ready(d.id)&&resolves==1);assert(runtime.body_enter(d.id,2)&&count==0&&waits.empty());assert(runtime.body_enter(d.id,1)&&count==1&&waits.size()==1);assert(limits==data.reset_limits());assert(writes.size()==4&&writes[0]==FieldCameraLimit::Top&&writes[1]==FieldCameraLimit::Left&&writes[2]==FieldCameraLimit::Right&&writes[3]==FieldCameraLimit::Bottom);
 assert(runtime.body_exit(d.id,1)&&count==0);assert(runtime.body_enter(d.id,1)&&count==1&&waits.size()==2);for(auto&[token,f]:waits){(void)token;assert(f());}waits.clear();assert(writes.size()==20);assert(limits[0]==int32_t(d.reference_margins[1])&&limits[1]==int32_t(d.reference_margins[0]));assert(limits[2]==int32_t(d.reference_margins[2])&&limits[3]==int32_t(d.reference_margins[3]));assert(offset.x==d.camera_offset.x&&offset.y==d.camera_offset.y);Vec2 size;assert(runtime.get_size(d.id,size));assert(size.x==520&&size.y==456);assert(runtime.body_exit(d.id,1));assert(runtime.body_enter(d.id,1)&&waits.size()==1);assert(runtime.exit_tree(d.id)&&waits.empty());assert(!runtime.body_enter(d.id,1));
}
