// Explicit manual parser/control cases; no automatic execution.
#include "encore/field_camera_arrows.hpp"
#include <cassert>
using namespace encore::upstream;
void camera_arrows_manual_cases(const std::vector<uint8_t>&bytes,const FieldIdentity&id){
 FieldCameraArrowsData data;std::string e;assert(data.load(bytes.data(),bytes.size(),id,e));assert(!data.scene_admitted());const auto source=data.script_sha();for(size_t at:{size_t(0),size_t(8),size_t(24),size_t(28),size_t(36),size_t(60),size_t(124),size_t(128)}){auto bad=bytes;bad[at]^=1;assert(!data.load(bad.data(),bad.size(),id,e));assert(data.script_sha()==source);}assert(!data.load(bytes.data(),bytes.size()-1,id,e));assert(data.records().size()*4==data.sprites().size()&&data.records().size()*5==data.players().size());
 const auto&r=data.records().front();FieldCameraArrowsRuntime runtime;FieldCameraArrowsHost host;std::map<uint32_t,std::function<bool(uint32_t)>>finished;std::map<uint64_t,std::pair<uint32_t,std::function<bool()>>>waits;unsigned starts=0,signals=0;
 host.bind=[](const FieldCameraArrowsData&,std::string&){return true;};host.observe=[](uint32_t,FieldArrowObservation&o,std::string&){o.alive=o.ancestors_admitted=o.descendants_ready=o.listeners_admitted=o.can_process=o.update_pending=o.visible_in_tree=o.material_admitted=true;o.world={Vec2{1,0},Vec2{0,1},Vec2{0,0}};o.parent=o.world;o.canvas_color={1,1,1,1};return true;};host.connect_animation_finished=[&](uint32_t id,std::function<bool(uint32_t)>f,std::string&){finished.emplace(id,std::move(f));return true;};host.publish_root=[](uint32_t,const FieldArrowRootState&,std::string&){return true;};host.publish_sprite=[](uint32_t,const FieldArrowSpriteState&,std::string&){return true;};host.animation_signal=[&](uint32_t id,bool started,uint32_t clip,std::string&){if(started){++starts;return true;}auto i=finished.find(id);return i==finished.end()||i->second(clip);};host.sprite_signal=[&](uint32_t id,FieldArrowSignal s,std::string&){++signals;if(s==FieldArrowSignal::FrameChanged){std::vector<std::function<bool()>>callbacks;for(auto i=waits.begin();i!=waits.end();){if(i->second.first==id){callbacks.push_back(i->second.second);i=waits.erase(i);}else++i;}for(auto&f:callbacks)if(!f())return false;}return true;};host.await_frame_changed=[&](uint32_t id,uint64_t token,std::function<bool()>f,std::string&){waits.emplace(token,std::make_pair(id,std::move(f)));return true;};host.cancel_frame_changed=[&](uint32_t,uint64_t token,std::string&){waits.erase(token);return true;};host.control_directions=[](std::vector<Vec2>&p,std::vector<Vec2>&r,std::string&){p={{1,0}};r={{-1,0}};return true;};assert(runtime.initialize(data,host,e));assert(runtime.create(r.id));assert(finished.empty());assert(runtime.ready(r.id)&&finished.size()==4);auto*main=data.player_for_target(r.id);assert(runtime.idle_leaf(main->id,.016f));assert(!runtime.root_state(r.id)->visible);assert(runtime.show(r.id));assert(runtime.idle_leaf(main->id,.016f));assert(runtime.root_state(r.id)->visible);assert(runtime.set_bounds(r.id,{50,50})&&runtime.set_offset(r.id,{0,0}));for(auto id:r.arrows)assert(runtime.sprite_state(id)->visible);
 auto*arrow=data.player_for_target(r.arrows[0]);assert(runtime.point_directions(r.id,{data.directions()[0]}));auto previous=starts;assert(runtime.point_directions(r.id,{data.directions()[0]})&&starts==previous);assert(runtime.idle_leaf(arrow->id,.2f));assert(!runtime.sprite_state(r.arrows[0])->playing);assert(runtime.unpoint_directions(r.id,{data.directions()[0]}));assert(runtime.idle_leaf(arrow->id,.2f));assert(runtime.sprite_state(r.arrows[0])->playing&&waits.size()==1);auto sender=waits.begin()->second.first;assert(runtime.idle_leaf(sender,.25f));assert(waits.empty());assert(runtime.sprite_state(sender)->frame==runtime.sprite_state(r.arrows[0])->frame);assert(runtime.handle_input_events(r.id));assert(runtime.set_arrow_visible(r.id,data.directions()[0],false));FieldArrowDraw pose;assert(runtime.draw(r.arrows[0],pose)&&!pose.visible);assert(signals>0);assert(runtime.hide(r.id));assert(runtime.idle_leaf(main->id,.2f));assert(!runtime.root_state(r.id)->visible);assert(runtime.exit_tree(r.id));assert(!runtime.show(r.id));
}
