// Explicitly manual parser/lifecycle cases; never run by automatic build.
#include "encore/field_birds.hpp"
#include <cassert>
#include <cmath>
#include <fstream>
#include <iterator>
using namespace encore::upstream;
void bird_manual_cases(const std::vector<uint8_t>&bytes,const FieldIdentity&id){
 FieldBirdData data;std::string e;assert(data.load(bytes.data(),bytes.size(),id,e));assert(!data.scene_admitted());const auto&n=data.records().front();auto expected=data.records().size();
 for(size_t offset:{size_t(0),size_t(8),size_t(24),size_t(28),size_t(36),size_t(60),size_t(124),size_t(128)}){auto bad=bytes;bad[offset]^=1;assert(!data.load(bad.data(),bad.size(),id,e));assert(data.valid()&&data.records().size()==expected);}assert(!data.load(bytes.data(),bytes.size()-1,id,e));
 FieldBirdRuntime runtime;SourceRandom rng(19),reference(19);uint32_t skin=reference.randi()%data.rules().skin_mod;reference.randf();reference.randi();reference.randi();unsigned textures=0,finished=0,timeouts=0;std::function<bool(FieldBirdClipRole)>finish;
 FieldBirdHost host;host.bind=[](const FieldBirdData&,std::string&){return true;};host.observe=[&](uint32_t,FieldBirdObservation&o,std::string&){o.alive=o.ancestors_admitted=o.ancestors_visible=o.source_signals_admitted=o.disabled_body_shape=o.clear_floor_state=o.material_admitted=true;o.parent=n.parent;o.canvas_color={1,1,1,1};return true;};host.connect=[&](const FieldBirdDescriptor&,std::function<bool(uint64_t)>,std::function<bool()>,std::function<bool()>,std::function<bool(FieldBirdClipRole)>f,std::string&){finish=std::move(f);return true;};host.texture=[&](uint32_t id,const FieldBirdSkin&,std::string&){assert(id==n.children[0]);++textures;return true;};host.publish=[](uint32_t,const FieldBirdState&,std::string&){return true;};host.body_snapshot=[](uint64_t id,FieldBirdBody&b,std::string&){b.global_player=id==1;b.local_position={-100000,0};return true;};host.animation_signal=[&](uint32_t,bool started,FieldBirdClipRole role,std::string&){if(!started){++finished;return finish(role);}return true;};host.timer_timeout=[&](uint32_t,std::string&){++timeouts;return true;};assert(runtime.initialize(data,rng,host,e));assert(runtime.create(n.id)&&runtime.ready(n.id));assert(rng.state()==reference.state());assert(runtime.state(n.id)->skin==skin&&!runtime.state(n.id)->process&&!runtime.state(n.id)->visible);assert(textures==1);
 assert(runtime.screen_enter(n.id));assert(rng.raw_draw_count()==8&&textures==2);assert(runtime.body_enter(n.id,1));assert(runtime.state(n.id)->clip==FieldBirdClipRole::Fly);assert(runtime.state(n.id)->input.x==1&&runtime.state(n.id)->input.y==-1);
 auto old=*runtime.state(n.id);assert(runtime.idle_process(n.id,.125,true));auto now=runtime.state(n.id);float world_x=(now->position.x-old.position.x)*n.parent[0].x;assert(std::abs(world_x-old.speed*.125f)<.01f);
 assert(runtime.idle_leaf(n.children[6],n.timer_wait,true));assert(timeouts==0&&runtime.state(n.id)->timer_running);assert(runtime.idle_leaf(n.children[6],.01,true));assert(timeouts==1&&!runtime.state(n.id)->timer_running);
 assert(runtime.screen_exit(n.id));assert(rng.raw_draw_count()==12&&!runtime.state(n.id)->visible&&!runtime.state(n.id)->process);assert(runtime.play(n.id,FieldBirdClipRole::Idle));assert(runtime.seek(n.id,data.clip(n.profile,FieldBirdClipRole::Idle)->length,true));assert(!runtime.state(n.id)->animation_playing&&finished==0);
 assert(runtime.play(n.id,FieldBirdClipRole::Idle));assert(runtime.seek(n.id,0,true));assert(runtime.idle_leaf(n.children[4],data.clip(n.profile,FieldBirdClipRole::Idle)->length,true));assert(finished==1&&(runtime.state(n.id)->clip==FieldBirdClipRole::Hop||runtime.state(n.id)->clip==FieldBirdClipRole::HopRight));assert(runtime.idle_leaf(n.children[4],.2,true));assert(finished==2&&runtime.state(n.id)->clip==FieldBirdClipRole::Idle);
 FieldBirdDraw draw;assert(runtime.draw(n.id,draw));assert(!draw.visible);assert(runtime.exit_tree(n.id));assert(!runtime.screen_enter(n.id));
}
