#pragma once
#include "battle_renderer.hpp"
#include "loading_texture.hpp"
#include "encore/field_butterfly.hpp"
#include <fstream>
class FieldButterflyRenderer{
 const encore::upstream::FieldButterflyData*data_=nullptr;std::vector<std::pair<uint32_t,encore::ctr::LoadingSpriteSheet>>sheets_;
 static uint32_t crc(const std::vector<uint8_t>&b){uint32_t c=~0u;for(auto v:b){c^=v;for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
public:
 ~FieldButterflyRenderer(){free();}void free(){if(!sheets_.empty())C3D_FrameSync();for(auto&s:sheets_)encore::ctr::loading_sprite_sheet_free(s.second);sheets_.clear();data_=nullptr;}
 bool load(const encore::upstream::FieldButterflyData&d,const char*root,std::string&e){if(!d.valid()||!root||!*root){e="Butterfly GPU source owner absent";return false;}FieldButterflyRenderer next;for(const auto&a:d.assets()){const auto path=std::string(root)+a.path;std::ifstream f(path,std::ios::binary);if(!f){e="Butterfly GPU texture unavailable";return false;}f.seekg(0,std::ios::end);if(f.tellg()!=a.bytes){e="Butterfly GPU source byte count";return false;}f.seekg(0);std::vector<uint8_t>raw(a.bytes);if(!f.read(reinterpret_cast<char*>(raw.data()),a.bytes)||crc(raw)!=a.crc){e="Butterfly GPU source CRC";return false;}next.sheets_.emplace_back(a.index,nullptr);auto&sheet=next.sheets_.back().second;sheet=encore::ctr::loading_sprite_sheet_acquire(path.c_str(),&e);if(!sheet||encore::ctr::loading_sprite_sheet_count(sheet)!=1){if(e.empty())e="Butterfly GPU sheet count";return false;}auto im=encore::ctr::loading_sprite_sheet_get_image(sheet,0);if(!im.tex||!im.subtex||Tex3DS_SubTextureRotated(im.subtex)||im.subtex->width!=a.width||im.subtex->height!=a.height){e="Butterfly GPU source shape";return false;}C3D_TexSetFilter(im.tex,GPU_NEAREST,GPU_NEAREST);}C3D_FrameSync();sheets_.swap(next.sheets_);data_=&d;e.clear();return true;}
 bool draw(const encore::upstream::FieldButterflyRuntime&r,uint32_t id,encore::upstream::Vec2 camera,float width,float height,float left,float top,bool ancestor_visible,uint32_t inherited_color,float depth,std::string&e)const{const auto*s=r.state(id);auto*b=data_?data_->binding(id):nullptr;if(!b||!s||r.content()!=data_||!s->ready){e="Butterfly GPU live source instance";return false;}if(!std::isfinite(camera.x)||!std::isfinite(camera.y)||!std::isfinite(width)||!std::isfinite(height)||!std::isfinite(left)||!std::isfinite(top)||!std::isfinite(depth)||width<=0||height<=0){e="Butterfly GPU viewport/camera";return false;}if(!s->alive||!s->visible||!ancestor_visible){e.clear();return true;}const auto*a=data_->asset(s->asset);encore::ctr::LoadingSpriteSheet sheet=nullptr;for(const auto&entry:sheets_)if(entry.first==s->asset)sheet=entry.second;if(!a||!sheet||s->frame>=data_->frames()){e="Butterfly GPU source art/frame";return false;}auto im=encore::ctr::loading_sprite_sheet_get_image(sheet,0);auto sub=*im.subtex;const uint32_t frame_width=a->width/data_->frames();const float du=(sub.right-sub.left)/a->width,origin=sub.left;sub.left=origin+s->frame*frame_width*du;sub.right=origin+(s->frame+1)*frame_width*du;sub.width=uint16_t(frame_width);if(s->flip)std::swap(sub.left,sub.right);im.subtex=&sub;auto world=r.world_position(id);float ox=s->sprite_offset.x-frame_width/2.f,oy=s->sprite_offset.y-a->height/2.f;if(data_->pixel_snap()){ox=std::floor(ox);oy=std::floor(oy);}float x=left+width/2-camera.x+world.x+(s->sprite_position.x+ox)*b->parent_scale,y=top+height/2-camera.y+world.y+(s->sprite_position.y+oy)*b->parent_scale;if(data_->pixel_snap()){x=std::floor(x+.5f);y=std::floor(y+.5f);}auto channel=[](uint32_t value,unsigned shift,float source){return uint32_t(std::floor(float((value>>shift)&255)*source+.5f));};uint32_t color=channel(inherited_color,0,b->color.x)|channel(inherited_color,8,b->color.y)<<8|channel(inherited_color,16,b->color.z)<<16|channel(inherited_color,24,b->color.w)<<24;C2D_ImageTint tint;C2D_PlainImageTint(&tint,color,0);if(!C2D_DrawImageAt(im,x,y,depth,&tint,b->parent_scale,b->parent_scale)){e="Butterfly GPU image submission";return false;}e.clear();return true;}
};
