#pragma once
#include "field_equipment_renderer.hpp"
#include "encore/field_psi.hpp"
#include <fstream>
// Source PSI graphics use real tex3ds sheets admitted before the GPU frame.
// Fonts, main panel and cursor borrow the existing checked Pause owners.
class FieldPsiRenderer {
 using Data=encore::upstream::FieldPsiData;using Menu=encore::upstream::FieldPsiMenu;using Phase=encore::upstream::FieldPsiPhase;using Role=encore::upstream::FieldPsiLayout;using ArtRole=encore::upstream::FieldLayoutRole;using Rect=encore::upstream::BattleValue;
 struct Asset{uint32_t role=0,width=0,height=0;encore::ctr::LoadingSpriteSheet sheet=nullptr;};
 const Data*data_=nullptr;const FieldEquipmentRenderer*art_=nullptr;encore::upstream::ItemView items_;std::vector<Asset>assets_;mutable std::string error_;mutable Rect clip_{};
 bool fail(const char*m)const{error_=m;return false;}static float pixel(float v){return std::floor(v+.5f);}
 const Asset*asset(uint32_t role)const{for(const auto&a:assets_)if(a.role==role)return&a;return nullptr;}
 static uint32_t tint(Rect c){return encore::ctr::loading_menu_flavor_color(C2D_Color32f(c.x,c.y,c.z,c.w));}
 Rect rect(Role role,float dx,float dy)const{auto r=data_->layout(role);r.x+=dx;r.y+=dy;return r;}
 bool region(uint32_t role,uint32_t u,uint32_t v,uint32_t sw,uint32_t sh,Rect r)const{auto*a=asset(role);if(!a||!a->sheet||!sw||!sh||u>a->width||v>a->height||sw>a->width-u||sh>a->height-v||r.z<0||r.w<0)return fail("PSI source texture region");if(r.z==0||r.w==0)return true;r.x=pixel(r.x);r.y=pixel(r.y);float x0=std::max(r.x,clip_.x),y0=std::max(r.y,clip_.y),x1=std::min(r.x+r.z,clip_.x+clip_.z),y1=std::min(r.y+r.w,clip_.y+clip_.w);if(x1<=x0||y1<=y0)return true;auto image=encore::ctr::loading_sprite_sheet_get_image(a->sheet,0);auto sub=*image.subtex;float du=(sub.right-sub.left)/a->width,dv=(sub.bottom-sub.top)/a->height,ox=sub.left,oy=sub.top;sub.left=ox+(u+(x0-r.x)*sw/r.z)*du;sub.right=ox+(u+(x1-r.x)*sw/r.z)*du;sub.top=oy+(v+(y0-r.y)*sh/r.w)*dv;sub.bottom=oy+(v+(y1-r.y)*sh/r.w)*dv;sub.width=uint16_t(pixel(x1-x0));sub.height=uint16_t(pixel(y1-y0));if(!sub.width||!sub.height)return true;return C2D_DrawImageAt({image.tex,&sub},pixel(x0),pixel(y0),0,nullptr,1,1)||fail("PSI GPU submit rejected");}
 bool patch(uint32_t role,Rect r,Rect p)const{auto*a=asset(role);if(!a)return fail("PSI source panel missing");if(p.x<0||p.y<0||p.z<0||p.w<0||p.x+p.z>a->width||p.y+p.w>a->height||r.z<p.x+p.z||r.w<p.y+p.w)return fail("PSI source patch geometry");const uint32_t us[]={0,uint32_t(p.x),a->width-uint32_t(p.z),a->width},vs[]={0,uint32_t(p.y),a->height-uint32_t(p.w),a->height};const float xs[]={r.x,r.x+p.x,r.x+r.z-p.z,r.x+r.z},ys[]={r.y,r.y+p.y,r.y+r.w-p.w,r.y+r.w};for(unsigned y=0;y<3;++y)for(unsigned x=0;x<3;++x)if(us[x+1]>us[x]&&vs[y+1]>vs[y]&&!region(role,us[x],vs[y],us[x+1]-us[x],vs[y+1]-vs[y],{xs[x],ys[y],xs[x+1]-xs[x],ys[y+1]-ys[y]}))return false;return true;}
 bool sprite(uint32_t role,Rect r)const{auto*a=asset(role);if(!a)return fail("PSI portrait binding absent");r.x+=(r.z-a->width)/2;r.y+=(r.w-a->height)/2;r.z=float(a->width);r.w=float(a->height);return region(role,0,0,a->width,a->height,r);}
 bool text(const BattleRenderer&font,std::string_view s,Rect r,uint32_t color,bool center=false)const{const std::string value(s);float x=r.x+(center?(r.z-font.text_width(value.c_str()))/2:0);return font.draw_text_clipped(value.c_str(),pixel(x),pixel(r.y),std::max(r.x,clip_.x),std::max(r.y,clip_.y),std::min(r.x+r.z,clip_.x+clip_.z),std::min(r.y+r.w,clip_.y+clip_.w),color)||fail("PSI source glyph unavailable");}
 bool cursor(const Menu&m,Rect label)const{Rect r;if(!art_->borrowed_rect(ArtRole::PauseCursor,r))return fail("PSI checked cursor unavailable");auto o=data_->layout(Role::CursorOffset),c=data_->layout(Role::CursorCenter);r.x=label.x+o.x+c.x-r.z/2;r.y=label.y+o.y+c.y-r.w/2;auto field=art_->content();using P=encore::upstream::FieldParameter;auto i=uint32_t(std::fmod(m.cursor_time()*field.parameter(P::CursorFps),4.0));auto frame=uint32_t(field.parameter(P(uint32_t(P::CursorFrame0)+i)));return art_->draw_borrowed_art(ArtRole::PauseCursor,r,frame,clip_.x,clip_.y,clip_.z,clip_.w)||fail(art_->error().c_str());}
 static uint32_t crc(const std::vector<uint8_t>&b){uint32_t c=~0u;for(auto v:b){c^=v;for(unsigned j=0;j<8;++j)c=(c>>1)^(0xedb88320u&uint32_t(-int32_t(c&1)));}return~c;}
public:
 FieldPsiRenderer()=default;FieldPsiRenderer(const FieldPsiRenderer&)=delete;FieldPsiRenderer&operator=(const FieldPsiRenderer&)=delete;~FieldPsiRenderer(){free();}
 void free(){if(!assets_.empty())C3D_FrameSync();for(auto&a:assets_)if(a.sheet)encore::ctr::loading_sprite_sheet_free(a.sheet);assets_.clear();data_=nullptr;art_=nullptr;items_={};}
 bool ready()const{return data_!=nullptr;}const std::string&error()const{return error_;}
 bool load(const Data&d,const FieldEquipmentRenderer*art,encore::upstream::ItemView items,const char*root,std::string&e){using B=encore::upstream::FieldBinding;std::string pin;for(auto byte:d.source_pin()){const char digits[]="0123456789abcdef";pin+=digits[byte>>4];pin+=digits[byte&15];}if(!d.valid()||!art||!art->ready()||!items.valid()||items.reviewed_commit()!=pin||!root||!*root||art->content().reviewed_commit()!=pin||art->content().binding(B::MainFont)!=d.source_font()||art->content().binding(B::NumberFont)!=d.number_font()){e="PSI checked font/art owners required";return false;}FieldPsiRenderer next;for(const auto&source:d.assets()){if(!source.file_bytes||!source.crc32){e="PSI source texture conversion receipt absent";return false;}std::string path=std::string(root)+source.path;std::ifstream f(path,std::ios::binary);if(!f){e="PSI GPU asset unavailable";return false;}f.seekg(0,std::ios::end);auto n=f.tellg();if(n!=source.file_bytes){e="PSI GPU asset size differs from source receipt";return false;}f.seekg(0);std::vector<uint8_t>b(static_cast<size_t>(n));if(!f.read(reinterpret_cast<char*>(b.data()),n)||crc(b)!=source.crc32){e="PSI GPU asset CRC rejected";return false;}Asset a;a.role=source.role;a.width=source.width;a.height=source.height;a.sheet=encore::ctr::loading_sprite_sheet_acquire(path.c_str(),&e);next.assets_.push_back(a);if(!a.sheet||encore::ctr::loading_sprite_sheet_count(a.sheet)!=1)return false;auto image=encore::ctr::loading_sprite_sheet_get_image(a.sheet,0);if(!image.tex||!image.subtex||Tex3DS_SubTextureRotated(image.subtex)||image.subtex->width!=source.width||image.subtex->height!=source.height){e="PSI GPU source texture dimensions";return false;}C3D_TexSetFilter(image.tex,GPU_NEAREST,GPU_NEAREST);}next.data_=&d;next.art_=art;next.items_=items;C3D_FrameSync();std::swap(data_,next.data_);std::swap(art_,next.art_);std::swap(items_,next.items_);assets_.swap(next.assets_);e.clear();return true;}
 // Exact borrowed font metrics are used by the menu's source 3/4-line decision.
 // The same resulting UTF-8 lines are drawn; no system-font fallback is used.
 static std::vector<std::string>wrapped_lines(const BattleRenderer&font,std::string_view text,float width){std::vector<std::string>lines;std::string line,word;auto push_word=[&](){if(word.empty())return;std::string test=line+word;if(!line.empty()&&font.text_width(test.c_str())>width){while(!line.empty()&&line.back()==' ')line.pop_back();lines.push_back(line);line.clear();}size_t at=0;uint32_t cp;while(at<word.size()){auto start=at;if(!encore::utf8_next(word,at,cp)){line.clear();word.clear();return;}auto glyph=word.substr(start,at-start);if(!line.empty()&&font.text_width((line+glyph).c_str())>width){lines.push_back(line);line.clear();}line+=glyph;}word.clear();};size_t at=0;uint32_t cp;while(at<text.size()){auto start=at;if(!encore::utf8_next(text,at,cp))return{};if(cp=='\n'){push_word();lines.push_back(line);line.clear();}else if(cp==' '){push_word();line+=' ';}else{word.append(text.substr(start,at-start));if(cp>=0x2e80){push_word();}}}push_word();lines.push_back(line);return lines;}
 static bool measure(const BattleRenderer&font,const FieldEquipmentRenderer&art,std::string_view text,float width,float&measured,float&wrapped_height,float&line,std::string&e){if(!art.ready()||width<=0){e="PSI source measure owners";return false;}const std::string value(text);measured=font.text_width(value.c_str());line=font.text_height(art.content().parameter(encore::upstream::FieldParameter::MainLineHeight));auto lines=wrapped_lines(font,text,width);if(lines.empty()||line<=0){e="PSI source measure failed";return false;}wrapped_height=line*lines.size();e.clear();return true;}
 bool draw(const Menu&m,const BattleRenderer&font,const BattleRenderer&number,float width,float height,float left=0,float top=0)const{using namespace encore::upstream;if(!m.visible())return true;if(!data_||m.content()!=data_||!art_->ready()||!std::isfinite(width)||!std::isfinite(height)||width<=0||height<=0)return fail("PSI draw owner/viewport rejected");clip_={left,top,width,height};auto platform=data_->layout(Role::PlatformViewport);float dx=left+(width-platform.x)/2,dy=top+(height-platform.y)/2+m.animation_y();auto panel=rect(Role::Panel,dx,dy),patch_shape=data_->layout(Role::PanelPatch);if(!art_->draw_borrowed_art(ArtRole::DescriptionPanel,panel,0,left,top,width,height,&patch_shape))return fail(art_->error().c_str());
  auto bar=rect(Role::CharacterBar,dx,dy);if(!patch(1,bar,data_->layout(Role::BarPatch)))return false;auto title=rect(Role::MenuTitle,dx,dy);auto inside=rect(Role::TitleBox,dx,dy),inside_patch=data_->layout(Role::TitlePatch),inside_expand=data_->layout(Role::TitleExpand);inside.x-=inside_expand.x;inside.y-=inside_expand.y;inside.z+=inside_expand.x+inside_expand.z;inside.w+=inside_expand.y+inside_expand.w;if(!art_->draw_borrowed_art(ArtRole::PauseInside,inside,0,left,top,width,height,&inside_patch)||!text(font,m.locale().title,title,0xffffffffu,true))return false;auto portrait=data_->layout(Role::Portrait);uint32_t count=0;for(const auto&p:data_->portraits()){const FieldPsiMember*member=nullptr;for(const auto&candidate:m.snapshot().party)if(candidate.character.character_id==p.character)member=&candidate;if(!member||!member->maximum_pp)continue;Rect r{bar.x+portrait.x+count*portrait.z,bar.y+portrait.y,portrait.z,portrait.w};if(!sprite(m.caster()&&m.caster()->character.character_id==p.character?p.highlight:p.normal,r))return false;++count;}
  if(count>1||m.groups().size()>m.rows())return fail("PSI visible source indicators/scrollbar require additional UI capability");auto normal=tint(items_.parameter(ItemParameter::NormalColor)),disabled=tint(items_.parameter(ItemParameter::DisabledColor));auto origin=data_->layout(Role::RowOrigin),levelorigin=data_->layout(Role::LevelOrigin),stride=data_->layout(Role::RowStride),levelstride=data_->layout(Role::LevelStride);for(uint32_t row=0;row<m.rows()&&m.page()+row<m.groups().size();++row){const auto&g=m.groups()[m.page()+row];auto*s=data_->skill(g.front());Rect label{panel.x+origin.x,panel.y+origin.y+row*stride.x,origin.z,origin.w};bool available=false;for(auto id:g){auto*variant=data_->skill(id);available|=variant->level<0||m.selectable(*variant);}if(!text(font,m.locale().code=="en"?s->name_en:s->name_zh,label,available?normal:disabled))return false;for(uint32_t column=0;column<g.size();++column){auto*variant=data_->skill(g[column]);Rect level{label.x+origin.z+levelorigin.x+column*levelstride.x,label.y,levelstride.y,levelstride.z};auto index=variant->level<0?0:uint32_t(variant->level);if(!text(font,data_->level_labels()[index],level,variant->level<0||m.selectable(*variant)?normal:disabled))return false;if(m.phase()==Phase::Skills&&row==m.row()&&column==m.column()&&!cursor(m,level))return false;}}
  auto divider=rect(Role::Divider,dx,dy);float x0=std::max(divider.x,clip_.x),y0=std::max(divider.y,clip_.y),x1=std::min(divider.x+divider.z,clip_.x+clip_.z),y1=std::min(divider.y+divider.w,clip_.y+clip_.w);if(x1>x0&&y1>y0)BattleRenderer::draw_rect(x0,y0,x1-x0,y1-y0,tint(data_->layout(Role::DividerColor)));auto description=rect(Role::Description,dx,dy);auto lines=m.description_wraps()?wrapped_lines(font,m.description(),description.z):std::vector<std::string>{std::string(m.description())};const float line=font.text_height(art_->content().parameter(FieldParameter::MainLineHeight));const auto policy=data_->layout(Role::DescriptionPolicy);for(uint32_t i=0;i<lines.size()&&i<uint32_t(policy.z);++i){auto r=description;r.y+=i*line;r.w=line;if(!text(font,lines[i],r,normal))return false;}
  if(m.cost_visible()){auto r=rect(Role::CostPanel,dx,dy);r.y+=m.cost_animation_y()-data_->cost_base_y();if(!patch(3,r,data_->layout(Role::CostPatch)))return false;auto label=data_->layout(Role::CostLabel),value=data_->layout(Role::CostValue);label.x+=r.x;label.y+=r.y;value.x+=r.x;value.y+=r.y;auto*s=m.selected();if(!text(number,m.locale().pp,label,normal)||!text(number,std::to_string(s?s->pp:0),value,normal,true))return false;}
  if(m.phase()==Phase::Targets){auto target=rect(Role::TargetPanel,dx,dy),head=rect(Role::TargetTitle,dx,dy),origin=data_->layout(Role::TargetOrigin),policy=data_->layout(Role::TargetPolicy),expand=data_->layout(Role::TargetExpand);target.w=policy.x+origin.y-policy.x+m.targets().size()*data_->layout(Role::RowOrigin).w+(m.targets().size()?m.targets().size()-1:0)*policy.z+policy.y;auto expanded=target;expanded.x-=expand.x;expanded.y-=expand.y;expanded.z+=expand.x;expanded.w+=expand.y;if(!patch(2,expanded,data_->layout(Role::TargetPatch))||!text(font,m.locale().whom,head,C2D_Color32f(data_->layout(Role::TargetTitleColor).x,data_->layout(Role::TargetTitleColor).y,data_->layout(Role::TargetTitleColor).z,data_->layout(Role::TargetTitleColor).w)))return false;for(uint32_t i=0;i<m.targets().size();++i){const FieldPsiMember*member=nullptr;for(const auto&candidate:m.snapshot().party)if(candidate.character.character_id==m.targets()[i])member=&candidate;if(!member)return fail("PSI source target disappeared");Rect r{target.x+origin.x,target.y+origin.y+i*origin.z,origin.w,data_->layout(Role::RowOrigin).w};if(i==m.target_selection()){auto color=data_->layout(Role::HighlightColor);float a=std::max(r.x,clip_.x),b=std::max(r.y,clip_.y),c=std::min(r.x+r.z,clip_.x+clip_.z),d=std::min(r.y+r.w,clip_.y+clip_.w);if(c>a&&d>b)BattleRenderer::draw_rect(a,b,c-a,d-b,tint(color));}if(!text(font,member->character.nickname,r,normal))return false;if(i==m.target_selection()&&!cursor(m,r))return false;}}
  return true;
 }
};
