#!/usr/bin/env python3
"""Checked source-derived defaults and bounded original-session save contract.

The embedded ENCSNAP1 templates are data, not previously played saves. Legacy
default IDs stay unchanged; startup resource IDs are placeholders. The New Game
controller stages source UID allocation and commits it only with accepted naming.
"""
from __future__ import annotations
import argparse, copy, csv, hashlib, io, json, re, struct, sys, zlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from tools.extract_battle_entry import Extractor, one, require
from tools.native_content import OPCODES
from tools.source_settings import choices as settings_choices
IR=ROOT/'content/native-session.json'
PACK=ROOT/'romfs/data/opening.encsession'
def read(p): return json.loads(Path(p).read_text())
def digest(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def source_startup_characters(ex, save, overrides, defaults):
    """Bounded PartyMember.init_from_dict, including EXP and equipment clamps.

    Resource UIDs are unique deterministic placeholders, never source random
    IDs. New Game stages replacement using a copy of the shared RNG/ledger;
    saved IDs remain opaque and are never regenerated by the snapshot codec.
    """
    pm=ex.text('Scripts/global/PartyMember.gd')
    character_source=ex.text('Scripts/global/Character.gd')
    inventory_source=ex.text('Scripts/global/Inventory.gd')
    item_source=ex.text('Scripts/global/Item.gd')
    global_source=ex.text('Scripts/global/global.gd')
    expected=[
        '_set_exp(max(dict["exp"], _level_to_exp(dict["level"])) as int, false)',
        '_exp = min(new_value, _level_to_exp(LEVEL_CAP)) as int',
        'var level_tens := min(level / 10, stats_dict_for_member[stat_name].size() - 2)',
        'var level_units := level - (level_tens * 10)',
        'return int(lerp(lower_stat, upper_stat, level_units / 10.0))',
        '_learned_skills.sort_custom(self, "_sort_skills")',
        'total_boosts[stat] = _permanent_boosts.get(stat, 0) + _inventory.get_equipment_boosts().get(stat, 0)',
        'return 0 if level == 1 else _level_to_exp(LEVEL_CAP) if level > LEVEL_CAP else int(level * level * (level + 1) * .75)',
    ]
    require(all(value in pm for value in expected),'Startup PartyMember initialization rules changed')
    require('HP: _hp = int(clamp(new_value, 0, get_max_hp()))' in character_source and
            'PP: _pp = int(clamp(new_value, 0, get_max_pp()))' in character_source,
            'Startup HP/PP clamp changed')
    require('item.get("doses", 1), int(item.get("uid", Item.get_uid(Item.used_uids_tab)))' in inventory_source and
            'self.doses = get_data().get("doses", 1)' in item_source,
            'Startup item initialization changed')
    require('save[key].append(item)' in global_source and 'if !item in save[key]:' in global_source,
            'Startup primitive-array override merge changed')
    def merge(value, override):
        result=copy.deepcopy(value)
        for key, entry in override.items():
            old=result.get(key)
            if isinstance(old,dict) and isinstance(entry,dict):result[key]=merge(old,entry)
            elif isinstance(old,list) and isinstance(entry,list):
                if not entry or (old and isinstance(old[0],(dict,list))):result[key]=copy.deepcopy(entry)
                else:result[key]=old+[v for v in entry if v not in old]
            else:result[key]=copy.deepcopy(entry)
        return result
    steps=ex.yaml('Data/NamingSequences/intro.yaml')['scenario']
    order=[step['target'] for step in steps if step['type']=='naming' and step['target'] in save]
    require(order==['ninten','ana','lloyd','pippi','teddy'],'Unreviewed startup naming roster')
    constants=dict(re.findall(r'^const ([A-Z]+) := "([a-z]+)"',pm,re.M))
    table=one(r'const PLAYER_STAT_TARGET_TABLE := \{(.*?)^\}',pm,'startup stat table',re.M|re.S)[1]
    targets={constants[symbol]:{key.lower():json.loads(values) for key,values in re.findall(r'\b([A-Z]+):\s*(\[[^\]]+\])',body)}
             for symbol,body in re.findall(r'^\t([A-Z]+): \{(.*?)^\t\},',table,re.M|re.S)}
    stat_names=['maxhp','maxpp','offense','defense','speed','iq','guts']
    skill_order=re.findall(r'"([^"]+)"',one(r'const SKILLS_ORDER := \[(.*?)^\]',pm,'startup skills order',re.M|re.S)[1])
    slots=json.loads(one(r'^const SLOTS := (\[[^\n]+\])',inventory_source,'equipment slots')[1])
    cap=int(one(r'^const LEVEL_CAP := (\d+)',pm,'startup level cap')[1])
    def level_exp(level):return 0 if level==1 else int(min(level,cap)**2*(min(level,cap)+1)*.75)
    next_uid=max([item['uid'] for c in defaults['characters'] for item in c['inventory']]+[item['uid'] for item in defaults['key_items']])+1
    roster=[];derivation=[]
    for identity in order:
        value=merge(save[identity],overrides[identity])
        require(value['status']==[] and not value.get('permanent_boosts') and value['nickname']=='',
                'Unreviewed initial startup modifiers/nickname')
        xp=min(max(value['exp'],level_exp(value['level'])),level_exp(cap))
        level=1
        while level<cap and xp>=level_exp(level+1):level+=1
        require(list(targets[identity])==stat_names,'Startup stat table schema changed')
        base={}
        for stat,values in targets[identity].items():
            tens=min(level//10,len(values)-2);units=level-tens*10
            base[stat]=int(values[tens]+(values[tens+1]-values[tens])*units/10.0)
        equipped={};inventory=[]
        for index,serialized in enumerate(value['inventory']):
            item_data=ex.yaml('Data/Items/'+serialized['item_name']+'.yaml')
            doses=serialized.get('doses',1)
            if doses==-1:doses=item_data.get('doses',1)
            uid=defaults['characters'][0]['inventory'][index]['uid'] if identity==order[0] else next_uid
            if identity!=order[0]:next_uid+=1
            inventory.append(dict(item_id=serialized['item_name'],equipped=serialized.get('equipped',False),doses=doses,uid=uid))
            if serialized.get('equipped',False):
                require(item_data['slot'] in slots,'Unreviewed startup equipment slot')
                if item_data['slot'] not in equipped:equipped[item_data['slot']]=item_data['boost']
        boosts={stat:sum(equipped.get(slot,{}).get(stat,0) for slot in slots) for stat in stat_names}
        effective={stat:base[stat]+boosts[stat] for stat in stat_names}
        skills=value['learnedSkills']
        require(len(set(skills))==len(skills) and all(skill in skill_order for skill in skills),'Unreviewed startup skill ordering')
        skills=sorted(skills,key=skill_order.index)
        current=dict(character_id=identity,nickname=value['nickname'],
                     level=level,experience=xp,hp=max(0,min(value['hp'],effective['maxhp'])),pp=max(0,min(value['pp'],effective['maxpp'])),
                     permanent_boosts=[],affinity_multipliers=[dict(id=k,value=v)for k,v in value.get('affinity_multipliers',{}).items()],
                     learned_skills=skills,status=[],inventory=inventory)
        roster.append(current)
        derivation.append(dict(character_id=identity,stat_targets=targets[identity],base_stats=base,equipment_boosts=boosts,effective_stats=effective))
    legacy_leader=copy.deepcopy(roster[0]);legacy_leader['nickname']=defaults['characters'][0]['nickname']
    require(legacy_leader==defaults['characters'][0],'Source startup leader differs from unchanged legacy defaults')
    return roster,derivation

def extract():
    ex=Extractor(ROOT)
    save=ex.yaml('Data/save_new_game.yaml');overrides=ex.yaml('Data/save_overrides.yaml')
    global_source=ex.text('Scripts/global/global.gd');data_source=ex.text('Scripts/global/globalData.gd')
    ex.data('Scripts/global/PartyMember.gd');ex.data('Scripts/global/Item.gd')
    ex.data('Scripts/global/Inventory.gd');ex.data('Scripts/global/Character.gd')
    source_save=one(r'^func save_game\(.*?\n(.*?)(?=^func )',global_source,'save_game',re.M|re.S)[1]
    require(source_save.index('save_from_dict(num, save_dict)')<source_save.index('globaldata.flags["saved"] = true'),'Saved flag write order changed')
    saved_flag=one(r'globaldata.flags\["([^"]+)"\] = true',source_save,'saved flag')[1]
    required=['content/native-opening.json','content/native-house.json','content/native-battle.json','content/native-items.json','content/native-round.json','content/doll-round.json']
    room,house,battle,items,first,second=[read(ROOT/p) for p in required]
    leader=save['party'][0];require(save['party']==[battle['party']['id']],'Unsupported party/owner')
    character=dict(save[leader]);character.update(overrides[leader])
    require(character['status']==[] and 'permanent_boosts'not in character,'Unreviewed initial modifiers')
    cap=ex.yaml('Data/Items/'+save[leader]['inventory'][0]['item_name']+'.yaml')
    key=ex.yaml('Data/Items/'+save['key_items'][0]['item_name']+'.yaml')
    require(len(items['initial_inventory'])==len(character['inventory'])==len(save['key_items'])==1,'Unreviewed inventory scope')
    require('self.doses = get_data().get("doses", 1)'in ex.text('Scripts/global/Item.gd'),'Item default doses changed')
    # Existing opening bypasses the naming UI; choose the pinned English default
    # name, without adopting debug auto_name's Tester/player-name side effect.
    rows=csv.DictReader(io.StringIO(ex.text('Translations/TranslatedText/menus - sheet.csv')))
    names={row['key']:row['en'] for row in rows}
    nickname=names[battle['party']['nickname_default_translation_key']]
    def item(source,uid):
        value=cap if source['item_name']==character['inventory'][0]['item_name'] else key
        return dict(item_id=source['item_name'],equipped=source.get('equipped',False),doses=value.get('doses',1),uid=uid)
    inventory=[item(character['inventory'][0],items['initial_inventory'][0]['id'])]
    key_items=[item(save['key_items'][0],max(x['id'] for x in items['initial_inventory'])+1)]
    flags=[dict(id=room['strings'][f['name_string']],value=bool(f['default_value']))for f in room['sections']['Flag']]
    for f in room['sections']['InitialFlag']:flags[f['flag_index']]['value']=bool(f['value'])
    shadow=one(r'^var respawn_shadow_effect := "([^"]+)"',data_source,'shadow effect')[1]
    player=one(r'^var player_name := "([^"]*)"',data_source,'player name')[1]
    scene=room['sections']['Scene'][0]
    require(save['scene']==room['strings'][scene['source_scene_string']] and save['scenename']==room['strings'][scene['display_name_string']],'Scene defaults mismatch')
    effective=battle['party']['effective_stats']
    defaults=dict(scene_id=save['scene'],scene_label=save['scenename'],position_x=scene['spawn'][0],position_y=scene['spawn'][1],direction_x=save['dirX'],direction_y=save['dirY'],run_sound=save['runsound'],shadow_effect=shadow,playtime_seconds=save['playtime'],settings=dict(text_speed=save['textspeed'],menu_flavor=save['menuflavor'],button_prompts=save['buttonprompts'],description=save['description']),player_name=player,favorite_food=save['favoritefood'],cash=save['cash'],bank=save['bank'],earned_cash=save['earned_cash'],characters=[dict(character_id=leader,nickname=nickname,level=character['level'],experience=character['exp'],hp=effective['hp'],pp=effective['pp'],permanent_boosts=[],affinity_multipliers=[dict(id=k,value=v)for k,v in character.get('affinity_multipliers',{}).items()],learned_skills=character['learnedSkills'],status=[],inventory=inventory)],party=[leader],key_items=key_items,storage=[],flags=flags,object_flags=[],seen_dialogue_flags=[],encountered=[],keys=[dict(id=k,value=v)for k,v in save['keys'].items()],rare_drops=[],source_version=one(r'^const GAME_VERSION := "([^"]+)"',global_source,'version')[1],saved_at='',is_debug=False,rng_policy=1)
    stats=list(battle['party']['stat_targets'])
    require(stats==['maxhp','maxpp','offense','defense','speed','iq','guts'],'Stat schema order changed')
    levels=[]
    for level in [first['victory']['initial_level'],second['encounter']['promoted_level']]:
        values=[int(t[0]+(t[1]-t[0])*level/10)+cap['boost'].get(k,0)for k,t in battle['party']['stat_targets'].items()]
        skills=character['learnedSkills']+([second['encounter']['learned_skill']]if level==second['encounter']['promoted_level']else [])
        levels.append(dict(level=level,minimum_exp=room['sections']['Experience'][level-1]['required_total_exp'],next_exp=room['sections']['Experience'][level]['required_total_exp'],stats=values,skills=skills))
    require(levels[0]['stats']==[effective[k]for k in stats] and levels[1]['stats']==[x['after']for x in second['growth']],'Derived stat contract disagrees with live battle resources')
    mutable={saved_flag,first['victory']['earned_cash_flag']}
    encounter_flag=battle['entry']['first_encounter_flag']
    if encounter_flag in {f['id']for f in flags}:mutable.add(encounter_flag)
    for command in room['sections']['Command']:
        if command['opcode']==OPCODES.index('SetFlag'):mutable.add(flags[command['target_index']]['id'])
    for b in room['sections']['Battle']:
        if b['win_flag_index']!=0xffffffff:mutable.add(flags[b['win_flag_index']]['id'])
    for door in house['openable_doors']:
        if door.get('flag') and door['policy']&1:mutable.add(door['flag'])
        if door.get('activates_flag'):mutable.add(door['activates_flag'])
        if door.get('deactivates_flag'):mutable.add(door['deactivates_flag'])
    require(mutable<={f['id']for f in flags},'Unregistered mutable flag: '+repr(mutable-{f['id']for f in flags}))
    # Only connected native rooms: select the source camera cell nearest each
    # already implemented door destination and the actual opening spawn.
    points=[scene['spawn']]+[d['destination']for d in house['doors']]
    cameras=room['sections']['CameraArea'];camera_ids=sorted({min(cameras,key=lambda c:sum((a-b)**2 for a,b in zip(c['center'],point)))['stable_id'] for point in points})
    startup=copy.deepcopy(defaults);startup['characters'],derivation=source_startup_characters(ex,save,overrides,defaults)
    return dict(schema=3,settings_choices=settings_choices(ex),kind='encore.native-session.source-ir',commit=ex.lock['commit'],scope='Single live party member; complete inactive startup naming roster; connected native house rooms; source leader levels 1 and 2; frozen source startup records; no inactive gameplay or event-transform snapshot',compatibility=dict(content_family=room['family'],content_revision=1,rules_revision=room['rules']),defaults=defaults,startup=startup,startup_derivation=derivation,levels=levels,saved_flag=saved_flag,earned_cash_flag=first['victory']['earned_cash_flag'],mutable_flags=sorted(mutable),camera_area_ids=camera_ids,uid_policy='Legacy defaults retain stable native IDs. Startup resource UIDs are unique placeholders, preserving Ninten/CashCard IDs and allocating inactive items in source inventory order. New Game stages replacement UIDs using copies of the existing shared source randomize/clock/UID ledger in source load order; accept commits the staged state, cancel discards it without live RNG mutation. Saved UIDs remain opaque and are preserved; resource placeholders do not reproduce source random IDs.',sources=ex.sources,dependencies={p:digest(ROOT/p)for p in required})

class Writer:
    def __init__(self):self.raw=bytearray()
    def put(self,fmt,*v):self.raw.extend(struct.pack('<'+fmt,*v))
    def text(self,s):b=s.encode('utf8');self.put('I',len(b));self.raw.extend(b)
    def array(self,a,fn):self.put('I',len(a));[fn(v)for v in a]
    def item(self,v):self.text(v['item_id']);self.put('BqI',v['equipped'],v['doses'],v['uid'])
    def flag(self,v):self.text(v['id']);self.put('B',v['value'])
    def integer(self,v):self.text(v['id']);self.put('q',v['value'])
    def real(self,v):self.text(v['id']);self.put('d',v['value'])
    def character(self,v):
        self.text(v['character_id']);self.text(v['nickname']);self.put('4q',*[v[k]for k in ['level','experience','hp','pp']]);self.array(v['permanent_boosts'],self.integer);self.array(v['affinity_multipliers'],self.real);self.array(v['learned_skills'],self.text)
        require(not v['status'],'Only empty initial status is supported');self.put('I',0);self.array(v['inventory'],self.item)

def encode_snapshot(s,c):
    w=Writer();w.text(s['scene_id']);w.text(s['scene_label']);w.put('4d',*[s[k]for k in ['position_x','position_y','direction_x','direction_y']]);w.text(s['run_sound']);w.text(s['shadow_effect']);w.put('2d',s['playtime_seconds'],s['settings']['text_speed']);w.text(s['settings']['menu_flavor']);w.text(s['settings']['button_prompts']);w.put('B',s['settings']['description']);w.text(s['player_name']);w.text(s['favorite_food']);w.put('3q',s['cash'],s['bank'],s['earned_cash']);w.array(s['characters'],w.character);w.array(s['party'],w.text);w.array(s['key_items'],w.item);w.array(s['storage'],w.item)
    for k in ['flags','object_flags','seen_dialogue_flags','encountered']:w.array(s[k],w.flag)
    for k in ['keys','rare_drops']:w.array(s[k],w.integer)
    w.text(s['source_version']);w.text(s['saved_at']);w.put('BI',s['is_debug'],s['rng_policy'])
    raw=struct.pack('<8s5I',b'ENCSNAP1',1,c['content_family'],c['content_revision'],c['rules_revision'],len(w.raw))+w.raw
    return raw+struct.pack('<I',zlib.crc32(raw))

def encode(r):
    require(r['schema'] in (1,2,3),'Unsupported native session schema')
    w=Writer();c=r['compatibility'];w.put('3I',c['content_family'],c['content_revision'],c['rules_revision']);template=encode_snapshot(r['defaults'],c);w.put('I',len(template));w.raw.extend(template)
    w.put('I',len(r['levels']))
    for level in r['levels']:w.put('3I7i',level['level'],level['minimum_exp'],level['next_exp'],*level['stats']);w.array(level['skills'],w.text)
    w.text(r['saved_flag']);w.text(r['earned_cash_flag']);w.array(r['mutable_flags'],w.text);w.array(r['camera_area_ids'],lambda x:w.put('I',x))
    if r['schema']>=2:
        startup=encode_snapshot(r['startup'],c);w.put('I',len(startup));w.raw.extend(startup)
    if r['schema']>=3:
        options=r['settings_choices'];w.array(options['speeds'],lambda x:w.put('d',x));w.array(options['flavors'],w.text);w.array(options['prompts'],w.text)
    return struct.pack('<8s4I',b'ENCNSESS',r['schema'],24+len(w.raw),zlib.crc32(w.raw),r['schema'])+w.raw

def verify_recipe(r):
    require(r==extract(),'Native session recipe differs from pinned source or reviewed scope')

def stage_files(source_root):
    r=read(IR);verify_recipe(r);root=Path(source_root).resolve();relative=Path("data/opening.encsession");target=(root/relative).resolve()
    require(target.is_relative_to(root),"Native session stage path escapes root")
    raw=target.read_bytes();require(raw==encode(r),"Stale staged native session pack")
    return {relative:raw}

def main():
    ap=argparse.ArgumentParser();ap.add_argument('action',choices=['extract','compile','verify'],nargs='?',default='compile');a=ap.parse_args()
    if a.action=='extract':r=extract();IR.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n')
    else:r=read(IR);verify_recipe(r)
    raw=encode(r)
    if a.action=='verify':require(PACK.read_bytes()==raw,'Stale native session pack')
    else:PACK.parent.mkdir(parents=True,exist_ok=True);PACK.write_bytes(raw)
    print('Native session:',len(raw),'bytes; checked source/defaults/stat rows; save-only bridge')
if __name__=='__main__':
    try:main()
    except (ValueError,KeyError,OSError,TypeError)as e:print('NATIVE SESSION ERROR:',e,file=sys.stderr);raise SystemExit(1)
