#!/usr/bin/env python3
"""Complete Player onready PackedScene source resources; never grants Ready."""
from pathlib import Path
import argparse,hashlib,json,math,struct,sys,zlib
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from tools.podunk_scene import PIN,read,write,require,sha
from tools import field_ui_manager_recipes as recipes
from tools.player_initialization import CLASSES
IR=ROOT/'content/native-player-preload-scenes.json';REVIEW=ROOT/'reports/player-preload-scenes/source-review.json';PACK=ROOT/'romfs/data/player.encpreloadscenes';FAMILY=0x454e0072

def extract(directory):
 initial=read(ROOT/'content/native-player-initialization.json'); rows=[v for v in initial['onready']if v.get('kind')==2 and v.get('native')=='PackedScene'];require(len(rows)==2,'Player source onready PackedScene scope changed')
 entries=[]
 old=recipes.CLASSES;recipes.CLASSES=CLASSES+['Line2D']
 try:
  for row in rows:
   name=Path(row['resource']).stem; d=directory/name
   r=recipes.extract_recipe(row['resource'],d/'native.json',d/'tree.json',d/'source.json');n=read(d/'native.json');proof=read(d/'source.json')
   require(bool(n['scene_states'])and bool(n['resources'])and len(n['nodes'])==len(r['records']),'Player preload complete SceneStates/resources required')
   entries.append(dict(row=row,recipe=r,native_snapshot=n,connections=proof['signal_connections']))
 finally:recipes.CLASSES=old
 out=dict(schema=1,family=FAMILY,format=1,capability=1,rules=1,commit=PIN,player_ir_sha256=sha(ROOT/'content/native-player-initialization.json'),owner_scene_id=initial['scene_id'],owner_source_sha256=initial['source_sha256'],entries=entries,scene_admitted=False)
 write(IR,out);write(REVIEW,dict(schema=1,commit=PIN,ir_sha256=sha(IR),sources={p:h for v in entries for p,h in v['recipe']['sources'].items()},exporter_sha256=sha(ROOT/'tools/godot_exporter/field_ui_manager.gd'),recipes_helper_sha256=sha(ROOT/'tools/field_ui_manager_recipes.py'),instantiated=False,ready_granted=False));return out

def load():
 d=read(IR);r=read(REVIEW);require(d['commit']==PIN and d['family']==FAMILY and d['format']==d['capability']==d['rules']==1 and d['scene_admitted']is False and r['ir_sha256']==sha(IR),'Player preload schema/review rejected')
 require(d['player_ir_sha256']==sha(ROOT/'content/native-player-initialization.json')and r['exporter_sha256']==sha(ROOT/'tools/godot_exporter/field_ui_manager.gd')and r['recipes_helper_sha256']==sha(ROOT/'tools/field_ui_manager_recipes.py'),'Player preload dependency changed')
 owner=read(ROOT/'content/native-player-initialization.json');require(d['owner_scene_id']==owner['scene_id']and d['owner_source_sha256']==owner['source_sha256'],'Player preload owner identity changed')
 for p,h in r['sources'].items():require(sha(ROOT/'upstream/MOTHER-Encore'/p)==h,'Player preload source changed '+p)
 require([x['row']for x in d['entries']]==[x for x in read(ROOT/'content/native-player-initialization.json')['onready']if x.get('kind')==2 and x.get('native')=='PackedScene'],'Player preload onready binding changed');return d

def encode(d):
 b=bytearray(128)
 def u(*v):b.extend(struct.pack('<'+'I'*len(v),*v))
 def t(s):x=s.encode();u(len(x));b.extend(x)
 def value(v):
  if v is None:u(0)
  elif type(v)is bool:u(1,int(v))
  elif type(v)is int:u(2);b.extend(struct.pack('<q',v))
  elif type(v)is float:require(math.isfinite(v),'Nonfinite PackedScene source');u(3);b.extend(struct.pack('<d',v))
  elif isinstance(v,str):u(4);t(v)
  elif isinstance(v,list):u(5,len(v));[value(x)for x in v]
  elif isinstance(v,dict):u(6,len(v));[(t(k),value(x))for k,x in v.items()]
  else:raise ValueError('Unsupported source Variant')
 b.extend(bytes.fromhex(d['player_ir_sha256']));u(len(d['entries']))
 for entry in d['entries']:
  r=entry['recipe'];value(entry['row']);u(r['scene_id']);b.extend(bytes.fromhex(r['source_sha256']));sub=bytearray(recipes.encode_recipe(r));struct.pack_into('<I',sub,28,7);u(len(sub));b.extend(sub);value(entry['native_snapshot']);value(entry['connections'])
 struct.pack_into('<8s8I',b,0,b'ENCPPSC1',1,128,len(b),zlib.crc32(b[128:]),FAMILY,1,1,d['owner_scene_id']);b[40:60]=bytes.fromhex(PIN);b[60:92]=bytes.fromhex(d['owner_source_sha256']);b[92:124]=bytes.fromhex(sha(IR));return bytes(b)

def stage_files(root):
 raw=encode(load());require((Path(root)/'data/player.encpreloadscenes').read_bytes()==raw,'Player preload generated bytes stale');return{Path('data/player.encpreloadscenes'):raw}
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('action',choices=['extract','compile']);a.add_argument('--directory',type=Path);args=a.parse_args()
 try:
  d=extract(args.directory)if args.action=='extract'else load();PACK.parent.mkdir(parents=True,exist_ok=True);PACK.write_bytes(encode(d));print('Player PackedScene resources:',len(d['entries']),'full source recipes; no instance/Ready')
 except(ValueError,KeyError,TypeError,OSError,struct.error)as e:sys.exit('PLAYER PRELOAD SCENES ERROR: '+str(e))
