#!/usr/bin/env python3
"""Validate measured official AnimationPlayer samples and generate a fixture."""
from __future__ import annotations
import argparse
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from tools.upstream import read_json
TIMES=[0,0.0001,0.083333,0.1,0.166667,0.2,0.25,0.333333,0.4,0.416667,
       0.5,0.6,0.799999,0.8,1,1.5,2.4,8,12.9]
STATES=['Idle','Walk','Run','Crouch']
DIRECTIONS=['Down','Left','Right','Up','DownLeft','DownRight','UpLeft','UpRight']

def fixture(document: dict) -> str:
    if document.get('schema')!=1 or document.get('source')!='res://Nodes/Reusables/Player.tscn':
        raise ValueError('Unknown animation reference schema/source')
    engine=document.get('godot',{})
    if [engine.get(k) for k in ('major','minor','patch','status','build','hash')]!=[3,6,2,'stable','official','3cd3caab6779a7f3ec3bbeb9f200db50c735cfc8']:
        raise ValueError('Animation reference requires pinned official Godot 3.6.2')
    rows=document.get('samples')
    if not isinstance(rows,list) or len(rows)!=32*len(TIMES)*2:
        raise ValueError('Incomplete animation reference domain')
    code='// GENERATED by tools/reference_animation.py from measured original AnimationPlayer. Do not edit.\n'
    code+='#pragma once\n#include <cstdint>\nnamespace animation_reference {\n'
    code+='struct Row {unsigned clip;double time;bool initial;uint16_t frame;bool main,special;};\nconstexpr Row rows[] = {\n'
    index=0
    for clip,name in enumerate(s+' '+d for s in STATES for d in DIRECTIONS):
        for time in TIMES:
            for visible in (False,True):
                row=rows[index];index+=1
                if set(row)!={'name','time','initial_visible','frame','main_visible','special_visible'}:
                    raise ValueError('Unknown animation sample fields')
                if row['name']!=name or type(row['time']) not in (int,float) or row['time']!=time or row['initial_visible'] is not visible:
                    raise ValueError('Animation reference domain changed/reordered')
                if type(row['frame'])!=int or not 0<=row['frame']<200:
                    raise ValueError('Invalid measured frame')
                if type(row['main_visible'])!=bool or type(row['special_visible'])!=bool:
                    raise ValueError('Invalid measured visibility')
                number=format(float(time),'.9g');number+= '' if '.' in number or 'e' in number else '.0'
                code+='    {'+str(clip)+','+number+','+','.join('true' if row[k] else 'false' for k in ['initial_visible'])+','+str(row['frame'])+','+','.join('true' if row[k] else 'false' for k in ['main_visible','special_visible'])+'},\n'
    code+='};\nstruct Tick {unsigned clip;float delta;uint16_t frame;bool main,special;};\nconstexpr Tick ticks[] = {\n'
    sequences=document.get('sequences')
    if not isinstance(sequences,list) or len(sequences)!=32:raise ValueError('Incomplete animation clock domain')
    for clip,(name,sequence) in enumerate(zip((s+' '+d for s in STATES for d in DIRECTIONS),sequences)):
        if sequence.get('name')!=name or len(sequence.get('frames',[]))!=75:raise ValueError('Animation clock domain changed')
        for tick,row in enumerate(sequence['frames']):
            if set(row)!={'frame','main_visible','special_visible'} or type(row['frame'])!=int or not 0<=row['frame']<200:
                raise ValueError('Invalid animation clock frame')
            if type(row['main_visible'])!=bool or type(row['special_visible'])!=bool:raise ValueError('Invalid animation clock visibility')
            delta='1.0f/60.0f' if tick<70 else ['0.0f','0.25f','0.8f','0.0f','1.2f'][tick-70]
            code+='    {'+str(clip)+','+delta+','+str(row['frame'])+','+','.join('true' if row[k] else 'false' for k in ['main_visible','special_visible'])+'},\n'
    return code+'};\n}\n'

def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reference',type=Path,required=True)
    parser.add_argument('--out',type=Path,default=ROOT/'tests/fixtures/animation_v0410.hpp')
    args=parser.parse_args()
    try:
        args.out.write_text(fixture(read_json(args.reference)),encoding='utf-8')
        return 0
    except (OSError,ValueError,KeyError,TypeError) as error:
        print('ANIMATION REFERENCE ERROR: '+str(error),file=sys.stderr);return 1

if __name__=='__main__':raise SystemExit(main())
