#!/usr/bin/env python3
"""Generate focused static-convex Godot 3.6.2 references, never from native output.

Only a fresh standalone engine project is written; upstream remains read-only.
Collision shapes come from the real Player.tscn hull plus explicit test solids.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess

ROOT=Path(__file__).resolve().parents[1]
PLAYER='upstream/MOTHER-Encore/Nodes/Reusables/Player.tscn'

def digest(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def rectangle(x,y,w,h): return [[x,y],[x+w,y],[x+w,y+h],[x,y+h]]
def cases(hull):
    wall=rectangle(12,-100,20,200)
    floor=rectangle(-100,16,200,20)
    definitions=[
        ('free',[0,0],[],[[64,-32]]*6),
        ('right_wall',[0,0],[wall],[[600,0]]*3),
        ('left_wall',[0,0],[rectangle(-32,-100,20,200)],[[-600,0]]*3),
        ('floor',[0,0],[floor],[[0,600]]*3),
        ('ceiling',[0,0],[rectangle(-100,-20,200,20)],[[0,-600]]*3),
        ('glancing',[0,0],[wall],[[600,240]]*8),
        ('parallel_contact',[6,0],[wall],[[0,64]]*6),
        ('zero_margin',[5.96,0],[wall],[[0,0]]*3),
        ('zero_penetration',[8,0],[wall],[[0,0]]*4),
        ('deep_penetration',[14,0],[wall],[[0,0]]*4),
        ('penetration_escape',[8,0],[wall],[[-120,0]]*3),
        ('inside_corner',[0,0],[wall,floor],[[600,600]]*8),
        ('corner_reversed',[0,0],[floor,wall],[[600,600]]*8),
        ('corner_penetration',[8,9],[wall,floor],[[0,0]]*4),
        ('sloped_wall',[0,0],[[[12,-20],[60,-20],[60,60]]],[[600,240]]*12),
        ('convex_furniture',[0,0],[[[16,8],[20,12],[20,20],[16,24],[8,24],[4,20],[4,12],[8,8]]],[[300,300]]*12),
        ('small_motion',[5.999,0],[wall],[[0.06,0],[0.06,0],[0,0]]),
        ('long_sweep',[0,0],[wall],[[30000,0]]),
        ('diagonal_near_miss',[0,-112],[wall],[[600,0]]*4),
        ('wall_end_slide',[0,91],[wall],[[600,600]]*12),
    ]
    return [dict(name=n,position=p,actor=hull,obstacles=o,velocities=v) for n,p,o,v in definitions]

def house_cases(hull,house_path,player_path):
    from world_geometry import geometry
    house=json.loads(house_path.read_text())
    actor,polygons=geometry(house,json.loads(player_path.read_text()))
    resources={r['id']:r for r in house['resources']}
    kinds=[]
    for node in house['nodes']:
        if node['class'] not in ('StaticBody2D','KinematicBody2D'): continue
        layer=int(node['properties']['collision_layer']['value']);mask=int(node['properties']['collision_mask']['value'])
        if not(layer&4353 or mask&1): continue
        for owner in node.get('physics_shape_owners',[]):
            for shape in owner['shapes']: kinds.append(resources[shape['id']]['class'])
    assert len(kinds)==len(polygons)
    assert [list(p) for p in actor]==hull,'Source and native-export player hull differ'
    # The opening flags adapter separately verifies these two unlocked doors.
    excluded={'Below/Openable Door/StaticBody2D','Below/Openable Door4/StaticBody2D'}
    solids=[p['vertices'] for p in polygons if p['body'] not in excluded]
    kinds=[kind for p,kind in zip(polygons,kinds) if p['body'] not in excluded]
    for points,kind in zip(solids,kinds):
        if kind=='RectangleShape2D':
            xs=sorted(set(p[0] for p in points));ys=sorted(set(p[1] for p in points))
            assert len(points)==4 and len(xs)==2 and len(ys)==2,'Only axis-aligned source rectangles reviewed'
        else: assert kind=='ConvexPolygonShape2D'
    assert len(solids)==103
    speed=64.0*(1.0/60.0)*64.0/1.7
    definitions=[
        ('house_walk_right',[520,397],[[speed,0]]*120,True),
        ('house_walk_up',[520,397],[[0,-speed]]*100,True),
        ('house_walk_down',[520,397],[[0,speed]]*80,True),
        ('house_lamp_left',[520,390],[[-speed,0]]*25,True),
        ('house_corner_glance',[579,410],[[speed,speed]]*60,True),
        ('house_diagonal',[520,410],[[speed,speed]]*100,True),
        ('house_penetration',[590,400],[[0,0]]*4,False),
    ]
    return [dict(name=n,position=p,actor=hull,obstacles=solids,obstacle_kinds=kinds,velocities=v,round_and_recover=r) for n,p,v,r in definitions]

def emit_header(cases,result,path):
    def number(v):
        s=format(float(v),'.9g')
        return s+('f' if '.' in s or 'e' in s else '.0f')
    def vec(v): return '{'+','.join(number(x) for x in v)+'}'
    text=['// Generated by tools/run_collision_reference.py from official Godot 3.6.2.',
          '// Do not edit expectations to suppress mismatches.',
          '#pragma once','#include "encore/collision.hpp"','#include <vector>',
          'namespace collision_reference {',
          'struct Frame { encore::upstream::Vec2 input, position, velocity; };',
          'struct Case { const char* name; encore::upstream::Vec2 start; encore::upstream::ConvexPolygon actor; std::vector<encore::upstream::ConvexPolygon> obstacles; std::vector<Frame> frames; bool round_and_recover; };',
          'inline const std::vector<Case> cases {']
    assert len(cases)==len(result['cases'])
    for source,actual in zip(cases,result['cases']):
        assert source['name']==actual['name'] and len(source['velocities'])==len(actual['frames'])
        hull='{{'+','.join(map(vec,source['actor']))+'}}'
        polygons='{'+','.join('{{'+','.join(map(vec,p))+'}}' for p in source['obstacles'])+'}'
        frames='{'+','.join('{'+','.join((vec(v),vec(f['position']),vec(f['velocity'])))+'}' for v,f in zip(source['velocities'],actual['frames']))+'}'
        text.append('    {'+json.dumps(source['name'])+','+vec(source['position'])+','+hull+','+polygons+','+frames+','+str(source.get('round_and_recover',False)).lower()+'},')
    text+=['};','}']
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text('\n'.join(text)+'\n')

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--godot',required=True,type=Path)
    parser.add_argument('--work',required=True,type=Path)
    parser.add_argument('--reports',required=True,type=Path)
    parser.add_argument('--fixture',type=Path)
    parser.add_argument('--house',type=Path)
    parser.add_argument('--player-data',type=Path)
    args=parser.parse_args()
    engine=args.godot.resolve();work=args.work.resolve();reports=args.reports.resolve()
    if work.exists() or reports.exists(): parser.error('work and reports must both be fresh directories')
    source=ROOT/PLAYER
    # Check the source byte inventory, not just the extracted coordinates.
    inventory=json.loads((ROOT/'compatibility/upstream-inventory.json').read_text())
    entries=inventory['files']
    if isinstance(entries,dict): expected=entries['Nodes/Reusables/Player.tscn']['sha256']
    else: expected=next(e['sha256'] for e in entries if e['path']=='Nodes/Reusables/Player.tscn')
    assert digest(source)==expected,'Player.tscn differs from pinned inventory'
    body=source.read_text().split('[node name="CollisionShape2D" type="CollisionPolygon2D" parent="."]')[1].split('[node')[0]
    offset=[float(x) for x in re.search(r'position = Vector2\(([^)]+)\)',body)[1].split(',')]
    raw=[float(x) for x in re.search(r'polygon = PoolVector2Array\(([^)]+)\)',body)[1].split(',')]
    hull=[[raw[i]+offset[0],raw[i+1]+offset[1]] for i in range(0,len(raw),2)]
    inputs=cases(hull)
    if bool(args.house)!=bool(args.player_data): parser.error('--house and --player-data must be supplied together')
    if args.house: inputs+=house_cases(hull,args.house,args.player_data)
    work.mkdir(parents=True);reports.mkdir(parents=True)
    (work/'project.godot').write_text('config_version=4\n[physics]\ncommon/physics_fps=60\n')
    (work/'cases.json').write_text(json.dumps(inputs,indent=2)+'\n')
    shutil.copyfile(ROOT/'tools/godot_exporter/collision_probe.gd',work/'probe.gd')
    command=[str(engine),'--path',str(work),'--script','res://probe.gd','--encore-out='+str(reports/'collision.json')]
    environment=os.environ.copy()
    for variable,directory in [('XDG_DATA_HOME','data'),('XDG_CONFIG_HOME','config'),('XDG_CACHE_HOME','cache')]:
        target=work/directory;target.mkdir();environment[variable]=str(target)
    completed=subprocess.run(command,capture_output=True,text=True,timeout=90,env=environment)
    (reports/'stdout.txt').write_text(completed.stdout);(reports/'stderr.txt').write_text(completed.stderr)
    completed.check_returncode()
    result=json.loads((reports/'collision.json').read_text())
    assert result['engine']['major']==3 and result['engine']['minor']==6 and result['engine']['patch']==2
    assert result['engine']['hash']=='3cd3caab6779a7f3ec3bbeb9f200db50c735cfc8'
    shutil.copyfile(work/'cases.json',reports/'cases.json')
    header=reports/'collision_v0362.hpp';emit_header(inputs,result,header)
    receipt={'scope':'one translated convex actor against static convex polygons; no game scripts or assets',
             'engine':result['engine'],'engine_binary_sha256':digest(engine),'player_sha256':digest(source),
             'probe_sha256':digest(work/'probe.gd'),'driver_sha256':digest(Path(__file__)),
             'cases':len(inputs),'frames':sum(len(c['velocities']) for c in inputs),
             'outputs':{p.name:digest(p) for p in [header,reports/'cases.json',reports/'collision.json']}}
    if args.house: receipt['exact_geometry']={str(p):digest(p) for p in (args.house,args.player_data)}
    (reports/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
    if args.fixture: args.fixture.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(header,args.fixture)
    print(json.dumps(receipt,indent=2))
if __name__=='__main__': main()
